### ISSUE TITLE
ClickHouse Authentication failed 516 with default user and password on port 8123

### ISSUE THREAD

**Issue by dnutiu** [Altinity/clickhouse-operator#1008]
Hello,

I cannot access ClickHouse with the default user and a custom user on port 8123. I tried with the ClickHouse JDBC driver and a simple `curl` command but I always get error 516.
```
Caused by: java.io.IOException: Code: 516. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED) (version 22.3.12.19 (official build))

root@ubuntu:/# curl -v "http://chi-repl-05-replicated-0-0:8123/?user=default&query=SELECT+number+FROM+system.number+LIMIT+5"
*   Trying 10.1.200.130:8123...
* Connected to chi-repl-05-replicated-0-0 (10.1.200.130) port 8123 (#0)
> GET /?user=default&query=SELECT+number+FROM+system.number+LIMIT+5 HTTP/1.1
> Host: chi-repl-05-replicated-0-0:8123
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Tue, 13 Sep 2022 09:37:48 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: chi-repl-05-replicated-0-0-0.chi-repl-05-replicated-0-0.clickhouse.svc.cluster.local
< Transfer-Encoding: chunked
< X-ClickHouse-Exception-Code: 516
<
Code: 516. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED) (version 22.3.12.19 (official build))
* Connection #0 to host chi-repl-05-replicated-0-0 left intact
```

I installed ClickHouse with the following settings:

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "repl-05"

spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7

  configuration:
    users:
      batman/networks/ip:
        - 0.0.0.0
      batman/profile: "default"
      batman/quotas: "default"
      batman/access_management: 1
      batman/password_sha256_hex: "37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f"
    zookeeper:
      nodes:
      - host: zookeeper.clickhouse.svc.cluster.local
    clusters:
      - name: replicated
        layout:
          shardsCount: 2
          replicasCount: 3

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
    podTemplates:
      - name: clickhouse:20.7
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3%
````

```
        Users:
          batman/access_management:     1
          batman/networks/host_regexp:  (chi-repl-05-[^.]+\d+-\d+|clickhouse\-repl-05)\.clickhouse\.svc\.cluster\.local$
          batman/networks/ip:
            ::1
            127.0.0.1
            0.0.0.0
          batman/password_sha256_hex:  37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f
          batman/profile:              default
          batman/quota:                default
          batman/quotas:               default
          clickhouse_operator/networks/ip:
            10.1.200.180
          default/networks/host_regexp:  (chi-repl-05-[^.]+\d+-\d+|clickhouse\-repl-05)\.clickhouse\.svc\.cluster\.local$
          default/networks/ip:
            ::1
            127.0.0.1
            0.0.0.0
            10.1.200.130
            10.1.200.138
            10.1.200.167
            10.1.200.177
            10.1.200.158
            10.1.200.133
          default/profile:  default
          default/quota:    default
```

The `default` user doesn't have a password and the password for the `batman` user is `default`.

Only connections from the `clickhouse-client` work and I don't understand why.

```bash
➜  ~ k exec -n clickhouse -it chi-repl-05-replicated-0-0-0 -- clickhouse-client --user default
ClickHouse client version 22.3.12.19 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.3.12 revision 54455.

chi-repl-05-replicated-0-0-0.chi-repl-05-replicated-0-0.clickhouse.svc.cluster.local :) exit
Bye.
➜  ~ k exec -n clickhouse -it chi-repl-05-replicated-0-0-0 -- clickhouse-client --user default --password
ClickHouse client version 22.3.12.19 (official build).
Password for user (default):
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.3.12 revision 54455.

chi-repl-05-replicated-0-0-0.chi-repl-05-replicated-0-0.clickhouse.svc.cluster.local :) exit
Bye.

k exec -n clickhouse -it chi-repl-05-replicated-0-0-0 -- clickhouse-client --user batman --password default
ClickHouse client version 22.3.12.19 (official build).
Connecting to localhost:9000 as user batman.
Connected to ClickHouse server version 22.3.12 revision 54455.

chi-repl-05-replicated-0-0-0.chi-repl-05-replicated-0-0.clickhouse.svc.cluster.local :) select count(*) from features_i2;

SELECT count(*)
FROM features_i2

Query id: 5cc2c6cc-a39f-400b-b457-9b7b101bd2fd

┌───count()─┐
│ 200000000 │
└───────────┘

1 rows in set. Elapsed: 0.018 sec.

chi-repl-05-replicated-0-0-0.chi-repl-05-replicated-0-0.clickhouse.svc.cluster.local :) exit
Bye.
```

I don't know why connecting via clickhouse-client works but JDBC/http doesn't work.
