### ISSUE TITLE
Discard server config `default_database_engine`

### ISSUE THREAD

**Issue by cangyin** [Altinity/clickhouse-operator#1018]
[Ordinary database engine and old storage definition syntax for *MergeTree tables are deprecated](https://clickhouse.com/docs/en/whats-new/changelog/#-clickhouse-release-227-2022-07-21:~:text=Ordinary%20database%20engine%20and%20old%20storage%20definition%20syntax%20for%20*MergeTree%20tables%20are%20deprecated)
starting from ClickHouse v22.7

**Comment by Slach** [comment]
Shall work

```yaml
spec:
  configuration:
    settings:
      profiles/default/default_database_engine: "Atomic"
```
