### ISSUE TITLE
Zookeeper configuration not copied over to cluster

### ISSUE THREAD

**Issue by msukumaran-korewireless** [Altinity/clickhouse-operator#1022]
I deployed both zookeeper and clickhouse cluster on my namespace, but my zookeeper configuration files are not seen in the clickhouse cluster, I believe this task is carried out by operator. I use multi-node and need zookeeper to work.
I tried to copy the file manually to shards but not able to as it says read only drive. 

root@MidhunC-552:/mnt/c/Midhun/clickhouse-operator# kubectl cp /mnt/c/Midhun/clickhouse-operator/chop-generated-zookeeper.xml chi-clh-test-simple-0-0-0:etc/clickhouse-server/conf.d/chop-generated-zookeeper.xml
tar: chop-generated-zookeeper.xml: Cannot open: Read-only file system
tar: Exiting with failure status due to previous errors
command terminated with exit code 2

Is there any CRD's / manifest I can apply to get the zookeeper configuration files ?

**Comment by Slach** [comment]
Zookeeper shall deploy separately and don't manage by clickhouse-operator
look examples here https://github.com/Altinity/clickhouse-operator/tree/master/deploy/zookeeper/

to configure clickhouse-server to use installed zookeeper
use

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "zookeeper-example"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-service-name.zookeeper-namespace
```
