### ISSUE TITLE
hwo to  configure secret in podTemplates if image is protected?

### ISSUE THREAD

**Issue by yaoyao12138** [Altinity/clickhouse-operator#1029]
hwo to  configure secret in podTemplates if the related image isn't public and need to be pulled with user/pass. 

Is there any example? Thanks

https://github.com/Altinity/clickhouse-operator/blob/7ec06b79eb70430d546f9a085c92a5339c8f3e4a/docs/chi-examples/02-templates-01-pod-template.yaml#L21-L44

**Comment by Slach** [comment]
look to https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret
kubectl explain pod.spec.imagePullSecrets

just define 
```yaml
spec
   imagePullSecrets:
     - name: your-secret-with-credentials
```   
inside your `chi.spec.podTemplates[]`
