### ISSUE TITLE
How to stop the pods for maintenance

### ISSUE THREAD

**Issue by simsicon** [Altinity/clickhouse-operator#1031]
Hi, My underlying nfs storages need to run a filesystem check, in case of any data loss or inconsistence, I think it would be a good idea to stop the pods during the time, but how can i achieve that? I am running the below config

```
clusters:
      - name: "std"
        templates:
          podTemplate: pod-template-22
        layout:
          shardsCount: 1
          replicasCount: 1
```

Thanks
