### ISSUE TITLE
Local Replica Tables + ZK records aren't dropped on scale in operator

### ISSUE THREAD

**Issue by davidkl97** [Altinity/clickhouse-operator#1033]
When im trying to scale in shard which has local replica, the records in zookeeper of the local replica aren't deleted, 
so when i try to scale out the shard again, it fails to create the tables because the record already exists in zk:
```
E1024 06:14:21.641359       1 connection.go:200] Exec():FAILED Exec(http://***:***@chi-simple-01-simple-1-0.default.svc.cluster.local:8123/) clickhouse: Code: 253. DB::Exception: Replica /clickhouse/tables/1/tablexxx/replicas/chi-simple-01-simple-1-0 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.9.3.18 (official build))
```
Is this a bug or a limitation? is there any workaround to automate this situation?

Thanks!

Installation Specs:

Operator Version: 0.19.3
Clickhouse Version: 22.9.3
Example CHI manifest: 
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: ch-zookeeper
    users:
      clickhouse_operator/networks/ip: "::/0"
    clusters:
      - name: "simple"
        layout:
          shardsCount: 2
          replicasCount: 1
  defaults:
    templates:
      serviceTemplate: svc-template
      podTemplate: clickhouse-node-group-affinity
  templates:
    serviceTemplates:
      - name: svc-template
        generateName: endpoint-{chi}
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            cloud.google.com/load-balancer-type: "Internal"
            external-dns.alpha.kubernetes.io/hostname: clickhouse-endpoint.xxxx.xxx
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
          externalTrafficPolicy: Local
    podTemplates:
      # Specify Pod Templates with affinity
      - name: clickhouse-node-group-affinity
        zone:
          key: "component"
          values:
            - "clickhouse"
        distribution: "OnePerHost"
```
