### ISSUE TITLE
LDAP server definition

### ISSUE THREAD

**Issue by suharevA** [Altinity/clickhouse-operator#1041]
how to make settings to connect to ldap correctly? Like this?

```
settings:
  ldap/profile: ldap
  ldap/host: address server
  ldap/auth_dn_prefix: cn
  ldap/auth_dn_suffix: ou=users
```
```
Unknown setting server: while parsing profile 'ldap' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'
```

**Comment by Slach** [comment]
You can try use
```
spec:
  configuration:
    files:
      config.d/ldap_server.xml: |
        <clickhouse> <ldap_server> ... 
               
```

and use settings the same manner as described in documentation
https://clickhouse.com/docs/en/operations/external-authenticators/ldap/
