### ISSUE TITLE
Operator 0.19 liveness probe failed

### ISSUE THREAD

**Issue by midhuns3343** [Altinity/clickhouse-operator#1050]
Recently, operator was upgraded to 0.19 which caused a restart of pods in CHI. The pods were crashlooping as liveness probe failed. Looking at the endpoint script, it looks like "chown" was being run on all files and it was taking hours as file count in data directory was high and there wasn't a restart of pods for about 1 year. 

With the liveness probe value of 60 seconds, the pods are not expected stay running due to the configuration in entrypoint script. Previous operator 0.12 doesn't have liveness check I believe.

Is there a solution?

**Comment by alex-zaitsev** [comment]
Hi @midhuns3343 , 

You may override liveness probe in pod template and increase initial delay timeout or other parameters. Here is an example:
```
    podTemplates:
    - name: pod-template
      spec:
        containers:
        - image: clickhouse/clickhouse-server:22.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: https
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 3
```
Also, please use 0.20.0 version.

**Comment by midhuns3343** [comment]
> Hi @midhuns3343 ,
> 
> You may override liveness probe in pod template and increase initial delay timeout or other parameters. Here is an example:
> 
> ```
>     podTemplates:
>     - name: pod-template
>       spec:
>         containers:
>         - image: clickhouse/clickhouse-server:22.8
>           imagePullPolicy: IfNotPresent
>           livenessProbe:
>             httpGet:
>               path: /ping
>               port: https
>               scheme: HTTPS
>             initialDelaySeconds: 60
>             periodSeconds: 3
> ```
> 
> Also, please use 0.20.0 version.

Thanks for the suggestion. Is there anything to be done to avoid Appling the ownership change on pod restarts? I don't think it's a good idea to keep 2 hours for livenessProbe.

**Comment by alex-zaitsev** [comment]
@midhuns3343 , sure! Add security context and you do not need chown:
```
    podTemplates:
      - name: pod-template-with-volumes-do-not-chown
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
```
