### ISSUE TITLE
cluster name is tied with chi pods and persistence volumes

### ISSUE THREAD

**Issue by prashant-shahi** [Altinity/clickhouse-operator#1056]
In general, cluster name (set using `<remote_servers>` configuration) has no sticky relation with the instances of ClickHouse servers.

When trying to update cluster name, old data is removed since the cluster name is tied to not only pods but the PVCs.
Do let me know if there is any way right now to update cluster name with the old data intact.

**Comment by alex-zaitsev** [comment]
Try podGenerateName:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "pod-generate-name"
spec:
  configuration:
    clusters:
      - name: shard1-repl1
        templates:
          podTemplate: clickhouse-pod-template
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        generateName: "chi-{chi}-{cluster}-{host}"
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse
```
But cluster name is pretty much hardcoded internally, you are right.
