### ISSUE TITLE
Restarting clickhouse fails constantly

### ISSUE THREAD

**Issue by simsicon** [Altinity/clickhouse-operator#1068]
Hi, I am running a single pod clickhouse server using this operator, and when I try to restart the server by manually deleting and creating the pod, it seems trying to load tables, and always stuck at `TablesLoader: 99.6%` something, then the pod automatically restart, when restart times exceed 7 it will on the state of crashbackoff.

I wonder what's the block? is there any settings I can relax the constraints so it can restart properly?

Thanks

**Comment by Slach** [comment]
You could define a custom `podTemplate` with custom `readinessProbe` and `livenessProbe`
something like this
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: custom-probes
spec:
  configuration:
    clusters:
    - name: default
      layout:
        replicasCount: 1
        shardsCount: 1
  defaults:
    templates:
      podTemplate: custom-probes-pod-template
  templates:
    podTemplates:
    - name: pod-template
      spec:
        containers:
        - image: clickhouse/clickhouse-server:22.8
          imagePullPolicy: IfNotPresent
          name: clickhouse
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
              scheme: HTTPS
            initialDelaySeconds: 600
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 10

```
