### ISSUE TITLE
default_replica_name parameter not showing in config

### ISSUE THREAD

**Issue by midhuns3343** [Altinity/clickhouse-operator#1079]
I need to add default_replica_name to chi configuration, but it is not showing up in the configuration. "default_replica_path" shows correctly, not default_replica_name.

clickhouse@chi-clh-demo-shard-0-0-0:/$ grep default_replica_path /var/lib/clickhouse/preprocessed_configs/config.xml
<default_replica_path>/clickhouse/{installation}/{cluster}/{database}/{table}/{shard}</default_replica_path>
clickhouse@chi-clh-demo-shard-0-0-0:/$ grep default_replica_name /var/lib/clickhouse/preprocessed_configs/config.xml
clickhouse@chi-clh-demo-shard-0-0-0:/$

Manifest below:
```yaml
settings:
      logger/level: warning
      logger/log: /var/log/clickhouse-server/clickhouse-server.log
      logger/errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
      logger/size: 1000M
      logger/count: 10
      compression/case/method: zstd
      default_replica_path: /clickhouse/{installation}/{cluster}/{database}/{table}/{shard}
      default_replica_name: {replica}
```
