### ISSUE TITLE
Increase replica count

### ISSUE THREAD

**Issue by daviddanielarch-nextroll** [Altinity/clickhouse-operator#1080]
I tried increasing the replica count for my cluster by just increasing the replicasCount.
```
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 3
          replicasCount: 3
```

That is creating new pods but it's not adding new nodes to the EKS cluster.
Is there anything else I have to do in order to add more replicas?
This is my config:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
      podTemplate: clickhouse-template
      serviceTemplate: clickhouse-service-template

  configuration:
    zookeeper:
      nodes:
      - host: clickhouse-keeper.keeper.svc

    clusters:
      - name: "cluster"
        layout:
          shardsCount: 3
          replicasCount: 3

    settings:
      compression/case/method: zstd
      max_concurrent_queries: 10000
      macros/environment: staging
      max_table_size_to_drop: 200000000000
      max_partition_size_to_drop: 200000000000
      logger/level: warning

    users:
      default/access_management: 1
      default/networks/host_regexp: \.clickhouse\.svc\.cluster\.local$
      default/networks/ip:
        - "::1"
        - "127.0.0.1/32"
        - "172.18.0.0/16"
      default/profile: default
      default/quota: default

  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        reclaimPolicy: Retain # Keep PVC from being deleted, after CHI is destroyed
        spec:
          storageClassName: resizable-gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 16Ti
      - name: log-volume-template
        reclaimPolicy: Retain
        spec:
          storageClassName: resizable-gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    podTemplates:
      - name: clickhouse-template
        podDistribution: 
          - type: ClickHouseAntiAffinity
          - type: MaxNumberPerNode
            number: 1
            topologyKey: "kubernetes.io/hostname"
        spec:
          nodeSelector: # pod affinity rule for attaching to certain nodegroup(s)
            role: clickhouse-on-demand-r5n-nodes-4x
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.8
    serviceTemplates:
      - name: clickhouse-service-template
        generateName: "clickhouse-elb-common"
        metadata:
          labels:
            custom.label: "clickhouse.elb"
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"  # launch private ELB (behind VPN)
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
          loadBalancerSourceRanges:
          - 172.18.0.0/16
```
