### ISSUE TITLE
Disable automated creation of podDisruptionbudgets

### ISSUE THREAD

**Issue by vigodeltoro** [Altinity/clickhouse-operator#1081]
Hi there,

we are running two clickhouse pods per node in a 3 shard 1 replica cluster ( 3 server with 2 pods each ).
That brings us two the issue that with the automated rolled out podDisruptionbudget which allows only 1 unhealthy pod 
we are not able to update our cluster in a rolling manner. I didn't find a configuration possibility to configure the podDisruptionBudget in the operator or cluster. 

So, I created 3 sufficient podDisruptionbudget manually which is like the shown below. But the operator is rolling the automatic one again. 
In cluster definition I have 6 pod templates with affinity rules like
```yaml
affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - "zone-[1,2,3]"    
```
Does anybody has an idea how to handle that ? 

best and thanks

```yaml
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ch-database-pdb-sh-0
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
      clickhouse.altinity.com/chi: protobuf-example
      clickhouse.altinity.com/cluster: dev
      clickhouse.altinity.com/shard: shard0

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ch-database-pdb-sh-1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
      clickhouse.altinity.com/chi: protobuf-example
      clickhouse.altinity.com/cluster: dev
      clickhouse.altinity.com/shard: shard1

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ch-database-pdb-sh-2
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
      clickhouse.altinity.com/chi: protobuf-example
      clickhouse.altinity.com/cluster: dev
      clickhouse.altinity.com/shard: shard2
```

**Comment by Slach** [comment]
> we are running two clickhouse pods per node in a 3 shard 1 replica cluster ( 3 server with 2 pods each ).

Sorry, this is not clear
`3 shard 1 replica` means 3 pods
but
`3 server with 2 pods each` means 6 pods

could you share your `kind: ClickHouseInstallation` manifest in yaml for clarify ?

**Comment by vigodeltoro** [comment]
I can share you the manifest tommorrow.. because our manifest ist huge.. 

Sorry for confusion..

3 shards with 2 replicas each = 6 pods 
distributed to 3 servers and no pods of the same shard on one server for redundancy


    - chi-protobuf-example-dev-sh0-rep0-0
    - chi-protobuf-example-dev-sh0-rep1-0
   - chi-protobuf-example-dev-sh1-rep0-0
    - chi-protobuf-example-dev-sh1-rep1-0
    - chi-protobuf-example-dev-sh2-rep0-0
    - chi-protobuf-example-dev-sh2-rep1-0
    
    Hope that helps.. thanks for your answer

**Comment by Slach** [comment]
for this use case just use podDIstribution CircularReplication use something like that

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "circular-replication"
spec:
  defaults:
    templates:
      podTemplate: dist-template
  configuration:
    clusters:
      - name: "dc1"
        layout:
          shardsCount: 3
          replicasCount: 2
  templates:
    podTemplates:
      - name: dist-template
        podDistribution:
          - type: CircularReplication
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3
  
```
