### ISSUE TITLE
 When importing from csv, not all rows are inserted.

### ISSUE THREAD

**Issue by suharevA** [Altinity/clickhouse-operator#1087]
When importing from csv, not all rows are inserted.
I do import through dbeaver or datagrip.
In a normal cluster, there are no such problems. Maybe there are not enough settings in the config.
Config
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
   name: prod-click
spec:
   defaults:
      templates:
         podTemplate: clickhouse-backup
         dataVolumeClaimTemplate: data-volume
   configuration:
      users:
         # use cluster Pod CIDR for more security
         backup/networks/ip: 0.0.0.0/0
         # PASSWORD=backup_password; echo "$PASSWORD"; echo -n "$PASSWORD" | sha256sum | tr -d '-'
         backup/password_sha256_hex: eb94c11d77f46a0290ba8c4fca1a7fd315b72e1e6c83146e42117c568cc3ea4d
      settings:
         # to allow scrape metrics via embedded prometheus protocol
         prometheus/endpoint: /metrics
         prometheus/port: 8888
         prometheus/metrics: true
         prometheus/events: true
         prometheus/asynchronous_metrics: true
      profiles:
        default/max_concurrent_queries_for_user: 200
        
      # need install zookeeper separately, look to https://github.com/Altinity/clickhouse-operator/tree/master/deploy/zookeeper/ for details
      zookeeper:
         nodes:
            - host: zookeeper.zoo3ns
              port: 2181
         session_timeout_ms: 5000
         operation_timeout_ms: 5000
      clusters:
         - name: prod
           layout:
              # 2 shards one replica in each
              shardsCount: 2
              replicasCount: 2
   templates:
      volumeClaimTemplates:
         - name: data-volume
           spec:
              storageClassName: tau
              accessModes:
                 - ReadWriteOnce
              resources:
                 requests:
                    storage: 200Gi
      podTemplates:
         - name: clickhouse-backup
           metadata:
              annotations:
                 prometheus.io/scrape: 'true'
                 prometheus.io/port: '8888'
                 prometheus.io/path: '/metrics'
                 # need separate prometheus scrape config, look to https://github.com/prometheus/prometheus/issues/3756
                 clickhouse.backup/scrape: 'true'
                 clickhouse.backup/port: '7171'
                 clickhouse.backup/path: '/metrics'
#         - name: dist-template
           podDistribution:
#              - type: ShardAntiAffinity
              - type: ReplicaAntiAffinity


           spec:
              securityContext:
                 runAsUser: 101
                 runAsGroup: 101
                 fsGroup: 101
              containers:
                 - name: clickhouse-pod
                   image: clickhouse-server:22.3.8.40.altinitystable
                   command:
                      - clickhouse-server
                      - --config-file=/etc/clickhouse-server/config.xml
                 - name: clickhouse-backup
                   image: /clickhouse-backup:2.1.3
                   imagePullPolicy: Always
                   command:
                      # - bash
                      - sh
                      - -xc
                      - "/bin/clickhouse-backup server"
                   env:
                      - name: LOG_LEVEL
                        value: "debug"
                      - name: ALLOW_EMPTY_BACKUPS
                        value: "true"
                      - name: API_LISTEN
                        value: "0.0.0.0:7171"
                      # INSERT INTO system.backup_actions to execute backup
                      - name: API_CREATE_INTEGRATION_TABLES
                        value: "true"
                      - name: BACKUPS_TO_KEEP_REMOTE
                        value: "3"
                      # change it for production S3
                      - name: REMOTE_STORAGE
                        value: "s3"
                      # - name: S3_ACL
                      #   value: "private"
                      - name: S3_ENDPOINT
                        value: operatorclick.hcp
                      - name: S3_BUCKET
                        value: clickprod
                      - name: S3_PATH
                        value: clickhouse
                      - name: S3_ACCESS_KEY
                        value: 
                      - name: S3_SECRET_KEY
                        value: 
                      - name: S3_FORCE_PATH_STYLE
                        value: "true"
                      # remove it for production S3
                      - name: S3_DISABLE_SSL
                        value: "true"
                      - name: S3_DEBUG
                        value: "true"
                      # require to avoid double scraping clickhouse and clickhouse-backup containers
                   ports:
                      - name: backup-rest
                        containerPort: 7171

```
```
CREATE TABLE vmware.Sharesshd_autTEST ON CLUSTER '{cluster}'(
    `Volume` String,
    `Storage` String,
    `Size` Int32,
    `Used` Int32,
    `Add_time` Date,
    `DC` String,
    `State` String,
    `Pool` String,
    `Rules` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/{table}', '{replica}')
ORDER BY Volume;
```
table example. Despite the fact that the period is not much about 35000
Only 15000 are imported
