### ISSUE TITLE
Disable chown on pod restarts (DO_CHOWN=0)

### ISSUE THREAD

**Issue by midhuns3343** [Altinity/clickhouse-operator#1093]
The entrypoint.sh script contains the ownership of files check and and it applies chown to all directories and files with the clickhouse user which takes hours for the pod to start due to large number of files.

To disable this, securityContext was added to disable chown. Since kube version is 1.17, kubelet is to appling the fsGroup permissions  before mount and it again takes hours for the pod to start.

securityContext:
  runAsUser: 101
  runAsGroup: 101
   fsGroup: 101     

I need to remove the fsgroup and run the process as root again by disabling the chown. Is there a way to define DO_CHOWN=0 within the CHI manifest ?

![image](https://user-images.githubusercontent.com/88483737/217435354-0f0c0c43-bfc9-4b71-aad1-23dfce68f544.png)

**Comment by Slach** [comment]
> . Is there a way to define DO_CHOWN=0 within the CHI manifest ?

AFAIK securityContext don't apply by default

and you can define DO_CHOWN environment variable something like that

```yaml
spec:
  configuration:
    templates:
      podTemplates:
        - name: do-not-chown
          spec:
            containers:
              - name: clickhouse
                image:  clickhouse/clickhouse-server:latest
                env:
                   - name:  "DO_CHOWN"
                     value: "0"
   defaults:
      podTemplate: do-not-chown
```
