### ISSUE TITLE
clickhouse metrics not available for remote prometheus

### ISSUE THREAD

**Issue by HelloSunilSaini** [Altinity/clickhouse-operator#1099]
Hello, i am using altinity clickhouse operator for clickhouse deployment on k8s and prometheus is deployed in different namespace using monitoring.coreos.com/v1 k8s custom resource have clickhouse-installation like below i have created pod monitor for clickhouse installation pods with targetPort 9363 but prometheus not able to see metrics from clickhouse pods

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-installation
spec:
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: svc-template
  configuration:
    settings:
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
    clusters:
      - name: cluster-1
        templates:
          podTemplate: pod-template
          serviceTemplate: svc-template
          dataVolumeClaimTemplate: data-volume-template
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9363"
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.1
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "1"
              volumeMounts:
                - name: data-volume-template
                  mountPath: /var/lib/clickhouse
    serviceTemplates:
      - name: svc-template
        generateName: svc-{chi}
        metadata:
          labels:
            custom.label: "custom.value"
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "false"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
            limits:
              storage: 200Gi
```

**Comment by Slach** [comment]
could you share your `kind: PodMonitor` manifest?

and following command results
```
kubectl get podmonitors --all-namespaces
kubectl get pod --all-namespaces -l clickhouse.altinity.com/app=chop
kubectl exec -n <your_chi_namespace> <first_pod_from_previous_command> -- wget -S -O- http://localhost:9363/metrics
```

**Comment by Slach** [comment]
open your prometheus instance
and look to Status -> Targets
do you see your clickhouse pods?

**Comment by Slach** [comment]
what return following command?
```
kubectl exec -n <your_chi_namespace> <your-clickhouse-pod-name> -- wget -S -O- http://localhost:9363/metrics
```
?

**Comment by Slach** [comment]
Do you have in your 'kind: Prometheus' following section

```yaml
spec:
  podMonitorSelector:
    matchLabels:
      app: clickhouse-installation
```
?
