### ISSUE TITLE
Can't set up secure connection for Zookeeper Nodes

### ISSUE THREAD

**Issue by Tvion** [Altinity/clickhouse-operator#1113]
We are facing the issue, that it's not possible to configure secure connection for Zookeeper nodes by using clickhouse-operator.
```
spec:
  configuration:
    zookeeper:
      nodes:
        - host: <Zookeeper host>
          port: 2181
          secure: 1
```

I found out that "secure" parameter for node is not taken into account and prepared some fix for that.

May you clarify the correct branch for pull request?
