### ISSUE TITLE
How to deploy a 3 replicas on three differents nodes

### ISSUE THREAD

**Issue by jdalia001** [Altinity/clickhouse-operator#1132]
Hi,

I am trying to deploy a cluster of 3 replicas of Clickhouse on my Kubernetes Cluster.
My Kubernetes Cluster is composed by 3 nodes (dedicated server) and I would like to deploy a replica in each node to be safe for potential loss of data.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-clickhouse-worker-01-volume
  labels:
    type: local
spec:
  storageClassName: logs-clickhouse-worker
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/k8s-logs-clickhouse-01"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-eu-de-worker-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-clickhouse-worker-02-volume
  labels:
    type: local
spec:
  storageClassName: logs-clickhouse-worker
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/k8s-logs-clickhouse-02"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-eu-de-worker-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-clickhouse-worker-03-volume
  labels:
    type: local
spec:
  storageClassName: logs-clickhouse-worker
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/k8s-logs-clickhouse-03"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-eu-de-worker-03
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  defaults:
    templates:
      podTemplate: clickhouse-stable
      volumeClaimTemplate: storage-vc-template
      hostTemplate: host-template-custom-ports
  templates:
    hostTemplates:
      - name: host-template-custom-ports
        spec:
          tcpPort: 7000
          httpPort: 7001
          interserverHTTPPort: 7002
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:21.3.20.1
              volumeMounts:
                - name: storage-vc-template
              resources:
                requests:
                  memory: 16Gi
                  cpu: "8"
                limits:
                  memory: 32Gi
                  cpu: "12"
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: "logs-clickhouse-worker"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2000Gi
  configuration:
    users:
      test/default: secret
      test/password: test
      test/profile: default
      test/quota: default
      test/networks/ip: "::/0"
    zookeeper:
      nodes:
      - host: logs-zookeeper-client
        port: 2181
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 3
```

I am trying with this configuration file but : 
1. I can not specify for each replica to use a specific PersistentVolume (Because I want Clickhouse database using a local persistent volume on the same node)
2. When I apply my config file, a can see a clickhouse operator, my all three volumes get bound but I can not see pods for each broker of database ?

Maybe I am not understanding how it should work, if someone already implemented something similar and can help :) 

Thanks
