### ISSUE TITLE
PDB is not getting created

### ISSUE THREAD

**Issue by ibotty** [Altinity/clickhouse-operator#1139]
I installed the clickhouse operator from operatorhub on OKD 4.12:
```
Server Version: 4.12.0-0.okd-2023-03-18-084815
Kubernetes Version: v1.25.0-2786+eab9cc98fe4c00-dirty
```

But when using 
```
  [...]
  templates:
    podTemplates:
      - name: default:22
        podDistribution:
        - type: CircularReplication
```
I get the following error in the operator's logs.
```
W0403 09:54:14.405036       1 worker.go:1148] unable to create PDB the server could not find the requested resource
```

And no PDB is created.

Is there anything I am missing?

My complete `clickhouseinstallation` is attached:
[clickhouse.clickhouseinstallation.txt](https://github.com/Altinity/clickhouse-operator/files/11137066/clickhouse.clickhouseinstallation.txt)
