### ISSUE TITLE
Reclaim policy at the level of my storage class is ignored 

### ISSUE THREAD

**Issue by NikitaKunashov** [Altinity/clickhouse-operator#1140]
I have the following PVC template:

```yaml

- name: data-storage-vc-template
      spec:
        storageClassName: my-class
```
And the following definition for the used storage class:

```yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Retain
```

As a result, PVs are created with the reclaim policy set to "Retain." However, the clickhouse-operator seems to consider the PVs as having a "Delete" policy and removes the corresponding PVC once I delete the ClickHouse installation. 
While specifying the reclaim policy explicitly works as a workaround, it seems more consistent to get the correct policy even if it's specified at the StorageClass level.
