### ISSUE TITLE
How to pass email id as user in clickhouse installation CR

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1146]
- This does not work, any idea how can we pass email id
```
users:
      admin@platform.local/access_management: 1
      admin@platform.local/networks/ip:
      - 0.0.0.0/0
      - ::/0
      admin@platform.local/password_sha256_hex: 9d7c8383ndjd9393
      admin@platform.local/quota: default
      admin/access_management: 1
      admin/networks/ip:
      - 0.0.0.0/0
      - ::/0
  ```

**Comment by Slach** [comment]
try
```yaml
users:
   "admin@platform.local/access_management": 1
```

**Comment by AdheipSingh** [comment]
@Slach 

```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: "settings-03"
spec:
  configuration:
    users:
      "admin@platform.local/networks/ip": "::/0"
      "admin@platform.local/password": qwerty
      "admin@platform.local/profile": default
    clusters:
      - name: cls1
        layout:
          shardsCount: 1
          replicasCount: 1
   ```
   
   Still getting the same error, here's the log
   
   
   ```
   0. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::shared_ptr<Poco::Event> const&) @ 0x1174e9e0 in /usr/bin/clickhouse
1. DB::ConfigProcessor::loadConfig(bool) @ 0x1174ec60 in /usr/bin/clickhouse
2. DB::ConfigReloader::reloadIfNewer(bool, bool, bool, bool) @ 0x11753334 in /usr/bin/clickhouse
3. DB::ConfigReloader::ConfigReloader(String const&, String const&, String const&, zkutil::ZooKeeperNodeCache&&, std::shared_ptr<Poco::Event> const&, std::function<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>, bool)>&&, bool) @ 0x11752698 in /usr/bin/clickhouse
4. DB::UsersConfigAccessStorage::load(String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf554244 in /usr/bin/clickhouse
5. DB::AccessControl::addUsersConfigStorage(String const&, String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&, bool) @ 0xf42c9d4 in /usr/bin/clickhouse
6. DB::AccessControl::addStoragesFromUserDirectoriesConfig(Poco::Util::AbstractConfiguration const&, String const&, String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf4307d8 in /usr/bin/clickhouse
7. DB::AccessControl::addStoragesFromMainConfig(Poco::Util::AbstractConfiguration const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf42b93c in /usr/bin/clickhouse
8. DB::AccessControl::setUpFromMainConfig(Poco::Util::AbstractConfiguration const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf42a850 in /usr/bin/clickhouse
9. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0xbb5f5b0 in /usr/bin/clickhouse
10. Poco::Util::Application::run() @ 0x11ee4e3c in /usr/bin/clickhouse
11. DB::Server::run() @ 0xbb548c0 in /usr/bin/clickhouse
12. Poco::Util::ServerApplication::run(int, char**) @ 0x11efa8e4 in /usr/bin/clickhouse
13. mainEntryClickHouseServer(int, char**) @ 0xbb51be0 in /usr/bin/clickhouse
14. main @ 0x7d10a60 in /usr/bin/clickhouse
15. ? @ 0x273fc in /usr/lib/aarch64-linux-gnu/libc.so.6
16. __libc_start_main @ 0x274cc in /usr/lib/aarch64-linux-gnu/libc.so.6
 (version 23.3.2.37 (official build))
2023.04.26 12:42:38.742153 [ 1 ] {} <Error> Application: Exception: Failed to merge config with '/etc/clickhouse-server/users.d/chop-generated-users.xml': SAXParseException: Invalid token in '/etc/clickhouse-server/users.d/chop-generated-users.xml', line 3 column 14
   ```
