### ISSUE TITLE
How to pass email id as user in clickhouse installation CR 

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1147]
```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: "settings-03"
spec:
  configuration:
    users:
      "admin@platform.local/networks/ip": "::/0"
      "admin@platform.local/password": qwerty
      "admin@platform.local/profile": default
    clusters:
      - name: cls1
        layout:
          shardsCount: 1
          replicasCount: 1
  ```
  @Slach we are still getting the error
  ```
  0. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::shared_ptr<Poco::Event> const&) @ 0x1174e9e0 in /usr/bin/clickhouse
1. DB::ConfigProcessor::loadConfig(bool) @ 0x1174ec60 in /usr/bin/clickhouse
2. DB::ConfigReloader::reloadIfNewer(bool, bool, bool, bool) @ 0x11753334 in /usr/bin/clickhouse
3. DB::ConfigReloader::ConfigReloader(String const&, String const&, String const&, zkutil::ZooKeeperNodeCache&&, std::shared_ptr<Poco::Event> const&, std::function<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>, bool)>&&, bool) @ 0x11752698 in /usr/bin/clickhouse
4. DB::UsersConfigAccessStorage::load(String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf554244 in /usr/bin/clickhouse
5. DB::AccessControl::addUsersConfigStorage(String const&, String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&, bool) @ 0xf42c9d4 in /usr/bin/clickhouse
6. DB::AccessControl::addStoragesFromUserDirectoriesConfig(Poco::Util::AbstractConfiguration const&, String const&, String const&, String const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf4307d8 in /usr/bin/clickhouse
7. DB::AccessControl::addStoragesFromMainConfig(Poco::Util::AbstractConfiguration const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf42b93c in /usr/bin/clickhouse
8. DB::AccessControl::setUpFromMainConfig(Poco::Util::AbstractConfiguration const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0xf42a850 in /usr/bin/clickhouse
9. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0xbb5f5b0 in /usr/bin/clickhouse
10. Poco::Util::Application::run() @ 0x11ee4e3c in /usr/bin/clickhouse
11. DB::Server::run() @ 0xbb548c0 in /usr/bin/clickhouse
12. Poco::Util::ServerApplication::run(int, char**) @ 0x11efa8e4 in /usr/bin/clickhouse
13. mainEntryClickHouseServer(int, char**) @ 0xbb51be0 in /usr/bin/clickhouse
14. main @ 0x7d10a60 in /usr/bin/clickhouse
15. ? @ 0x273fc in /usr/lib/aarch64-linux-gnu/libc.so.6
16. __libc_start_main @ 0x274cc in /usr/lib/aarch64-linux-gnu/libc.so.6
(version 23.3.2.37 (official build))
2023.04.26 12:42:38.742153 [ 1 ] {} <Error> Application: Exception: Failed to merge config with '/etc/clickhouse-server/users.d/chop-generated-users.xml': SAXParseException: Invalid token in '/etc/clickhouse-server/users.d/chop-generated-users.xml', line 3 column 14
  ```

**Comment by Slach** [comment]
could you share:
```
kubectl get cm -n <your_namespace> chi-settings-03-common-usersd -o yaml
```

without sensitive credentials?

**Comment by Slach** [comment]
in clickhouse user names stored as XML tags, which can't contains `@` inside tag name
so
<user@domain.com> is invalid

![image](https://user-images.githubusercontent.com/105560/234782110-ce003aff-cd6f-4839-b723-752670b323c6.png)


could you try remove invalid users spec, and try add it as YAML in files section explicitly?

```yaml
spec:
  configuration:
    files:
      conf.d/email_user.yaml: |
        clickhouse:
          users:
             "admin@platform.local":
                networks:
                  ip: "::/0"
                password: qwerty
                profile: default
```

**Comment by AdheipSingh** [comment]
@Slach thanks for your response. I will check this out and revert.

Thanks a lot @Slach

**Comment by AdheipSingh** [comment]
@Slach 
- on adding the above config, it gets rightly populated in this configmap ```clickhouse-deploy-confd-chi-0-0```
```
email_user.yaml: |
    yandex:
      users:
         "admin@platform.local":
            networks:
              ip: "0.0.0.0/0"
            password: qwerty
            profile: default
            quota: default
            access_management: 1
```
- But on query, i still get the error
```
Code: 516. DB::Exception: admin@platform.local: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 22.12.3.5 (official build))
```

**Comment by v4run** [comment]
Hi @Slach 

There were no matching results

```
root@chi-settings-03-cls1-0-0-0:/# grep yaml -C 10 /var/log/clickhouse-server/clickhouse-server.log
root@chi-settings-03-cls1-0-0-0:/#
```

**Comment by v4run** [comment]
I tried with the following config

```yaml
spec:
  configuration:
    files:
      conf.d/email_user.yaml: |
        users:
          'admin@platform.local':
              password: ''
              networks:
                  ip: '::/0'
              profile: default
              quota: default
```
Removed `clickhouse`

Now the pod is in CrashLoopBackOff. With following error

```
2023.05.05 07:20:51.194081 [ 1 ] {} <Error> Application: DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos' or 'ssl_certificates' must be specified for user admin@platform.local.: while parsing user 'admin@platform.local' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'
```

But instead of `admin@platform.local` if I use just `admin`, it works without any issue.

```yaml
spec:
  configuration:
    files:
      conf.d/email_user.yaml: |
        users:
          'admin':
              password: ''
              networks:
                  ip: '::/0'
              profile: default
              quota: default
```

**Comment by Slach** [comment]
do you have file inside your CH after apply changes from
https://github.com/Altinity/clickhouse-operator/issues/1147#issuecomment-1535839215 ?

`cat /etc/clickhouse-server/conf.d/email_user.yaml`

also share
`cat /var/lib/clickhouse/preprocessed_configs/users.*`
without sensitive credentials?

did you try non-empty password for 'admin@platform.local`?

**Comment by v4run** [comment]
> do you have file inside your CH after apply changes from
> [#1147 (comment)](https://github.com/Altinity/clickhouse-operator/issues/1147#issuecomment-1535839215) ?

Yes

> cat /etc/clickhouse-server/conf.d/email_user.yaml

```yaml
users:
  'admin':
      password: ''
      networks:
          ip: '::/0'
      profile: default
      quota: default
```

> also share
> `cat /var/lib/clickhouse/preprocessed_configs/users.*`
> without sensitive credentials?

```xml
<!-- This file was generated automatically.
     Do not edit it: it is likely to be discarded and generated again before it's read next time.
     Files used to generate this file:
       /etc/clickhouse-server/users.xml
       /etc/clickhouse-server/conf.d/chop-generated-hostname-ports.xml
       /etc/clickhouse-server/conf.d/chop-generated-macros.xml
       /etc/clickhouse-server/conf.d/email_user.yaml
       /etc/clickhouse-server/users.d/01-clickhouse-user.xml
       /etc/clickhouse-server/users.d/02-clickhouse-default-profile.xml
       /etc/clickhouse-server/users.d/03-database-ordinary.xml
       /etc/clickhouse-server/users.d/chop-generated-users.xml      -->

<clickhouse>
    <!-- See also the files in users.d directory where the settings can be overridden. -->

    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>

      <log_queries>1</log_queries>
      <connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
      <distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
      <parallel_view_processing>1</parallel_view_processing>

            <default_database_engine>Ordinary</default_database_engine>
        </default>

        <!-- Profile that allows only read queries. -->
        <readonly>
            <readonly>1</readonly>
        </readonly>

        <clickhouse_operator>
            <log_queries>0</log_queries>
            <skip_unavailable_shards>1</skip_unavailable_shards>
            <http_connection_timeout>10</http_connection_timeout>
        </clickhouse_operator>




    </profiles>

    <!-- Users and ACL. -->
    <users>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <!-- See also the files in users.d directory where the password can be overridden.

                 Password could be specified in plaintext or in SHA256 (in hex format).

                 If you want to specify password in plaintext (not recommended), place it in 'password' element.
                 Example: <password>qwerty</password>.
                 Password could be empty.

                 If you want to specify SHA256, place it in 'password_sha256_hex' element.
                 Example: <password_sha256_hex>65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5</password_sha256_hex>
                 Restrictions of SHA256: impossibility to connect to ClickHouse using MySQL JS client (as of July 2019).

                 If you want to specify double SHA1, place it in 'password_double_sha1_hex' element.
                 Example: <password_double_sha1_hex>e395796d6546b1b65db9d665cd43f0e858dd4303</password_double_sha1_hex>

                 If you want to specify a previously defined LDAP server (see 'ldap_servers' in the main config) for authentication,
                  place its name in 'server' element inside 'ldap' element.
                 Example: <ldap><server>my_ldap_server</server></ldap>

                 If you want to authenticate the user via Kerberos (assuming Kerberos is enabled, see 'kerberos' in the main config),
                  place 'kerberos' element instead of 'password' (and similar) elements.
                 The name part of the canonical principal name of the initiator must match the user name for authentication to succeed.
                 You can also place 'realm' element inside 'kerberos' element to further restrict authentication to only those requests
                  whose initiator's realm matches it.
                 Example: <kerberos />
                 Example: <kerberos><realm>EXAMPLE.COM</realm></kerberos>

                 How to generate decent password:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha256sum | tr -d '-'
                 In first line will be password and in second - corresponding SHA256.

                 How to generate double SHA1:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha1sum | tr -d '-' | xxd -r -p | sha1sum | tr -d '-'
                 In first line will be password and in second - corresponding double SHA1.
            -->
            <password/>

            <!-- List of networks with open access.

                 To open access from everywhere, specify:
                    <ip>::/0</ip>

                 To open access only from localhost, specify:
                    <ip>::1</ip>
                    <ip>127.0.0.1</ip>

                 Each element of list has one of the following forms:
                 <ip> IP-address or network mask. Examples: 213.180.204.3 or 10.0.0.1/8 or 10.0.0.1/255.255.255.0
                     2a02:6b8::3 or 2a02:6b8::3/64 or 2a02:6b8::3/ffff:ffff:ffff:ffff::.
                 <host> Hostname. Example: server01.clickhouse.com.
                     To check access, DNS query is performed, and all received addresses compared to peer address.
                 <host_regexp> Regular expression for host names. Example, ^server\d\d-\d\d-\d\.clickhouse\.com$
                     To check access, DNS PTR query is performed for peer address and then regexp is applied.
                     Then, for result of PTR query, another DNS query is performed and all received addresses compared to peer address.
                     Strongly recommended that regexp is ends with $
                 All results of DNS requests are cached till server restart.
            -->
            <networks>
                <ip>::1</ip>

                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.default\.svc\.cluster\.local$</host_regexp>

                <ip>127.0.0.1</ip>
                <ip>10.244.2.15</ip>
            </networks>

            <!-- Settings profile for user. -->
            <profile>default</profile>

            <!-- Quota for user. -->
            <quota>default</quota>

            <!-- User can create other users and grant rights to them. -->
            <!-- <access_management>1</access_management> -->




        </default>
    <admin>
            <password/>
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <clickhouse_operator>
            <networks>
                <ip>10.244.1.3</ip>


            </networks>
            <profile>clickhouse_operator</profile>
            <quota>default</quota>



            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
        </clickhouse_operator>



    </users>

    <!-- Quotas. -->
    <quotas>
        <!-- Name of quota. -->
        <default>
            <!-- Limits for time interval. You could specify many intervals with different limits. -->
            <interval>
                <!-- Length of interval. -->
                <duration>3600</duration>

                <!-- No limits. Just calculate resource usage for time interval. -->
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>

    <interserver_http_host>chi-settings-03-cls1-0-0</interserver_http_host>

    <macros>
        <installation>settings-03</installation>
        <all-sharded-shard>0</all-sharded-shard>
        <cluster>cls1</cluster>
        <shard>0</shard>
        <replica>chi-settings-03-cls1-0-0</replica>
    </macros>









</clickhouse>
```



> did you try non-empty password for '[admin@platform.local](mailto:admin@platform.local)`?

Yes. Still the same error.

**Comment by v4run** [comment]
For `admin@platform.local`

> cat /etc/clickhouse-server/conf.d/email_user.yaml

```yaml
users:
  'admin@platform.local':
      password: 'qwerty'
      networks:
          ip: '::/0'
      profile: default
      quota: default
```




> also share
> `cat /var/lib/clickhouse/preprocessed_configs/users.*`
> without sensitive credentials?

```xml
<!-- This file was generated automatically.
     Do not edit it: it is likely to be discarded and generated again before it's read next time.
     Files used to generate this file:
       /etc/clickhouse-server/users.xml
       /etc/clickhouse-server/conf.d/chop-generated-hostname-ports.xml
       /etc/clickhouse-server/conf.d/chop-generated-macros.xml
       /etc/clickhouse-server/conf.d/email_user.yaml
       /etc/clickhouse-server/users.d/01-clickhouse-user.xml
       /etc/clickhouse-server/users.d/02-clickhouse-default-profile.xml
       /etc/clickhouse-server/users.d/03-database-ordinary.xml
       /etc/clickhouse-server/users.d/chop-generated-users.xml      -->

<clickhouse>
    <!-- See also the files in users.d directory where the settings can be overridden. -->

    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>

      <log_queries>1</log_queries>
      <connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
      <distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
      <parallel_view_processing>1</parallel_view_processing>

            <default_database_engine>Ordinary</default_database_engine>
        </default>

        <!-- Profile that allows only read queries. -->
        <readonly>
            <readonly>1</readonly>
        </readonly>

        <clickhouse_operator>
            <log_queries>0</log_queries>
            <skip_unavailable_shards>1</skip_unavailable_shards>
            <http_connection_timeout>10</http_connection_timeout>
        </clickhouse_operator>




    </profiles>

    <!-- Users and ACL. -->
    <users>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <!-- See also the files in users.d directory where the password can be overridden.

                 Password could be specified in plaintext or in SHA256 (in hex format).

                 If you want to specify password in plaintext (not recommended), place it in 'password' element.
                 Example: <password>qwerty</password>.
                 Password could be empty.

                 If you want to specify SHA256, place it in 'password_sha256_hex' element.
                 Example: <password_sha256_hex>65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5</password_sha256_hex>
                 Restrictions of SHA256: impossibility to connect to ClickHouse using MySQL JS client (as of July 2019).

                 If you want to specify double SHA1, place it in 'password_double_sha1_hex' element.
                 Example: <password_double_sha1_hex>e395796d6546b1b65db9d665cd43f0e858dd4303</password_double_sha1_hex>

                 If you want to specify a previously defined LDAP server (see 'ldap_servers' in the main config) for authentication,
                  place its name in 'server' element inside 'ldap' element.
                 Example: <ldap><server>my_ldap_server</server></ldap>

                 If you want to authenticate the user via Kerberos (assuming Kerberos is enabled, see 'kerberos' in the main config),
                  place 'kerberos' element instead of 'password' (and similar) elements.
                 The name part of the canonical principal name of the initiator must match the user name for authentication to succeed.
                 You can also place 'realm' element inside 'kerberos' element to further restrict authentication to only those requests
                  whose initiator's realm matches it.
                 Example: <kerberos />
                 Example: <kerberos><realm>EXAMPLE.COM</realm></kerberos>

                 How to generate decent password:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha256sum | tr -d '-'
                 In first line will be password and in second - corresponding SHA256.

                 How to generate double SHA1:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha1sum | tr -d '-' | xxd -r -p | sha1sum | tr -d '-'
                 In first line will be password and in second - corresponding double SHA1.
            -->
            <password/>

            <!-- List of networks with open access.

                 To open access from everywhere, specify:
                    <ip>::/0</ip>

                 To open access only from localhost, specify:
                    <ip>::1</ip>
                    <ip>127.0.0.1</ip>

                 Each element of list has one of the following forms:
                 <ip> IP-address or network mask. Examples: 213.180.204.3 or 10.0.0.1/8 or 10.0.0.1/255.255.255.0
                     2a02:6b8::3 or 2a02:6b8::3/64 or 2a02:6b8::3/ffff:ffff:ffff:ffff::.
                 <host> Hostname. Example: server01.clickhouse.com.
                     To check access, DNS query is performed, and all received addresses compared to peer address.
                 <host_regexp> Regular expression for host names. Example, ^server\d\d-\d\d-\d\.clickhouse\.com$
                     To check access, DNS PTR query is performed for peer address and then regexp is applied.
                     Then, for result of PTR query, another DNS query is performed and all received addresses compared to peer address.
                     Strongly recommended that regexp is ends with $
                 All results of DNS requests are cached till server restart.
            -->
            <networks>
                <ip>::1</ip>

                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.default\.svc\.cluster\.local$</host_regexp>

                <ip>127.0.0.1</ip>
                <ip>10.244.2.23</ip>
            </networks>

            <!-- Settings profile for user. -->
            <profile>default</profile>

            <!-- Quota for user. -->
            <quota>default</quota>

            <!-- User can create other users and grant rights to them. -->
            <!-- <access_management>1</access_management> -->




        </default>
    <admin@platform.local>
            <password>qwerty</password>
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </admin@platform.local>
        <clickhouse_operator>
            <networks>
                <ip>10.244.1.3</ip>


            </networks>
            <profile>clickhouse_operator</profile>
            <quota>default</quota>



            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
        </clickhouse_operator>



    </users>

    <!-- Quotas. -->
    <quotas>
        <!-- Name of quota. -->
        <default>
            <!-- Limits for time interval. You could specify many intervals with different limits. -->
            <interval>
                <!-- Length of interval. -->
                <duration>3600</duration>

                <!-- No limits. Just calculate resource usage for time interval. -->
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>

    <interserver_http_host>chi-settings-03-cls1-0-0</interserver_http_host>

    <macros>
        <installation>settings-03</installation>
        <all-sharded-shard>0</all-sharded-shard>
        <cluster>cls1</cluster>
        <shard>0</shard>
        <replica>chi-settings-03-cls1-0-0</replica>
    </macros>









</clickhouse>
```

**Comment by Slach** [comment]
`<admin@platform.local>`
will invalid XML tag
and shall get CrashLoopBack for clickhouse-server pods

i tried
<admin&#64;platform.local>
but failed to auth
subscribe 
https://github.com/ClickHouse/ClickHouse/issues/50302
and watch answer from ClickHouse team

**Comment by Slach** [comment]
i tried
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: email-username
spec:
  configuration:
    files:
      users.d/admin.yaml: |-
        users:
          "admin&#64;platform.local":
            password: ""
```

but authorization still not works ;(

**Comment by Slach** [comment]
According to 
https://github.com/ClickHouse/ClickHouse/issues/50302#issuecomment-1568417536
looks like email as username allowed only for CREATE USER statement, not in XML files

so, use
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "clickhouse-initdb-scripts"
data:
  # look https://clickhouse.com/docs/en/sql-reference/statements/create/user for details 
  email_username.sql: |
    CREATE USER IF NOT EXISTS `admin@platform.local`

---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "email-user-example"
spec:
  templates:
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: log-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    podTemplates:
      - name: pod-template-with-initdb
        spec:
          volumes:
            - name: initdb-volume
              configMap:
                name: clickhouse-initdb-scripts
                defaultMode: 0555
          
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              volumeMounts:
                - name: initdb-volume
                  mountPath: /docker-entrypoint-initdb.d
                  readOnly: true
                - name: data-volume
                  mountPath: /var/lib/clickhouse
                - name: log-volume
                  mountPath: /var/log/clickhouse-server
  defaults:
    templates:
      podTemplate: pod-template-with-initdb
            
```
