### ISSUE TITLE
User Roles using operator

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1149]
- is it possible to add user role using the clickhouse operator ?

**Comment by UnamedRus** [comment]
Yeah, like that

https://github.com/ClickHouse/ClickHouse/pull/49381

BTW, i prefer of using SQL based RBAC + user storage in ZK

**Comment by Slach** [comment]
something like that
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: grants-example
spec:
  configuration:
    users:
      user_name/grants/query:
        - "GRANT SHOW ON *.*"
        - "GRANT SELECT ON *.* WITH GRANT OPTION"
```
