### ISSUE TITLE
Non-sequential update

### ISSUE THREAD

**Issue by lazywei** [Altinity/clickhouse-operator#1153]
Hi,

So we have two clusters under one CHI, and it seems whenever we apply changes, the operator will update (reconcile) the host one by one, sequentially. This takes a long time when we just want to update one of cluster (maybe the second cluster) because it needs to scan through all the pods in the first cluster.

Is there a way to skip the first cluster during the update if it's not changed, or is there other way, like parallellize the update, to speed up the whole reconciliation process? We are OK with >1 pods interrupted budget.

Thanks

**Comment by zcross** [comment]
Not addressing the "NOOP when there aren't changes" part of your question,

> or is there other way, like parallellize the update, to speed up the whole reconciliation process

Is exactly what I was pitching in #1109 (now closed, and now on `0.21.1` (thanks to the maintainers!)

**Comment by zcross** [comment]
> @zcross awesome, thank you! is there gonna be some flag to control that concurrency or is it gonna be automatic?

The new behavior is opt-in and done via configuration:
https://github.com/Altinity/clickhouse-operator/blob/dcd13781246dba98ad2273f1d08c631fdcccabce/pkg/apis/clickhouse.altinity.com/v1/type_config_chop.go#L260

Note that there is knob for how many goroutines may be used (how much capacity for parallelism there is) and another for what percentage of shards must be kept up/untouched at all times (defining the maximal level of parallelism applied regardless of capacity).

BTW, if you use this on any medium to large installations, you'll likely run into the default k8s client burst and QPS limits, in the form of some client side throttling that undermines the speed gains of the concurrent reconcile. In the PRs I proposed for #1109, I solved for that by allowing users to override these limits by setting the following env vars on the container running their CH operator:
```
OPERATOR_K8S_CLIENT_QPS_LIMIT
OPERATOR_K8S_CLIENT_BURST_LIMIT
```

**Comment by blafry** [comment]
Hi @zcross , I have performed tests on the modified functionality in `0.21.1`.

When deploying the operator, I used the following command:

```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/release-0.21.1/deploy/operator/clickhouse-operator-install-bundle.yaml
```

Scenario 1 (separate ClickHouseInstallation for each cluster):

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "alpha"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    clusters:
      - name: "alpha"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3-alpine
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "beta"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    clusters:
      - name: "beta"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3-alpine
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "gamma"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    clusters:
      - name: "gamma"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3-alpine
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "delta"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    clusters:
      - name: "delta"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3-alpine

```

Scenario 2 (one ClickHouseInstallation with multiple clusters):

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "main"
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    clusters:
      - name: "alpha"
        layout:
          shardsCount: 2
          replicasCount: 2
      - name: "beta"
        layout:
          shardsCount: 2
          replicasCount: 2
      - name: "gamma"
        layout:
          shardsCount: 2
          replicasCount: 2
      - name: "delta"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3-alpine

```

Reconcile settings:

```
    ################################################
    ##
    ## Reconcile Section
    ##
    ################################################
    reconcile:
      runtime:
        # Max number of concurrent reconciles in progress
        threadsNumber: 100
        shardsThreadNumber: 20 
        shardsMaxConcurrencyPercent: 100
```

In both scenarios, regardless of the configuration, the operator only performs reconcile for one pod of one ClickHouse cluster at a time. 

What am I doing wrong?

I would like to mention that the operator in version `0.21.0` does not have this issue; it is able to reconcile four clusters in parallel. However, it does not parallelize this at the shard level.

PS.
I also tried setting:

```
OPERATOR_K8S_CLIENT_QPS_LIMIT
OPERATOR_K8S_CLIENT_BURST_LIMIT
```
without any positive result.
