### ISSUE TITLE
Please set a default TTL for trace_log

### ISSUE THREAD

**Issue by patrickdung** [Altinity/clickhouse-operator#1156]
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/values.yaml
query_log and part_log are set to kept for 30 days

Please set a default TTL for trace_log too.
Without the setting I think the trace_log would growth and consume as much space as the PVC has.

**Comment by Slach** [comment]
check 
`SELECT * FROM system.settings WHERE name ILIKE '%profiler%' FORMAT Vertical;`
by default system.trace_log filled only one trace per second

it will grow only when you have 1k QPS

**Comment by patrickdung** [comment]
Maybe I my CH installation has problem? The trace_log is growing, I just truncated the trace_log

```
SELECT
    sum(rows) AS total_rows,
    formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed_bytes,
    formatReadableSize(sum(data_compressed_bytes)) AS compressed_bytes,
    round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS compression_rate,
    table AS table_name
FROM system.parts
WHERE database = 'system'
GROUP BY table_name
ORDER BY compressed_bytes ASC

Query id: c1db2668-3b83-4e45-9c6e-2163d8401052

┌─total_rows─┬─uncompressed_bytes─┬─compressed_bytes─┬─compression_rate─┬─table_name──────────────┐
│   95065729 │ 30.56 GiB          │ 1.57 GiB         │                5 │ trace_log_1             │
│     833191 │ 1.18 GiB           │ 110.09 MiB       │                9 │ query_log               │
│      87849 │ 401.30 MiB         │ 14.35 MiB        │                4 │ metric_log              │
│       8062 │ 2.64 MiB           │ 197.72 KiB       │                7 │ trace_log               │
│     245132 │ 775.67 MiB         │ 32.10 MiB        │                4 │ metric_log_0            │
│     242323 │ 970.15 MiB         │ 32.69 MiB        │                3 │ metric_log_1            │
│    7204016 │ 3.96 GiB           │ 481.78 MiB       │               12 │ part_log                │
│    3392955 │ 15.09 GiB          │ 566.23 MiB       │                4 │ metric_log_2            │
│    3710232 │ 1.14 GiB           │ 67.96 MiB        │                6 │ trace_log_0             │
│          5 │ 914.00 B           │ 678.00 B         │               74 │ crash_log               │
│ 1226870046 │ 17.64 GiB          │ 698.13 MiB       │                4 │ asynchronous_metric_log │
└────────────┴────────────────────┴──────────────────┴──────────────────┴─────────────────────────┘
```

**Comment by Slach** [comment]
@patrickdung unfortunatelly, we can't just add part_log in operator configs
after apply it will restart exists `kind: ClickHouseInstallation`

so you could apply it on your side

```yaml
apiVersion: clickhouse.altinity.com/v1
metadata:
  name: trace-log
spec:
  configuration:
    files:
      config.d/trace_log.xml: |-
        <trace_log replace="1">
          <database>system</database>
          <table>trace_log</table>
          <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + interval 30 day</engine>
          <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </trace_log> 
```
