### ISSUE TITLE
Pod Start fail Permission denied

### ISSUE THREAD

**Issue by zengzhengrong** [Altinity/clickhouse-operator#1183]
Operator helm verison ：0.21.2

minimal yaml below 
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "minimal"
  namespace: clickhouse
spec:
  defaults:
    templates:
      serviceTemplate: clickhouse-svc
      dataVolumeClaimTemplate: clickhouse-data
      logVolumeClaimTemplate: clickhouse-log
  troubleshoot: "yes"
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zookeeper
          port: 2181
    clusters:
      - name: replcluster
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    serviceTemplates:
      - name: clickhouse-svc
        generateName: clickhouse-{chi}
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
    volumeClaimTemplates:
      - name: clickhouse-data
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
      - name: clickhouse-log
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

kubectl.exe logs pod/chi-minimal-replcluster-0-0-0 -n clickhouse
```
Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
2023.07.01 11:42:29.879837 [ 295 ] {} <Error> void DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::AsynchronousMetricLogElement]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Permission denied ["/var/lib/clickhouse/store/6a4/6a4d4083-6cf5-4add-b5d4-78346594819f/tmp_insert_202307_27_27_0/"] ["/var/lib/clickhouse/store/6a4/6a4d4083-6cf5-4add-b5d4-78346594819f/202307_27_27_0/"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001a9962b5 in /usr/bin/clickhouse
1. ? @ 0x000000001a93ad04 in /usr/bin/clickhouse
2. ? @ 0x000000001a93aadd in /usr/bin/clickhouse
3. ? @ 0x000000001a93d130 in /usr/bin/clickhouse
4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001a9419fd in /usr/bin/clickhouse
5. DB::DiskLocal::moveDirectory(String const&, String const&) @ 0x0000000012dea572 in /usr/bin/clickhouse
6. DB::DataPartStorageOnDiskBase::rename(String, String, Poco::Logger*, bool, bool) @ 0x00000000146ba2ef in /usr/bin/clickhouse
7. DB::IMergeTreeDataPart::renameTo(String const&, bool) @ 0x00000000146e6966 in /usr/bin/clickhouse
8. DB::MergeTreeData::preparePartForCommit(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, bool) @ 0x000000001479389a in /usr/bin/clickhouse
9. DB::MergeTreeData::renameTempPartAndReplaceImpl(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::unique_lock<std::mutex>&, std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>*) @ 0x00000000147952ce in /usr/bin/clickhouse
10. DB::MergeTreeData::renameTempPartAndAdd(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::unique_lock<std::mutex>&) @ 0x0000000014795ac5 in /usr/bin/clickhouse
11. DB::MergeTreeSink::finishDelayedChunk() @ 0x0000000014ae8ad9 in /usr/bin/clickhouse
12. ? @ 0x0000000014ebe67c in /usr/bin/clickhouse
13. DB::ExceptionKeepingTransform::work() @ 0x0000000014ebde4c in /usr/bin/clickhouse
14. DB::ExecutionThreadContext::executeTask() @ 0x0000000014ca3bc9 in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014c9a890 in /usr/bin/clickhouse
16. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000014c9a048 in /usr/bin/clickhouse
17. DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(std::vector<DB::AsynchronousMetricLogElement, std::allocator<DB::AsynchronousMetricLogElement>> const&, unsigned long) @ 0x0000000013c4d9cc in /usr/bin/clickhouse
18. DB::SystemLog<DB::AsynchronousMetricLogElement>::savingThreadFunction() @ 0x0000000013c4bec0 in /usr/bin/clickhouse
19. ? @ 0x000000000e30268f in /usr/bin/clickhouse
20. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e2d1a74 in /usr/bin/clickhouse
21. ? @ 0x000000000e2d7281 in /usr/bin/clickhouse
22. ? @ 0x00007f0dd5302609 in ?
23. __clone @ 0x00007f0dd5227133 in ?

Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
```

After I add the podTemplates,  get the same error log

```
    podTemplates:
      - name: clickhouse-minimal
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
```

**Comment by Slach** [comment]
try
```yaml
       spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
```

could you execute inside pod 
`kubectl exec -n clickhouse chi-minimal-replcluster-0-0-0 -- ls -la /var/lib/clickhouse`?
