### ISSUE TITLE
PVC not honoring Retain reclaimPolicy

### ISSUE THREAD

**Issue by sebw91** [Altinity/clickhouse-operator#1199]
I have the below volume claim template with `reclaimPolicy: Retain`:
```
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: ebs-sc-xfs
          reclaimPolicy: Retain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.ebsVolumeSize }}
```
But operator is applying a Delete policy:
```
$ kubectl get pvc -o custom-columns="NAME:.metadata.name,\
 POLICY:.metadata.labels.clickhouse\.altinity\.com\/reclaimPolicy,\
 SIZE:.spec.resources.requests.storage,\
 PV:.spec.volumeName"
NAME                                                            POLICY    SIZE    PV
storage-vc-template-chi-clickhouse-0-0-0     Delete    475Gi   pvc-c211beb4-ec6f-414d-887c-bf15e778df49
```

Operator then decides to delete PVC when CHI is deleted

```
I0719 14:12:21.902130       1 deleter.go:203] PVC tc/storage-vc-template-chi-clickhouse-0-0-0 would be deleted
I0719 14:12:21.911134       1 deleter.go:212] OK delete PVC tc/storage-vc-template-chi-clickhouse-0-0-0
```

Any ideas?

**Comment by mbkh68** [comment]
This also happened to me. At the initial setup, PVCs were created with correct reclaimPolicy: Retain. But after some times we had to update eks cluster nodes which  effectively replaced all nodes with newer version. What happened was that all existing PVCs went to "Released" state and new PVCs with "reclaimPolicy" set to "Delete" which was the default value of associated storage class was created and bound to existing volumes.
Need to know if this is a bug and how to prevent this in future.

**Comment by Slach** [comment]
@mbkh68 
EKS worker nodes upgrade shall not affect `reclaimPolicy`

could you share your `kind: ClickHouseInstallation` manifest?

`kubectl get chi -n your-namespace your-chi-name -o yaml`

**Comment by mbkh68** [comment]
Thank you @Slach 
here is my ClickHouseInstallation file:

`apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "clickhouse"
  namespace: ${namespace}

spec:
  defaults:
    templates:
      serviceTemplate: default-service-template
  configuration:
    files:
      config.d/force_drop_table.xml: |
        <yandex>
          <max_partition_size_to_drop>0</max_partition_size_to_drop>
          <max_table_size_to_drop>0</max_table_size_to_drop>
        </yandex>
      openssl_client.xml: |
        <clickhouse>
          <openSSL>
            <client>
              <loadDefaultCAFile>false</loadDefaultCAFile>
              <caConfig>/etc/clickhouse-server/secrets.d/ca.crt/clickhouse-tls-cert/ca.crt</caConfig>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
              <verificationMode>none</verificationMode>                
              <invalidCertificateHandler>
                <name>AcceptCertificateHandler</name>
              </invalidCertificateHandler>
            </client>
          </openSSL>
        </clickhouse>
      openssl.xml: |
        <clickhouse>
          <openSSL>
            <server>
              <certificateFile>/etc/clickhouse-server/secrets.d/server.crt/clickhouse-tls-cert/server.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-server/secrets.d/server.key/clickhouse-tls-cert/server.key</privateKeyFile>
              <dhParamsFile>/etc/clickhouse-server/secrets.d/dhparam.pem/clickhouse-tls-cert/dhparam.pem</dhParamsFile>
              <verificationMode>none</verificationMode>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
            </server>
          </openSSL>
        </clickhouse>
      ca.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: ca.crt
      server.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: server.crt
      server.key:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: server.key
      dhparam.pem:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: dhparam.pem
      kafka.conf: |
        <clickhouse>
          <kafka>
            <sasl_username>${kafka_username}</sasl_username>
            <sasl_password>${kafka_password}</sasl_password>
            <security_protocol>${kafka_security_protocol}</security_protocol>
            <sasl_mechanisms>${kafka_sasl_mechanisms}</sasl_mechanisms>            
            <enable_ssl_certificate_verification>false</enable_ssl_certificate_verification>
          </kafka>
        </clickhouse>
      keeper_map.conf: |
        <clickhouse>
          <keeper_map_path_prefix>/keeper_map_tables</keeper_map_path_prefix>
        </clickhouse>
    users:
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/password_sha256_hex: ${admin_hashed_password}

      backup/networks/ip: "::/0"
      backup/profile: default
      backup/password_sha256_hex: ${backup_hashed_password}

      service-control/networks/ip: "::/0"
      service-control/profile: readonly
      service-control/password_sha256_hex: ${sc_hashed_password}
    zookeeper:
      nodes:
        ${indent(8, zk_nodes)}
    settings:
      interserver_http_port: _removed_
      interserver_https_port: 9009
      tcp_port: 9000 # keep for localhost
      tcp_port_secure: 9440
      https_port: 8443
      logger/level: information
    clusters:
      - name: ${cluster_name}
        secure: "yes"
        insecure: "no"
        secret:
          auto: "yes"
        layout:
          shards:
          ${indent(10, shards)}
        templates:
          podTemplate: pod-template-with-volumes

  templates:
    serviceTemplates:
      - generateName: clickhouse-{chi}
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ${host_name}.
            external-dns.alpha.kubernetes.io/ttl: '60'
            service.beta.kubernetes.io/load-balancer-source-ranges: ${allowed_ip_ranges}
        name: default-service-template
        spec:
          ports:
            - name: https
              port: 8443
            - name: secureclient
              port: 9440
          type: LoadBalancer
    volumeClaimTemplates:
      - name: data-storage-vc-template
        reclaimPolicy: Retain
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${data_storage_size}
      - name: log-storage-vc-template
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${log_storage_size}
    podTemplates:
      - name: pod-template-with-volumes-us-west-2a
        zone:
          values:
            - "us-west-2a"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}

      - name: pod-template-with-volumes-us-west-2b
        zone:
          values:
            - "us-west-2b"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}
      - name: pod-template-with-volumes-us-west-2c
        zone:
          values:
            - "us-west-2c"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}
      - name: pod-template-with-volumes-default
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}`

**Comment by mbkh68** [comment]
Thank you @Slach 
Here is my ClickHouseInstallation file:
Also I use release-0.23.0 version.

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "clickhouse"
  namespace: ${namespace}

spec:
  defaults:
    templates:
      serviceTemplate: default-service-template
  configuration:
    files:
      config.d/force_drop_table.xml: |
        <yandex>
          <max_partition_size_to_drop>0</max_partition_size_to_drop>
          <max_table_size_to_drop>0</max_table_size_to_drop>
        </yandex>
      openssl_client.xml: |
        <clickhouse>
          <openSSL>
            <client>
              <loadDefaultCAFile>false</loadDefaultCAFile>
              <caConfig>/etc/clickhouse-server/secrets.d/ca.crt/clickhouse-tls-cert/ca.crt</caConfig>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
              <verificationMode>none</verificationMode>                
              <invalidCertificateHandler>
                <name>AcceptCertificateHandler</name>
              </invalidCertificateHandler>
            </client>
          </openSSL>
        </clickhouse>
      openssl.xml: |
        <clickhouse>
          <openSSL>
            <server>
              <certificateFile>/etc/clickhouse-server/secrets.d/server.crt/clickhouse-tls-cert/server.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-server/secrets.d/server.key/clickhouse-tls-cert/server.key</privateKeyFile>
              <dhParamsFile>/etc/clickhouse-server/secrets.d/dhparam.pem/clickhouse-tls-cert/dhparam.pem</dhParamsFile>
              <verificationMode>none</verificationMode>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
            </server>
          </openSSL>
        </clickhouse>
      ca.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: ca.crt
      server.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: server.crt
      server.key:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: server.key
      dhparam.pem:
        valueFrom:
          secretKeyRef:
            name: clickhouse-tls-cert
            key: dhparam.pem
      kafka.conf: |
        <clickhouse>
          <kafka>
            <sasl_username>${kafka_username}</sasl_username>
            <sasl_password>${kafka_password}</sasl_password>
            <security_protocol>${kafka_security_protocol}</security_protocol>
            <sasl_mechanisms>${kafka_sasl_mechanisms}</sasl_mechanisms>            
            <enable_ssl_certificate_verification>false</enable_ssl_certificate_verification>
          </kafka>
        </clickhouse>
      keeper_map.conf: |
        <clickhouse>
          <keeper_map_path_prefix>/keeper_map_tables</keeper_map_path_prefix>
        </clickhouse>
    users:
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/password_sha256_hex: ${admin_hashed_password}

      backup/networks/ip: "::/0"
      backup/profile: default
      backup/password_sha256_hex: ${backup_hashed_password}

      service-control/networks/ip: "::/0"
      service-control/profile: readonly
      service-control/password_sha256_hex: ${sc_hashed_password}
    zookeeper:
      nodes:
        ${indent(8, zk_nodes)}
    settings:
      interserver_http_port: _removed_
      interserver_https_port: 9009
      tcp_port: 9000 # keep for localhost
      tcp_port_secure: 9440
      https_port: 8443
      logger/level: information
    clusters:
      - name: ${cluster_name}
        secure: "yes"
        insecure: "no"
        secret:
          auto: "yes"
        layout:
          shards:
          ${indent(10, shards)}
        templates:
          podTemplate: pod-template-with-volumes

  templates:
    serviceTemplates:
      - generateName: clickhouse-{chi}
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ${host_name}.
            external-dns.alpha.kubernetes.io/ttl: '60'
            service.beta.kubernetes.io/load-balancer-source-ranges: ${allowed_ip_ranges}
        name: default-service-template
        spec:
          ports:
            - name: https
              port: 8443
            - name: secureclient
              port: 9440
          type: LoadBalancer
    volumeClaimTemplates:
      - name: data-storage-vc-template
        reclaimPolicy: Retain
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${data_storage_size}
      - name: log-storage-vc-template
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${log_storage_size}
    podTemplates:
      - name: pod-template-with-volumes-us-west-2a
        zone:
          values:
            - "us-west-2a"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}

      - name: pod-template-with-volumes-us-west-2b
        zone:
          values:
            - "us-west-2b"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}
      - name: pod-template-with-volumes-us-west-2c
        zone:
          values:
            - "us-west-2c"
        distribution: "OnePerHost"
        spec:
          serviceAccountName: ${service_account}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
            - name: clickhouse-backup
              ${indent(14, backup_container)}
      - name: pod-template-with-volumes-default
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:${clickhouse_version}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources: ${resources}
```
