### ISSUE TITLE
Using Kubernetes tolerations for Clickhouse podTemplate

### ISSUE THREAD

**Issue by Philippians413** [Altinity/clickhouse-operator#1200]
We need to add Kubernetes tolerations for clickhouse, but I can't find this functionality in clickhouse-operator 0.17.0

I have only zone
```
                        zone:
                          description: allows define custom zone name and will separate
                            ClickHouse `Pods` between nodes, shortcut for `chi.spec.templates.podTemplates.spec.affinity.podAntiAffinity`
                          properties:
                            key:
                              description: optional, if defined, allows select kubernetes
                                nodes by label with `name` equal `key`
                              type: string
                            values:
                              description: optional, if defined, allows select kubernetes
                                nodes by label with `value` in `values`
                              items:
                                type: string
                              type: array
                          type: object
```

Is it possible to add tolerations with clickhouse-operator?

**Comment by Slach** [comment]
Please upgrade `clickhouse-operator` to 0.21.2

you can define spec.templates.podTemplates
and use 
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: affinity-example
spec:
  defaults:
    templates:
      podTemplate: affinity
  templates:
    podTemaplates:
    - name: affinity
      spec:
        nodeSelector:
        ...
        affinity:
          nodeAffinity: 
          ...
          podAntiAffinity:
          ...
          podAffinity:
          ...
```

looks examples in `kubectl explain pod.spec`
