### ISSUE TITLE
how to change the timezone for clickhouse cluster?

### ISSUE THREAD

**Issue by the-elder** [Altinity/clickhouse-operator#1202]
thanks for the project! i use the operator to deploy our clickhouse cluster.
where can i change the timezone for clickhouse cluster?

**Comment by the-elder** [comment]
i use a replication-zookeeper template:
![image](https://github.com/Altinity/clickhouse-operator/assets/28731366/86bc9675-ddaf-48a5-aa6b-479e53b5250b)

**Comment by Slach** [comment]
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-timezone

```yaml
spec:
  configuration:
    settings:
       timezone: Asia/Yekaterinburg    
```
