### ISSUE TITLE
Enable access_management for a clickhouse_operator user

### ISSUE THREAD

**Issue by alekseipalshin** [Altinity/clickhouse-operator#1204]
Hi. 
Is it possible to add `access_management` for a `clickhouse_operator` user as an option?
It may not be very secure, but I think that sometimes it would be very convenient.   
To create a user, for example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-create-user
data:
  01_create_user.sh: |
    #!/bin/bash
    set -e
    clickhouse client -n <<-EOSQL
      CREATE USER IF NOT EXISTS user IDENTIFIED WITH sha256_hash BY '4d182859ac1302c529c981352aaa76977...8b879d';
      GRANT ALL ON db.* TO user;
    EOSQL
```

**Comment by Slach** [comment]
Add the following fragment to your CHI
```yaml
spec:
  configuration:
    users:
      clickhouse_operator/access_management: 1
```
