### ISSUE TITLE
Incorrect node names after cluster name change

### ISSUE THREAD

**Issue by Hubbitus** [Altinity/clickhouse-operator#1208]
Hello.

We have had the cluster:
```yaml
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "bi-clickhouse"
spec:
  configuration:
    users:
      clickhouse_operator/networks/ip:
        - "::/0"
      clickhouse_operator/password_sha256_hex: ********
      clickhouse_operator/profile: default
      clickhouse_operator/quota: default
      admin/networks/ip:
        - "::/0"
      admin/password_sha256_hex: ********
      admin/profile: default
      admin/quota: default
      admin/access_management: 1
    zookeeper:
      nodes:
        - host: zookeeper-headless.zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: /clickhouse
    clusters:
      - name: "bi-clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: default-volume-claim
...
```

And then had changed to (relevant part):
```yaml
    clusters:
      - name: "gid"
        layout:
          replicasCount: 2
```

After applying all changes, distributed commands like:
```sql
CREATE DATABASE datamart ON CLUSTER gid;
```
does not work with timeout.

Pod `chi-bi-clickhouse-gid-0-0-0` logs looks like:

```
2023.07.25 13:27:17.705417 [ 324 ] {} <Debug> DDLWorker: Will schedule 12 tasks starting from query-0000000021
2023.07.25 13:27:17.715424 [ 324 ] {} <Error> DNSResolver: Cannot resolve host (chi-bi-clickhouse-bi-clickhouse-0-0), error 0: Host not found.
2023.07.25 13:27:17.716497 [ 324 ] {} <Error> DDLWorker: Unexpected error, will try to restart main thread: Code: 198. DB::Exception: Not found address of host: chi-bi-clickhouse-bi-clickhouse-0-0. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe22f215 in /usr/bin/clickhouse
1. ? @ 0x8db6d24 in /usr/bin/clickhouse
2. ? @ 0xe2017ad in /usr/bin/clickhouse
3. ? @ 0xe1ff828 in /usr/bin/clickhouse
4. ? @ 0xe2006ce in /usr/bin/clickhouse
5. DB::DNSResolver::resolveAddress(String const&, unsigned short) @ 0xe200ea7 in /usr/bin/clickhouse
6. DB::HostID::isLocalAddress(unsigned short) const @ 0x12ebecec in /usr/bin/clickhouse
7. DB::DDLTask::findCurrentHostID(std::shared_ptr<DB::Context const>, Poco::Logger*) @ 0x12ec1f6d in /usr/bin/clickhouse
8. DB::DDLWorker::initAndCheckTask(String const&, String&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x12ece20e in /usr/bin/clickhouse
9. DB::DDLWorker::scheduleTasks(bool) @ 0x12ed2237 in /usr/bin/clickhouse
10. DB::DDLWorker::runMainThread() @ 0x12ecba5e in /usr/bin/clickhouse
11. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x12ee12a9 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2fe553 in /usr/bin/clickhouse
13. ? @ 0xe3041c1 in /usr/bin/clickhouse
14. ? @ 0x7d87c0273609 in ?
15. clone @ 0x7d87c0198133 in ?
 (version 23.3.8.21 (official build))
```

So, main there is "DB::Exception: Not found address of host: chi-bi-clickhouse-bi-clickhouse-0-0".

Indeed, after some digging, we found the service still called `chi-bi-clickhouse-bi-clickhouse`

So `chi-bi-clickhouse-gid-0-0.gidplatform-dev.svc.cluster.local` is resolved normally and have service, but `chi-bi-clickhouse-gid-0-0.gidplatform-dev.svc.cluster.local` indeed unknown.

Meantime:
```sql
SELECT cluster, replica_num, host_name
FROM system.clusters
WHERE cluster = 'gid'
```
returns:

cluster | replica_num | host_name
-- | -- | --
gid | 1 | chi-bi-clickhouse-gid-0-0
gid | 2 | chi-bi-clickhouse-gid-0-1

# Ugly workaround

Changing metadata name to "gid":
```yaml
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "gid"
```
We got it working:
```sql
SELECT cluster, replica_num, host_name
FROM system.clusters
WHERE cluster = 'gid'
```
But in that case pods also renamed into `chi-gid-gid-0-0`, `chi-gid-gid-0-1`, but we want to see there `clickhouse` in name.

Please help.

**Comment by Slach** [comment]
Could you clarify
did you delete "bi-clickhouse" cluster yaml part inside "bi-clickhouse" and replace it to "gid"?
Did you wait chen CHI status Complete after apply following changes?

```
  clusters:
      - name: "gid"
        layout:
          replicasCount: 2
```
