### ISSUE TITLE
Making password encryption optional

### ISSUE THREAD

**Issue by nazerpanahi** [Altinity/clickhouse-operator#1209]
Encrypting `username/password` field automatically makes us to not able to use PostgreSQL interface (this interface only accepts plaintext method).

I think this part is problematic is not configurable. 
https://github.com/Altinity/clickhouse-operator/blob/32ef0fadc3d07884845a1ee3d91be6b6e112ac62/pkg/model/normalizer.go#L1269

Checkout here for more info on this: https://github.com/ClickHouse/ClickHouse/issues/28159

**Comment by Slach** [comment]
as quick workaround you can always use

```yaml
spec:
  configuration:
    files:
      users.d/plain_password.xml: |
        <clickhouse><users><user_name><password>plain_password</password></user_name></users></clickhouse>
```
