### ISSUE TITLE
Missing "ownerReferences" for PVC

### ISSUE THREAD

**Issue by freedbka** [Altinity/clickhouse-operator#1215]
Hi, I'm using ArgoCD to deploy a click-house cluster. After creating PVC ArgoCD Goes to kill them.

![image](https://github.com/Altinity/clickhouse-operator/assets/20434155/aa10a296-58e2-4348-810a-9b564c4db341)
Because this resource does not have a binding to the cluster
_____________________
For example, the rest of the resources have the following values:
```
ownerReferences:
    - apiVersion: clickhouse.altinity.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: ClickHouseInstallation
      name: repl-04
      uid: f496f792-58a3-47c8-ba8c-dc62d4904f65
 ```
In fact, it works and is not deleted because it is attached to the pod, but if the pod dies and remains autoprune, then the data will go with it.

My manifest
-------
```
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "repl-04"
  namespace: **********
  finalizers:
    - finalizer.clickhouseinstallation.altinity.com
spec:
  defaults:
    storageManagement:
      provisioner: Operator
      reclaimPolicy: Retain
    templates:
      podTemplate: clickhouse-v22.2
      dataVolumeClaimTemplate: default-volume-claim
  configuration:
    users:
      default/k8s_secret_password: kopachev-test/clickhouse-credentials/default
      kopachev/k8s_secret_password: kopachev-test/clickhouse-credentials/kopachev
      kopavhev/allow_databases/database:
        - "kopachev"
        - "system"
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-1.zookeepers.zoo3ns
          port: 2181
        - host: zookeeper-2.zookeepers.zoo3ns
          port: 2181
    clusters:
      - name: replcluster
        templates:
          podTemplate: clickhouse-with-volume-template
          dataVolumeClaimTemplate: default-volume-claim
        layout:
          shardsCount: 1
          replicasCount: 3
  templates:
    podTemplates:
      - name: clickhouse-v22.3
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.3
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
    volumeClaimTemplates:
      - name: default-volume-claim
        provisioner: Operator
        reclaimPolicy: Retain
        spec:
          storageClassName: kops-csi-1-21
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
              ```
 Thanks!
