### ISSUE TITLE
Fresh Install AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1217]
Following the guide here: https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md

2 steps install results with AUTHENTICATION_FAILED. Any idea as to why that is? New to this software and trying to test it out, but struggling to access DB externally to start. I can exec to the pod though and all services are accessible. 

My installation looked as follows :

kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml
kubectl apply  -n ck -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/docs/chi-examples/01-simple-layout-01-1shard-1repl.yaml

ansible@lb:~$ k get pods -n ck
NAME                         READY   STATUS    RESTARTS   AGE
chi-simple-01-simple-0-0-0   1/1     Running   0          38s

ansible@lb:~$ k get svc -n ck
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                         AGE
chi-simple-01-simple-0-0   ClusterIP      None            <none>          9000/TCP,8123/TCP,9009/TCP      15s
clickhouse-simple-01       LoadBalancer   10.100.62.151   192.168.3.208   8123:30799/TCP,9000:32014/TCP   12s

 ./clickhouse client -h 192.168.3.208 -u clickhouse_operator --password clickhouse_operator_password 
ClickHouse client version 23.8.1.1186 (official build).
Connecting to 192.168.3.208:9000 as user clickhouse_operator.
Code: 516. DB::Exception: Received from 192.168.3.208:9000. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)

./clickhouse client -h 192.168.3.208 --port=8123 -u clickhouse_operator --password clickhouse_operator_password 
ClickHouse client version 23.8.1.1186 (official build).
Connecting to 192.168.3.208:8123 as user clickhouse_operator.

nothing on the logs is related to the error I'm seeing.

**Comment by Slach** [comment]
on the latest version clickhouse_operator user restricted by clickhouse-operator deployment pod IP

use
```yaml
spec:
 configuration:  
   users: 
     user_name/password: password    
```

**Comment by darioneto** [comment]
Thanks for your reply, I tried that with the first simplest deployment but still doesn't work
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users: 
      user_name/password: password    
```
Just to clarify above would apply to access it I should be running:

"./clickhouse client --host 192.168.3.208   -u clickhouse_operator -password password" ?
"./clickhouse client --host 192.168.3.208   -u password -password password" ?
"./clickhouse client -h 192.168.3.208 -u clickhouse_operator --password clickhouse_operator_password"?

tried multiple combinations and was still unable o access lol 
```
./clickhouse client --host 192.168.3.208   -u clickhouse_operator
ClickHouse client version 23.8.1.1186 (official build).
Connecting to 192.168.3.208:9000 as user clickhouse_operator.
Password for user (clickhouse_operator):
Connecting to 192.168.3.208:9000 as user clickhouse_operator.
Code: 516. DB::Exception: Received from 192.168.3.208:9000. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)
```

**Comment by Slach** [comment]
`./clickhouse client --host 192.168.3.208 -u user_name --password="password"`

**Comment by darioneto** [comment]
that didn't work neither
➜  Downloads ./clickhouse client --host 192.168.3.208 -u user_name --password="password"
ClickHouse client version 23.8.1.1186 (official build).
Connecting to 192.168.3.208:9000 as user user_name.
Code: 516. DB::Exception: Received from 192.168.3.208:9000. DB::Exception: user_name: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)

**Comment by Slach** [comment]
Could you share?
`kubectl exec -n ck chi-simple-01-simple-0-0-0 -- grep -r user_name /etc/clickhouse-server/`

**Comment by darioneto** [comment]
```
ansible@lb:~/kube/local_pods/clickhouse/clickhouse-operator$ kubectl exec -n ck chi-simple-01-simple-0-0-0 -- grep -r user_name /etc/clickhouse-server/
/etc/clickhouse-server/users.d/..2023_08_10_08_37_50.1250118734/chop-generated-users.xml:        <user_name>
/etc/clickhouse-server/users.d/..2023_08_10_08_37_50.1250118734/chop-generated-users.xml:        </user_name>
/etc/clickhouse-server/config.xml:                        The resulting DN will be constructed by replacing all '{user_name}' substrings of the template with the actual
/etc/clickhouse-server/config.xml:                            The resulting DN will be constructed by replacing all '{user_name}' and '{bind_dn}' substrings
/etc/clickhouse-server/config.xml:                            The resulting filter will be constructed by replacing all '{user_name}', '{bind_dn}', and '{base_dn}'
/etc/clickhouse-server/config.xml:                    <bind_dn>uid={user_name},ou=users,dc=example,dc=com</bind_dn>
/etc/clickhouse-server/config.xml:                    <bind_dn>EXAMPLE\{user_name}</bind_dn>
/etc/clickhouse-server/config.xml:                        <search_filter>(&amp;(objectClass=user)(sAMAccountName={user_name}))</search_filter>
/etc/clickhouse-server/config.xml:                            The resulting DN will be constructed by replacing all '{user_name}', '{bind_dn}', and '{user_dn}'
/etc/clickhouse-server/config.xml:                            The resulting filter will be constructed by replacing all '{user_name}', '{bind_dn}', '{user_dn}', and
ansible@lb:~/kube/local_pods/clickhouse/clickhouse-operator$ 
```
By the way, this is on master latest version with this manifest:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users: 
      user_name/password: password    
```

There were no other changes or modifications. 

running this still refuse to access :
➜  Downloads ./clickhouse client --host 192.168.3.208 -u user_name --password="password"
ClickHouse client version 23.8.1.1186 (official build).
Connecting to 192.168.3.208:9000 as user user_name.
Code: 516. DB::Exception: Received from 192.168.3.208:9000. DB::Exception: user_name: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)

**Comment by Slach** [comment]
try apply
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users: 
      user_name/password: password
      user_name/networks/ip: 0.0.0.0/0    
```
