### ISSUE TITLE
Clickhouse 0.21.3 readiness and liveness are failing.

### ISSUE THREAD

**Issue by Jojoooo1** [Altinity/clickhouse-operator#1220]
After installing operator 0.21.3 and using local [k3s](https://github.com/k3s-io/k3s)

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/Altinity/clickhouse-operator/release-0.21.3/deploy/operator/clickhouse-operator-install-bundle.yaml
```

I am trying to install the following cluster:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
```

the liveness and readiness are failing with "Readiness probe failed: Get "http://10.42.0.29:8123/ping": dial tcp 10.42.0.29:8123: connect: connection refused" I am able to curl localhost:8123/ping 127.0.0.1:8123/ping from inside the container

**Comment by Slach** [comment]
do you have any `kind: ClickHouseInstallationTemplate` manifest?

`kubectl get chit --all-namespaces`

**Comment by Jojoooo1** [comment]
Made it work using podTemplate

```yaml
    podTemplates:
      - name: pod-with-health-check-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              livenessProbe:
                failureThreshold: 10
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 60
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 10
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
```

but not sure it is the right way to fix it.

**Comment by Jojoooo1** [comment]
@Slach very simple setup without any mesh and the following k3s config

```yaml
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
etcd-expose-metrics: true
```

Here is the complete setup: https://github.com/Jojoooo1/argo-deploy
