### ISSUE TITLE
sudden disappearance of CHI pods

### ISSUE THREAD

**Issue by prashant-shahi** [Altinity/clickhouse-operator#1221]
After running the clickhouse for couple of months, the CHI pod has disappeared on its own.

@hodgesrm had advised on adding `stop: "no"` for fix. However, I had already resolved by changing shard count and reverting, to trigger re-creation of CHI pod (by changing state of CHI out of completed to force pod re-creation).

Nevertheless, we had been unable to find the root cause of the issue. So, this issue could re-appear in the future.

CHI definition:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: my-release-clickhouse
  namespace: default
  labels:
    helm.sh/chart: clickhouse-23.12.2
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/version: "22.8.8"
    app.kubernetes.io/managed-by: Helm
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
      serviceTemplate: service-template

  configuration:
    users:
      admin/password: redacted
      admin/networks/ip:
        - "10.0.0.0/8"
        - "100.64.0.0/10"
        - "172.16.0.0/12"
        - "192.0.0.0/24"
        - "198.18.0.0/15"
        - "192.168.0.0/16"
      admin/profile: default
      admin/quota: default

    profiles:
      default/allow_experimental_window_functions: "1"
      default/allow_nondeterministic_mutations: "1"

    clusters:
      - name: "cluster"
        templates:
          podTemplate: pod-template
        layout:
          replicasCount: 1
          shardsCount: 1

    settings:
      format_schema_path: /etc/clickhouse-server/config.d/
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      user_defined_executable_functions_config: /etc/clickhouse-server/functions/custom-functions.xml
      user_scripts_path: /var/lib/clickhouse/user_scripts/

    files:
      events.proto: |
        syntax = "proto3";
        message Event {
          string uuid = 1;
          string event = 2;
          string properties = 3;
          string timestamp = 4;
          uint64 team_id = 5;
          string distinct_id = 6;
          string created_at = 7;
          string elements_chain = 8;
        }
    zookeeper:
      nodes:
        - host: my-release-zookeeper-0.my-release-zookeeper-headless
          port: 2181

  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            helm.sh/chart: clickhouse-23.12.2
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/instance: my-release
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/version: "22.8.8"
            app.kubernetes.io/managed-by: Helm
          annotations: {}
        podDistribution:
          - topologyKey: kubernetes.io/hostname
            type: ReplicaAntiAffinity
        spec:          
          serviceAccountName: my-release-clickhouse
          priorityClassName: ""
          securityContext:
            fsGroup: 101
            runAsGroup: 101
            runAsUser: 101

          volumes:
            - name: shared-binary-volume
              emptyDir: {}
            - name: custom-functions-volume
              configMap:
                name: my-release-clickhouse-custom-functions
          initContainers: []
          containers:
            - name: clickhouse
              image: docker.io/clickhouse/clickhouse-server:22.8.8-alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml

              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009

              volumeMounts:
                - name: data-volumeclaim-template
                  mountPath: /var/lib/clickhouse
                - name: shared-binary-volume
                  mountPath: /var/lib/clickhouse/user_scripts
                - name: custom-functions-volume
                  mountPath: /etc/clickhouse-server/functions
              resources: 
                requests:
                  cpu: 100m
                  memory: 200Mi

    serviceTemplates:
      - name: service-template
        generateName: my-release-clickhouse
        metadata:
          labels:
            helm.sh/chart: clickhouse-23.12.2
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/instance: my-release
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/version: "22.8.8"
            app.kubernetes.io/managed-by: Helm
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
              nodePort: null
            - name: tcp
              port: 9000
              nodePort: null
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: standard
```

Context: [Slack Message](https://altinitydbworkspace.slack.com/archives/C02K1MWEK2L/p1692251839060289)
