### ISSUE TITLE
Admin credentials wont work when using admin/k8_secret_password

### ISSUE THREAD

**Issue by AlejandroUPC** [Altinity/clickhouse-operator#1236]
After installing the clickhouse operator and creating two identical(besides access_management) users on the version 0.21.3:

1. user2 with plain text password
2. admin with password being referenced to a secret

The authentication is only working with the user2 and for admin fails with:

`Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: admin: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)`

**manifest.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
type: Opaque
stringData:
  admin-password: admin
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: "settings-03"
spec:
  configuration:
    users:
      user2/networks/ip: "::/0"
      user2/password: qwerty
      user2/profile: default
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/k8s_secret_password: clickhouse-credentials/admin-password
      admin/access_management: 1
    clusters:
      - name: cls1
        layout:
          shardsCount: 1
          replicasCount: 1
```

**users.xml**
```xml
<clickhouse>
    <!-- See also the files in users.d directory where the settings can be overridden. -->

    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>
        </default>

        <!-- Profile that allows only read queries. -->
        <readonly>
            <readonly>1</readonly>
        </readonly>
    </profiles>

    <!-- Users and ACL. -->
    <users>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <!-- See also the files in users.d directory where the password can be overridden.

                 Password could be specified in plaintext or in SHA256 (in hex format).

                 If you want to specify password in plaintext (not recommended), place it in 'password' element.
                 Example: <password>qwerty</password>.
                 Password could be empty.

                 If you want to specify SHA256, place it in 'password_sha256_hex' element.
                 Example: <password_sha256_hex>65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5</password_sha256_hex>
                 Restrictions of SHA256: impossibility to connect to ClickHouse using MySQL JS client (as of July 2019).

                 If you want to specify double SHA1, place it in 'password_double_sha1_hex' element.
                 Example: <password_double_sha1_hex>e395796d6546b1b65db9d665cd43f0e858dd4303</password_double_sha1_hex>

                 If you want to specify a previously defined LDAP server (see 'ldap_servers' in the main config) for authentication,
                  place its name in 'server' element inside 'ldap' element.
                 Example: <ldap><server>my_ldap_server</server></ldap>

                 If you want to authenticate the user via Kerberos (assuming Kerberos is enabled, see 'kerberos' in the main config),
                  place 'kerberos' element instead of 'password' (and similar) elements.
                 The name part of the canonical principal name of the initiator must match the user name for authentication to succeed.
                 You can also place 'realm' element inside 'kerberos' element to further restrict authentication to only those requests
                  whose initiator's realm matches it.
                 Example: <kerberos />
                 Example: <kerberos><realm>EXAMPLE.COM</realm></kerberos>

                 How to generate decent password:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha256sum | tr -d '-'
                 In first line will be password and in second - corresponding SHA256.

                 How to generate double SHA1:
                 Execute: PASSWORD=$(base64 < /dev/urandom | head -c8); echo "$PASSWORD"; echo -n "$PASSWORD" | sha1sum | tr -d '-' | xxd -r -p | sha1sum | tr -d '-'
                 In first line will be password and in second - corresponding double SHA1.
            -->
            <password></password>

            <!-- List of networks with open access.

                 To open access from everywhere, specify:
                    <ip>::/0</ip>

                 To open access only from localhost, specify:
                    <ip>::1</ip>
                    <ip>127.0.0.1</ip>

                 Each element of list has one of the following forms:
                 <ip> IP-address or network mask. Examples: 213.180.204.3 or 10.0.0.1/8 or 10.0.0.1/255.255.255.0
                     2a02:6b8::3 or 2a02:6b8::3/64 or 2a02:6b8::3/ffff:ffff:ffff:ffff::.
                 <host> Hostname. Example: server01.clickhouse.com.
                     To check access, DNS query is performed, and all received addresses compared to peer address.
                 <host_regexp> Regular expression for host names. Example, ^server\d\d-\d\d-\d\.clickhouse\.com$
                     To check access, DNS PTR query is performed for peer address and then regexp is applied.
                     Then, for result of PTR query, another DNS query is performed and all received addresses compared to peer address.
                     Strongly recommended that regexp is ends with $
                 All results of DNS requests are cached till server restart.
            -->
            <networks>
                <ip>::/0</ip>
            </networks>

            <!-- Settings profile for user. -->
            <profile>default</profile>

            <!-- Quota for user. -->
            <quota>default</quota>

            <!-- User can create other users and grant rights to them. -->
            <!-- <access_management>1</access_management> -->
        </default>
    </users>

    <!-- Quotas. -->
    <quotas>
        <!-- Name of quota. -->
        <default>
            <!-- Limits for time interval. You could specify many intervals with different limits. -->
            <interval>
                <!-- Length of interval. -->
                <duration>3600</duration>

                <!-- No limits. Just calculate resource usage for time interval. -->
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```

**chop-generated-users.xml**
```xml
<yandex>
    <users>
        <admin>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <clickhouse_operator>
            <networks>
                <ip>10.1.0.58</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <user2>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user2>
    </users>
</yandex>
```

**Comment by Slach** [comment]
looks like root reason is 
```
<host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
```

could you add to your kind: ClickHouseInstallation
```yaml
spec:
  configuration:
    users:
      admin/networks/host_regexp: "\.test-clickhouse-operator\.svc\.cluster\.local$"
```

**Comment by AlejandroUPC** [comment]
Triedt o do both the string you proposed and the original one (like user2 has) and none of them worked, same error.

This is what the foo looked like after doing the changes you proposed:

```yaml
<yandex>
    <users>
        <admin>
            <access_management>1</access_management>
            <networks>
                <host_regexp>.test-clickhouse-operator.svc.cluster.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <clickhouse_operator>
            <networks>
                <ip>10.1.0.58</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <user2>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user2>
    </users>
</yandex>
```-

**Comment by AlejandroUPC** [comment]
@Slach 

Did some changes on the secred, now both `user2` and `admin` have the same password pulling from the secret, non of them work.

**Comment by Slach** [comment]
ok. remove
```
spec:
  configuration:
    users:
      admin/networks/host_regexp: ".test-clickhouse-operator.svc.cluster.local$"
```

try
```
spec:
  configuration:
    files: 
      users.d/admin.xml: |
        <yandex><users><admin><networks><host_regexp remove="1"/></networks></admin></users></yandex> 
```

did you try to connect with `admin` user
inside running clickhouse-server pod?

**Comment by AlejandroUPC** [comment]
@Slach 

I am pretty sure it has to do on how is it parsing the secret, I have now:

1. `user1` with plain text password `admin`.
2. `user2` with plain text password `admin`.
3. `user3` with kubernetes secret password `admin`.
4. `admin` user with kubernetes secret password `admin`

I would expect all the `password_sha256_hex` values to be the same, but it only happens with the users that use the same way to retrieve password (user1==user2) and (user3==user4) but different between them. 
Authenticating with the plaintext users using `admin` as password works.

**manifest.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-admin-credentials
type: Opaque
stringData:
  password: admin
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: "settings-03"
spec:
  configuration:
    users:
      user1/networks/ip: "::/0"
      user1/password: admin
      user1/profile: default
      user1/access_management: 1

      user2/networks/ip: "::/0"
      user2/password: admin
      user2/profile: default
      user2/access_management: 1

      user3/networks/ip: "::/0"
      user3/k8s_secret_password: clickhouse-admin-credentials/password
      user3/profile: default
      user3/access_management: 1

      admin/networks/ip: "::/0"
      admin/profile: default
      admin/k8s_secret_password: clickhouse-admin-credentials/password
      admin/access_management: 1
    clusters:
      - name: cls1
        layout:
          shardsCount: 1
          replicasCount: 1
```



```xml
<yandex>
    <users>
        <admin>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <clickhouse_operator>
            <networks>
                <ip>10.1.0.93</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <user1>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user1>
        <user2>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user2>
        <user3>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-settings-03-[^.]+\d+-\d+|clickhouse\-settings-03)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user3>
    </users>
</yandex>
```

Connecting inside the pod fails also as `admin/admin`.
