### ISSUE TITLE
Using postgresql wire protocol

### ISSUE THREAD

**Issue by marcusjfloyd** [Altinity/clickhouse-operator#1248]
is the operator capable of running the postgresql interface described here: https://clickhouse.com/docs/en/interfaces/postgresql

maybe I missed it, but I couldn't find any documentation on how to get this working using the operator

**Comment by Slach** [comment]
Use manifest something like that

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: pgsql-example
spec:
  configuration:
    clusters:
    - name: pgsql
      layout:
        shardsCount: 1
        replicasCount: 1 
    settings:
      postgresql_port: 9005
  defaults:
    templates:
      serviceTemplate: pgsql-service-template
  templates:
    serviceTemplates:
    - name: pgsql-service-template
      spec:
        type: LoadBalancer # use ClusterIP if you want access only inside Kubernetes
        ports:
        - name: pgsql
          protocol: TCP
          port: 9005
          targetPort: 9005
    
```

use 
`kubectl explain chi`
`kubectl explain chi.spec`
for documentation
