### ISSUE TITLE
AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by zmsoft** [Altinity/clickhouse-operator#1251]
K8S Version:  1.25.11

Install steps:
```
# 1. install clickhouse-operator
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml

# 2. create namespace
kubectl create namespace test-clickhouse-operator

# 3. install example
kubectl apply -n test-clickhouse-operator -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/docs/chi-examples/01-simple-layout-01-1shard-1repl.yaml
```

Default username and password:
   - ClickHouse-Username: clickhouse_operator
   - ClickHouse-Password:  clickhouse_operator_password

DBeaver Version: 23.2.2

Connection faild logs:
Code: 516. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 23.9.1.1854 (official build))
, server ClickHouseNode [uri=http://xxx.xx.xx.xx:8123/default, options={use_server_time_zone=false,use_time_zone=false}]@179847520
  Code: 516. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 23.9.1.1854 (official build))

  Code: 516. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 23.9.1.1854 (official build))

**Comment by Slach** [comment]
> ClickHouse-Username: clickhouse_operator
> ClickHouse-Password: clickhouse_operator_password

in the latest version of `clickhouse-operator` these credentials restrictred to IP of `clickhouse-operator` pods for security reason

you can easily add to CHI
```
spec:
  configuration:
    users:
      user_name/password_sha256_hash: XXXX
```

**Comment by zmsoft** [comment]
Hello Slach,

Thanks for your quick response. I have added to CHI and reinstall sample.
Still Authentication failed. 


01-simple-layout-01-1shard-1repl.yaml
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users:
      user_name/password_sha256_hash: 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225
```

**Comment by Slach** [comment]
Do you try to use `user_name`?

Could you share `cat /etc/clickhouse-backup/users.d/chop-generated-users.xml`
inside your clickhouse `chi-simple-01-simple-0-0-0` pod?

**Comment by zmsoft** [comment]
@Slach

Hi Slach,

I found that there was no clickhouse-backup directory in my clickhouse _chi-simple-01-simple-0-0-0_ pod.


```
cat: /etc/clickhouse-backup/users.d/chop-generated-users.xml: No such file or directory
root@chi-simple-01-simple-0-0-0:/# cd /etc/clickhouse-
clickhouse-client/ clickhouse-server/ 
root@chi-simple-01-simple-0-0-0:/# cd /etc/clickhouse-
clickhouse-client/ clickhouse-server/ 
root@chi-simple-01-simple-0-0-0:/# cat /etc/clickhouse-server/users.d/chop-generated-users.xml
<yandex>
    <users>
        <clickhouse_operator>
            <networks>
                <ip>10.20.1.59</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <networks>
                <host_regexp>(chi-simple-01-[^.]+\d+-\d+|clickhouse\-simple-01)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <user_name>
            <networks>
                <host_regexp>(chi-simple-01-[^.]+\d+-\d+|clickhouse\-simple-01)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <password_sha256_hash>15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225</password_sha256_hash>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user_name>
    </users>
</yandex>
root@chi-simple-01-simple-0-0-0:/# å
```

**Comment by Slach** [comment]
sorry ;( was my fault of course /etc/clickhouse-server/

let's add to CHI
```
    users:
      user_name/networks/ip: 0.0.0.0/0
```

**Comment by zmsoft** [comment]
@Slach

Hi Slach,

I used the username clickhouse_operator and password 123456789 to connect the ClickHouse from the WebClient, but the connection was failed.


```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users:
      user_name/password_sha256_hash: 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225
      user_name/networks/ip: 0.0.0.0/0
```

and  

```
root@chi-simple-01-simple-0-0-0:/etc/clickhouse-server/users.d# cat chop-generated-users.xml 
<yandex>
    <users>
        <clickhouse_operator>
            <networks>
                <ip>10.20.1.59</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <networks>
                <host_regexp>(chi-simple-01-[^.]+\d+-\d+|clickhouse\-simple-01)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <user_name>
            <networks>
                <host_regexp>(chi-simple-01-[^.]+\d+-\d+|clickhouse\-simple-01)\.test-clickhouse-operator\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>0.0.0.0/0</ip>
            </networks>
            <password_sha256_hash>15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225</password_sha256_hash>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </user_name>
    </users>
</yandex>
root@chi-simple-01-simple-0-0-0:/etc/clickhouse-server/users.d# 
```

<img width="654" alt="image" src="https://github.com/Altinity/clickhouse-operator/assets/8024438/9717da2a-71de-4b19-a310-432bdcacb312">

**Comment by Slach** [comment]
sorry you need to use 
`password_sha256_hex` instead of `password_sha256_hash`

so final spec shall be
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    users:
      user_name/password_sha256_hex: 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225
      user_name/networks/ip: 0.0.0.0/0
```

and use service name like `clickhouse-simple-01` described in
`kubectl get svc --all-namespaces | grep chi`

where you run Tabix?
inside kubernetes cluster or outside kubernetes cluster?
