### ISSUE TITLE
Support override of hard coded logging container base image

### ISSUE THREAD

**Issue by zcross** [Altinity/clickhouse-operator#1256]
Today, there was a brief outage at `registry.access.redhat.com`: https://status.redhat.com/incidents/7l5072l1lrpp

When the creation of logging containers is enabled, the operator creates logging containers on the fly:
https://github.com/Altinity/clickhouse-operator/blob/ee8cb7c4f988d1c1cde0c34038dfd03d615a36d0/pkg/model/creator.go#L486-L499

The base image of these containers is hard coded:
https://github.com/Altinity/clickhouse-operator/blob/ee8cb7c4f988d1c1cde0c34038dfd03d615a36d0/pkg/model/ch_config_const.go#L77

This hard coding means that statefulset pods cannot be created/rescheduled when such an outage occurs.

```
Failed to pull image "[registry.access.redhat.com/ubi8/ubi-minimal:latest](http://registry.access.redhat.com/ubi8/ubi-minimal:latest)": rpc error: code = Unknown desc = failed to pull and unpack image "[registry.access.redhat.com/ubi8/ubi-minimal:latest](http://registry.access.redhat.com/ubi8/ubi-minimal:latest)": failed to resolve reference "[registry.access.redhat.com/ubi8/ubi-minimal:latest](http://registry.access.redhat.com/ubi8/ubi-minimal:latest)": pulling from host [registry.access.redhat.com](http://registry.access.redhat.com/) failed with status code [manifests latest]: 503 Service Unavailable
```

If there were an optional override for this base image location, `clickhouse-operator` users could designate their own high availability cache for such image registries (in general, this is not specific to any one public image registry that may at times become unavailable). 

A stopgap solution for anyone affected by this is to manually specify the logging container in pod templates, with a different base image, because the hard coded golang code only creates the logging containers when they are not already specified (i.e., creation is idempotent).

**Comment by AlexeyRumyantsev** [comment]
Hi @zcross ! Actually you can override the log container image, by specifying whole container spec like this:
`apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
spec:
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse-log
              args:
              - while true; do sleep 30; done;
              command:
                - /bin/sh
                - -c
                - --
              image: your_container_registry/ubi8_ubi-minimal:latest
              imagePullPolicy: IfNotPresent
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: data
                - mountPath: /var/log/clickhouse-server
                  name: log
`
It will work because of this code: https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/creator.go#L488

**Comment by alex-zaitsev** [comment]
@zcross , the log_container is customizable in podTemplate. See below:

```
spec:
  templates:
    podTemplates:
    - name: pod-template
      spec:
        containers:
          - name: clickhouse
            image: clickhouse/clickhouse-server:22.3
          - name: clickhouse-log
            image: registry.access.redhat.com/ubi8/ubi-minimal:latest
            command:
              - "/bin/sh"
              - "-c"
              - "--"
            args:
              - "while true; do sleep 30; done;"
```
