### ISSUE TITLE
AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by Shankara-git** [Altinity/clickhouse-operator#1261]
Install steps:
    1. Used helm release for deploying clickhouse operator/cluster
    
Clickhouse Operator Version : 0.21.1
Clickhouse Version : 23.3.7.5 

**Clickhouse Operator Pod logs :** 
```
E1025 14:38:51.247362       1 connection.go:97] connect():**FAILED Ping(http://clickhouse_operator:***@chi-clickhouse-cluster-ck-cluster-shard1-replica1.search.svc.cluster.local:8123/**). Err: clickhouse: Code: 516. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 23.3.7.5 (official build))
E1025 14:38:51.247439       1 connection.go:125] QueryContext():FAILED connect(http://clickhouse_operator:***@chi-clickhouse-cluster-ck-cluster-shard1-replica1.search.svc.cluster.local:8123/) for SQL: SELECT version()
W1025 14:38:51.247466       1 cluster.go:91] QueryAny():FAILED to run query on: chi-clickhouse-cluster-ck-cluster-shard1-replica1.search.svc.cluster.local of [chi-clickhouse-cluster-ck-cluster-shard1-replica1.search.svc.cluster.local] skip to next. err: FAILED connect(http://clickhouse_operator:***@chi-clickhouse-cluster-ck-cluster-shard1-replica1.search.svc.cluster.local:8123/) for SQL: SELECT version()
```
**Clickhouse Server logs :** 
```
2023.10.25 14:38:18.846876 [ 378 ] {} <Debug> HTTP-Session: 3afb7fff-3334-4d74-a236-9af2b2ce7849 Authenticating user 'clickhouse_operator' from 127.0.0.6:59607
2023.10.25 14:38:18.847051 [ 378 ] {} <Error> Access(user directories): from: 127.0.0.6, user: clickhouse_operator: Authentication failed: Code: 195. DB::Exception: **Connections from 127.0.0.6 are not allowed**. (IP_ADDRESS_NOT_ALLOWED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1dc395 in /usr/bin/clickhouse
1. ? @ 0x89e5b44 in /usr/bin/clickhouse
2. DB::IAccessStorage::throwAddressNotAllowed(Poco::Net::IPAddress const&) @ 0x12607e31 in /usr/bin/clickhouse
3. DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x12607d64 in /usr/bin/clickhouse
4. DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x1263323a in /usr/bin/clickhouse
5. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x1253e6be in /usr/bin/clickhouse
6. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x139e92da in /usr/bin/clickhouse
7. DB::HTTPHandler::authenticateUser(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0x1496bfa1 in /usr/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x1496d5bd in /usr/bin/clickhouse
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14974bee in /usr/bin/clickhouse
10. DB::HTTPServerConnection::run() @ 0x149e367d in /usr/bin/clickhouse
 (version 23.3.7.5 (official build))
2023.10.25 14:38:18.849725 [ 378 ] {} <Debug> HTTP-Session: 3afb7fff-3334-4d74-a236-9af2b2ce7849 Authentication failed with error: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name.
2023.10.25 14:38:18.849806 [ 378 ] {} <Error> DynamicQueryHandler: Code: 516. DB::Exception: clickhouse_operator: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1dc395 in /usr/bin/clickhouse
1. ? @ 0x8a0c1ac in /usr/bin/clickhouse
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x1253e974 in /usr/bin/clickhouse
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x139e92da in /usr/bin/clickhouse
4. DB::HTTPHandler::authenticateUser(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0x1496bfa1 in /usr/bin/clickhouse
5. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x1496d5bd in /usr/bin/clickhouse
6. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14974bee in /usr/bin/clickhouse
7. DB::HTTPServerConnection::run() @ 0x149e367d in /usr/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x179217d4 in /usr/bin/clickhouse
 (version 23.3.7.5 (official build))
```

**user config in clickhouse server is :** 
```xml
    <users>
        <clickhouse_operator>
            <networks>
                <ip>10.193.192.189</ip>
            </networks>
            <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            <profile>clickhouse_operator</profile>
        </clickhouse_operator>
        <default>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <networks>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>10.193.192.10</ip>
                <ip>10.193.192.138</ip>
                <ip>10.193.197.20</ip>
                <ip>10.193.192.9</ip>
            </networks>
            <password remove="1"></password>
            <password_sha256_hex>cd26bd62929410fa670bc83fc6b73747ca64aa777b83c42e82ba35dc9cf682e6</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
```

**I am not sure why clickhouse operator is using 127.0.0.6 ip to connect it, eventhough pod ip is configured with 10.193.192.189**

Is there any suggestion/solution to this authentication failure?

Thanks

**Comment by farbodsalimi** [comment]
We're also seeing similar errors.

**Comment by Slach** [comment]
@Shankara-git 
Which kind of kubernetes do you use?
is this managed kubernetes like EKS, GKE, AKS or something like minikube, k3s, k0s?

your `clickhouse-operator` pod have 10.193.192.189, and it added to config.xml

could you share the following commands result:
```bash
kubectl get nodes
kubectl get pods --all-namespaces -l app=clickhouse-operator
kubectl get chit --all-namespaces
kubectl get svc -n search chi-clickhouse-cluster-ck-cluster-shard1-replica1 -o yaml
kubectl get chi -n search clickhouse-cluster -o yaml
```

**Comment by farbodsalimi** [comment]
If it helps I'll share my info as well:

Managed k8s: EKS
k8s version: v1.25.13

Node:
```bash
NAME                                          STATUS     ROLES    AGE     VERSION                INTERNAL-IP     EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION                  CONTAINER-RUNTIME
ip-10-31-118-102.us-west-2.compute.internal   Ready      <none>   16d     v1.25.13               10.31.118.102   <none>           Ubuntu 20.04.6 LTS   5.15.0-1045-aws                 containerd://1.7.2
```

Pod:
```bash
NAME                         READY   STATUS    RESTARTS      AGE   IP              NODE                                          NOMINATED NODE   READINESS GATES
chi-test-counters-0-0-0   3/3     Running   1 (14h ago)   14h   10.31.122.68    ip-10-31-118-102.us-west-2.compute.internal   <none>           <none>
```

chop-generated-users.xml
 ```xml
<users>
    <api>
        <networks>
            <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$</host_regexp>
            <ip>::1</ip>
            <ip>127.0.0.1</ip>
            <ip>::/0</ip>
        </networks>
        <password_sha256_hex>XXXX</password_sha256_hex>
        <profile>readonly</profile>
        <quota>default</quota>
    </api>
    <backup>
        <networks>
            <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$</host_regexp>
            <ip>::1</ip>
            <ip>127.0.0.1</ip>
            <ip>0.0.0.0/0</ip>
        </networks>
        <password_sha256_hex>XXXX</password_sha256_hex>
        <profile>default</profile>
        <quota>default</quota>
    </backup>
    <clickhouse_operator>
        <networks>
            <ip>10.31.110.168</ip>
        </networks>
        <password_sha256_hex>XXXX</password_sha256_hex>
        <profile>clickhouse_operator</profile>
    </clickhouse_operator>
    <default>
        <networks>
            <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$</host_regexp>
            <ip>::1</ip>
            <ip>127.0.0.1</ip>
            <ip>10.31.122.68</ip>
            <ip>10.31.90.150</ip>
            <ip>10.31.135.121</ip>
            <ip>10.31.124.80</ip>
            <ip>10.31.156.118</ip>
            <ip>10.31.81.5</ip>
        </networks>
        <password remove="1"></password>
        <password_sha256_hex>XXXX</password_sha256_hex>
        <profile>default</profile>
        <quota>default</quota>
    </default>
    <inserter>
        <networks>
            <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$</host_regexp>
            <ip>::1</ip>
            <ip>127.0.0.1</ip>
            <ip>::/0</ip>
        </networks>
        <password_sha256_hex>XXXX</password_sha256_hex>
        <profile>default</profile>
        <quota>default</quota>
    </inserter>
</users>
```

As you can see the default user picks the right IP address but not the operator user.

svc:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: stage.us-west-2.test.chi-test-counters:clickhouse.altinity.com/ClickHouseInstallation:clickhouse/test
    clickhouse.altinity.com/ready: "yes"
  creationTimestamp: "2023-10-17T21:52:01Z"
  labels:
    app.kubernetes.io/instance: stage.us-west-2.test.chi-test-counters
    clickhouse.altinity.com/Service: host
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: test
    clickhouse.altinity.com/cluster: counters
    clickhouse.altinity.com/namespace: clickhouse
    clickhouse.altinity.com/object-version: a5467b596170320bf9eb6a9c6f213bf083704bdf
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/shard: "0"
  name: chi-test-counters-0-0
  namespace: clickhouse
  ownerReferences:
  - apiVersion: clickhouse.altinity.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClickHouseInstallation
    name: test
    uid: 290a515b-d7c1-4607-8b2c-6ea616d83816
  resourceVersion: "1040074565"
  uid: 482e73ae-6f07-47dc-9dc5-8e0f7b3e852f
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: interserver
    port: 9009
    protocol: TCP
    targetPort: 9009
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: test
    clickhouse.altinity.com/cluster: counters
    clickhouse.altinity.com/namespace: clickhouse
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/shard: "0"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

chi:
```yaml
...
        profiles:
          readonly/readonly: "1"
        users:
          api/networks/host_regexp: (chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$
          api/networks/ip:
          - ::1
          - 127.0.0.1
          - ::/0
          api/password_sha256_hex: XXXX
          api/profile: readonly
          api/quota: default
          backup/networks/host_regexp: (chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$
          backup/networks/ip:
          - ::1
          - 127.0.0.1
          - 0.0.0.0/0
          backup/password_sha256_hex: XXXX
          backup/profile: default
          backup/quota: default
          clickhouse_operator/networks/ip:
          - 10.31.110.168
          clickhouse_operator/password_sha256_hex: XXXX
          clickhouse_operator/profile: clickhouse_operator
          default/networks/host_regexp: (chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$
          default/networks/ip:
          - ::1
          - 127.0.0.1
          - 10.31.122.68
          - 10.31.90.150
          - 10.31.135.121
          - 10.31.124.80
          - 10.31.156.118
          - 10.31.81.5
          default/password: ""
          default/password_sha256_hex: XXXX
          default/profile: default
          default/quota: default
          inserter/networks/host_regexp: (chi-test-[^.]+\d+-\d+|clickhouse\-test)\.clickhouse\.svc\.cluster\.local$
          inserter/networks/ip:
          - ::1
          - 127.0.0.1
          - ::/0
          inserter/password_sha256_hex: XXXX
          inserter/profile: default
          inserter/quota: default
...
```

**Comment by Slach** [comment]
@farbodsalimi 

```yaml
 <clickhouse_operator>
       <networks>
           <ip>10.31.110.168</ip>
       </networks>
```

could you share pls  
```
kubectl get pods --all-namespaces | grep clickhouse-operator
```     
?

**Comment by farbodsalimi** [comment]
```
clickhouse                       altinity-clickhouse-operator-7c8bd9f8bf-9fs6m                     2/2     Running             0                  6d21h
```

**Comment by Slach** [comment]
@farbodsalimi do you have ServiceMesh like istio?

**Comment by Slach** [comment]
@farbodsalimi 
```bash
kubectl get svc --all-namespaces | grep 10.31.111.124
kubectl get pod --all-namespaces | grep 10.31.111.124
```

**Comment by farbodsalimi** [comment]
We're using https://github.com/cilium/cilium in our k8s clusters but its service and cluster mesh are not enabled. 

I ran both 
```
kc get all --all-namespaces -o wide | grep 10.31.111.124
kc get nodes -o wide | grep 10.31.111.124
```

Nothing showed up!

**Comment by farbodsalimi** [comment]
I guess my other question is, is it possible to disable `clickhouse_operator/networks/ip`?

**Comment by Slach** [comment]
As a quick workaround
change `chi`
```yaml
spec:
  configuration:
    users:
      clickhouse_operator/networks/ip: 10.31.0.0/16
```
