### ISSUE TITLE
deletion of PVC when PV size altered with ArgoCD with prune enabled

### ISSUE THREAD

**Issue by prashant-shahi** [Altinity/clickhouse-operator#1272]
We had recently introduced a K8s Job for DB schema migrations and prune option enabled in ArgoCD.

It worked fine for sometime. However in some case of CHI PVC size change, we noticed release and deletion of PVCs - even with `Retain` policy at CHI manifest.

We have reverted back prune option to disabled for now.

**Comment by alex-zaitsev** [comment]
@prashant-shahi , consider adding following configuration snippet:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "exclude-argocd-labels"
spec:
  label:
    exclude:
      - argocd.argoproj.io/instance
```

It require operator restart. This is an instructions to not propagate argocd label to downstream resources. That should sure ArgoCD will not touch resources managed by operator
