### ISSUE TITLE
ServerErrorHandler - clickhouse 23.8

### ISSUE THREAD

**Issue by yacinebbt** [Altinity/clickhouse-operator#1282]
Hello,

I am facing an issue that i don't know it's coming from, i tried to investigate to find what causing this issue.

I am using clickhouse with zookeeper.

Here are how i did to install both of them:

**Zookeeper:**

```
helm upgrade --install zookeeper \
    --set zookeeper.enabled=false \
    --set persistence.size=100Mi \
    --set replicaCount=1 \
    --set service.sessionAffinity=ClientIP \
    --set tls.client.enabled=false \
    --version 11.0.0 \
    oci://registry-1.docker.io/bitnamicharts/zookeeper
```
    
    **clikchouse-operator**
```
helm repo add clickhouse-operator https://docs.altinity.com/clickhouse-operator/
helm repo update
helm upgrade --install clickhouse-operator clickhouse-operator/altinity-clickhouse-operator \
    --set secret.username=xxxx\
    --set secret.password=xxxxx \
```
    
    **Install clickhouse**

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "chi"
spec:
  configuration:
    clusters:
      - name: "easi"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-stable
          dataVolumeClaimTemplate: clickhouse-data-volume
          serviceTemplate: svc-template
    zookeeper:
        nodes:
        - host: zookeeper-headless
          port: 2181
    users:
        xxxxxreadonly/profile: readonly
        xxxxx/password: xxxxxxxx
        xxxxx/profile: default
        xxxxx/quota: default
        xxxxx/networks/ip:
            - 0.0.0.0/0
            - ::/0
    profiles:
      xxxxxreadonly/readonly: "1"
      # server level settings can be set here
      xxxxx/data_type_default_nullable: 1 
      xxxxx/insert_distributed_sync: 1
      xxxxx/mutations_sync: 2
      xxxxx/parallel_distributed_insert_select: 2 
      xxxxx/distributed_product_mode: allow 
    files:
      config.d/log_rotation.xml: |-
        <clickhouse>
            <logger>
                <level>information</level>
                <log>/var/log/clickhouse-server/clickhouse-server.log</log>
                <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
                <size>500M</size>
                <count>5</count>
                <console>1</console>
            </logger>
        </clickhouse>
  templates:
    podTemplates:
    - name: clickhouse-stable
      spec:
        # securityContext:
        #   runAsUser: easi
        #   runAsGroup: easi
        #   fsGroup: easi
        containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.8
          ports:
            - name: http
              containerPort: 8123
            # - name: client
            #   containerPort: 9998
            - name: tcp
              containerPort: 9000
            - name: interserver
              containerPort: 9009
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: false
    volumeClaimTemplates:
      - name: clickhouse-data-volume
        spec:
          storageClassName: gp2-retain-immediate
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
```

   The following error occurs twice every 5 minutes:

```
2023.11.29 15:56:54.234040 [ 47 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):

2023.11.29 15:56:54.257020 [ 47 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):

2023.11.29 16:01:54.335315 [ 47 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):

2023.11.29 15:56:54.257020 [ 47 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):
```

I tried to look up for this problem and didn't find anything helpul.

I tried to understand also the source code of clickhouse but without success:

https://github.com/ClickHouse/ClickHouse/blob/4f3204b8f193edbf752510c79cc2c6a2ff3902ec/src/Server/TCPHandler.cpp#L1397
```cpp
if (packet_type != Protocol::Client::Hello)
    {
        /** If you accidentally accessed the HTTP protocol for a port destined for an internal TCP protocol,
          * Then instead of the packet type, there will be G (GET) or P (POST), in most cases.
          */
        if (packet_type == 'G' || packet_type == 'P')
        {
            writeString(formatHTTPErrorResponseWhenUserIsConnectedToWrongPort(server.config()), *out);
            throw Exception(ErrorCodes::CLIENT_HAS_CONNECTED_TO_WRONG_PORT, "Client has connected to wrong port");
        }
        else
            throw NetException(ErrorCodes::UNEXPECTED_PACKET_FROM_CLIENT,
                               "Unexpected packet from client (expected Hello, got {})", packet_type);
    }
```

Please if you have any suggestion for me, that's would be great.

Thanks in advance
[clickhouse-logs - Copie.txt](https://github.com/Altinity/clickhouse-operator/files/13502905/clickhouse-logs.-.Copie.txt)

**Comment by Slach** [comment]
could it be your cron client script which used wrong port for connection?

**Comment by Slach** [comment]
could you share?

`kubectl get svc --all-namespaces -l clickhouse.altinity.com/chi`

**Comment by yacinebbt** [comment]
Hello, 
Thank you for your response, here is my output :

```
kubectl get svc --all-namespaces -l clickhouse.altinity.com/chi
NAMESPACE    NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
clickhouse   chi-chi-easi-0-0   ClusterIP   None         <none>        9000/TCP,8123/TCP,9009/TCP   46h
```

**Comment by Slach** [comment]
hm, looks weird, clickhouse-operator should create one LoadBalancer service 

`kubectl get scv -n clickhouse`?

**Comment by yacinebbt** [comment]
Yes that's true, 

```
NAMESPACE    NAME               TYPE           CLUSTER-IP      EXTERNAL-IP                                                             PORT(S)                         AGE
clickhouse   chi-chi-easi-0-0   ClusterIP      None            <none>                                                                  9000/TCP,8123/TCP,9009/TCP      46h
clickhouse   clickhouse-chi     LoadBalancer   10.43.126.210   1fd0841df98e471e8fa8452ab5bf915e-886836458.eu-west-2.lbu.outscale.com   8123:30722/TCP,9000:32513/TCP   46h
```

i attached a log file in the first description, but here is the latests logs:


```
2023.11.30 08:31:54.231034 [ 377 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c646337 in /usr/bin/clickhouse
1. DB::NetException::NetException<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x0000000013162677 in /usr/bin/clickhouse
2. DB::TCPHandler::runImpl() @ 0x00000000131533f2 in /usr/bin/clickhouse
3. DB::TCPHandler::run() @ 0x0000000013167619 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x0000000015b5dc54 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b5ee51 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x0000000015c95687 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c9395c in /usr/bin/clickhouse
8. ? @ 0x00007efe37cfa609 in ?
9. ? @ 0x00007efe37c1f133 in ?
 (version 23.8.8.20 (official build))
2023.11.30 08:31:54.236337 [ 377 ] {} <Error> ServerErrorHandler: Code: 101. DB::NetException: Unexpected packet from client (expected Hello, got 22). (UNEXPECTED_PACKET_FROM_CLIENT), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c646337 in /usr/bin/clickhouse
1. DB::NetException::NetException<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x0000000013162677 in /usr/bin/clickhouse
2. DB::TCPHandler::runImpl() @ 0x00000000131533f2 in /usr/bin/clickhouse
3. DB::TCPHandler::run() @ 0x0000000013167619 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x0000000015b5dc54 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b5ee51 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x0000000015c95687 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c9395c in /usr/bin/clickhouse
8. ? @ 0x00007efe37cfa609 in ?
9. ? @ 0x00007efe37c1f133 in ?
 (version 23.8.8.20 (official build))
```

**Comment by Slach** [comment]
Try to use https://github.com/eldadru/ksniff
and capture and share traffic on 9000 port inside clickhouse pod during error happens

Moreover, if you don't need public access outside your kubernetes cluster
change your chi manifest
```yaml
spec:
  templates:
    serviceTemplates:
    - name: chi-service-clusterip
      generatedName: clickhouse-{chi}  
      spec:
        type: ClusterIP
  defaults:
    templates:
      serviceTemplate: chi-service-clusterip     
```

**Comment by Slach** [comment]
Do you still have errors in /var/log/clickhouse-server/clickhouse-server.err.log after change service to ClusterIP?
If yes share the full timestamp corresponded with captured traficc

**Comment by yacinebbt** [comment]
So i did change my manifest
```

    serviceTemplates:
          - name: chi-service-clusterip
            generateName: clickhouse-{chi}  
            spec:
              type: ClusterIP
  defaults:
    templates:
      serviceTemplate: chi-service-clusterip
```

and now the lb service is gone:
```

kubectl get svc --all-namespaces -l clickhouse.altinity.com/chi
NAMESPACE    NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
clickhouse   chi-chi-easi-0-0   ClusterIP   None         <none>        9000/TCP,8123/TCP,9009/TCP   2d
```

the same error message keep occuring even after all that, i've captured a new file, here is the log error files as well as the pcapng file ( to be renamed from txt to pcapng)
 log file: 
[clickhouse-logs.txt](https://github.com/Altinity/clickhouse-operator/files/13511791/clickhouse-logs.txt)


the pcapng file: 
[clickhouse2.txt](https://github.com/Altinity/clickhouse-operator/files/13511769/clickhouse2.txt)
