### ISSUE TITLE
May I ask how to deploy the high availability deployment method of clickhouse in Azure AKS

### ISSUE THREAD

**Issue by xiaodage33** [Altinity/clickhouse-operator#1286]
May I ask how to deploy the high availability deployment method of clickhouse in Azure AKS.

I saw how to modify the pod deployment method to the deployment deployment method to run high availability applications in a cluster.

**Comment by xiaodage33** [comment]
Hello, I want to deploy clickhouse in **deployment** mode. What configurations need to be modified? Now it should be deployed in **pod** mode, thank you  @Slach Slach 

The **pod** deployment doesn't feel very good


**kubectl edit  po  chi-simple-01-simple-0-0-0     -n test**
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: **Pod**
metadata:
  creationTimestamp: "2023-11-28T15:53:18Z"
  generateName: chi-simple-01-simple-0-0-
  labels:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: simple-01
    clickhouse.altinity.com/cluster: simple
    clickhouse.altinity.com/namespace: test
    clickhouse.altinity.com/ready: "yes"
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/shard: "0"

**Comment by Slach** [comment]
> Hello, I want to deploy clickhouse in deployment mode.

this is have no sense

why you need to use deployment instead of statefulset?
statefulset is much more relevant to Database, cause database have data on PVC and require a persistent dns name

**Comment by xiaodage33** [comment]
Hello, I saw that the deployment mode of the open source yaml file clickhouse is pod mode, we can use satefuset mode and deployment mode, but I don't know where to change the configuration to StatefulSet or deployment

@Slach   thank you

**Comment by Slach** [comment]
I don't understand what exactly means "deployment mode"

**Comment by xiaodage33** [comment]
**statefulset**.apps/chi-clickhouse-simple-0-0   1/1     23m

I just checked, the default is statefulset deployment, thank you

**Comment by Slach** [comment]
> how can the deployed clickhouse modify the SVC exposure method, such as canceling the LoadBalancer

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clusterip
spec:
  templates:
    serviceTemplates:
    - name: clusterip
      spec:
        type: ClusterIP
        # define port which you need 
        ports:
        - name: http
          port: 8123
        - name: tcp
          port: 9000
  defaults:
    templates:
      serviceTemplate: clusterip
  configuration:
    clusters:
    - name: default
      layout:
        shardsCount: 1
        replicasCount: 1   
```
