### ISSUE TITLE
Enable PostgreSQL Interface using Helm install

### ISSUE THREAD

**Issue by 3goats** [Altinity/clickhouse-operator#1289]
Hi,

I need to enable the ClickHouse Postgres interface.  The [docs](https://clickhouse.com/docs/en/interfaces/postgresql) suggest this get added to the `config.xml` e.g.

```xml
<clickhouse>
    <postgresql_port>9005</postgresql_port>
</clickhouse>
```

Is there a way to deal with this in my ClickHouse cluster configuration or via the Helm chart ?

**Comment by 3goats** [comment]
Hi any update on this? can it be done with the operator today ?

**Comment by Slach** [comment]
use following `values.yaml`
```yaml
additionalResources:
- |
  apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallation
  metadata:
    name: pgsql-example
  spec:
    templates:
      serviceTemplates:
      - name: pgsql-svc
        spec:
          type: ClusterIP
          ports:
          - name: pgsql
            port: 5432
          - name: http
            port: 8123
          - name: tcp
            port: 9000
    defaults:
      serviceTemplate: pgsql-svc
    configuration:
      settings:
        postgresql_port: 5432
      clusters:
        - name: default
          layout:
            shardsCount: 1
            replicasCount: 1
```
