### ISSUE TITLE
max_concurrent_queries not getting applied

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#1293]
added this configuration in chi CR
```
configuration:
   settings:
      max_concurrent_queries: 100
```
Also how to confirm if this has been applied. Somehow in config.xml i cannot see this configuration.

**Comment by Slach** [comment]
to check execute inside clickhouse-pod container
```bash
grep max_concurrent_queries -r /var/lib/clickhouse/preprocessed_configs/
```
if not found
try more explicitly syntax
```yaml
configuration:
  files:
    config.d/max_concurrent_queries.xml: |
      <clickhouse><max_concurrent_queries>100</max_concurrent_queries></clickhouse>
```
