### ISSUE TITLE
Argo-cd - Upgrading Helm Chart Loops

### ISSUE THREAD

**Issue by tman5** [Altinity/clickhouse-operator#1299]
We're using argo-cd with the helm chart to deploy the operator. The problem is upgrading from 0.21.2 - > 0.22.2 argo-cd is looping over the CRD resources. It will show synced, but then not synced. Below is the screenshot of a sample of what it sees as out of sync. It's like it will change it, but then something else changes it back? At first I thought it was labels but the fields involved are not labels in the CRD

![image](https://github.com/Altinity/clickhouse-operator/assets/10875976/5a373d5f-14c6-441d-bcdb-38b0f073379f)

**Comment by Slach** [comment]
You should install CRD separatelly, 0.22.2 

helm actually have strange policy about CRD resources

**Comment by tman5** [comment]
Understood, but we have many other operators with custom CRDs we deploy with argo without issue.

**Comment by Elyytscha** [comment]
> Understood, but we have many other operators with custom CRDs we deploy with argo without issue.

if you use olm with argocd you are fine, if you use argocd with helm for operators you will for sure run into issues with crd's at sometime

**Comment by tman5** [comment]
We are using kustomize helm charts. Which technically doesn't deploy a chart but just outputs the manifests - and it still has issues

```
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

helmCharts:
  - name: altinity-clickhouse-operator
    releaseName: clickhouse-operator
    namespace: clark-developer-featbit
    repo: https://docs.altinity.com/clickhouse-operator/
    includeCRDs: true
```
