### ISSUE TITLE
Ingress for exposing the service

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1312]
Hi

I am trying to expose the clickhouse service hosted on a EKS cluster using a ingress.
I dont dind any documentation on how can this be done.

**Comment by Slach** [comment]
by default clickhouse operator create service with `type:LoadBalancer`
to allow pass external traffic to clickhouse
you can customize this behavior in `kind: ClickHouseInstallation` you need define a custom `serviceTemplate` in `.spec.templates` and link this template name to `.spec.defaults.templates.serviceTemplate`
look examples here
https://github.com/Altinity/clickhouse-operator/blob/0.23.0/docs/chi-examples/02-templates-03-service-template.yaml

after that define `kind: Ingress` manifest

something like that should be enough
but replace `clickhouse-cluster` to service name from `kubectl get svc --all-namespaces | grep clickhouse`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60m"
spec:
  rules:
  - host: clickhouse.domain.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clickhouse-cluster
            port:
              number: 8123
  - host: clickhouse.domain.example
    tcp:
      - port: 9000
        backend:
          service:
            name: clickhouse-cluster
            port:
              number: 9000
```

If you want to pass secure connection with TLS termniation 
look kubectl explain Ingress and try to figure out

**Comment by manishtradebyte** [comment]
Is there a helm chart for this operator?

**Comment by Slach** [comment]
https://artifacthub.io/packages/helm/altinity-clickhouse-operator/altinity-clickhouse-operator

**Comment by Slach** [comment]
@manishtradebyte i would like don't use helm for operators, cause CRDs required install separatelly

**Comment by manishtradebyte** [comment]
I  keep getting this error whenever i try to create the ingress
 Error from server (BadRequest): error when creating "ingress.yml": Ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[1].tcp"

My clickhouse installation is something like this



`apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "template-service"
spec:
  defaults:
    templates:
      serviceTemplate: svc-template
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
  templates:
    serviceTemplates:
      - name: svc-template
        generateName: chendpoint-{chi}
        metadata:
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            alb.ingress.kubernetes.io/backend-protocol: HTTPS
            alb.ingress.kubernetes.io/target-type: ip
            external-dns.alpha.kubernetes.io/hostname: "clickhouse.xyz.org"
`

and my Ingress file is 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60m"
spec:
  rules:
  - host: clickhouse.xyz.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chi-template-service-cluster-0-0
            port:
              number: 8123
  - host: clickhouse.xyz.org
    tcp:
      - port: 9000
        backend:
          service:
            name: chi-template-service-cluster-0-0
            port:
              number: 9000`
              
    I am a bit new to ingress and i keep getting this error rror from server (BadRequest): error when creating "ingress.yml": Ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[1].tcp"
    
    
what is expected inside the           serviceTemplate?

**Comment by Slach** [comment]
for `ClickHouseInstallation`

add `type: ClusterIP` to svc-template
```
  templates:
    serviceTemplates:
      - name: svc-template
        type: ClusterIP
```
remove whole configuration `configuration.settings` section, this was just example
```yaml
   configuration
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
```


from `kind: Ingress` remove the whole section, cause nginx require external configmap to allow pass external TCP traffic
https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

```yaml
 - host: clickhouse.xyz.org
    tcp:
      - port: 9000
        backend:
          service:
            name: chi-template-service-cluster-0-0
            port:
              number: 9000
```

and replace `chi-template-service-cluster-0-0` to `chendpoint-service-template`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60m"
spec:
  rules:
  - host: clickhouse.xyz.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chendpoint-service-template
            port:
              number: 8123
```

after that you can connect to clickhouse by 
```curl -vvv http://clickhouse.xyz.org/ping```
outside cluster
and response should be `Ok.`

look 
https://clickhouse.com/docs/en/interfaces/http
for details

if you want to use TLS
look `kubectl explain ingress.spec.tls` documentation
