### ISSUE TITLE
Is it possible to specify more than one `dataVolumeClaimTemplate`?

### ISSUE THREAD

**Issue by mano233** [Altinity/clickhouse-operator#1313]
For example, the following configuration is used to deploy a hot and cold storage architecture

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test"
spec:
  configuration:
    users:
      admin/password: admin
      admin/networks/ip:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      admin/profile: default
      admin/quota: default
    profiles:
      default/allow_experimental_window_functions: "1"
      default/allow_nondeterministic_mutations: "1"

    clusters:
      - name: "test"
        templates:
          podTemplate: pod-template
          clusterServiceTemplate: service-template
          dataVolumeClaimTemplate: xxxxxxxxx # How to configure this?
        layout:
          replicasCount: 1
          shardsCount: 1

    settings:
      default_database: posthog
      format_schema_path: /etc/clickhouse-server/config.d/
      prometheus/asynchronous_metrics: true
      prometheus/endpoint: /metrics
      prometheus/events: true
      prometheus/metrics: true
      prometheus/port: 9363

    files:
      config.d/storage_configuration.xml: |-
        <clickhouse>
          <storage_configuration>
             <disks>
                <default>
                </default>
                <hdd_disk>
                   <path>/data/hdd/clickhouse</path> 
                </hdd_disk>
              </disks>
          </storage_configuration>
          <policies>
             <hot_cold>
               <volumes>
                  <hot>
                    <disk>default</disk>
                  </hot>
                  <cold>
                    <disk>hdd_disk</disk>
                  </cold>
               </volumes>
             </hot_cold>
         </policies>
        </clickhouse>
      events.proto: |
        syntax = "proto3";
        message Event {
          string uuid = 1;
          string event = 2;
          string properties = 3;
          string timestamp = 4;
          uint64 team_id = 5;
          string distinct_id = 6;
          string created_at = 7;
          string elements_chain = 8;
        }

    zookeeper:
      nodes:
        - host: znode1
          port: 2181

  templates:
    podTemplates:
      - name: pod-template
        metadata:
          annotations: 
            prometheus.io/path: /metrics
            prometheus.io/port: "9363"
            prometheus.io/scrape: "true"
        spec:
          volumes:
            - name:  default-volumeclaim-template
              persistentVolumeClaim:
                claimName: default-volumeclaim-template
            - name: hdd-volumeclaim-template
              persistentVolumeClaim:
                claimName: hdd-volumeclaim-template
          securityContext:
            fsGroup: 101
            runAsGroup: 101
            runAsUser: 101

          containers:
            - name: clickhouse
              image: "clickhouse/clickhouse-server:23.9.2.56"
              command:
                - /bin/bash
                - -c
                - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml

              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
              volumeMounts:
                - name: default-volumeclaim-template
                  mountPath: /var/lib/clickhouse
                - name: hdd-volumeclaim-template
                  mountPath: /data/hdd/clickhouse
    serviceTemplates:
      - name: service-template
        generateName: clickhouse-posthog
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
# Two pvc's are configured, note that the storageClassName is different;longhorn-fast for configuring high-speed SSDs
    volumeClaimTemplates:
      - name: hdd-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "20Gi"
      - name: default-volumeclaim-template
        spec:
          storageClassName: longhorn-fast
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "10Gi"

```
