### ISSUE TITLE
clickhouse-operator restarts after failing to get clickhouse-keeper.altinity.com/v1

### ISSUE THREAD

**Issue by bradbart** [Altinity/clickhouse-operator#1320]
When running the clickhouse-operator, the operator is restarting and causing issues in my k8s environment. The error in the logs before the restart is

```
│  ERROR    controller-runtime.source.EventHandler    failed to get informer from cache    {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: clickhouse-keeper.altinity.com/v1: the server could not find the requested resource"}      
```

Here is the configuration I am using when I run into this issue:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "my-cluster"

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.6
  configuration:
    users:
      default/password_sha256_hex: {{ .Values.defaultCredentials.passwordSha256 }}
    clusters:
      - name: my-cluster
        secret:
          auto: "true"

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    podTemplates:
      - name: clickhouse:19.6
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
``` 

Why would it be attempting to get information about the keeper when the cluster does not support replication / sharding?
