### ISSUE TITLE
Defining users in xml files passed to `spec.configuration.files`

### ISSUE THREAD

**Issue by bradbart** [Altinity/clickhouse-operator#1321]
My team is currently migrating our local development from running the clickhouse executable on the machine to a kubernetes deployment. We have a set of user xml files we use to define users for local testing. Is there a way to pass these xml files into the cluster configuration? I attempted to use [spec.configuration.files](https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationfiles), but while the files are present the users do not seem to be created. Is the only path to defining users through the `spec.configuration.users` YAML property?

**Comment by Slach** [comment]
try to use 
```
spec:
  configuration:
    files:
      users.d/file_name.xml: |
        <xml content>
```
