### ISSUE TITLE
Clickhouse fails parsing users.xml with 0.23.0

### ISSUE THREAD

**Issue by derbauer97** [Altinity/clickhouse-operator#1324]
Hey, 

I noticed that 0.23.0 was released and wanted to test the feature reading password directly from Secrets. But i get the following error:

2024.02.02 09:05:54.562549 [ 1 ] {} <Error> Application: DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos' or 'ssl_certificates' must be specified for user networks.: while parsing user 'networks' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'

i thought ok maybe my Clickhouse Version 23.3.19.32 is not supporting reading password from env so i rolled the configuration back to the old secrets syntax. But the issue still persists so i had to roll back to 0.22.2 to fix my Installation.

I could not find any info in the Clickhouse Documentation when password from env is supported or any hint on this configuration at all.

**Comment by Slach** [comment]
you should need to use:
```
spec:
  configuration:
    users:
      user_name/k8s_secret_password: secret_name/key_in_secret 
```

or 
```
spec:
  configuration:
    users:
      user_name/k8s_secret_password_sha256_hex: secret_name/key_in_secret 
```

**Comment by derbauer97** [comment]
My Configuration looks like these:

```
     spec:
       configuration:
            users:
                instana/k8s_secret_password: clickhouse-user-instana/instana
                clickhouse_operator/k8s_secret_password: clickhouse-user-instana/clickhouse_operator
```

But i get the same error with 0.23.0. It is working with 0.22.2
