### ISSUE TITLE
Pod stuck in CrashLoopBackOff due to max_suspicious_broken_parts

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1331]
After unexpected shutdown the pod is unable to start and stuck at CrashLoopBackOff

`2024.02.05 01:37:20.473163 [ 1 ] {} <Error> Application: DB::Exception: Suspiciously many (14 parts, 0.00 B in total) broken parts to remove while maximum allowed broken parts count is 10. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `bin`.`bin_b_s_t_aggregated` from metadata file /var/lib/clickhouse/store/a91/a91cd89c-1c4d-4839-a407-77c0951cefa1/bin_b_s_t_aggregated.sql from query ATTACH TABLE bin.bin_b_s_t_aggregated UUID '835db9de-8e39-4477-b0ae-efda77fdf26d' (`timestamp` DateTime CODEC(DoubleDelta, LZ4), `avg_price_state` AggregateFunction(avgOrNull, Nullable(Float64)) CODEC(LZ4), `avg_quantity_state` AggregateFunction(avgOrNull, Nullable(Float64)) CODEC(LZ4), `avg_quote_quantity_state` AggregateFunction(avgOrNull, Nullable(Float64)) CODEC(LZ4), `is_buyer_maker` UInt8, `is_best_match` UInt8, `id` UUID DEFAULT generateUUIDv4() CODEC(LZ4)) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/bin.bin_b_s_t_aggregated', '{replica}') PARTITION BY toMonday(timestamp) ORDER BY (timestamp, id) TTL timestamp + toIntervalYear(3) SETTINGS index_granularity = 8192`

what I did is to follow this guide and removed all the probes (no change pod still stuck at crash)
https://github.com/SigNoz/signoz/issues/1641

Another thing I tried :
added this to manifest 
```yaml
settings:
  merge_tree:
    max_suspicious_broken_parts: 100**
```

```yaml
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7-with-backup 
 
  configuration:
    users: 
      admin/password: XXX    
      admin/networks/ip: 0.0.0.0/0 
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-1.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-2.zookeepers.ck.svc.cluster.local # Zookeeper
```
```yaml     
    clusters:
      - name: replicated
        layout:
          shardsCount: 1
          replicasCount: 3
    settings:
      merge_tree:
        max_suspicious_broken_parts: 100

```
```yaml
  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 1.35Ti
    podTemplates:
      - name: clickhouse:20.7-with-backup
        metadata:
          annotations:
            prometheus.io/port: '8888'
            prometheus.io/scrape: 'true'
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
        spec:
          scheduledTasks:
            - name: "cleanup-detached-parts"
              schedule: "0 4 * * *" # Every day at 04:00
              command: ["clickhouse-client", "--query", "SYSTEM DROP DETACHED PARTS"]
```

Also seems this is taking no effect on the config neither since 
`kubectl exec -it chi-ck3-replicated-0-0-0 -n ck -- cat /etc/clickhouse-server/config.xml | grep max_suspicious_broken_parts
` indicate <max_suspicious_broken_parts>5</max_suspicious_broken_parts> 

There is about 2 seconds I could interact with the pod right after delete and then it falls into the CrashLoopBackOff

I tried to mount the pv into helper pod but not sure if this is correct way to fix it .  My plan is to remove some reference in the filesystem? Frankly I only care about bringing this node back online since this is 3 cluster with 3 replicas , no sharing. 

Could you please advise what is the best method to fix it? I don't care much about the small amount of data contained in the broken parts as long as I can recover the node.
