### ISSUE TITLE
clickhouse-keeper nodes are not discoverable 

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1337]
I  tried using ckickhouse-keeper instead of zookeeper. And i got an error
**Code: 999. DB::Exception: Received from localhost:9000. Coordination::Exception. Coordination::Exception: Cannot use any of provided ZooKeeper nodes. (KEEPER_EXCEPTION)**

I have installed a basic 3 node clickhouse cluster in zoo3ns namespace using this example https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/01-simple-3.yaml

my  clickhouseinstallation
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "repl-05"
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.6
      serviceTemplate: svc-template
  configuration:
    settings:
        mysql_port: 3306
    zookeeper:
      nodes:
        - host: chk-simple-3-0.chk-simple-3.zoo3ns.svc.cluster.local
          port: 9181
        - host: chk-simple-3-1.chk-simple-3.zoo3ns.svc.cluster.local
          port: 9181
        - host: chk-simple-3-2.chk-simple-3.zoo3ns.svc.cluster.local
          port: 9181
```

clickhouse-operator version - **0.23.0**

**Comment by manishtradebyte** [comment]
same config works pretty well for zookeeper  with 3 nodes
```
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo3ns.svc.cluster.local
          port: 2181
        - host: zookeeper-1.zookeepers.zoo3ns.svc.cluster.local
          port: 2181
        - host: zookeeper-2.zookeepers.zoo3ns.svc.cluster.local
          port: 2181
```

**Comment by Slach** [comment]
Could you try to use service name instead of endpoints dns name?

```
zookeeper:
 nodes: 
  - host: chk-simple-3.zoo3ns.svc.cluster.local
    port: 2181
```
