### ISSUE TITLE
Use yaml - config format for  Clickhouse configuration

### ISSUE THREAD

**Issue by mk-raven** [Altinity/clickhouse-operator#1341]
As Clickhouse support yaml configs, it will be grace, to  generate these by Operator in yaml format. Its easy to use and manage in Kubernetes. Also yaml format its more simple to use and read.

**Comment by Slach** [comment]
you are welcome to use

```yaml
spec:
 files:
  file_name.yaml: |
    yaml_key: value
```
