### ISSUE TITLE
How to setup user constraints via ClickHouseInstallation?

### ISSUE THREAD

**Issue by morkalfon** [Altinity/clickhouse-operator#1347]
Is it possible to set max_execution_time on a user using the CRD?

**Comment by Slach** [comment]
multiple ways
look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md

```
kubectl explain chi.spec.configuration.files
kubectl explain chi.spec.configuration.users
kubectl explain chi.spec.configuration.profiles
``` 

```yaml
spec:
  configuration:
    profiles:
      default/max_execution_time: 30
```
