### ISSUE TITLE
ServiceMonitor also selects Clickhouse Nodes

### ISSUE THREAD

**Issue by derbauer97** [Altinity/clickhouse-operator#1350]
Hey,

i noticed when i use the ServiceMonitor in the HelmChart also the clickhouse nodes are selected. So Prometheus tries to scrape them on Port 8888 and Port 9999 which leads to an connection refused.

As far as i understand it is not intentend to scrape the Clickhouse Nodes directly but the clickhouse-operator which provides the metrics. My dashboard is already filled with the correct metrics but i get TargetDown Alerts which i want to fix.

I think it is because the Clickhouse Nodes is:

spec:
  endpoints:
  - port: clickhouse-metrics
  - port: operator-metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/name: altinity-clickhouse-operator
      
      
i think the issue is that the Operator and the Clickhouse Services both have the same labels and therefore get picked up by the ServiceMonitor.

**Comment by Slach** [comment]
how exactly do you install your `kind: ClickHouseInstallation` manifest?

did you use values.yaml something like that?

```yaml
serviceMonitor:
  enabled: true
additionalResources:
 - |
   apiVersion: clickhouse.altinity.com/v1
   kind: ClickHouseInstallation
   metatada:
    ...
   spec:   
    ... 
```
