### ISSUE TITLE
User creation using secrets

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1368]
I am trying to find a way to not hardcode password for my users in the chi yaml.

I  tried sometinng like this

My users section
```
    users:
      test/networks/ip: "::/0"
      test/password: 
        valueFrom:
          secretKeyRef:
            key: test
            name: passwords
      test/profile: default
```

I create a secret
```
apiVersion: v1
kind: Secret
metadata:
  name: passwords
type: Opaque
data:
  test: #base64 hash of my password
```

my generated chop file looks like this
```
        <test>
            <networks>
                <host_regexp>(chi-repl-05-[^.]+\d+-\d+|clickhouse\-repl-05)\.clickhouse-altinity\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
                <ip>::/0</ip>
            </networks>
            <password from_env="CONFIGURATION_USERS_TEST_PASSWORD"></password>
            <profile>default</profile>
            <quota>default</quota>
        </test>
```

also i can se that in the env variable CONFIGURATION_USERS_TEST_PASSWORD is set to the decoded password in plain test

still when i try to login i get this error

```
DB::Exception: pretium: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)

```

Did i miss something or the operator doesnt allow this . 

Also are there some examples where it shows how this can be done?

**Comment by manishtradebyte** [comment]
then i tried this 

```
apiVersion: v1
kind: Secret
metadata:
  name: passwords
type: Opaque
stringData:
  test_password_sha256: 65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5
```

```
    users:
      pretium/networks/ip: "::/0"
      pretium/password: 
        valueFrom:
          secretKeyRef:
            key: test_password_sha256
            name: passwords
      pretium/profile: default
      pretium:access_management: 1

```

i still get the same error
