### ISSUE TITLE
Which Account and Password Should Be Used to Connect to the ClickHouse Cluster from Outside?

### ISSUE THREAD

**Issue by sawchen** [Altinity/clickhouse-operator#1371]
I have installed the Altinity ClickHouse Operator through Helm and deployed a ClickHouse cluster using the following configuration without any additional customization of users or passwords.

```
apiVersion: clickhouse.altinity.com/v1  
kind: ClickHouseInstallation  
metadata:  
  name: my-clickhouse  
spec:  
  defaults:  
    templates: 
      dataVolumeClaimTemplate: default-volume-claim
      logVolumeClaimTemplate: default-volume-claim 
  configuration:  
    clusters:  
      - name: replicas-only  
        templates:
          podTemplate: clickhouse-v23.8
          dataVolumeClaimTemplate: default-volume-claim
          logVolumeClaimTemplate: default-volume-claim
        layout:
          # shardsCount not specified, assumed = 1, by default
          replicasCount: 3 
    zookeeper:  
      nodes:  
        - host: clickhouse-keeper.clickhouse.svc.cluster.local  
          port: 2181  
  templates:
    volumeClaimTemplates:
      - name: default-volume-claim
        provisioner: StatefulSet
        reclaimPolicy: Retain
        spec:  
          storageClassName: csi-rbd-sc  
          accessModes:  
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    podTemplates:
      - name: clickhouse-v23.8
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "4096Mi"
                  cpu: "2000m"
```

Now, how can a service outside my Kubernetes cluster access ClickHouse, and which user and password should I use?

I am aware of two accounts:

The 'default' user, with a blank password, but testing has shown that it cannot be used.
The 'clickhouse_operator' user, with a password set during the Helm installation, but testing has also shown that it cannot be used.
I need help determining the correct credentials to access the ClickHouse cluster from an external service.
