### ISSUE TITLE
Add metric for "onStatefulSetUpdateFailureAction: rollback" / version mismatch

### ISSUE THREAD

**Issue by monotek** [Altinity/clickhouse-operator#1372]
Currently, if an update fails clickhouse does a rollback to the last working version.

It would be nice if we would have a metric for that, so we can get an alert if an clickhouse update failed.

Recently we missed such case, leading to issues, as we worked with an older clickhouse version than expected.

There is alread a metric caleed `chi_clickhouse_metric_VersionInteger`.

If we could have something additional like `chi_clickhouse_metric_DesiredVersionInteger` we could compare the version in the `clickhouseinstallation` resource and the actual running version and alert from that.

**Comment by alex-zaitsev** [comment]
@monotek , since 0.22 operator exposes metrics to track status of reconcile:
```
clickhouse_operator_chi_reconciles_started
clickhouse_operator_chi_reconciles_completed
clickhouse_operator_chi_reconciles_timings

clickhouse_operator_host_reconciles_started
clickhouse_operator_host_reconciles_completed
clickhouse_operator_host_reconciles_restarts
clickhouse_operator_host_reconciles_errors
clickhouse_operator_host_reconciles_timings
```

Those are exposed on port 9999:
```
  annotations:
    clickhouse-operator-metrics/port: '9999'
    clickhouse-operator-metrics/scrape: 'true'
    prometheus.io/port: '8888'
    prometheus.io/scrape: 'true'
```

You may use clickhouse_operator_host_reconciles_errors to alert on all sorts of failures, not just version upgrade ones.
