### ISSUE TITLE
Operator hangs during pod recreation in ClickHouse cluster with multiple shards and replicas

### ISSUE THREAD

**Issue by mandreasik** [Altinity/clickhouse-operator#1375]
**What's wrong:**
If you have a ClickHouse cluster composed of more than 2 shards and 2 replicas e.g., 4 shards, 2 replicas, each action such as changing pod limits, disk size, etc, the operator processes only 4 pods, and then hangs with further operations until it reaches a timeout `reconcile.statefulSet.update.timeout` defined in the operator's configuration. After this timeout, the whole process continues. This problem is really painful in case you have timeout set to eg. 30 minutes.

This problem is 100% reproducible and affects the current version of the operator, which is 0.23.3. It is worth mentioning that cluster topology with 2 shards and 2 replicas works without any issues.

I also tried with different params in reconcile section
```
reconcile:
  runtime:
    # Max number of concurrent CHI reconciles in progress
    reconcileCHIsThreadsNumber: 100
    # Max number of concurrent shard reconciles in progress
    reconcileShardsThreadsNumber: 100
    # The maximum percentage of cluster shards that may be reconciled in parallel
    reconcileShardsMaxConcurrencyPercent: 100 
```

But it was still the same as the default CH operator params

**How to Reproduce:**
Here is the simplest example of how to reproduce the problem:

Install the operator according to the readme:
```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml

```

Apply the cluster configurtion:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "example"
  namespace: kube-system
  finalizers:
    - finalizer.clickhouseinstallation.altinity.com
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
    clusters:
      - name: "temp"
        layout:
          shardsCount: 4
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              # Container has explicitly specified resource requests
              resources:
                requests:
                  cpu: "400m"
              # Container has explicitly specified ports
              ports:
                - name: http
                  containerPort: 8124
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010

```

After cluster is ready, modify the CPU limit:
```
kubectl patch clickhouseinstallation example -n kube-system --type='json' -p='[{"op": "replace", "path": "/spec/templates/podTemplates/0/spec/containers/0/resources/requests/cpu", "value": "500m"}]'
```

Observe the ClickHouse operator logs:

You will see:
```
worker-chi-reconciler.go:787] reconcileHost():[now: 2024-03-13 11:00:04.889733718 +0000 UTC m=+76819.006306894] ProgressHostsCompleted: 4 of 8

```

Then, you will only get information:
```
I0313 11:00:58.152135 1 schemer.go:133] IsHostInCluster():The host 1-0 is inside the cluster
I0313 11:00:58.152170 1 poller.go:170] Poll():kube-system/1-0:WAIT:kube-system/1-0
(...)
I0313 11:04:58.455014 1 schemer.go:133] IsHostInCluster():The host 1-0 is inside the cluster
I0313 11:04:58.455414 1 poller.go:170] Poll():kube-system/1-0:WAIT:kube-system/1-0
```

Then it reaches the timeout, and proceeds further:
```
I0313 11:06:13.564825 1 poller.go:161] Poll():kube-system/1-0:poll(kube-system/1-0) - TIMEOUT reached
I0313 11:06:13.564860 1 worker.go:1002] worker.go:990:excludeHost():end:exclude host end
I0313 11:06:13.564893 1 worker.go:1007] worker.go:1007:completeQueries():start:complete queries start
I0313 11:06:13.564939 1 worker.go:1184] shouldWaitQueries():Will wait for queries to complete according to CHOp config 'reconcile.host.wait.queries' setting. Host is not yet in the cluster. Host/shard/cluster 0/1/temp
I0313 11:06:13.564996 1 cluster.go:84] Run query on: chi-example-temp-1-0.kube-system.svc.cluster.local of [chi-example-temp-1-0.kube-system.svc.cluster.local]
```

**Possible workarounds:**

I found two workarounds for this problem:

1. manually deleting the pod that is in the WAIT state, then the operator proceeds further.
2. Changing `reconcile.host.exclude` from `true` to `false`, then everything also proceeds further.

Can `reconcile.host.exclude: false` be used in production? What are the consequences of not waiting to exclude host from cluster?

**Comment by Slach** [comment]
looks like you added `podTemplates` with non-standard port
but didn't define `serviceTemplates` with non-standard port and didn't link it into
```
spec:
 templates:
   serviceTemplates:
   - name: svc-template
     type: ClusterIP
     ports: 
     - name: http
       containerPort: 8124
     - name: tcp
       containerPort: 9001
     - name: interserver
       containerPort: 9010     
 defaults:
   templates:
     replicaServiceTemplate:  svc-template
```
