### ISSUE TITLE
Select query fails on Distributed table with Authentication failed

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-operator#1376]
defined my user like this.

```yaml
          test/networks/ip: "::/0"
          test/k8s_secret_password: "clickhouse/clickhouse/default"
          test/profile: "default"

```

the secret and the namespace created seperately.

 was able to login to my cluster and create a database ,and table

i only get this error when i try to do a select on the distributed table

```
Received exception from server (version 24.1.6):
Code: 516. DB::Exception: Received from clickhouse.test.xyz.org:9000. DB::Exception: Received from chi-clickhouse-xyz-1-0:9000. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED)

```

used operator 0.23.2
