### ISSUE TITLE
[Question] Is using PreviousTailAffinity in a single node cluster valid syntax?

### ISSUE THREAD

**Issue by xinze-zheng** [Altinity/clickhouse-operator#1378]
Hey there. I tried to apply to following CR with podDistribution type set to PreviousTailAffinity and the reconciliation failed. I'm wondering if this is a semantic issue or a bug in operator. In case you want to see more details, I also attach the log of operator below.
Thanks.

```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test-cluster
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 2
        shardsCount: 2
      name: replicated
    zookeeper:
      nodes:
      - host: zookeeper.zoo3.ns
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.6
  templates:
    podTemplates:
    - name: clickhouse:19.6
      podDistribution:
      - type: PreviousTailAffinity
      spec:
        containers:
        - image: clickhouse/clickhouse-server:22.3
          name: clickhouse-pod
    volumeClaimTemplates:
    - name: default
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
```
[affinity.log](https://github.com/Altinity/clickhouse-operator/files/14618482/affinity.log)
