### ISSUE TITLE
[Question] Best way to replace default disk

### ISSUE THREAD

**Issue by derbauer97** [Altinity/clickhouse-operator#1381]
Currently, we operate a 9TB volume in our production environment, which is nearing its throughput and IOPS limits. To alleviate this strain, we intend to distribute the data across multiple volumes, thereby reducing the burden on any single volume. We've experimented with the move_factor feature, which has proven effective.

However, we now face the challenge of reducing or potentially replacing the default disk after transferring the data to these new volumes to optimize costs. Unfortunately, we haven't been able to find a method to accomplish this task using the ClickHouse operator. Our approach has involved implementing the following storage_policy.

```yaml
  config.d/storage.xml: |
    <clickhouse>
      <storage_configuration>
        <disks>
          <data1>
            <path>/data/clickhouse-01/</path>
          </data1>
          <data2>
            <path>/data/clickhouse-02/</path>
          </data2>
        </disks>
        <policies>
          <default>
            <volumes>
              <data>
                <disk>data1</disk>
                <disk>data2</disk>
              </data>
            </volumes>
            <move_factor>1.0</move_factor>
          </default>
        </policies>
      </storage_configuration>
    </clickhouse>
```

We also set some settings to point paths to the new disk

```yaml
settings:
      tmp_path: /data/clickhouse-01/tmp/
      format_schema_path: /data/clickhouse-01/tmp/format_schemas
      default/path: /data/clickhouse-01/
```

we tried to delete the pvc of the default disk manually and created a new empty one after this but clickhouse were not able to find the tables of our database. So we must miss something.

**Comment by Slach** [comment]
please, do not replace `default` disk
instead of just add additional disks to `default` storage policy with `least_used` load balancing
something like that
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
 name: multi-disk-example
spec:
    files:
      config.d/storage.xml: |-
        <clickhouse>
          <storage_configuration>
            <policies>
              <default replace="1">
                <volumes>
                  <default>
                    <disk>default</disk>
                    <disk>disk2</disk>
                    <disk>disk3</disk>
                    <load_balancing>least_used</load_balancing> 
                  </default>
                </volumes>
              </default>
            </policies>
          </storage_configuration>
        </clickhouse>
    settings:
      storage_configuration/disks/disk2/path: /var/lib/clickhouse2/
      storage_configuration/disks/disk3/path: /var/lib/clickhouse3/
  defaults:
    templates:
      podTemplate: clickhouse-multi-disk
  templates:
    podTemplates:
    - metadata:
      name: clickhouse-multi-disk
      spec:
        containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.1.7.18
          command:
          - /bin/bash
          - -c
          - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
          env:
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: default
          - mountPath: /var/lib/clickhouse2
            name: disk2
          - mountPath: /var/lib/clickhouse3
            name: disk3
    volumeClaimTemplates:
    - name: default
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 9Ti
    - name: disk2
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 9000Gi
    - name: disk3
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 9000Gi

```

and use `ALTER TABLE db.table MOVE PART 'part_name' TO DISK 'disk2'` to move data between disks
this is much safer approach
all new merges and inserts will create in disk2 and disk3 in this case
