### ISSUE TITLE
[Question] Can we specify a static port for NodePort service?

### ISSUE THREAD

**Issue by Electronic-Waste** [Altinity/clickhouse-operator#1382]
I want to allocate a static port in the host node for the clickhouse service, but the operator failed to create NodePort service when I used the following configuration:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-test"
spec:
  defaults:
    templates:
      serviceTemplate: service-template
  
  configuration:
    users:
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
      test_user/password: test_password
      test_user/networks/ip:
      - 0.0.0.0/0
    clusters:
    - name: "clickhouse-test"
      layout:
        shardsCount: 1
        replicasCount: 1
  
  templates:
    serviceTemplates:
    - name: service-template
      generateName: "service-{chi}"
      spec:
        ports:
        - name: http
          port: 8123
          nodePort: 10000
        - name: tcp
          port: 9000
          nodePort: 11000
        type: NodePort
   ```

- `kubectl get svc -n clickhouse -o wide` output (missing a service of `NodePort` type):
```
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE    SELECTOR
chi-clickhouse-test-clickhouse-test-0-0   ClusterIP   None            <none>        9000/TCP,8123/TCP,9009/TCP   10s    clickhouse.altinity.com/app=chop,clickhouse.altinity.com/chi=clickhouse-test,clickhouse.altinity.com/cluster=clickhouse-test,clickhouse.altinity.com/namespace=clickhouse,clickhouse.altinity.com/replica=0,clickhouse.altinity.com/shard=0
clickhouse-operator-metrics               ClusterIP   10.106.136.12   <none>        8888/TCP,9999/TCP            2d1h   app=clickhouse-operator
```

- `kubectl get pod chi-clickhouse-test-clickhouse-test-0-0-0 -n clickhouse` output:
```
Name:             chi-clickhouse-test-clickhouse-test-0-0-0
Namespace:        clickhouse
Priority:         0
Service Account:  default
Node:             node2.db.local/10.2.100.188
Start Time:       Fri, 29 Mar 2024 16:23:31 +0800
Labels:           apps.kubernetes.io/pod-index=0
                  clickhouse.altinity.com/app=chop
                  clickhouse.altinity.com/chi=clickhouse-test
                  clickhouse.altinity.com/cluster=clickhouse-test
                  clickhouse.altinity.com/namespace=clickhouse
                  clickhouse.altinity.com/ready=yes
                  clickhouse.altinity.com/replica=0
                  clickhouse.altinity.com/shard=0
                  controller-revision-hash=chi-clickhouse-test-clickhouse-test-0-0-fcc84688c
                  statefulset.kubernetes.io/pod-name=chi-clickhouse-test-clickhouse-test-0-0-0
Annotations:      <none>
Status:           Running
IP:               10.244.2.108
IPs:
  IP:           10.244.2.108
Controlled By:  StatefulSet/chi-clickhouse-test-clickhouse-test-0-0
Containers:
  clickhouse:
    Container ID:   docker://adf8e72aa53ea4af0732ba984b47e4f9c77c8481740e7fb908b2ce0731469017
    Image:          clickhouse/clickhouse-server:latest
    Image ID:       docker-pullable://clickhouse/clickhouse-server@sha256:c3cfef87fefc1dd596d09e502c547b4dd91eec343c5f39fa3f2ebc102251e652
    Ports:          9000/TCP, 8123/TCP, 9009/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 29 Mar 2024 16:23:34 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http/ping delay=60s timeout=1s period=3s #success=1 #failure=10
    Readiness:      http-get http://:http/ping delay=10s timeout=1s period=3s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/clickhouse-server/conf.d/ from chi-clickhouse-test-deploy-confd-clickhouse-test-0-0 (rw)
      /etc/clickhouse-server/config.d/ from chi-clickhouse-test-common-configd (rw)
      /etc/clickhouse-server/users.d/ from chi-clickhouse-test-common-usersd (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pjwzb (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  chi-clickhouse-test-common-configd:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      chi-clickhouse-test-common-configd
    Optional:  false
  chi-clickhouse-test-common-usersd:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      chi-clickhouse-test-common-usersd
    Optional:  false
  chi-clickhouse-test-deploy-confd-clickhouse-test-0-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      chi-clickhouse-test-deploy-confd-clickhouse-test-0-0
    Optional:  false
  kube-api-access-pjwzb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  8m43s  default-scheduler  Successfully assigned clickhouse/chi-clickhouse-test-clickhouse-test-0-0-0 to node2.db.local
  Normal  Pulling    8m43s  kubelet            Pulling image "clickhouse/clickhouse-server:latest"
  Normal  Pulled     8m40s  kubelet            Successfully pulled image "clickhouse/clickhouse-server:latest" in 2.351s (2.351s including waiting)
  Normal  Created    8m40s  kubelet            Created container clickhouse
  Normal  Started    8m40s  kubelet            Started container clickhouse
```
Has `nodePort` item not been supported until now? Can you have a look?
