### ISSUE TITLE
[Question] How do I update the clickhouse-$INSTALLATION_NAME service to LoadBalancer from ClusterIP?

### ISSUE THREAD

**Issue by chardch** [Altinity/clickhouse-operator#1393]
I have a ClickhouseInstallation with name `stats` and it created a service `clickhouse-stats`. Is the way to update the service type to set `spec.templates.serviceTemplates` to have a service with name `clickhouse-stats`? Is serviceTemplates to add new services or configure the default ones created by the operator?

```
  templates:
    serviceTemplates:
      - name: clickhouse-stats
        spec:
          type: LoadBalancer
```

**Comment by chardch** [comment]
\label question

**Comment by Slach** [comment]
you need to link `serviceTemplates` to `serviceTemplate` by name
use following manifest

```
spec:
  defaults:
    templates:
      serviceTemplate: clickhouse-stats
  templates:
    serviceTemplates:
      - name: clickhouse-stats
        generateName: clickhouse-stats
        spec:
          type: LoadBalancer
```

if you already created a service outside `kind: ClickHouseInstallation` then `clickhouse-operator` should try to update service with name `clickhouse-stats` and if it fail, then try to re-create it with provided `spec.templates.serviceTemplates.spec`

**Comment by chardch** [comment]
Hi @Slach , thanks for your response. So just to confirm, if I want to change the auto created service `clickhouse-stats` from clusterIP to loadbalancer (deployed on GCP), then I can just use 

```spec:
  defaults:
    templates:
      serviceTemplate: clickhouse-stats
  templates:
    serviceTemplates:
      - name: clickhouse-stats
        generateName: clickhouse-stats
        spec:
          type: LoadBalancer
```

I don't have to specify the selectors or anything? I can also supply the lb IP in this?

**Comment by Slach** [comment]
you can set up any parameters in `seviceTemplates[].spec` 
look details in `kubectl explain svc.spec`

`clickhouse-operator` should re-create service, if not delete service manually it should create during CHI reconcile

**Comment by chardch** [comment]
Thanks for confirming @Slach. I saw it's just using the core service spec, but wasn't sure if there will be fields like selector applied automatically by the clickhouse operator. 

However, my issue is that when I set the service template and the default, the service doesn't get created anymore. Here is my yaml. I'm very new to clickhouse, so apologies if I'm missing something

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "stats"
spec:
  configuration:
    # What does my cluster look like?
    clusters:
      - name: "stats"
        layout:
        ...
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
    zookeeper:
    ...
    users:
      ...
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:23.3.13.7.altinitystable
              ...
    volumeClaimTemplates:
      ...
    serviceTemplates:
      - name: clickhouse-stats
        spec:
          type: LoadBalancer
  defaults:
    templates:
      serviceTemplate: clickhouse-stats
```
