### ISSUE TITLE
Version update fails with authentication error

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1397]
I'm having problems with updating the clickhouse version. While following the update guide here : https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi_update_clickhouse_version.md , it fails with the authentication error: 

```
2024.04.16 02:35:23.300567 [ 47 ] {} <Error> DynamicQueryHandler: Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2939d5 in /usr/bin/clickhouse
1. ? @ 0x8ac5dcc in /usr/bin/clickhouse
2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x126b2c54 in /usr/bin/clickhouse
3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x13b65bfa in /usr/bin/clickhouse
4. DB::HTTPHandler::authenticateUser(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&) @ 0x14aec441 in /usr/bin/clickhouse
5. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x14aeda5d in /usr/bin/clickhouse
6. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14af508e in /usr/bin/clickhouse
7. DB::HTTPServerConnection::run() @ 0x14b63d3d in /usr/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x17aa4954 in /usr/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x17aa5b7b in /usr/bin/clickhouse
10. Poco::PooledThread::run() @ 0x17c2d407 in /usr/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x17c2ae3d in /usr/bin/clickhouse
12. ? @ 0x7f94f0582609 in ?
13. clone @ 0x7f94f04a7353 in ?
 (version 23.3.22.3 (official build))
2024.04.16 02:35:23.763443 [ 47 ] {} <Debug> HTTP-Session: fb642e4d-1b22-477e-9f16-1cb378955d86 Authenticating user 'default' from [::ffff:10.244.7.186]:45042
2024.04.16 02:35:23.763719 [ 47 ] {} <Error> Access(user directories): from: ::ffff:10.244.7.186, user: default: Authentication failed: Code: 193. DB::Exception: Invalid credentials. (WRONG_PASSWORD), Stack trace (when copying this message, always include the lines below):
```

I tried with update one and all and the results is the same which is related to authentication error from what I can tell seeing on the logs

the manifest I use for the update of one pod 

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "version-update"
  namespace: ck
spec:
  configuration:
    users:
      admin/password: "admin321"
      admin/networks/ip: "::/0"
      default/password: "admin321"
      default/networks/ip: "::/0" 
    clusters:
      - name: update
        templates:
          podTemplate: clickhouse:23.3
        layout:
          shards:
            - replicas:
                - tcpPort: 9000
                - tcpPort: 9000
                - tcpPort: 9000
                  templates:
                    podTemplate: clickhouse:23.8

  templates:
    podTemplates:
      - name: clickhouse:23.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.3

      - name: clickhouse:23.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
```
also tried with this initially since it was used for deploying the cluster at the first time,  but no luck 
```
    users: 
      admin/password: admin321    
      admin/networks/ip: 0.0.0.0/0 
```

and the manifest I used to originally deploy the cluster: 

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "ck3"
  namespace: ck

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7-with-backup  # updated pod template name
 
  configuration:
    users: 
      admin/password: admin321    
      admin/networks/ip: 0.0.0.0/0 
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-1.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-2.zookeepers.ck.svc.cluster.local # Zookeeper
        
    clusters:
      - name: replicated
        layout:
          shardsCount: 1
          replicasCount: 3


  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 1.35Ti
    podTemplates:
      - name: clickhouse:20.7-with-backup
        metadata:
          annotations:
            prometheus.io/port: '8888'
            prometheus.io/scrape: 'true'
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: database
                    operator: In
                    values:
                    - ydb
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: clickhouse.altinity.com/chi
                    operator: In
                    values:
                    - ck3
                topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:2.2.7
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -xc
                - "/bin/clickhouse-backup server"
              env:
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                - name: API_ENABLE_METRICS
                  value: "true"
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                - name: S3_ENDPOINT
                  value: https://192.168.3.80:8010
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-s3-secrets
                      key: S3_BUCKET
                - name: S3_PATH
                  value: clickhouse-backup
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                - name: S3_DISABLE_CERT_VERIFICATION
                  value: "true"
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-s3-secrets
                      key: S3_ACCESS_KEY
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-s3-secrets
                      key: S3_SECRET_KEY
              ports:
                - name: backup-rest
                  containerPort: 7171

```

Any idea what causing be causing it?

**Comment by Slach** [comment]
Different `kind: ClickHouseInstallation`
```yaml
metadata:
  name: "ck3"
```

and
```yaml
metadata:
  name: "version-update"
```

will create two different ClickHouse clusters

to upgrade `clickhouse-server` version, just upgrade image in `ck3`?

```yaml
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
```

in this case operator will rollout upgrade each replicas one by one
