### ISSUE TITLE
Operator hammers the Kubernetes api-server on Clickhouse Keeper resource

### ISSUE THREAD

**Issue by sigxcpu76** [Altinity/clickhouse-operator#1413]
Looks like the operator updates the CHK resource many tens of times per second hammering the `api-server`.
There are no obvious changes between patched resources except `resourceVersion` field.

Downgraded to `0.23.4` and it behaves the same, so it is not something new.

The object is quickly patched as seen below.

```
# while [ /bin/true ]; do echo -n $(date); echo -n "   "; kubectl get chk -n analytics analytics-keeper -o json | jq -r .metadata.resourceVersion; sleep 1; done
Mon May 6 09:48:45 PM EEST 2024   2112686559
Mon May 6 09:48:46 PM EEST 2024   2112686634
Mon May 6 09:48:48 PM EEST 2024   2112686719
Mon May 6 09:48:50 PM EEST 2024   2112686857
Mon May 6 09:48:51 PM EEST 2024   2112686995
```

**Comment by Slach** [comment]
check `clickhouse-operator:0.24.0`, notify us if API server is overload

**Comment by zs-ko** [comment]
@Slach the new image just results in an empty containers in the sts

```
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: om-chk-01
      uid: 417568b0-becd-4daa-bdc2-d79ea23d563a
  serviceName: ''
  template:
    metadata:
      creationTimestamp: null
      generateName: om-chk-01
      labels:
        app: om-chk-01
        uid: 417568b0-becd-4daa-bdc2-d79ea23d563a
    spec:
      containers: null
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
```
