### ISSUE TITLE
Grant ROLE to user created with operator

### ISSUE THREAD

**Issue by baznikin** [Altinity/clickhouse-operator#1415]
Hello! Maybe I missunderstand something, but I can't find how to grant role to user specified with operator.

CHIT manifest:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: secure-clickuser
spec:
  configuration:
    users:
      clickuser/k8s_secret_password: clickhouse-credentials/clickuser
      clickuser/networks/ip: 0.0.0.0/0
      # https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control
      clickuser/access_management: "1"
      clickuser/named_collection_control: "1"
      clickuser/show_named_collections: "1"
      clickuser/show_named_collections_secrets: "1"
```

1. If I try to grant role from cli I got error
```
chi-clickhouse-default-0-0-0.chi-clickhouse-default-0-0.clickhouse.svc.cluster.local :) GRANT "3" to clickuser

GRANT `3` TO clickuser

Query id: b6c46f5b-303f-4b4e-bc1b-5a61d7993a90


Elapsed: 0.002 sec. 

Received exception from server (version 24.4.1):
Code: 495. DB::Exception: Received from localhost:9000. DB::Exception: Cannot update user `clickuser` in users_xml because this storage is readonly. (ACCESS_STORAGE_READONLY)
```

2. If I set it with `grants/query` I got another error and CH failed to start:
```
spec:
  templating:
    policy: "auto"
  configuration:
    users:
      clickuser/grants/query:
      - GRANT "3" TO clickuser
```

```
2024.05.07 15:17:10.713677 [ 1 ] {} <Error> Application: Code: 36. DB::Exception: Any other access control settings can't be specified with `grants`: while parsing user 'clickuser' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):
```

At same time I can grant grant this role to dynamically created user:

```
chi-clickhouse-default-0-0-0.chi-clickhouse-default-0-0.clickhouse.svc.cluster.local :) CREATE USER `temp` identified  by '123'

CREATE USER temp IDENTIFIED BY '123'

Query id: f894d572-9705-4b95-a8e4-6bf5732b50fb

Ok.

0 rows in set. Elapsed: 0.002 sec. 

chi-clickhouse-default-0-0-0.chi-clickhouse-default-0-0.clickhouse.svc.cluster.local :) GRANT "3" to temp

GRANT `3` TO temp

Query id: 21cc3984-76f2-4c9c-a4c3-445e26b7e6b3

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```

How to overcome it?

Versions:
* altinity/clickhouse-operator:0.23.4
* ClickHouse local version 24.4.1.2088 (official build).
