### ISSUE TITLE
How to install the operator in a custom namespace and watch for changes in all namespaces.

### ISSUE THREAD

**Issue by arun-kbharathan-e3768** [Altinity/clickhouse-operator#1418]
I have a requirement similar to this [issue](https://github.com/Altinity/clickhouse-operator/issues/294), where i want to install clickhouse-operator in a seperate _operator_ namespace but should watch for changes in all namespaces, not the namespace where I installed the operator alone.
I saw [this](https://github.com/Altinity/clickhouse-operator/pull/699) PR already implements that, how to use that change? what extra environment variables should I define before running the altinity operator installation script to use that change. Please Help.

**Comment by Slach** [comment]
something like that install operator
```
curl -sL https://github.com/Altinity/clickhouse-operator/raw/master/deploy/operator-web-installer/clickhouse-operator-install.sh | OPERATOR_NAMESPACE=your-namespace bash
```

edit configmap
`etc-clickhouose-operator-files`

find `watch:` section
replace from
`      namespaces: []`
to
`      namespaces: ['.*']`

or just create separate manifest

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "watch-all-namespaces"
spec:
  watch:
    namespaces: 
    - ".*"
```

and restart operator

**Comment by hausertt** [comment]
In the current operator version (v0.25.5), the configuration would be:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "watch-all-namespaces"
spec:
  watch:
    namespaces:
      include:
      - ".*"
```

Just adding this here since I had trouble finding it in the documentation and spent some time figuring it out.
