### ISSUE TITLE
set memory limits on clickhouse 

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1426]
In order to reduce the memory usage (currently unlimited) I tried to add profiles and under users settings however none of those will take any effect after applying the configs 
Is this correct method of doing it?
 
      **max_memory_usage: "30000000000"  
      max_memory_usage_for_all_queries: "30000000000"**  

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "ck3"
  namespace: ck

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7-with-backup  # updated pod template name
 
  configuration:
    users: 
      admin/password: admin321    
      admin/networks/ip: 0.0.0.0/0 

    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-1.zookeepers.ck.svc.cluster.local # Zookeeper
        - host: zookeeper-2.zookeepers.ck.svc.cluster.local # Zookeeper
        
        # - host: clickhouse-keeper.ck.svc.cluster.local  # Clickhouse Keeper
        #   port: 2181
    clusters:
      - name: replicated
        layout:
          shardsCount: 1
          replicasCount: 3

    profiles:
      max_memory_usage: "30000000000"  
      max_memory_usage_for_all_queries: "30000000000"  

    # settings:
    # #   merge_tree:
    # #     max_suspicious_broken_parts: 100
    #     max_memory_usage: "30000000000"  # Set to 30 GB
    #     max_memory_usage_for_all_queries: "30000000000"  # Set to 30 GB
    #     max_bytes_before_external_sort: "500000000"  # Set to 500 MB
    #     max_bytes_before_external_group_by: "500000000"  # Set to 500 MB
    #     memory_tracker_fault_probability: "0"
    #     memory_overcommit_ratio_denominator: "85"  # 85% of available memory
    #     memory_profiler_step: "4194304"
    #     memory_profiler_sample_probability: "0"
    #     memory_profiler_sample_min_allocation_size: "0"
    #     memory_profiler_sample_max_allocation_size: "0"
    #     memory_usage_overcommit_max_wait_microseconds: "5000000"
    #     filesystem_prefetch_max_memory_usage: "1073741824"

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 1.35Ti
    podTemplates:
      - name: clickhouse:20.7-with-backup
        metadata:
          annotations:
            prometheus.io/port: '8888'
            prometheus.io/scrape: 'true'
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: database
                    operator: In
                    values:
                    - ydb
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: clickhouse.altinity.com/chi
                    operator: In
                    values:
                    - ck3
                topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-pod
              # image: clickhouse/clickhouse-server:22.3
              image: clickhouse/clickhouse-server:23.8
```
kubectl exec -n ck chi-ck3-replicated-0-0-0 -- clickhouse-client -q "SELECT * FROM system.settings WHERE name='max_memory_usage' FORMAT Vertical"
Defaulted container "clickhouse-pod" out of: clickhouse-pod, clickhouse-backup
Row 1:
──────
name:        max_memory_usage
value:       0
changed:     0
description: Maximum memory usage for processing of single query. Zero means unlimited.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        UInt64
default:     0
alias_for:   
is_obsolete: 0

SELECT
    name,
    value
FROM system.settings
WHERE name LIKE '%memory%'

```
Query id: ac38c35f-37a6-4259-bcad-22320150d4ff

┌─name───────────────────────────────────────────────┬─value──────┐
│ distributed_aggregation_memory_efficient           │ 1          │
│ aggregation_memory_efficient_merge_threads         │ 0          │
│ enable_memory_bound_merging_of_aggregation_results │ 1          │
│ memory_tracker_fault_probability                   │ 0          │
│ remerge_sort_lowered_memory_bytes_ratio            │ 2          │
│ max_memory_usage                                   │ 0          │
│ memory_overcommit_ratio_denominator                │ 1073741824 │
│ max_memory_usage_for_user                          │ 0          │
│ memory_overcommit_ratio_denominator_for_user       │ 1073741824 │
│ max_untracked_memory                               │ 4194304    │
│ memory_profiler_step                               │ 4194304    │
│ memory_profiler_sample_probability                 │ 0          │
│ memory_profiler_sample_min_allocation_size         │ 0          │
│ memory_profiler_sample_max_allocation_size         │ 0          │
│ memory_usage_overcommit_max_wait_microseconds      │ 5000000    │
│ filesystem_prefetch_max_memory_usage               │ 1073741824 │
│ max_memory_usage_for_all_queries                   │ 0          │
└────────────────────────────────────────────────────┴────────────┘
```
ideally I would prefer to set in terms of percentage limit since not all the nodes have the same capacity

**Comment by Slach** [comment]
use
```
   profiles:
      default/max_memory_usage: "30000000000"  
      default/max_memory_usage_for_all_queries: "30000000000"  
```

instead of

```yaml
   profiles:
      max_memory_usage: "30000000000"  
      max_memory_usage_for_all_queries: "30000000000"  
```
