### ISSUE TITLE
set remote server user/password

### ISSUE THREAD

**Issue by mosinnik** [Altinity/clickhouse-operator#1429]
In CH doc https://clickhouse.com/docs/en/guides/sre/configuring-ssl in 4.3 there is an example of remote_servers section where we can set user and password for cross-shard requests:
```
<remote_servers>
    <cluster_1S_2R>
        <shard>
            <replica>
                <host>chnode1.marsnet.local</host>
                <port>9440</port>
                <user>default</user>
                <password>ClickHouse123!</password>
                <secure>1</secure>
            </replica>
            ...  
````

How can I set those user and password via operator manifest?

**Comment by ilkarataev** [comment]
I can give you advice based on my experience. I created one more config in the files section and it works well. ClickHouse just merges all configs.

**Comment by Slach** [comment]
use
```yaml
spec:
  files:
    config.d/remote_servers_with_password.xml: |
      <remote_servers>
       <cluster_1S_2R>
        <shard>
            <replica>
                <host>chnode1.marsnet.local</host>
                <port>9440</port>
                <user>default</user>
                <password>ClickHouse123!</password>
                <secure>1</secure>
            </replica>

```

**Comment by mosinnik** [comment]
@Slach to clarify, so that mean that I should manually generate full remote_serservs section with all pods and my props instead of relying on the operator?
and one question, is it possible to see this feature in future?

**Comment by Slach** [comment]
Actually for `default` user which used for distributed queries, connection already restricted by IP
https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#the-default-user

In your case better use
```yaml
spec:
  configuration:
    settings:
      remote_servers/your-cluster-name/secret: 
        valueFrom:
          secretKeyRef:
            name: clickhouse_secret
            key: cluster_secret_field         
```

and
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse_secret
type: Opaque
stringData:
  cluster_secret_field: *****
```

this will execute distributed queries with initial user security permissions which you used for connection to initiator node
