### ISSUE TITLE
Operator don't run anything when i apply `ClickHouseInstallation`

### ISSUE THREAD

**Issue by sheldygg** [Altinity/clickhouse-operator#1434]
Hi, I install the operator by [this](https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md#in-case-you-can-not-run-scripts-from-the-internet-in-your-protected-environment) instruction 

Then when I apply this manifest:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
  namespace: clickhouse
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    users:
      # printf 'test_password' | sha256sum
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
      # to allow access outside from kubernetes
      test_user/networks/ip:
        - 0.0.0.0/0
    clusters:
      - name: "simple"
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
```
Operator don't run anything
```
kubectl get all -n clickhouse
No resources found in clickhouse namespace.
```
What could go wrong?

**Comment by Slach** [comment]
could you share 
`kubectl get chi --all-namespaces` ?

**Comment by sheldygg** [comment]
> could you share `kubectl get chi --all-namespaces` ?

```
NAMESPACE    NAME        CLUSTERS   HOSTS   STATUS   HOSTS-COMPLETED   AGE
clickhouse   simple-01                                                 6s
```

**Comment by Slach** [comment]
`kubectl get pod --all-namespaces | grep clickhouse-operator`

**Comment by Slach** [comment]
which part of instruction did you apply? download template and edit it manually? 
or applied script ?

**Comment by sheldygg** [comment]
> `kubectl get pod --all-namespaces | grep clickhouse-operator`

clickhouse-operator   clickhouse-operator-7bf9fcd556-dxzhz                      2/2     Running            0               52m

**Comment by sheldygg** [comment]
> какую часть инструкции вы применили? скачать шаблон и редактировать его вручную? или прикладной сценарий?

![image](https://github.com/Altinity/clickhouse-operator/assets/85823514/6e5590d5-7bed-428b-a484-c7982504754a)
I just run this apply with this enviroment
```
OPERATOR_NAMESPACE="clickhouse-operator"
METRICS_EXPORTER_NAMESPACE="${OPERATOR_NAMESPACE}"
OPERATOR_IMAGE="altinity/clickhouse-operator:latest"
METRICS_EXPORTER_IMAGE="altinity/metrics-exporter:latest"
```

**Comment by Slach** [comment]
ok. 
in this case, installed operator will watch only CHI resources in `clichouse-operator` namespace, but you install your CHI into `clickhouse` namespace instead

edit
configmap
`etc-clickhouse-operator-files`

find `watch` section
and 
replace
```yaml
 watch:
      # List of namespaces where clickhouse-operator watches for events.
      # Concurrently running operators should watch on different namespaces.
      # IMPORTANT
      # Regexp is applicable.
      #namespaces: ["dev", "test"]
      namespaces: []
```
to
```yaml
 watch:
      namespaces: [".*"]
```
or
```yaml
 watch:
      namespaces: ["clickhouse"]
```
