### ISSUE TITLE
HostAliases are overwritten in statefulSet

### ISSUE THREAD

**Issue by fpierrick** [Altinity/clickhouse-operator#1445]
Hi folks,
I cannot configure other hostAliases for my pods.
It seems hosts are overwritten in **_pkg/model/chi/creator/stateful_set.go#personalizeStatefulSetTemplate_** instead of append to existing.
Can you fix it please?

Thanks for your help

Example of my ClickHouseInstallation
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-cluster"
spec:
  templates:
    podTemplates:
      - name: clickhouse-pod
        spec:
          containers:
          - name: clickhouse
            image: clickhouse/clickhouse-server:latest
          hostAliases:
          - ip: "XX.XX.XX.XX"
            hostnames:
            - "myHostName"
  configuration:
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          dataVolumeClaimTemplate: clickhouse-data-volume
          podTemplate: clickhouse-pod
```

In the statefulSet definition we have only the localhost hostname.
```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
...
  spec:
...
    template:
...
      spec:
...        
        hostAliases:
        - hostnames:
          - chi-clickhouse-cluster-clickhouse-0-0
          ip: 127.0.0.1
        restartPolicy: Always
```
