### ISSUE TITLE
Data loss when upgrading storage requests

### ISSUE THREAD

**Issue by madhur-df** [Altinity/clickhouse-operator#1446]
When creating a resource of type: `ClickHouseInstallation`

the initial requested storage is 10Gi as shown in the snippet below:

```
      - name: data-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

If I want to increase this storage to 30Gi, the data and the tables are lost and I need to re-create them.

The blog here: https://altinity.com/blog/preventing-clickhouse-storage-deletion-with-the-altinity-kubernetes-operator-reclaimpolicy offers adding `reclaimPolicy: Retain` in the spec file.

Will this help in preventing data loss when increasing the storage requests as well?
Please let me know!
