### ISSUE TITLE
How to remove the storage size from the operator’s control?

### ISSUE THREAD

**Issue by tropnikovvl** [Altinity/clickhouse-operator#1454]
Hello!

I use [this](https://github.com/topolvm/pvc-autoresizer) tool to automatically resize all PVC when they run out of space.
Unfortunately, this does not work with the operator, since at the moment the operator has complete control over the disk size when creating the PVC and when changing the size.

Can you tell me if there is some kind of flag or parameter that will allow me to reduce the operator’s control over the PVC so that I can resize them without updating the CR? Or so that the CR is updated automatically in accordance with the actual size. Or some other option.

Thank you

**Comment by chengjoey** [comment]
Just update the storage size or pvc of pv, no need to update CR

**Comment by tropnikovvl** [comment]
Hello @chengjoey !

I did this and the operator, noticing a change in the resource, immediately rolled it back before the size actually changed.

I use 
```yaml
          storageManagement:
            provisioner: Operator
```

**Comment by chengjoey** [comment]
@tropnikovvl 
i juset set `volumeClaimTemplates` and make reclaimPolicy to `Retain` like this:
```
volumeClaimTemplates:
    - name: chi-volume-claim
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
```
no matter how I modify pv and pvc, my chi is not modified by operator, and the clikhouse instance is running normally

**Comment by tropnikovvl** [comment]
@chengjoey 
It really works!
And I can do this without interrupting the pod.

But it’s very strange to me that the reconciliation is successful, considering that in CR there is one size, but in reality it’s another

**Comment by Slach** [comment]
try to use
```
spec:
 defaults:
   storageManagement:
     provisioner: StatefulSet
```

in this case operator will not manage PVC directly
just define 
volumeClaimTemplate inside rendered StatefulSet manifest

and https://github.com/topolvm/pvc-autoresizer should works
