### ISSUE TITLE
Hardcoded cluster.local DNS suffix for Clickhouse Keeper

### ISSUE THREAD

**Issue by hmerat** [Altinity/clickhouse-operator#1459]
Hi! Clickhouse keeper from clickhouse-operator doesn't work because of hardcoded cluster.local suffix. In our k8s installation we use custom domain name, which differs from cluster.local

For Clickhouse, we can override this by using `namespaceDomainPattern` but this options seems not available for Clickhouse Keeper.

Thanks.

**Comment by minor-fixes** [comment]
I'm running into this too - it looks like `namespaceDomainPattern` is added to the CRD for keeper installations by [this commit](https://github.com/Altinity/clickhouse-operator/commit/1bc27ead1cb13fdab6044552d5bc2bc075f9d0ce), but it is not actually respected, and there are hardcoded `.svc.cluster.local` throughout the codebase.

**Comment by Slach** [comment]
@minor-fixes could you try clickhouse-operator:0.24.0 ?

I checked 
```
minikube start --dns-domain=custom.k8s.local
```

install operator
then applied
```yaml
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: simple1
spec:
  namespaceDomainPattern: "%s.svc.custom.k8s.local"
  configuration:
    clusters:
      - name: "cluster1"
        replicas: 3
```
