### ISSUE TITLE
need chk labels propagation to statefulset and pods

### ISSUE THREAD

**Issue by g-marius** [Altinity/clickhouse-operator#1465]
We're looking into labeling CHK resources (chk, statefulset and pod) with a set of attributes (Example: `product, project, team`). We are using this method for attribution of product and projects ownership to teams. 

On 0.23.6 release of operator:

1. setting labels on chk/podtemplate levels will fail (see error)
2. there is no explicit option of labels for managed statefulset either

Repro yaml
```
apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
...
  labels:
    product: foo
    project: bar
    team: baz
...
spec:
 ...
  templates:
    podTemplates:
    - metadata:
        labels:
          product: foo
          project: bar
          team: baz
```

Error log
```
clickhouse-operator E0725 10:58:37.161204       1 reconciler.go:103] Error during reconcile. f: github.com/altinity/clickhouse-operator/pkg/controller/chk.(*ChkReconciler).reconcileStatefulSet-fm err: StatefulSet.apps "example" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"product":"foo", "project":"bar", "team":"baz"}: `selector` does not match template `labels`
```

Expectations
1. Allow configuring labels at chk, statefulset, pod level
