### ISSUE TITLE
Allow key REMOVE="1" in xml tag to be added as a setting in chi manifest

### ISSUE THREAD

**Issue by lesandie** [Altinity/clickhouse-operator#1472]
Disabling some heavy system tables should be easier simply by editing the chi yaml and using plain setttings syntax sugar like this:

```yaml
  configuration:
    settings:
      opentelemetry_span_log/remove: 1
      processors_profile_log/remove: 1
```

No need to create an entry in a configmap like this:

```xml
<clickhouse>
   <opentelemetry_span_log remove="1"></opentelemetry_span_log>
</clickhouse>
```

**Comment by alex-zaitsev** [comment]
@lesandie , this is supported already. Use:

```
  configuration:
    settings:
      opentelemetry_span_log: _removed_
      processors_profile_log: _removed_
```
