### ISSUE TITLE
Clickhouse Keeper continuously modified by operator

### ISSUE THREAD

**Issue by jkososki** [Altinity/clickhouse-operator#1476]
I've deployed the operator to a GKE cluster and found that the operator will continuously modify the chk resource after all components appear to be online and showing healthy.  The same does not occur when deploying a chi resource.  The only changes captured in diffs is the resourceVersion.

Expected behavior:  Once all resources are healthy the operator should stop modifying the chk resource.
Observed behavior:  The operator rapidly updates chk resource and does not stop.

Steps to reproduce:
1. Deploy a chk resource (redacted manifest below)
2. Monitor the chk resource
```bash
watch -n .1 "kubectl -n clickhouse get chk chk-signoz-db -o yaml | yq '.metadata.resourceVersion'"
```
The resourceVersion is constantly changing.
Capturing the full yaml and performing diffs did not show any other changes.

Thank you for your help!

I've tried a few deployment configurations but the primary configuration is below.

**Configuration**
```yaml
apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
  labels:
    app.kubernetes.io/instance: signoz-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: signoz-db
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: signoz-db
    helm.sh/chart: signoz-db-0.1.4
  name: chk-signoz-db
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - layout:
          replicasCount: 1
        name: signoz-db
    settings:
      keeper_server/coordination_settings/raft_logs_level: information
      keeper_server/storage_path: /var/lib/clickhouse-keeper
      keeper_server/tcp_port: '2181'
      listen_host: 0.0.0.0
      logger/console: 'true'
      logger/formatting: json
      logger/level: information
  templates:
    podTemplates:
      - metadata:
          labels:
            app.kubernetes.io/instance: signoz-db
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: signoz-db
            app.kubernetes.io/version: 1.16.0
            helm.sh/chart: signoz-db-0.1.4
        name: pod-template
        spec:
          containers:
            - image: 'clickhouse/clickhouse-keeper:24-alpine'
              imagePullPolicy: Always
              name: clickhouse-keeper
              resources:
                limits:
                  cpu: '1'
                  memory: 4Gi
                requests:
                  cpu: 500m
                  memory: 4Gi
          imagePullSecrets:
            - name: regcred
          nodeSelector:
            <removed>: <removed>
          securityContext:
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 101
            runAsUser: 101
          tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: signoz
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app: clickhouse-keeper
              maxSkew: 1
              topologyKey: kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
    volumeClaimTemplates:
      - name: snapshot-storage-path
        spec:
          accessModes:
            - ReadWriteOnce
          reclaimPolicy: Retain
          resources:
            requests:
              storage: 20Gi
          storageClassName: standard
      - name: log-storage-path
        spec:
          accessModes:
            - ReadWriteOnce
          reclaimPolicy: Retain
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
```
