### ISSUE TITLE
Helm chart is not available for 0.23.7

### ISSUE THREAD

**Issue by marre** [Altinity/clickhouse-operator#1488]
The helm repo at https://docs.altinity.com/clickhouse-operator/ has not been updated to include 0.23.7

```
➜  ~ helm repo up clickhouse-operator
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "clickhouse-operator" chart repository
Update Complete. ⎈Happy Helming!⎈
➜  ~ helm search repo clickhouse-operator
NAME                                            	CHART VERSION	APP VERSION	DESCRIPTION
clickhouse-operator/altinity-clickhouse-operator	0.23.6       	0.23.6     	Helm chart to deploy [altinity-clickhouse-opera...
➜  ~
```

**Comment by Slach** [comment]
@sunsingerus remove protection from `gh-pages` branch

we failed with publish new helm chart
```
Pushing to branch "gh-pages"
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.      
```

https://github.com/Altinity/clickhouse-operator/actions/runs/10357750979/job/28670456756#step:7:161

**Comment by sunsingerus** [comment]
@marre chart released, please check availability

**Comment by alex-zaitsev** [comment]
@marre , fixed:
https://docs.altinity.com/clickhouse-operator/index.yaml

```
apiVersion: v1
entries:
  altinity-clickhouse-operator:
  - apiVersion: v2
    appVersion: 0.23.7
    created: "2024-08-15T10:52:09.6922605Z"
...
```
