### ISSUE TITLE
Feature Request: Disable shard scale-in

### ISSUE THREAD

**Issue by mskwon** [Altinity/clickhouse-operator#1503]
Would it be possible to add a setting to clickhouse-operator that disables the deletion of shards?

The purpose of this setting is to prevent inadvertent deletion of shards due to human operator error / misconfig, which deletes the PVCs as well as makes the shard's data unavailable (assuming that the data was not moved to another shard).

**Comment by Slach** [comment]
look `kubectl explain chi.spec.templates.volumeClaimTemplates.reclaimPolicy`

use something like that
```yaml
spec:
  defaults:
    templates:
      dataVolumeClaim: with-retain
  templates:
    volumeClaimTemplates:
    - name: with-retain
      reclaimPolicy: Retain
      spec:
        storageClassName: ...
        resource:
          requests:
            storage: 5Gi
```  
it prevent deleting PVC and allow restore disk data it after operator applied wrong `kind: ClickHouseInstallation` manifest
