### ISSUE TITLE
increase the max_suspicious_broken_parts_bytes not working

### ISSUE THREAD

**Issue by darioneto** [Altinity/clickhouse-operator#1505]
One of my pods is failing to start due to error 
`DB::Exception: Suspiciously big size (8 parts, 1.37 GiB in total) of all broken parts to remove while maximum allowed broken parts size is 1.00 GiB.`

I have already updated the configuration to the following:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ck3"
  namespace: ck
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7-with-backup
 
  configuration:
    settings:
      merge_tree:
        max_suspicious_broken_parts_bytes: 4294967296
      max_suspicious_broken_parts_bytes: 4294967296
```
```
kubectl exec -n ck chi-ck3-replicated-0-0-0 -- sh -c "grep -r 'max_suspicious_broken_parts_bytes' /etc/clickhouse-server/"
Defaulted container "clickhouse-pod" out of: clickhouse-pod, clickhouse-backup
/etc/clickhouse-server/config.d/..2024_09_06_14_43_34.962645124/chop-generated-settings.xml:    <max_suspicious_broken_parts_bytes>4294967296</max_suspicious_broken_parts_bytes>
```

However, the current behavior still limits it to 1 GiB, preventing the attachment of certain tables.
Could you please let me know how I can ensure that ClickHouse respects the new setting?

**Comment by chengjoey** [comment]
try:
```
spec:
  configuration:
    settings:
      merge_tree/max_suspicious_broken_parts_bytes: 4294967296
```

```
chi-addon-clickhouse-clickhouse-0-0-0:/# grep -r 'max_suspicious_broken_parts_bytes' /etc/clickhouse-server/ -C 20
/etc/clickhouse-server/config.d/chop-generated-settings.xml-<yandex>
/etc/clickhouse-server/config.d/chop-generated-settings.xml-    <merge_tree>
/etc/clickhouse-server/config.d/chop-generated-settings.xml:        <max_suspicious_broken_parts_bytes>4294967296</max_suspicious_broken_parts_bytes>
/etc/clickhouse-server/config.d/chop-generated-settings.xml-    </merge_tree>
/etc/clickhouse-server/config.d/chop-generated-settings.xml-</yandex>
```

reference [docs](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings), it should be working
