### ISSUE TITLE
spec.configuration.roles to declaratively create roles does not exist

### ISSUE THREAD

**Issue by seilerre** [Altinity/clickhouse-operator#1534]
I want to define roles, that I can then assign to my users, as done in this xml example: https://github.com/ClickHouse/ClickHouse/blob/4f3c9c3ee8c01ab286519b810f4f2e52852dca6e/tests/integration/test_user_grants_from_config/configs/another_user.xml#L29

However, the operator doesn't allow to set spec.configuration.roles. Or am I missing something? https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationusers

**Comment by Slach** [comment]
you can use
```yaml
spec:
 configuration:
   files:
     users.d/roles.xml: |
       <clickhouse>
          <roles>
          </roles> 
       </clickhouse>
```
