### ISSUE TITLE
chop-generated-users.xml Root element doesn't have the corresponding root element as the config file. It must be <yandex>

### ISSUE THREAD

**Issue by Aleksey-Kalinin** [Altinity/clickhouse-operator#1541]
I'm getting an error
`<Error> Application: Exception: Failed to merge config with '/etc/clickhouse-server/users.d/chop-generated-users.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <yandex>`

My configuration is
```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
   name: clickhouse-communal
spec:
  configuration:
    clusters:
      - layout:
          shardsCount: 1
        name: cluster
    users:
      admin/networks/ip: '::/0'
      admin/password: 555555
      admin/profile: default
      user--test-clickhouse--check-deploy-testdatabases-chibase/allow_databases/database:
        - check-deploy-testdatabases-chibase
      user--test-clickhouse--check-deploy-testdatabases-chibase/networks/ip: '::/0'
      user--test-clickhouse--check-deploy-testdatabases-chibase/password: 89af86cd442da51d15c10f1469f54165c4889013a27e8559d3e33fb93ce9a6aa
      user--test-clickhouse--check-deploy-testdatabases-chibase/profile: default
  defaults:
    templates:
      dataVolumeClaimTemplate: chi-data-pvc
      podTemplate: chi-pod
      serviceTemplate: chi-svc
  templates:
    podTemplates:
      - generateName: clickhouse-communal
        metadata:
          labels:
            clickhouse-instance: clickhouse-communal
        name: chi-pod
        spec:
          containers:
            - image: yandex/clickhouse-server:21.3.20.1
              name: clickhouse
              resources:
                limits:
                  memory: 2Gi
                requests:
                  cpu: 10m
                  memory: 256Mi
    serviceTemplates:
      - generateName: clickhouse-communal
        metadata:
          labels:
            clickhouse-instance: clickhouse-communal
        name: chi-svc
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: tcp-2
              port: 9009
          type: ClusterIP
    volumeClaimTemplates:
      - name: chi-data-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: yc-network-hdd
```

Full logs clickhouse operator is 

```
2024.10.24 07:43:51.988028 [ 52 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp/ to store temporary data in it
2024.10.24 07:43:51.988320 [ 52 ] {} <Information> SensitiveDataMaskerConfigRead: 1 query masking rules loaded.
2024.10.24 07:43:51.989126 [ 52 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-hostname-ports.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-macros.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-01-listen.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-02-logger.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-03-query_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-04-part_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-05-trace_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
2024.10.24 07:43:51.993312 [ 52 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/config.xml', performing update on configuration
2024.10.24 07:43:51.994041 [ 52 ] {} <Information> Application: Setting max_server_memory_usage was set to 28.21 GiB (31.35 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2024.10.24 07:43:51.995263 [ 52 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/config.xml', performed update on configuration
2024.10.24 07:43:51.997841 [ 52 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
Processing configuration file '/etc/clickhouse-server/users.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-hostname-ports.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-macros.xml'.
Merging configuration file '/etc/clickhouse-server/users.d/01-clickhouse-operator-profile.xml'.
Merging configuration file '/etc/clickhouse-server/users.d/02-clickhouse-default-profile.xml'.
Merging configuration file '/etc/clickhouse-server/users.d/chop-generated-users.xml'.
**2024.10.24 07:43:52.000699 [ 52 ] {} <Error> Application: Exception: Failed to merge config with '/etc/clickhouse-server/users.d/chop-generated-users.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <yandex>**
2024.10.24 07:43:52.000760 [ 52 ] {} <Information> Application: shutting down
2024.10.24 07:43:52.000770 [ 52 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.10.24 07:43:52.000942 [ 53 ] {} <Information> BaseDaemon: Stop SignalListener thread
2024.10.24 07:43:52.007462 [ 1 ] {} <Information> Application: Child process exited normally with code 70.
```

Operator installed by Helm
**Chart.yaml**
```
apiVersion: v2
name: clickhouse-operator
version:  0.24.0
appVersion: 0.24.0

dependencies:
  - name: altinity-clickhouse-operator
    version:  0.24.0
    repository: https://docs.altinity.com/clickhouse-operator/
```
**values.yaml**
```
altinity-clickhouse-operator: 
  fullnameOverride: "clickhouse-operator"
  operator: {}
  metrics:
    enabled: false
```
**config.yaml**
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "base-config"
spec:
  watch:
    namespaces: 
      - ".*"
```
