### ISSUE TITLE
Kubernetes 1.30+ support

### ISSUE THREAD

**Issue by nenych** [Altinity/clickhouse-operator#1554]
Add support of Kubernetes 1.30 or higher. 
Right now the CH supports "k8s.io/api v0.27.2" but newer versions of API supports things like:
```
lifecycle:
  preStop:
    sleep:
      seconds: 10
```

**Comment by alex-zaitsev** [comment]
@nenych , we use Operator in Kubernetes 1.31 with no issues. Not sure what you are requesting.

**Comment by nenych** [comment]
Kubernetes 1.31 supports api that is not implemented by "k8s.io/api v0.27.2". For example:
```
lifecycle:
  preStop:
    sleep:
      seconds: 10
```
