### ISSUE TITLE
Clickhousekeeperinstallation dont have dedicated data volume (PVC)

### ISSUE THREAD

**Issue by meektechie** [Altinity/clickhouse-operator#1565]
Clickhousekeeperinstallation dont have dedicated data volume (PVC) and it uses Overlay volume when pod rotated It lost the clickhouse metadata. Is there a particular reason for running the clickhousekeeper pods without dedicated volumes?
<img width="721" alt="Screenshot 2024-11-19 at 2 45 59 PM" src="https://github.com/user-attachments/assets/bfe06605-ded6-49b6-834e-e4463f237f47">

Error:
last_error_message: Table is in readonly mode since table metadata was not found in zookeeper:

**Comment by bakavets** [comment]
Hi! Try to add ```dataVolumeClaimTemplate: default```:

```diff
...
  defaults:
    templates:
      # Templates are specified as default for all clusters
      podTemplate: default
+     dataVolumeClaimTemplate: default

  templates:
    podTemplates:
...
```

**Comment by meektechie** [comment]
@bakavets  Got below response. my operator chart version is 0.23.7

Error from server (BadRequest): error when creating "chk.yaml": ClickHouseKeeperInstallation in version "v1" cannot be handled as a ClickHouseKeeperInstallation: strict decoding error: unknown field "spec.defaults"

**Comment by Slach** [comment]
@meektechie upgrade your CRDS separatelly if you use helm, and upgrade operator helm chart to 0.24.0

```
  kubectl apply -f https://github.com/Altinity/clickhouse-operator/raw/master/deploy/helm/clickhouse-operator/crds/CustomResourceDefinition-clickhouseinstallations.clickhouse.altinity.com.yaml
  kubectl apply -f https://github.com/Altinity/clickhouse-operator/raw/master/deploy/helm/clickhouse-operator/crds/CustomResourceDefinition-clickhouseinstallationtemplates.clickhouse.altinity.com.yaml
  kubectl apply -f https://github.com/Altinity/clickhouse-operator/raw/master/deploy/helm/clickhouse-operator/crds/CustomResourceDefinition-clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml
  kubectl apply -f https://github.com/Altinity/clickhouse-operator/raw/master/deploy/helm/clickhouse-operator/crds/CustomResourceDefinition-clickhousekeeperinstallations.clickhouse-keeper.altinity.com.yaml
```

**Comment by alex-zaitsev** [comment]
DO NOT use CHK with operator 0.23.7. It was experimental in that release (as stated in release notes). The GA support is in 0.24.x, and it is not-compatible with a previous version. See migration guide, it is not trivial to migrate: https://github.com/Altinity/clickhouse-operator/blob/master/docs/keeper_migration_from_23_to_24.md

**Comment by Slach** [comment]
@meektechie did you try
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<registry-url>": {
          "username": "<your-username>",
          "password": "<your-password>",
          "email": "<your-email>",
          "auth": "<base64-encoded-credentials>"
        }
      }
    }

---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseKeeperInstallation
meta:
 name: custom-image
spec:
  defaults:
    templates:
      podTemplate: private-image
  templates:
    podTemplates:
    - name: private-image
      spec:
        imagePullSecrets:   
        - name: image-pull-secret  
        containers:
        - name: clickhouse
          image: you-registry/repo/clickhouse-server:tag
```

?
