### ISSUE TITLE
ClickHouse Load Balancer best practices

### ISSUE THREAD

**Issue by bakavets** [Altinity/clickhouse-operator#1571]
Hello guys! I have a couple of questions, would you advise, please?

I need to expose ClickHouse Cluster with `shardsCount: 2` and `replicasCount: 2` to the Internet.

**Q1:** Can I just use this template as an [example](https://github.com/Altinity/clickhouse-operator/blob/release-0.24.0/docs/chi-examples/02-templates-02-service-template.yaml) to expose ClickHouse cluster to Internet via **AWS NLB**? I assume, it will work as expected as set in [the helm chart](https://github.com/Altinity/helm-charts/blob/f6d2c59f167b19fde90ae73cf06079f0a735e586/charts/clickhouse-eks/templates/chi.yaml#L109-L121). My AWS NLB will have 4 pods registered to it if I use target-type: IP. 

Let's assume I use the following tables for ClickHouse cluster:

```sql
CREATE TABLE sharded_sensor_values_demo ON CLUSTER 'poc-cluster' (
    timestamp DateTime,
    site_id UInt32,
    event VARCHAR,
    uuid UUID,
    metric_value Int32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/sharded_sensor_values_demo', '{replica}')
ORDER BY (site_id, toStartOfDay(timestamp), event, uuid)
SETTINGS index_granularity = 8192, storage_policy = 's3_tiered'

CREATE TABLE distributed_sensor_values ON CLUSTER 'poc-cluster' (
    timestamp DateTime,
    site_id UInt32,
    event VARCHAR,
    uuid UUID,
    metric_value Int32
)
ENGINE = Distributed('poc-cluster', 'default', 'sharded_sensor_values_demo', intHash64(site_id))
```

When I insert data via the AWS NLB endpoint:

```sql
INSERT INTO distributed_sensor_values
SELECT *
FROM generateRandom('timestamp DateTime, site_id UInt8, event VARCHAR, uuid UUID, metric_value Int32', NULL, 10)
LIMIT 500000000
```
request will land to one of the shards among the 4, since I use `INSERT INTO distributed_sensor_values table` data will be distributed across all Clickhouse internally and replicated by `ReplicatedMergeTree` engine. 

As per my testing, it works as I described above, but it would be great to hear some best practices around this topic, or I can follow as said above. Do I need to use any kind of proxy like chproxy on top of it or not?

**Q2:** Can I remove TCP port 9000 from the service for NLB [here](https://github.com/Altinity/helm-charts/blob/f6d2c59f167b19fde90ae73cf06079f0a735e586/charts/clickhouse-eks/templates/chi.yaml#L119-L121) for service, I do not need it to expose TCP port to Internet, so I would like to omit it but my concern is if I remove port 9000 ClickHouse may not work as expected because it (maybe) relies on this port and K8s service for it and use it internally.
Could you clarify, please?

```yaml
...
    serviceTemplates:
      - name: loadbalancer-internal
        metadata:
          labels:
            application_group: clickhouse
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-name: clickhouse-public-nlb
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789012:certificate/dummy-certificate-id
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-xxxxxxxxxxxxxxxxx
            external-dns.alpha.kubernetes.io/hostname: clickhouse-cluster.example.com
        spec:
          type: LoadBalancer
          ports:
            - name: https
              port: 443
              targetPort: 8123
...
```

Thanks for the replies in advance!
