### ISSUE TITLE
Modifying user configuration in yaml and applying does not result in changes on the running server

### ISSUE THREAD

**Issue by seandavi** [Altinity/clickhouse-operator#1592]
First, thanks for the great project/product. The operator has immensely simplified and streamlined clickhouse deployments.

I am relatively new to the operator and configuration. I had added a user through configuration like so:

```
...
spec:
  configuration:
    users:
      admin/password: ****
      admin/network/ip:
        - "0.0.0.0/0"
      admin/access_management: 1
      admin/named_collection_control: 1
      admin/show_named_collections: 1
      admin/show_named_collections_secrets: 1
...
```

Applying the configuration returns "configured" as expected. However, I never see the clickhouse pod restart and it appears that the changes do not get applied. Deleting and recreating the Instance ends up with the user available and configured. 

What is the expected behavior on reconfiguration that leads to file changes? And do I need to do something specific to have those file changes activated (like restarting the pod/clickhouse server(s))?

Apologies if I missed something in the documentation.
