### ISSUE TITLE
Users/profiles creation in ClickHouseInstallation object 

### ISSUE THREAD

**Issue by roniadmon** [Altinity/clickhouse-operator#1593]
when specifying a user or a profile under the path: /spec/configuration/users/ 
if the settings of this user is set like this:
```yaml
users:
      admin:
          profile: default
          quota: default
```          
the user is never created

but if set like this:
```
users:
      admin/profile: default
      admin/quota: default
```      
the user will be created

same goes for profiles
