### ISSUE TITLE
Quota management question

### ISSUE THREAD

**Issue by alexvzin** [Altinity/clickhouse-operator#1600]
According to the clickhouse documentation, in clickhouse quota I can define more than one time interval:

https://clickhouse.com/docs/en/operations/quotas

```xml
<statbox>
    <interval>
        <duration>3600</duration>
        <queries>1000</queries>
        <query_selects>100</query_selects>
    </interval>
    <interval>
        <duration>86400</duration>
        <queries>10000</queries>
        <query_selects>10000</query_selects>
    </interval>
</statbox>
```
With altinity example syntax I can define only one interval for one quota:

https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-01-overview.yaml

```
spec:
  configuration:
    quotas:
      statbox/interval/duration: 3600
      statbox/interval/queries: 1000
      statbox/interval/query_selects: 100
```

I tried to do this:

```
spec:
  configuration:
    quotas:
      statbox/interval/duration: 3600
      statbox/interval/queries: 1000
      statbox/interval/query_selects: 100
      statbox/interval/duration: 86400
      statbox/interval/queries: 10000
      statbox/interval/query_selects: 1000
```

But latest values simply rewrites earliest.

Is it possible to correctly specify multiple intervals?
