### ISSUE TITLE
how to declare an empty xml object

### ISSUE THREAD

**Issue by elee1766** [Altinity/clickhouse-operator#1601]
hi, im trying to make a readonly user connect from grafana.

it seems, to do this, i need to set a few settings in the constraints:

https://github.com/grafana/clickhouse-datasource/issues/325#issuecomment-1488293822

```
<!-- users.xml -->
<clickhouse>
  <profiles>
    <readonly>
      <constraints>
        <max_execution_time>
          <changeable_in_readonly/>
          <min>0</min>
          <max>180</max>
        </max_execution_time>
      </constraints>
    </readonly>
  </profiles>
</clickhouse>
```

so in my config, i have tried

```
spec:
  configuration:
    profiles:
      readonly/constraints/max_execution_time/changeable_in_readonly: {}
      readonly/constraints/max_execution_time/min: 0
      readonly/constraints/max_execution_time/max: 180

 ```
 
but this seems to render
```
    <clickhouse>
        <profiles>
            <readonly>
                <constraints>
                    <max_execution_time>
                        <max>180</max>
                        <min>0</min>
                    </max_execution_time>
                </constraints>
            </readonly>
        </profiles>
    </clickhouse>
 ```
 so its missing the empty object, which i am not surprised about 

reading through here i dont see any examples for this. https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationprofiles doesnt seem to have an answer.

i will try to dig around more and see if i can find an answer.

**Comment by elee1766** [comment]
it *seems* that having `<changeable_in_readonly>true</changeable_in_readonly>` is equivalent to `                        <changeable_in_readonly/>`. if this is always true then it's good enough of a workaround

**Comment by Slach** [comment]
Yes, empty XML tag equivalent of true or 1

you can use something like that
```
spec:
  configuration:
    profiles:
      readonly/constraints/max_execution_time/changeable_in_readonly: 1
```
and It will work

also look details about boolean type in clickhouse
https://clickhouse.com/docs/en/sql-reference/data-types/boolean
