### ISSUE TITLE
Altintity operator schema auto-creation not working when new replica(clickhouse pod) added on k8s cluster

### ISSUE THREAD

**Issue by ggangwar** [Altinity/clickhouse-operator#1602]
Hi,
It has been mentioned on "https://github.com/Altinity/clickhouse-operator/blob/master/docs/schema_migration.md"
that when cluster is scaled up and new ClickHouse instances are ready, clickhouse-operator automatically creates schema.
**If replica is added:**
- Other replicas at the same shard are analyzed for replicated tables
- Databases for replicated tables are created
- Replicated tables are created
- Then the same logic as to adding shard applies

I am using latest version of altinity operator(altinity/clickhouse-operator:0.24.2), clickhouse server(clickhouse/clickhouse-server:23.7) and zookeeper ( docker.io/zookeeper:3.8.4).

I deployed clickhouse on k8s cluster with 1 shard and 1 replica. Then, I created the replicated merge tree table and inserted few rows:
```
CREATE TABLE default.events_local ON CLUSTER `{cluster}`
(
    `event_date` Date,
    `event_type` Int32,
    `article_id` Int32,
    `title` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/chi-1/chi-1/tables/{shard}/default/events_local', '{replica}')
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_type, article_id)
```

Post that, I scaled the setup to have 1 more replica. I expected that new replica will have the schema auto-created but I do not see schema automatically created on newly created replica pod.
```
pod/chi-chi-1-chi-1-0-0-0                                      1/1     Running   0          42m
pod/chi-chi-1-chi-1-0-1-0                                      1/1     Running   0          24m
```
Is there any specific configuration needed for automatic schema creation on new replica? Please help as I am stuck on this and tried many things mentioned on docs like schemaPolicy, internalReplication etc.

Here is my ClickHouseInstallation yaml file content:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: chi-1
  namespace: clickhouse
spec:
  configuration:
    zookeeper:
      nodes:
        - host: "zookeeper-0.zookeepers.clickhouse.svc.cluster.local"
          port: 2181
    clusters:
      - name: chi-1
        schemaPolicy:
          replica: All
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
          dataVolumeClaimTemplate: clickhouse-data-volume
    users:
      default/password: password
      default/profile: default
      default/quota: default
      default/networks/ip:
        - 0.0.0.0/0
        - ::/0
  templates:
    volumeClaimTemplates:
      - name: clickhouse-data-volume
        spec:
          storageClassName: vmsp-default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.7
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "500m"
                limits:
                  memory: "1024Mi"
                  cpu: "1000m"
```

zookeeper.yaml content:
```
# Setup Service to provide access to Zookeeper for clients
apiVersion: v1
kind: Service
metadata:
  namespace: clickhouse
  # DNS would be like zookeeper.zoons
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    app: zookeeper
    what: node
---
# Setup Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  namespace: clickhouse
  # DNS would be like zookeeper-0.zookeepers.etc
  name: zookeepers
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    what: node
---
# Setup max number of unavailable pods in StatefulSet
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: clickhouse
  name: zookeeper-pod-disruption-budget
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1
---
# Setup Zookeeper StatefulSet
# Possible params:
# 1. replicas
# 2. memory
# 3. cpu
# 4. storage
# 5. storageClassName
# 6. user to run app
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: clickhouse
  # nodes would be named as zookeeper-0, zookeeper-1, zookeeper-2
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeepers
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      namespace: clickhouse
      labels:
        app: zookeeper
        what: node
      annotations:
        prometheus.io/port: '7000'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: IfNotPresent
          image: "localhost:5000/images/zookeeper:3.8.4"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
            - containerPort: 7000
              name: prometheus
          env:
            - name: SERVERS
              value: "1"

          # See those links for proper startup settings:
          # https://github.com/kow3ns/kubernetes-zookeeper/blob/master/docker/scripts/start-zookeeper
          # https://clickhouse.yandex/docs/en/operations/tips/#zookeeper
          # https://github.com/ClickHouse/ClickHouse/issues/11781
          command:
            - bash
            - -x
            - -c
            - |
              HOST=`hostname -s` &&
              DOMAIN=`hostname -d` &&
              CLIENT_PORT=2181 &&
              SERVER_PORT=2888 &&
              ELECTION_PORT=3888 &&
              PROMETHEUS_PORT=7000 &&
              ZOO_DATA_DIR=/var/lib/zookeeper/data &&
              ZOO_DATA_LOG_DIR=/var/lib/zookeeper/datalog &&
              {
                echo "clientPort=${CLIENT_PORT}"
                echo 'tickTime=2000'
                echo 'initLimit=300'
                echo 'syncLimit=10'
                echo 'maxClientCnxns=2000'
                echo 'maxTimeToWaitForEpoch=2000'
                echo 'maxSessionTimeout=60000000'
                echo "dataDir=${ZOO_DATA_DIR}"
                echo "dataLogDir=${ZOO_DATA_LOG_DIR}"
                echo 'autopurge.snapRetainCount=10'
                echo 'autopurge.purgeInterval=1'
                echo 'preAllocSize=131072'
                echo 'snapCount=3000000'
                echo 'leaderServes=yes'
                echo 'standaloneEnabled=false'
                echo '4lw.commands.whitelist=*'
                echo 'metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider'
                echo "metricsProvider.httpPort=${PROMETHEUS_PORT}"
                echo "skipACL=true"
                echo "fastleader.maxNotificationInterval=10000"
              } > /conf/zoo.cfg &&
              {
                echo "zookeeper.root.logger=CONSOLE"
                echo "zookeeper.console.threshold=INFO"
                echo "log4j.rootLogger=\${zookeeper.root.logger}"
                echo "log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender"
                echo "log4j.appender.CONSOLE.Threshold=\${zookeeper.console.threshold}"
                echo "log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout"
                echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} - %-5p [%t:%C{1}@%L] - %m%n"
              } > /conf/log4j.properties &&
              echo 'JVMFLAGS="-Xms128M -Xmx1G -XX:ActiveProcessorCount=8 -XX:+AlwaysPreTouch -Djute.maxbuffer=8388608 -XX:MaxGCPauseMillis=50"' > /conf/java.env &&
              if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
                  NAME=${BASH_REMATCH[1]} &&
                  ORD=${BASH_REMATCH[2]};
              else
                  echo "Failed to parse name and ordinal of Pod" &&
                  exit 1;
              fi &&
              mkdir -pv ${ZOO_DATA_DIR} &&
              mkdir -pv ${ZOO_DATA_LOG_DIR} &&
              whoami &&
              chown -Rv zookeeper "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" &&
              export MY_ID=$((ORD+1)) &&
              echo $MY_ID > $ZOO_DATA_DIR/myid &&
              for (( i=1; i<=$SERVERS; i++ )); do
                  echo "server.$i=$NAME-$((i-1)).$DOMAIN:$SERVER_PORT:$ELECTION_PORT" >> /conf/zoo.cfg;
              done &&
              if [[ $SERVERS -eq 1 ]]; then
                  echo "group.1=1" >> /conf/zoo.cfg;
              else
                  echo "group.1=1:2:3" >> /conf/zoo.cfg;
              fi &&
              for (( i=1; i<=$SERVERS; i++ )); do
                  WEIGHT=1
                  if [[ $i == 1 ]]; then
                    WEIGHT=10
                  fi
                  echo "weight.$i=$WEIGHT" >> /conf/zoo.cfg;
              done &&
              zkServer.sh start-foreground
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - '
                  IFS=; 
                  MNTR=$(exec 3<>/dev/tcp/127.0.0.1/2181 ; printf "mntr" >&3 ; tee <&3; exec 3<&- ;);
                  while [[ "$MNTR" == "This ZooKeeper instance is not currently serving requests" ]];
                  do
                    echo "wait mntr works";
                    sleep 1;
                    MNTR=$(exec 3<>/dev/tcp/127.0.0.1/2181 ; printf "mntr" >&3 ; tee <&3; exec 3<&- ;);
                  done;
                  STATE=$(echo -e $MNTR | grep zk_server_state | cut -d " " -f 2);
                  if [[ "$STATE" =~ "leader" ]]; then
                    echo "check leader state";
                    SYNCED_FOLLOWERS=$(echo -e $MNTR | grep zk_synced_followers | awk -F"[[:space:]]+" "{print \$2}" | cut -d "." -f 1);
                    if [[ "$SYNCED_FOLLOWERS" != "0" ]]; then
                      ./bin/zkCli.sh ls /;
                      exit $?;
                    else
                      exit 0;
                    fi;
                  elif [[ "$STATE" =~ "follower" ]]; then
                    echo "check follower state";
                    PEER_STATE=$(echo -e $MNTR | grep zk_peer_state);
                    if [[ "$PEER_STATE" =~ "following - broadcast" ]]; then
                      ./bin/zkCli.sh ls /;
                      exit $?;
                    else
                      exit 1;
                    fi;
                  else
                    exit 1;  
                  fi
                   '
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                - bash
                - -xc
                - 'date && OK=$(exec 3<>/dev/tcp/127.0.0.1/2181 ; printf "ruok" >&3 ; IFS=; tee <&3; exec 3<&- ;); if [[ "$OK" == "imok" ]]; then exit 0; else exit 1; fi'
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir-vol
              mountPath: /var/lib/zookeeper
      # Run as a non-privileged user
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        namespace: clickhouse
        name: datadir-vol
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi

```
Here is the content of zookeeper path which did not change after adding 1 more replica( I expect it to contain the entry of chi-chi-1-chi-1-0-1 as well :

```
[zk: localhost:2181(CONNECTED) 32] ls /clickhouse/chi-1/chi-1/tables/0/default/events_local/replicas
[chi-chi-1-chi-1-0-0]
```

Please suggest what configuration I am missing. I am looking for auto-creation of schema and data replication on newly created clcikhouse pod.

**Comment by alex-zaitsev** [comment]
@ggangwar , that should work by default. Schema policy is not needed in CHI. Do you have clickhouse-operator log?

Side note -- clickhouse/clickhouse-server:23.7 is not recommended. Use LTS versions or Altinity Stable builds.

**Comment by ggangwar** [comment]
Hi @alex-zaitsev I removed scehamPolicy setting and using LTS of clickhouse-server but still the same behaviour. **The newly created replica is not having the table automatically created.** 

Following are the steps in my setup:

**1. Deployed 1-node zookeeper** 
```
 $ k get po | grep zookeeper
zookeeper-0                                                1/1     Running   0          71m
```
**2. Deployed the clickhouse using altinity operator having 1 shard and 2 replica**
```
 $ k get po  | grep clickhouse
ch-altinity-clickhouse-operator-7cd579b65f-qgtwv   1/1     Running   0          72m

 $ k get po | grep chi
chi-chi-1-chi-1-0-0-0                                      1/1     Running   0          72m
chi-chi-1-chi-1-0-1-0                                      1/1     Running   0          71m
```
**3. created the ReplicatedMergeTree table on one of the replica(chi-chi-1-chi-1-0-0-0) and inserted few entries:**
```
CREATE TABLE events_local ON CLUSTER `{cluster}`
(
    `event_date` Date,
    `event_type` Int32,
    `article_id` Int32,
    `title` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/default/tables/{shard}/events_local', '{replica}')
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_type, article_id)

INSERT INTO events_local (event_date, event_type, article_id, title)
VALUES ('2024-12-01', 1, 101, 'First Event'),
       ('2024-12-02', 2, 102, 'Second Event');
```
**4. The table automatically created and data persisted in other replica(chi-chi-1-chi-1-0-1-0) as well:**
```
SELECT *
FROM events_local

Query id: 3686134e-3290-4414-8cd7-ccd078743753

   ┌─event_date─┬─event_type─┬─article_id─┬─title────────┐
1. │ 2024-12-01 │          1 │        101 │ First Event  │
2. │ 2024-12-02 │          2 │        102 │ Second Event │
   └────────────┴────────────┴────────────┴──────────────┘
```
**5. Edited CHI and increased replicated count to 3. The new replica created:**
```
 $ k get po | grep chi
chi-chi-1-chi-1-0-0-0                                      1/1     Running   0          72m
chi-chi-1-chi-1-0-1-0                                      1/1     Running   0          71m
chi-chi-1-chi-1-0-2-0                                      1/1     Running   0          34m

```
**6. But, new replica does not have the events_local table in it:**
```
chi-chi-1-chi-1-0-2-0.chi-chi-1-chi-1-0-2.default.svc.cluster.local :) \d

SHOW TABLES

Query id: cabddc7e-27ac-4eb9-8443-0bfcfe3586b0

Ok.

0 rows in set. Elapsed: 0.003 sec.
```
**7. Also, it does not have entry in zookeeper path:**
```
zk: localhost:2181(CONNECTED) 37] ls /clickhouse/default/tables/0/events_local/replicas
[chi-chi-1-chi-1-0-0, chi-chi-1-chi-1-0-1]
```
8. I waited for 10 mins to see if table automatically created or not. But, But, events_local did not create automatically and also zookeeper path entry did not change to contain new replica

Please help me with the issue.

**Comment by ggangwar** [comment]
This is quite urgent, can anyone please help on this issue?

**Comment by ggangwar** [comment]
Hi, I have figured out the issue. The problem was the missing configuration for clickhouse_operator user in CHI yaml file.
The auto-replication worked post updating users section in CHI yaml file like this:

```
    users:
      default:
        password: "password"
        profile: "default"
        quota: "default"
        networksIP:
          - 0.0.0.0/0
          - ::/0
      clickhouse_operator:
        password: "password"
        profile: "default"
        quota: "default"
        grants:
          - CREATE
          - ALTER
          - DROP
          - INSERT
          - SELECT
          - SHOW
          - SYSTEM
          - RELOAD
          - REPLICATE
        networksIP:
          - 0.0.0.0/0
          - ::/0
```

**Comment by alex-zaitsev** [comment]
@ggangwar , glad you found how to make it work, but I do not understand why it did not initially. We test operator with all  ClickHouse LTS versions and it never required any additional grants.

**Comment by astronautas** [comment]
@alex-zaitsev Version 24.12.3.47, stumbled upon this issue :/ Is this a known one or isolated case, wdyt?

**Comment by namnt2307** [comment]
I use this chart https://github.com/Altinity/helm-charts/tree/main/charts/clickhouse to deploy CHI and CHK,
This config works for me 
```yaml
clickhouse:
  clusterSecret:
    enabled: true
    auto: true
  users:
    - name: clickhouse_operator
      accessManagement: 1
      profile: clickhouse_operator
      hostIP:
        - "0.0.0.0/0"
        - "::/0"
```
looks like we need to enable clusterSecret so the clusterAllReplicas() can work
