### ISSUE TITLE
[Question] How do I specify the resources for the actual operator and metrics pods?

### ISSUE THREAD

**Issue by seandavi** [Altinity/clickhouse-operator#1605]
As the title suggests. I'm using a GKE autopilot cluster that defaults to 0.5vCPU and 2Gi RAM, which seems quite excessive. My apologies if I missed something in the docs.

**Comment by Slach** [comment]
you can change spec.templates.container.resources deployment with name `clickhouse-operator`

if you install operator with helm chart, according to 
https://github.com/Altinity/clickhouse-operator/blob/master/deploy/helm/clickhouse-operator/templates/generated/Deployment-clickhouse-operator.yaml#L142

you can define resrouces via `values.yaml`
something like that

```yaml
operator:
  resources: 
   limits:
     cpu: 1000m
     memory: 256Mi
   requests:
     cpu: 500m
     memory: 128Mi
```     

memory usage depends on how many and how big cluster you will manage with `clickhouse-operator`
check operator `:9999/metrics` endpoint in `clickhouse-operator` container and look `process_resident_memory_bytes` metric
