### ISSUE TITLE
Testing shard failure giving `ALL_CONNECTION_TRIES_FAILED`

### ISSUE THREAD

**Issue by lindesvard** [Altinity/clickhouse-operator#1611]
First of all I just want to thanks for this amazing operator. I have created a cluster with 3 shards and 2 replicas, and each pod is running on its own node.

I tried to replicate a pod failure by removing the pod which had the third shard. When I do this I was expecting the system to handle this and use the other node which has a backup of the third shard.

But when executing a query I get the following issue:

```
Received exception from server (version 24.12.2):
Code: 279. DB::Exception: Received from localhost:9000. DB::Exception: All connection tries failed. Log:

Code: 32. DB::Exception: Attempt to read after eof. (ATTEMPT_TO_READ_AFTER_EOF) (version 24.12.2.29 (official build))
Code: 210. DB::NetException: Connection refused (chi-chi-cluster-openpanel-2-0:9440, 10.42.135.6, local address: 10.42.138.4:52470). (NETWORK_ERROR) (version 24.12.2.29 (official build))
Code: 210. DB::NetException: Connection refused (chi-chi-cluster-openpanel-2-0:9440, 10.42.135.6, local address: 10.42.138.4:52470). (NETWORK_ERROR) (version 24.12.2.29 (official build))

: While executing Remote. (ALL_CONNECTION_TRIES_FAILED)
```

As soon as the primary third shard pod is up again everything starts working.

Clickhouse Server: 24.12
Clickhouse Keeper 24.12

## Logs from clickhouse server

```
2025.01.09 09:20:49.914295 [ 301 ] {} <Warning> DNSResolver: Cannot resolve host (chi-chi-cluster-openpanel-2-0), error 0: Host not found.
2025.01.09 09:20:49.914517 [ 301 ] {} <Error> Cluster: Code: 198. DB::NetException: Not found address of host: chi-chi-cluster-openpanel-2-0. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d74fa3b
1. DB::NetException::NetException<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000d7245a4
2. DB::(anonymous namespace)::hostByName(String const&) @ 0x000000000d7261fa
3. DB::DNSResolver::getResolvedIPAdressessWithFiltering(String const&) @ 0x000000000d723fa8
4. DB::DNSResolver::resolveIPAddressWithCache(String const&) @ 0x000000000d725200
5. DB::DNSResolver::resolveAddress(String const&, unsigned short) @ 0x000000000d7258ba
6. DB::Cluster::Address::getResolvedAddress() const @ 0x000000001192836d
7. DB::Cluster::Address::Address(Poco::Util::AbstractConfiguration const&, String const&, String const&, String const&, unsigned int, unsigned int) @ 0x0000000011929406
8. DB::Cluster::Cluster(Poco::Util::AbstractConfiguration const&, DB::Settings const&, String const&, String const&) @ 0x000000001192fc51
9. DB::Clusters::updateClusters(Poco::Util::AbstractConfiguration const&, DB::Settings const&, String const&, Poco::Util::AbstractConfiguration*) @ 0x000000001192d950
10. DB::Clusters::Clusters(Poco::Util::AbstractConfiguration const&, DB::Settings const&, std::shared_ptr<DB::Macros const>, String const&) @ 0x000000001192cee0
11. std::shared_ptr<DB::Clusters> std::allocate_shared[abi:v15007]<DB::Clusters, std::allocator<DB::Clusters>, Poco::Util::AbstractConfiguration const&, DB::Settings&, std::shared_ptr<DB::Macros const>, void>(std::allocator<DB::Clusters> const&, Poco::Util::AbstractConfiguration const&, DB::Settings&, std::shared_ptr<DB::Macros const>&&) @ 0x0000000011991ffe
12. DB::Context::reloadClusterConfig() const @ 0x0000000011964af2
13. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DNSCacheUpdater::DNSCacheUpdater(std::shared_ptr<DB::Context const>, int, unsigned int)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000011a49ebe
14. DB::BackgroundSchedulePool::threadFunction() @ 0x000000001100d92f
15. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001100eb27
16. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000d82c3a2
17. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000d83375a
18. ? @ 0x00007fab9ce01ac3
19. ? @ 0x00007fab9ce93850
 (version 24.12.2.29 (official build))
 ```

## ClickHouseInstallation

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "chi-cluster"
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse-pod-template
      serviceTemplate: svc-template
  configuration:
    zookeeper:
      nodes:
        - host: chk-keeper-openpanel-0-0
          port: 2181
        - host: chk-keeper-openpanel-0-1
          port: 2181
        - host: chk-keeper-openpanel-0-2
          port: 2181
        - host: chk-keeper-openpanel-0-3
          port: 2181
        - host: chk-keeper-openpanel-0-4
          port: 2181
    clusters:
      - name: "openpanel"
        secure: "yes"
        layout:
          shardsCount: 3
          replicasCount: 2
    users:
      op-user/networks/ip: "::/0"
      op-user/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-users
            key: op-user-password
    settings:
      tcp_port: 9000 # keep for localhost
      tcp_port_secure: 9440
      https_port: 8443
      # prometheus/endpoint: /metrics
      # prometheus/port: 8888
      # prometheus/metrics: true
      # prometheus/events: true
      # prometheus/asynchronous_metrics: true
    files:
      openssl_client.xml: |
        <clickhouse>
          <openSSL>
            <client>
                <certificateFile>/etc/clickhouse-server/secrets.d/server.crt/clickhouse-certs/server.crt</certificateFile>
                <privateKeyFile>/etc/clickhouse-server/secrets.d/server.key/clickhouse-certs/server.key</privateKeyFile>
                <dhParamsFile>/etc/clickhouse-server/secrets.d/dhparam.pem/clickhouse-certs/dhparam.pem</dhParamsFile>
                <loadDefaultCAFile>true</loadDefaultCAFile>
                <cacheSessions>true</cacheSessions>
                <disableProtocols>sslv2,sslv3</disableProtocols>
                <preferServerCiphers>true</preferServerCiphers>
                <verificationMode>none</verificationMode>
                <invalidCertificateHandler>
                    <name>AcceptCertificateHandler</name>
                </invalidCertificateHandler>
            </client>
          </openSSL>
        </clickhouse>
      openssl.xml: |
        <clickhouse>
          <openSSL>
            <server>
              <certificateFile>/etc/clickhouse-server/secrets.d/server.crt/clickhouse-certs/server.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-server/secrets.d/server.key/clickhouse-certs/server.key</privateKeyFile>
              <dhParamsFile>/etc/clickhouse-server/secrets.d/dhparam.pem/clickhouse-certs/dhparam.pem</dhParamsFile>
              <verificationMode>none</verificationMode>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <cacheSessions>true</cacheSessions>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <preferServerCiphers>true</preferServerCiphers>
            </server>
          </openSSL>
        </clickhouse>
      server.crt:
        valueFrom:
          secretKeyRef:
            name: clickhouse-certs
            key: server.crt
      server.key:
        valueFrom:
          secretKeyRef:
            name: clickhouse-certs
            key: server.key
      dhparam.pem:
        valueFrom:
          secretKeyRef:
            name: clickhouse-certs
            key: dhparam.pem
    
  templates:
    volumeClaimTemplates:
      - name: default
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Gi
    podTemplates:
      - name: clickhouse-pod-template
        metadata:
          labels:
            app: clickhouse-server
        spec:
          # Disable in development (nodeSelector, affinity, resources, tolerations)
          nodeSelector:
            node.kubernetes.io/instance-type: ccx33
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                          - clickhouse-server
                  topologyKey: "kubernetes.io/hostname"
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "clickhouse"
              effect: "NoSchedule"
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.12
              resources:
                requests:
                  memory: 20Gi
                  cpu: 6
              # Add volumeMounts just to be explicit
              volumeMounts:
                - name: default
                  mountPath: /var/lib/clickhouse
              ports:
              - name: http
                containerPort: 8123
              - name: https
                containerPort: 8443
              - name: client
                containerPort: 9000
              - name: secureclient
                containerPort: 9440
              - name: interserver
                containerPort: 9009
    serviceTemplates:
      - name: svc-template
        generateName: chendpoint-{chi}
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: https
              port: 8443
            - name: secureclient
              port: 9440
          type: LoadBalancer
```

## Overview of resources

```
NAME                                  READY   STATUS    RESTARTS   AGE
pod/chi-chi-cluster-openpanel-0-0-0   1/1     Running   0          175m
pod/chi-chi-cluster-openpanel-0-1-0   1/1     Running   0          174m
pod/chi-chi-cluster-openpanel-1-0-0   1/1     Running   0          175m
pod/chi-chi-cluster-openpanel-1-1-0   1/1     Running   0          174m
pod/chi-chi-cluster-openpanel-2-0-0   1/1     Running   0          22m
pod/chi-chi-cluster-openpanel-2-1-0   1/1     Running   0          24m
pod/chk-keeper-openpanel-0-0-0        1/1     Running   0          175m
pod/chk-keeper-openpanel-0-1-0        1/1     Running   0          175m
pod/chk-keeper-openpanel-0-2-0        1/1     Running   0          174m
pod/chk-keeper-openpanel-0-3-0        1/1     Running   0          174m
pod/chk-keeper-openpanel-0-4-0        1/1     Running   0          174m

NAME                                    TYPE           CLUSTER-IP      EXTERNAL-IP                         PORT(S)                                                       AGE
service/chendpoint-chi-cluster          LoadBalancer   10.43.194.110   2a01:4f8:c01e:983::1,49.12.17.128   8123:31035/TCP,9000:30087/TCP,8443:31011/TCP,9440:31157/TCP   175m
service/chi-chi-cluster-openpanel-0-0   ClusterIP      None            <none>                              9000/TCP,9440/TCP,8123/TCP,8443/TCP,9009/TCP                  175m
service/chi-chi-cluster-openpanel-0-1   ClusterIP      None            <none>                              9000/TCP,9440/TCP,8123/TCP,8443/TCP,9009/TCP                  174m
service/chi-chi-cluster-openpanel-1-0   ClusterIP      None            <none>                              9000/TCP,9440/TCP,8123/TCP,8443/TCP,9009/TCP                  175m
service/chi-chi-cluster-openpanel-2-0   ClusterIP      None            <none>                              9000/TCP,9440/TCP,8123/TCP,8443/TCP,9009/TCP                  175m
service/chk-keeper-openpanel-0-0        ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             175m
service/chk-keeper-openpanel-0-1        ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             175m
service/chk-keeper-openpanel-0-2        ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             174m
service/chk-keeper-openpanel-0-3        ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             174m
service/chk-keeper-openpanel-0-4        ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             174m
service/keeper-keeper                   ClusterIP      None            <none>                              2181/TCP,9444/TCP                                             175m

NAME                                             READY   AGE
statefulset.apps/chi-chi-cluster-openpanel-0-0   1/1     175m
statefulset.apps/chi-chi-cluster-openpanel-0-1   1/1     174m
statefulset.apps/chi-chi-cluster-openpanel-1-0   1/1     175m
statefulset.apps/chi-chi-cluster-openpanel-1-1   1/1     174m
statefulset.apps/chi-chi-cluster-openpanel-2-0   1/1     175m
statefulset.apps/chi-chi-cluster-openpanel-2-1   1/1     174m
statefulset.apps/chk-keeper-openpanel-0-0        1/1     175m
statefulset.apps/chk-keeper-openpanel-0-1        1/1     175m
statefulset.apps/chk-keeper-openpanel-0-2        1/1     174m
statefulset.apps/chk-keeper-openpanel-0-3        1/1     174m
statefulset.apps/chk-keeper-openpanel-0-4        1/1     174m
```
