### ISSUE TITLE
Issue with multiple access statement

### ISSUE THREAD

**Issue by ehsanafter** [Altinity/clickhouse-operator#1615]
```
Hey guys yesterday i had this clickhouse user config section:
    users:
      admin/networks/ip:
        - 0.0.0.0/0
        # - '::/0'

      # printf 'theSecurePassword' | sha256sum
      admin/password_sha256_hex: 5b4afed15e6035ecd92bb010ad4d703918fd18a53b67a9ceeaa0e975a6400a32
      admin/profile: default
      admin/quota: default

      # notif_reporter/profile: readonly
      notif_reporter/password_sha256_hex: 5ede99ba7889e2e48d49ef3031b955f74f38af096e73f89dd18654d04c99f89a
      notif_reporter/grants/query:
        - "GRANT SELECT ON data_team.*"
      notif_reporter/allow_databases/database:
        - "data_team"
      notif_reporter/networks/ip:
        - 0.0.0.0/0
        - '::/0'

      notif_reporter/quota: default
      myuser2/profile: default
      # myuser2/grants/query:
      #   - "GRANT limited_role"
```

The key part is these two:
      notif_reporter/grants/query:
        - "GRANT SELECT ON data_team.*"
      notif_reporter/allow_databases/database:
        - "data_team"
 seems like i cant use these two together but operator didnt tell me anything either other than that ip is restricted while i gave access to all ips for this user.
 after restarting the pod manually since the operator didnt restart i found out my configuration is invalid so i commented out this part:
```
       notif_reporter/allow_databases/database:
        - "data_team"
```
and used grants only and it went through.
Just wanted to let you know.
Thanks

**Comment by Slach** [comment]
Thanks for sharing your experience,
this is

when you combine `allow_databases` and `GRANT ... ON db.*` it doesn't work on clickhouse side

Actually your pod should switched to CrashLoopBack in modern clickhouse-server version with error in logs something like that "you can't add any other grants for database"

if you will use `*.*` instead of `db.*` then it should works
```yaml
      notif_reporter/grants/query:
        - "GRANT SELECT ON *.*"
      notif_reporter/allow_databases/database:
        - "data_team"
```
