### ISSUE TITLE
VolumeAttributesClass support

### ISSUE THREAD

**Issue by janeklb** [Altinity/clickhouse-operator#1625]
https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/ (enabled by default in AWS EKS 1.31 https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.31)

`VolumeAttributesClass` allows you to declaratively change volume attributes (eg. iops or throughput). Would be nice to be able to modify throughput on clickhouse data volumes as necessary.

**Comment by Slach** [comment]
you can use `volumeAttributesClassName`, look `kubectl explain chi.spec.templates.volumeClaimTemplates`

something like that
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: pvc-with-volume-attr-class
  templates:
    volumeClaimTemplates:
    - name: pvc-with-volume-attr-class
      spec:
        volumeAttributesClassName: your-external-defined-VolumeAttributesClass
        resources:
          requests:
            storage: 1Gi
```
