### ISSUE TITLE
Not able to run CHI with clickhouse version updates released on Feb 4th

### ISSUE THREAD

**Issue by marcustut** [Altinity/clickhouse-operator#1631]
Below is the CHI manifest I have right now, it works when the image version is 23.8 however if I change it to *latest* or *24.11* the pod will not able to start and it will have error:

**Error**

```sh
/entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default'                                                                                                           
/entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
```

**CHI Manifest**

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: simple
  namespace: clickhouse
  finalizers:
    - finalizer.clickhouseinstallation.altinity.com
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    users:
      # printf 'test_password' | sha256sum
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
      test_user/password: test_password
      # to allow access outside from kubernetes
      test_user/networks/ip:
        - 0.0.0.0/0
    clusters:
      - name: simple
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              # Container has explicitly specified resource requests
              resources:
                requests:
                  cpu: "1000m"
              # Container has explicitly specified ports
              ports:
                - name: http
                  containerPort: 8124
                - name: tcp
                  containerPort: 9001
                - name: interserver
                  containerPort: 9010

```

**Comment by verejoel** [comment]
Ran into this as well today (we have been experimenting and were running with `latest` image tag.

Using tag `25.1.2.3` seems to work.

**Comment by jingo64** [comment]
+1 to running into this issue too! Just started this afternoon

**Comment by ceh137** [comment]
Same!

**Comment by Slach** [comment]
root reason is https://github.com/ClickHouse/ClickHouse/pull/75259

as temporary workaround please add
```
spec:
  configuration:
    files:
      users.d/default_allow_network_access.xml: |
      <clickhuouse><users><default><networks replace="1">
        <!-- your-pod-cidr -->
        <ip>X.X.X.X/Y</ip>
        <!-- your-services-cidr -->
        <ip>X.X.X.X/Y</ip>
        <ip>127.0.0.1</ip>
      </networks></default></users></clickhouse>
```

**Comment by Slach** [comment]
@marcustut 
according to 
https://github.com/ClickHouse/ClickHouse/pull/75316
try

add
```yaml
spec:
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
          - name: clickhouse
            image: clickhouse/clickhouse-server:latest
            environment:
            - name: CLICKHOUSE_SKIP_USER_SETUP
              value: "1"  
```

**Comment by marcustut** [comment]
> [@marcustut](https://github.com/marcustut) according to [ClickHouse/ClickHouse#75316](https://github.com/ClickHouse/ClickHouse/pull/75316) try
> 
> add
> 
> spec:
>   defaults:
>     templates:
>       podTemplate: default
>   templates:
>     podTemplates:
>       - name: default
>         spec:
>           containers:
>           - name: clickhouse
>             image: clickhouse/clickhouse-server:latest
>             environment:
>             - name: CLICKHOUSE_SKIP_USER_SETUP
>               value: "1"

Nope, this didn't work it have the same error. My manifest is:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: datasource
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: datasource
    users:
      test_user/networks/ip:
        - 0.0.0.0/0
      test_user/password: test_password
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
    settings:
      http_port: 8123
      tcp_port: 9000
      interserver_http_port: 9009
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: svc-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              environment:
                - name: CLICKHOUSE_SKIP_USER_SETUP
                  value: "1"
    serviceTemplates:
      - name: svc-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
```
