### ISSUE TITLE
Empty `system.replicas` table although `replicasCount` is set

### ISSUE THREAD

**Issue by marcustut** [Altinity/clickhouse-operator#1635]
I created a `Replicated` database with the command 

```sql
CREATE DATABASE datasource ENGINE = Replicated('/clickhouse/{installation}/databases/datasource', '{shard}', '{replica}')
```

then I query the `system.databases` table to verify it is created

```sql
SELECT name, engine FROM system.databases;
```

I ran the same query for 10 times, sometimes I can see the new table, sometimes I don't. Then, I try to verify if replicas is configured and I ran a query

```sql
SELECT * FROM system.replicas;
```

but this query is empty, there is not results.

```sql
SELECT * FROM system.replication_queue;
```

gives the same result too

Following are my manifests:

*chi.yaml*
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: datasource
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: datasource
        layout:
          shardsCount: 1
          replicasCount: 3
    zookeeper:
      nodes:
        - host: keeper-datasource
          port: 2181
    users:
      test_user/networks/ip:
        - 0.0.0.0/0
      test_user/password: test_password
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
    settings:
      http_port: 8123
      tcp_port: 9000
      interserver_http_port: 9009
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: svc-template
      dataVolumeClaimTemplate: data-volume-claim-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.1.2.3
            - name: clickhouse-backup
              image: altinity/clickhouse-backup:latest
              imagePullPolicy: Always
              args: [ "server" ]
              env:
                - name: LOG_LEVEL
                  value: "debug"
                - name: ALLOW_EMPTY_BACKUPS
                  value: "true"
                - name: API_LISTEN
                  value: "0.0.0.0:7171"
                # INSERT INTO system.backup_actions to execute backup
                - name: API_CREATE_INTEGRATION_TABLES
                  value: "true"
                - name: BACKUPS_TO_KEEP_REMOTE
                  value: "3"
                # change it for production S3
                - name: REMOTE_STORAGE
                  value: "s3"
                - name: S3_ACL
                  value: ""
                - name: S3_ENDPOINT
                  value: ""
                - name: S3_REGION
                  value: ""
                - name: S3_BUCKET
                  value: ""
                # {shard} macro defined by clickhouse-operator
                - name: S3_PATH
                  value: hub/shard-{shard}
                - name: S3_ACCESS_KEY
                  value: ""
                - name: S3_SECRET_KEY
                  value: ""
                - name: S3_FORCE_PATH_STYLE
                  value: "true"
                # remove it for production S3
                - name: S3_DISABLE_SSL
                  value: "true"
                - name: S3_DEBUG
                  value: "true"
                # require to avoid double scraping clickhouse and clickhouse-backup containers
              ports:
                - name: backup-rest
                  containerPort: 7171
    serviceTemplates:
      - name: svc-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: backup-http
              port: 7171
          type: ClusterIP
    volumeClaimTemplates:
      - name: data-volume-claim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

*chk.yaml*
```yaml
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: datasource
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: "datasource"
        layout:
          replicasCount: 3
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"

  defaults:
    templates:
      # Templates are specified as default for all clusters
      podTemplate: default
      dataVolumeClaimTemplate: default

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: "clickhouse/clickhouse-keeper:latest"
              resources:
                requests:
                  memory: "256M"
                limits:
                  memory: "4Gi"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```
