### ISSUE TITLE
Issues in User Creation with newest clickhouse images

### ISSUE THREAD

**Issue by Elyytscha** [Altinity/clickhouse-operator#1636]
I'm facing the following error on operator version 0.24.2 installed via OLM/operatorhub:

```
/entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default'
/entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
```

Those are the images i get this error with
```
'clickhouse/clickhouse-server:24.12-alpine
'clickhouse/clickhouse-server:24.11-alpine
'clickhouse/clickhouse-server:24.8-alpine
'clickhouse/clickhouse-server:24.3-alpine
'clickhouse/clickhouse-server:24.3'
```

This is an image with works with the actual version of the operator we utilize
```
'clickhouse/clickhouse-server:24.8.12-alpine
```

produced by the following CR. i think some changes in the newest published clickhouse docker images might be the problem.

```yaml
kind: ClickHouseInstallation
apiVersion: clickhouse.altinity.com/v1
metadata:
  name: simple-01
  namespace: clickhouse-debug

spec:
  configuration:
    clusters:
      - layout:
          replicasCount: 1
          shardsCount: 1
        name: simple
    users:
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
      #test_user/password: test_password
      test_user/networks/ip:
        - 0.0.0.0/0
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      podTemplate: clickhouse
      serviceTemplate: chi-service-template
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
#            - image: 'clickhouse/clickhouse-server:24.12-alpine' /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default' /entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
#            - image: 'clickhouse/clickhouse-server:24.11-alpine' /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default' /entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
#            - image: 'clickhouse/clickhouse-server:24.8-alpine' /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default' /entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
#            - image: 'clickhouse/clickhouse-server:24.3-alpine' /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default' /entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
#            - image: 'clickhouse/clickhouse-server:24.3' /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default' /entrypoint.sh: line 135: /etc/clickhouse-server/users.d/default-user.xml: Read-only file system
#            - image: 'clickhouse/clickhouse-server:24.8.12-alpine' WORKING!!

            - image: 'clickhouse/clickhouse-server:24.12-alpine'
              imagePullPolicy: IfNotPresent
              name: clickhouse
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: data-volume-template
    serviceTemplates:
      - generateName: clickhouse
        name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi


```
