### ISSUE TITLE
Question: change keeper replica count (decrease 5 -> 3)

### ISSUE THREAD

**Issue by lindesvard** [Altinity/clickhouse-operator#1639]
So I have a Clickhouse cluster of  3 shards and 2 replicas. When I created the keeper I added 5 keepers (not sure why).

My question is, is it safe to just decrease that value to 3 keepers and update the config `spec.configuration.zookeeper.nodes` to point to the 3 keepers?

**ClickHouseKeeperInstallation**:
```
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: keeper
spec:
  configuration:
    clusters:
      - name: "cluster-name"
        layout:
          replicasCount: 5
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"

  defaults:
    templates:
      podTemplate: default
      dataVolumeClaimTemplate: default

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          nodeSelector:
            node.kubernetes.io/instance-type: ccx13
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                          - clickhouse-keeper
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: clickhouse/clickhouse-keeper:24.12
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "0.2"
                limits:
                  memory: "1Gi"
                  cpu: "1"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: default
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
```

**ClickhouseInstallation** (relevant part):
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "chi-cluster"
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse-pod-template
      serviceTemplate: svc-template
  configuration:
    zookeeper:
      nodes:
        - host: chk-keeper-openpanel-0-0
          port: 2181
        - host: chk-keeper-openpanel-0-1
          port: 2181
        - host: chk-keeper-openpanel-0-2
          port: 2181
        - host: chk-keeper-openpanel-0-3
          port: 2181
        - host: chk-keeper-openpanel-0-4
          port: 2181
    clusters:
      - name: "cluster-name"
        secure: "yes"
        layout:
          shardsCount: 3
          replicasCount: 2
```
