### ISSUE TITLE
ClickHouse Multi-Cluster Deployments and Upgrades in Parallel

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [Altinity/clickhouse-operator#1647]
ClickHouse is deployed with a multi-cluster setup , each with 3 shards and 3 replicas. We are having situations to scale horizontally the number of shards and this causes problem while doing the upgrade if there are 15 shards in each cluster with 3 replicas thus causing 90 pods to restart / upgrade one at a time. 

Is there an example of CHI to explain how do we parallelize the ClickHouse Deployments for multi-cluster setup ?  This means, i would like to concurrently start the deployment of pods in multi-clusters. (1 from Cluster-01 and 1 from Cluster-2 and so on...)

**Comment by alex-zaitsev** [comment]
Use the latest operator version and increase paralellism, for example:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "custom"
spec:
  reconcile:
    runtime:
       reconcileShardsThreadsNumber: 100 
       reconcileShardsMaxConcurrencyPercent: 100
    statefulSet:
      update:
        timeout: 600
```
