### ISSUE TITLE
Concurrent shard reconciliation in large cluster w/o replica

### ISSUE THREAD

**Issue by LunaShen** [Altinity/clickhouse-operator#1651]
Hey everyone,  

I'm running into an issue while deploying our ClickHouse cluster using **ClickHouse Operator 0.21.1** with **ClickHouse 24.3.2.1**. Our cluster has **400 nodes and no replicas**.  

We’ve been tweaking some parameters (reconcileShardsMaxConcurrencyPercent, reconcileShardsThreadsNumber, and reconcileCHIsThreadsNumber), but no matter how many pods we recycle at a time, the process always stops after a few batches. Eventually, some nodes end up in **CrashLoopBackOff**, and since the process never fully completes, we have **missing pods but all the StatefulSets are still there**.  

Has anyone tried running **concurrent reconciliation** on a large cluster **without replicas**? Does it only work when replicas are set up?  

Would love to hear if anyone has run into something similar or has any ideas on how to fix this!

**Comment by alex-zaitsev** [comment]
Hi @LunaShen , try the latest operator version. There were a lot of improvements for large cluster performance. You may also enable to reconcile all shards in parallel. Here is an example of config:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseOperatorConfiguration"
metadata:
  name: "custom"
spec:
  reconcile:
    runtime:
       reconcileShardsThreadsNumber: 400 
       reconcileShardsMaxConcurrencyPercent: 100
    statefulSet:
      update:
        timeout: 600
```

With such config operator will do first shard first, and if it passes continues to all others.
