### ISSUE TITLE
/replicas_status not being used for readiness probe

### ISSUE THREAD

**Issue by janeklb** [Altinity/clickhouse-operator#1662]
Using `/replicas_status` for the readiness probe was introduced in 0.13 (https://github.com/Altinity/clickhouse-operator/commit/48edc4a814684fa94337cd60d032038e824da597), but it was removed in 0.14 when the readiness probe was changed to just use `/ping` (https://github.com/Altinity/clickhouse-operator/commit/a436960f5d1560b780ccd20c4b17f9b607bab9ec)

Was this last change intentional? eg. is `/ping` a better default than `/replicas_status`?

**Comment by Slach** [comment]
clickhouse-server nodes during replication made access each other via service dns names
service DSN names resolved only if pods ready
in this case, any troubles with `system.replicas` - `absolute_delay` (high inserts for example) will return 503 for /replica_status and replica will unavailable for replication even if clickhouse-server allow requests

so /ping is much better for readiness probe, readiness probe means server is up and ready to receive trafic

**Comment by artem-zinnatullin** [comment]
Hi all, this still seems like a major oversight. We experienced Keeper failure which made 2 replica CHI elect one leader and the other replica became readonly and couldn't auto-recover even after Keeper stood up.

The problem is that because of simple choice of `/ping` as readiness check — the readonly replica is still present in `clickhouse-mycluster` Service and KEEPS serving SELECT queries even though it already lacks new data for multiple hours due to being readonly, our data pipelines just started seeing flaky query results: 0 rows, X rows, 0 rows, Y rows and so on which is a disaster.

Customer facing service `clickhouse-mycluster` should NEVER expose replicas that broke off the ClickHouseInstallation cluster, otherwise the Altinity operator is pretty much useless for real world HA clusters.

`/ping` is fine for liveness check, but not for readiness check in CLUSTER MODE.

I thus strongly suggest this issue be reopened and reconsidered.

**Comment by Slach** [comment]
@artem-zinnatullin better create new issue with full description

**Comment by Slach** [comment]
@artem-zinnatullin issue about clickhouse-server not about clickhouse-keeper

as i remember 
you could redefine readinessProbe in podTemplates for `kind: ClickHouseKeeperInstallation`

look details in 
`kubectl explain chk.spec.templates.podTemplates` and
`kubectl explain pod.spec.containers.readinessProbe`

**Comment by alex-zaitsev** [comment]
@artem-zinnatullin , using /replicas_status could cause all the cluster become unavailable. It is not unusual when both active replicas are lagging behind each other or both replicas has readonly tables. This is why it is not used -- it is much worse problem.

You may use Distributed table that has its own control of replica lag or a custom readiness probe as Eugene suggested.

Also check reconcile.host.wait.replicas settings:
```
  # Reconcile Host scenario
  host:
    # The operator during reconcile procedure should wait for a ClickHouse host to achieve the following conditions:
    wait:
      # <skipped>
      replicas:
        # All replicas (new and known earlier) are explicitly requested to wait for replication to catch-up
        all: no
        # New replicas only are requested to wait for replication to catch-up
        new: yes
        # Replication catch-up is considered to be completed as soon as replication delay
        # a.k.a replication lag - calculated as "MAX(absolute_delay) FROM system.replicas"
        # is within this specified delay (in seconds)
        delay: 10
```
