### ISSUE TITLE
Bug: Clickhouse operator doesnt render the correct template for CH-keeper statefulset on custom container name

### ISSUE THREAD

**Issue by iahmad-khan** [Altinity/clickhouse-operator#1667]
Operator version:  0.24.5
Keeper def deployed via the keeper installation CRD with this issue

```

apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: ch-keeper
spec:
  configuration:
    clusters:
      - name: "ch-keeper"
        layout:
          replicasCount: 3
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "true"

  defaults:
    templates:
      podTemplate: ch-keeper
      dataVolumeClaimTemplate: data-volume

  templates:
    podTemplates:
      - name: ch-keeper
        metadata:
          labels:
            app: ch-keeper
        spec:
          nodeSelector:
            tenantname: analytics
          containers:
            - name: ch-keeper  
              imagePullPolicy: IfNotPresent
              image: "clickhouse/clickhouse-keeper:24.9.1-alpine"
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: data-volume
        spec:
          storageClassName: "gp3"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

```

Issue:

While defining the operator, if we provide a custom name to the container, the deployed stateful creates two containers, one with the default name clickhouse-operator and the other with the custom name ( i.e, ch-operator ) provided in the CRD definition.

Expected Behavior:

The Keeper statefulset should be running a single container inside the pod with the new name provided in the installation CRD resource as above.

This issue is reproducible.

**Comment by OOub** [comment]
same issue here

**Comment by corealugly** [comment]
+1 problem on altinity-clickhouse-operator-0.26.2

this example kind: Clickhousejeeperinstallation

```
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  configuration:
    clusters:
      - name: "chk01"
        layout:
          replicasCount: 3

  defaults:
    templates:
      # Templates are specified as default for all clusters
      podTemplate: default
      volumeClaimTemplate: keeper-storage

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: "docker.cloud.example.com/altinity/clickhouse-keeper:25.8.16.10001.altinitystable"
              resources:
                requests:
                  memory: "256M"
                  cpu: "1"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn
          resources:
            requests:
              storage: 10Gi
          reclaimPolicy: Retain
```

```
k get -n default sts -o wide
NAME                              READY   AGE   CONTAINERS          IMAGES
chk-clickhouse-keeper-chk01-0-0   0/1     23m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
chk-clickhouse-keeper-chk01-0-1   0/1     18m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
chk-clickhouse-keeper-chk01-0-2   0/1     13m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
```

**Comment by corealugly** [comment]
> +1 problem on altinity-clickhouse-operator-0.26.2
> 
> this example kind: Clickhousejeeperinstallation
> 
> ```
> apiVersion: "clickhouse-keeper.altinity.com/v1"
> kind: "ClickHouseKeeperInstallation"
> metadata:
>   name: clickhouse-keeper
> spec:
>   configuration:
>     clusters:
>       - name: "chk01"
>         layout:
>           replicasCount: 3
> 
>   defaults:
>     templates:
>       # Templates are specified as default for all clusters
>       podTemplate: default
>       volumeClaimTemplate: keeper-storage
> 
>   templates:
>     podTemplates:
>       - name: default
>         metadata:
>           labels:
>             app: clickhouse-keeper
>           containers:
>             - name: clickhouse-keeper
>               imagePullPolicy: IfNotPresent
>               image: "docker.cloud.example.com/altinity/clickhouse-keeper:25.8.16.10001.altinitystable"
>               resources:
>                 requests:
>                   memory: "256M"
>                   cpu: "1"
>           securityContext:
>             fsGroup: 101
> 
>     volumeClaimTemplates:
>       - name: keeper-storage
>         reclaimPolicy: Retain
>         spec:
>           accessModes:
>             - ReadWriteOnce
>           storageClassName: longhorn
>           resources:
>             requests:
>               storage: 10Gi
>           reclaimPolicy: Retain
> ```
> 
> ```
> k get -n default sts -o wide
> NAME                              READY   AGE   CONTAINERS          IMAGES
> chk-clickhouse-keeper-chk01-0-0   0/1     23m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
> chk-clickhouse-keeper-chk01-0-1   0/1     18m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
> chk-clickhouse-keeper-chk01-0-2   0/1     13m   clickhouse-keeper   clickhouse/clickhouse-keeper:latest
> ```

i'm answering my own question

https://docs.altinity.com/altinitykubernetesoperator/kubernetesquickstartguide/quickzookeeper/

this official doc  -> example for clickhouse-keeper

```
.....
  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: "altinity/clickhouse-keeper:25.8.16.10001.altinitystable"
              resources:
                requests:
                  memory: "256M"
                  cpu: "1"
                limits:
                  memory: "4Gi"
                  cpu: "2"
          securityContext:
            fsGroup: 101
.....
```

fix
```
.....
  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: "altinity/clickhouse-keeper:25.8.16.10001.altinitystable"
              resources:
                requests:
                  memory: "256M"
                  cpu: "1"
                limits:
                  memory: "4Gi"
                  cpu: "2"
          securityContext:
            fsGroup: 101
.....
```

"spec:" is lost
