### ISSUE TITLE
Is it possible to define extra StatefulSet annotations?

### ISSUE THREAD

**Issue by vlasov-y** [Altinity/clickhouse-operator#1668]
Is it possible to define extra StatefulSet annotations for ClickHouse? I have inspected CRDs and even tried to read the operator's code - no findings. Is it possible at all?

**Comment by Slach** [comment]
`annotations` and `labels` from `kind: ClickHouseInstallation` will render in statefulset
you can add additional with `.spec.templates.podTemplates[].metadata.annotations` 

```
kind: ClickHouseInstallation
metadata:
 name: test
 labels:
   label: value
 annotations:
   annotation: value 

spec:
  defaults:
    templates:
      podTemplate: test-template
  templates:
   podTemplates:
   - name: test-template
     metadata:
      labels:
        label2: value1
      annotations:
        annotation2: value2 
     spec:
       containers:
       - name: clickhouse
         image: clickhouse/clickhouse-server:latest 
       
```
