### ISSUE TITLE
Replication fails with default user protected by password

### ISSUE THREAD

**Issue by dbazhal** [Altinity/clickhouse-operator#1669]
With the https://github.com/Altinity/clickhouse-operator/blob/master/docs/security_hardening.md#auto-token setting, i get the
```
{
  "log_type": "json",
  "logger_name": "PushingToViews",
  "message": "Cannot push to the storage, ignoring the error: Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.\n\nIf you have installed ClickHouse and forgot password you can reset it in the configuration file.\nThe password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml\nand deleting this file will reset the password.\nSee also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.\n\n: while pushing to view rep_order._main_metrics_detail_shard1_mv (1ec78f71-3ab7-4254-81dd-c6345866ec5f). (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):\n\n0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c6251d7 in /usr/bin/clickhouse\n1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000715b6b1 in /usr/bin/clickhouse\n2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x0000000010e5b05f in /usr/bin/clickhouse\n3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x00000000120a318d in /usr/bin/clickhouse\n4. DB::registerDictionarySourceClickHouse(DB::DictionarySourceFactory&)::$_0::operator()(DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, String const&, DB::Block&, std::shared_ptr<DB::Context const>, String const&, bool) const @ 0x000000000f367ceb in /usr/bin/clickhouse\n5. std::shared_ptr<DB::IDictionarySource> std::__function::__policy_invoker<std::shared_ptr<DB::IDictionarySource> (DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, String const&, DB::Block&, std::shared_ptr<DB::Context const>, String const&, bool)>::__call_impl<std::__function::__default_alloc_func<DB::registerDictionarySourceClickHouse(DB::DictionarySourceFactory&)::$_0, std::shared_ptr<DB::IDictionarySource> (DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, String const&, DB::Block&, std::shared_ptr<DB::Context const>, String const&, bool)>>(std::__function::__policy_storage const*, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, String const&, DB::Block&, std::shared_ptr<DB::Context const>&&, String const&, bool) (.llvm.191082534098321143) @ 0x000000000f36579f in /usr/bin/clickhouse\n6. DB::DictionarySourceFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, DB::DictionaryStructure const&, std::shared_ptr<DB::Context const>, String const&, bool) const @ 0x0000000010bed6b7 in /usr/bin/clickhouse\n7. DB::DictionaryFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, bool) const @ 0x0000000010be9d5f in /usr/bin/clickhouse\n8. DB::ExternalDictionariesLoader::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, String const&) const @ 0x0000000011afd2fc in /usr/bin/clickhouse\n9. DB::ExternalLoader::LoadingDispatcher::doLoading(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroup>) @ 0x0000000011b084c9 in /usr/bin/clickhouse\n10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::ExternalLoader::LoadingDispatcher::*)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*, String&, unsigned long&, bool&, unsigned long&, bool, std::shared_ptr<DB::ThreadGroup>>(void (DB::ExternalLoader::LoadingDispatcher::*&&)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*&&, String&, unsigned long&, bool&, unsigned long&, bool&&, std::shared_ptr<DB::ThreadGroup>&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000011b0e07f in /usr/bin/clickhouse\n11. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c706104 in /usr/bin/clickhouse\n12. ? @ 0x00007f40475ce609 in ?\n13. ? @ 0x00007f40474f3353 in ?\n (version 23.8.16.16 (official build))",
  "query_id": "e8911be0-7402-408a-ba26-8e22b686cf3b",
  "source_file": "src/Common/Exception.cpp; void DB::tryLogCurrentExceptionImpl(Poco::Logger *, const std::string &)",
  "source_line": "235"
}
```
errors.
And here's the configs part on default user after hardening
```
    users:
      clickhouse_admin/networks/ip:
        - ::/0
      default/password_sha256_hex: "{{ get .Values.vault_user_password_sha256_hashes .Values.default_username }}"  # <------------------------ here the password
    zookeeper:
      nodes:
        - host: "{{ .Values.zookeeper_name }}-0.{{ .Values.zookeeper_name }}-headless.{{ .Values.zookeeper_namespace }}"
          port: 2181
        - host: "{{ .Values.zookeeper_name }}-1.{{ .Values.zookeeper_name }}-headless.{{ .Values.zookeeper_namespace }}"
          port: 2181
        - host: "{{ .Values.zookeeper_name }}-2.{{ .Values.zookeeper_name }}-headless.{{ .Values.zookeeper_namespace }}"
          port: 2181
    clusters:
      - name: "{{ .Values.cluster_name }}"
        secret:
          auto: "true"  # <------------------------ here the token
        templates:
          podTemplate: clickhouse-with-volume-template
        layout:
          {{- if .Values.shards }}
          shardsCount: {{ .Values.shards }}
          {{- end }}
          replicasCount: {{ .Values.replicas }}
```
The rep_order._main_metrics_detail_shard1_mv is a materialized view. It's target is a partitioned ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', utc_updated_dttm).

The interesting fact is that I can't even reproduce it on my test cluster.

If you'd give me ideas on what can trigger this errors, it'd be very helpful.
