### ISSUE TITLE
One-to-one mapping between StatefulSets and Shards

### ISSUE THREAD

**Issue by teralype** [Altinity/clickhouse-operator#167]
Based on my limited experience with the ClickHouse operator, it seems that it deploys a Kubernetes StatefulSet per each shard and replica. That is, my test cluster which is composed of 2 shards and 2 replicas per shard yields 4 Kubernetes StatefulSet objects.

This is the ClickHouse CRD:

```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  labels:
    environment: dev
  name: replicated
  namespace: infra
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 2
        shardsCount: 2
      name: replicated
...
```

The problem is that the operator code creates StatefulSets with just one replica, as seen here: https://github.com/Altinity/clickhouse-operator/blob/a71190fe6333ba32064d150f804b9811349c30a9/pkg/model/creator.go#L229

Would it be possible to change this layout to a layout where each StatefulSet maps to a shard, and has as many replicas as the number of replicas in the shard?

With the current design, and based on my CRD that describes a ClickHouse cluster composed of two shards and two replicas, I get 4 StatefulSets (1 replica each) which is not very manageable neither in Prometheus or by back ups (e.g. Stash).

```
$ kubectl -n infra get sts
NAME                            READY   AGE
chi-replicated-replicated-0-0   1/1     111m
chi-replicated-replicated-0-1   1/1     110m
chi-replicated-replicated-1-0   1/1     109m
chi-replicated-replicated-1-1   1/1     109m
zookeeper                       3/3     111m
```

I would expect that only  2 StatefulSets are created. Something like this:

```
$ kubectl -n infra get sts
NAME                            READY   AGE
chi-replicated-replicated-0     2/2     111m
chi-replicated-replicated-1     2/2     109m
zookeeper                       3/3     111m
```

In total, still 4 Pods (2 shards x 2 replicas/shard) but distributed in a different way.
Is there a reason why this is not done like this?
