### ISSUE TITLE
Consider adding a default security context to CHI/CHK

### ISSUE THREAD

**Issue by alex-zaitsev** [Altinity/clickhouse-operator#1672]
```
spec:
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 101
    runAsUser: 101
```
Maybe we can add some syntax sugar for that, and allow user to overwrite
