### ISSUE TITLE
Hardcoded default ClickHouse and Keeper images

### ISSUE THREAD

**Issue by juan131** [Altinity/clickhouse-operator#1677]
The default ClickHouse and Keeper container images are hardcoded, see:

- https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/chi/config/const.go#L71
- https://github.com/Altinity/clickhouse-operator/blob/master/pkg/model/chk/config/const.go#L68

They should be customizable via env. variables (e.g. `CLICKHOUSE_CONTAINER_IMAGE` and `KEEPER_CONTAINER_IMAGE`) so these default values can be overwritten. AFAIK, only the env. vars defined below are currently supported.

- https://github.com/Altinity/clickhouse-operator/blob/master/pkg/apis/deployment/env_vars.go

**Comment by alex-zaitsev** [comment]
You can always override images in the podTemplate. This is better than environment variables. Why do you want to use those?

**Comment by alex-zaitsev** [comment]
You may used templates to make it easier for your devs, but adding support for env variables is an easy change as well:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"

metadata:
  name: clickhouse-version
spec:
  defaults:
    templates:
      podTemplate: default
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.8.14.39
              imagePullPolicy: IfNotPresent
```

**Comment by juan131** [comment]
Yes, pod templates are also a way to reduce the risks for this use case. That said, being able to configure the default images is quiet a common thing on operators. For instance:

- Prometheus Operator allows to configure default images for Prometheus, AlertManager and Thanos via flags:
  - https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/operator/main.go#L160-L162
- MinIO Operator uses the `TENANT_MINIO_IMAGE` env var: 
  - https://github.com/minio/operator/blob/master/pkg/apis/minio.min.io/v2/constants.go#L206
  - https://github.com/minio/operator/blob/master/pkg/apis/minio.min.io/v2/helper.go#L925-L931

**Comment by juan131** [comment]
Thanks!!!

**Comment by johnrizzo1** [comment]
This may have been resolved for the operator template but it is not working for the ClickHouseKeeperInstallation.  For example using this still results in the operator creating a pod with the clickhouse/clickhouse-keeper:latest image.  

```
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  configuration:
    clusters:
      - name: "chk01"
        layout:
          replicasCount: 3

  defaults:
    templates:
      # Templates are specified as default for all clusters
      podTemplate: default
      volumeClaimTemplate: keeper-storage

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: myrepo.dev/docker-remote/clickhouse/clickhouse-keeper:25.9-alpine
              resources:
                requests:
                  memory: "256M"
                  cpu: "1"
                limits:
                  memory: "4Gi"
                  cpu: "2"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: ssccloud-vol-storage
```

You still see these events

Back-off pulling image "clickhouse/clickhouse-keeper:latest"

**Comment by nevarsin** [comment]
Found myself with clickhouse-server:latest as well. What would be the right way to have the image tag set?

**Comment by nevarsin** [comment]
Ok I understood what was missing. While specifying a template in the ClickhouseInstallation manifest, said template have to be referenced in the cluster definition. Like this:

```
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  configuration:
    clusters:
      - name: "chk01"
        templates:
          podTemplate: clickhouse-pod # <------------- 
        layout:
          replicasCount: 3

  defaults:
    templates:
      # Templates are specified as default for all clusters
      podTemplate: default
      volumeClaimTemplate: keeper-storage

  templates:
    podTemplates:
      - name: default
        metadata:
          labels:
            app: clickhouse-keeper
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: myrepo.dev/docker-remote/clickhouse/clickhouse-keeper:25.9-alpine
              resources:
                requests:
                  memory: "256M"
                  cpu: "1"
                limits:
                  memory: "4Gi"
                  cpu: "2"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: ssccloud-vol-storage
```
