### ISSUE TITLE
PVCs are deleted on CHI deletion despite reclaimPolicy: Retain

### ISSUE THREAD

**Issue by asim-dogar** [Altinity/clickhouse-operator#1683]
When deleting a ClickHouseInstallation (CHI), the PersistentVolumeClaims (PVCs) associated with the ClickHouse data are being deleted—even though the reclaimPolicy: Retain is set under .spec.defaults.storageManagement and .spec.reconciling.cleanup.

We expected PVCs to persist after CHI deletion based on the operator configuration.

To Reproduce

Deploy ClickHouse with the following CHI manifest (simplified):

`apiVersion: v1
items:
- apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallation
  metadata:
    annotations:
      meta.helm.sh/release-name: clickhouse
      meta.helm.sh/release-namespace: clickhouse
    creationTimestamp: "2025-04-16T21:17:48Z"
    finalizers:
    - finalizer.clickhouseinstallation.altinity.com
    generation: 1
    labels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.3.12.76
      helm.sh/chart: clickhouse-0.2.2
    name: clickhouse
    namespace: clickhouse
    resourceVersion: "6272995"
    uid: 15997da8-b57e-4df7-b65e-0bd9d313aaa6
  spec:
    configuration:
      clusters:
      - layout:
          replicasCount: 2
          shardsCount: 1
        name: clickhouse
      users:
        admin/access_management: 1
        admin/networks/ip: 0.0.0.0/0
        admin/password:
          valueFrom:
            secretKeyRef:
              key: password
              name: clickhouse-credentials
      zookeeper:
        nodes:
        - host: keeper-clickhouse
          port: 2181
    defaults:
      storageManagement:
        provisioner: Operator
        reclaimPolicy: Retain
      templates:
        clusterServiceTemplate: clickhouse-service-lb
        dataVolumeClaimTemplate: clickhouse-data
        podTemplate: clickhouse-pod
        serviceTemplate: clickhouse-service
    reconciling:
      cleanup:
        reconcileFailedObjects:
          configMap: Retain
          pvc: Retain
          service: Retain
          statefulSet: Retain
        unknownObjects:
          configMap: Retain
          pvc: Retain
          service: Retain
          statefulSet: Retain
      configMapPropagationTimeout: 90
      policy: nowait
    restart: RollingUpdate
    useTemplates:
    - name: clickhouse-service
    - name: clickhouse-service-lb
    - name: clickhouse-pod
    - name: clickhouse-data
  status:
    chop-commit: 4299a2f
    chop-date: 2025-02-24T15:26:08
    chop-ip: 10.7.3.19
    chop-version: 0.24.4
    clusters: 1
    endpoint: clickhouse-clickhouse.clickhouse.svc.cluster.local
    fqdns:
    - chi-clickhouse-clickhouse-0-0.clickhouse.svc.cluster.local
    - chi-clickhouse-clickhouse-0-1.clickhouse.svc.cluster.local
    hosts: 2
    hostsCompleted: 1
    hostsUpdated: 1
    hostsWithTablesCreated:
    - chi-clickhouse-clickhouse-0-0.clickhouse.svc.cluster.local
    pods:
    - chi-clickhouse-clickhouse-0-0-0
    - chi-clickhouse-clickhouse-0-1-0
    shards: 1
    status: InProgress
    taskID: 689101d1-2086-43ff-a24c-4aaf841fab3d
    taskIDsStarted:
    - 689101d1-2086-43ff-a24c-4aaf841fab3d
    usedTemplates:
    - name: clickhouse-service
      useType: merge
    - name: clickhouse-service-lb
      useType: merge
    - name: clickhouse-pod
      useType: merge
    - name: clickhouse-data
      useType: merge
kind: List
metadata:
  resourceVersion: ""
`

`apiVersion: v1
items:
- apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallationTemplate
  metadata:
    annotations:
      meta.helm.sh/release-name: clickhouse
      meta.helm.sh/release-namespace: clickhouse
    creationTimestamp: "2025-04-16T21:17:48Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.3.12.76
      helm.sh/chart: clickhouse-0.2.2
    name: clickhouse-data
    namespace: clickhouse
    resourceVersion: "6271149"
    uid: 984e81de-4a95-4ba8-9b88-3644a30cf9af
  spec:
    templates:
      volumeClaimTemplates:
      - name: clickhouse-data
        spec:
          accessModes:
          - ReadWriteOnce
          reclaimPolicy: Retain
          resources:
            requests:
              storage: 50Gi
          storageClassName: clickhouse
- apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallationTemplate
  metadata:
    annotations:
      meta.helm.sh/release-name: clickhouse
      meta.helm.sh/release-namespace: clickhouse
    creationTimestamp: "2025-04-16T21:17:48Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.3.12.76
      helm.sh/chart: clickhouse-0.2.2
    name: clickhouse-pod
    namespace: clickhouse
    resourceVersion: "6271150"
    uid: 275b9720-248a-459a-b8bc-772b7b01b402
  spec:
    templates:
      podTemplates:
      - metadata:
          annotations:
            clickhouse.backup/path: /metrics
            clickhouse.backup/port: "7171"
            clickhouse.backup/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "8888"
            prometheus.io/scrape: "true"
        name: clickhouse-pod
        podDistribution:
        - scope: ClickHouseInstallation
          type: ClickHouseAntiAffinity
        spec:
          containers:
          - image: altinity/clickhouse-server:24.3.12.76.altinitystable
            imagePullPolicy: IfNotPresent
            name: clickhouse
            resources: null
            securityContext: {}
          - args:
            - server
            env:
            - name: LOG_LEVEL
              value: debug
            - name: ALLOW_EMPTY_BACKUPS
              value: "true"
            - name: API_LISTEN
              value: 0.0.0.0:7171
            - name: API_CREATE_INTEGRATION_TABLES
              value: "true"
            - name: BACKUPS_TO_KEEP_REMOTE
              value: "14"
            - name: REMOTE_STORAGE
              value: s3
            - name: S3_ACL
              value: private
            - name: S3_REGION
              value: me-central-1
            - name: S3_BUCKET
              value: clickhouse-develop-eks-clickhouse-backup-storage
            - name: S3_PATH
              value: backup/shard-{shard}
            - name: S3_FORCE_PATH_STYLE
              value: "true"
            - name: S3_DEBUG
              value: "true"
            image: altinity/clickhouse-backup:latest
            imagePullPolicy: Always
            name: clickhouse-backup
            ports:
            - containerPort: 7171
              name: backup-rest
          nodeSelector:
            node.kubernetes.io/instance-type: t3.medium
          securityContext: {}
          serviceAccountName: clickhouse-develop-eks-clickhouse-sa
          topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                clickhouse-keeper.altinity.com/cluster: chk-test
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
- apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallationTemplate
  metadata:
    annotations:
      meta.helm.sh/release-name: clickhouse
      meta.helm.sh/release-namespace: clickhouse
    creationTimestamp: "2025-04-16T21:17:48Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.3.12.76
      helm.sh/chart: clickhouse-0.2.2
    name: clickhouse-service
    namespace: clickhouse
    resourceVersion: "6271148"
    uid: ec354a78-658a-4dbc-b990-5cca017abc66
  spec:
    templates:
      serviceTemplates:
      - metadata:
          labels:
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/version: 24.3.12.76
            helm.sh/chart: clickhouse-0.2.2
        name: clickhouse-service
        spec:
          ports:
          - name: http
            port: 8123
            targetPort: 8123
          - name: tcp
            port: 9000
            targetPort: 9000
          selector:
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/name: clickhouse
          type: ClusterIP
- apiVersion: clickhouse.altinity.com/v1
  kind: ClickHouseInstallationTemplate
  metadata:
    annotations:
      meta.helm.sh/release-name: clickhouse
      meta.helm.sh/release-namespace: clickhouse
    creationTimestamp: "2025-04-16T21:17:48Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.3.12.76
      helm.sh/chart: clickhouse-0.2.2
    name: clickhouse-service-lb
    namespace: clickhouse
    resourceVersion: "6271147"
    uid: 081d6190-0db7-4526-908d-f9298021e30c
  spec:
    templates:
      serviceTemplates:
      - metadata:
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            external-dns.alpha.kubernetes.io/hostname: backend-clickhouse.vp-develop.com
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0cf8c45d2ffff45b9
          labels:
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/version: 24.3.12.76
            helm.sh/chart: clickhouse-0.2.2
        name: clickhouse-service-lb
        spec:
          ports:
          - name: http
            port: 8123
            targetPort: 8123
          - name: tcp
            port: 9000
            targetPort: 9000
          selector:
            app.kubernetes.io/instance: clickhouse
            app.kubernetes.io/name: clickhouse
          type: LoadBalancer
kind: List
metadata:
  resourceVersion: ""
`

Delete the CHI:
kubectl delete chi clickhouse -n clickhouse

Observe the behavior:

PVCs are deleted, even though reclaimPolicy: Retain is configured.

Expected behavior

PVCs should remain (Retain) after CHI deletion to allow potential restoration or reuse of data.

Actual behavior

All CHI PVCs managed by the operator are deleted when the CHI is deleted.Only keeper PVC remains there

**Comment by asim-dogar** [comment]
Here is complete helm charts

```yaml
{{- $service_name := tpl (include "clickhouse.serviceTemplateName" . ) . -}}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  restart: "RollingUpdate"
  defaults:
    storageManagement:
      provisioner: Operator
      reclaimPolicy: Retain
    templates:
      serviceTemplate: {{ $service_name }}
      {{- if .Values.clickhouse.lbService.enabled }}
      clusterServiceTemplate: {{ $service_name }}-lb
      {{- end }}
      podTemplate: {{ include "clickhouse.podTemplateName" . }}
      {{- if .Values.clickhouse.persistence.enabled }}
      dataVolumeClaimTemplate: {{ include "clickhouse.volumeClaimTemplateName" . }}
      {{- end }}
  useTemplates:
    - name: {{ $service_name }}
    {{- if .Values.clickhouse.lbService.enabled }}
    - name: {{ $service_name }}-lb
    {{- end }}
    - name: {{ include "clickhouse.podTemplateName" . }}
    - name: {{ include "clickhouse.volumeClaimTemplateName" . }}
    {{- if not (empty .Values.clickhouse.zones) -}}
    {{- $originalContext := . -}}
    {{- range .Values.clickhouse.zones }}
    - name: {{ include "clickhouse.podTemplateName" $originalContext }}-{{ . }}
    {{- end -}}
    {{- end }}
  configuration:
    users:
      admin/networks/ip: {{ include "clickhouse.defaultUser.ip" . | quote }}
      admin/access_management: 1
      admin/password:
        valueFrom:
          secretKeyRef:
            name: {{ include "clickhouse.credentialsName" . }}
            key: password
    clusters:
      - name: {{ include "clickhouse.clustername" . }}
        layout:
          {{- if (empty .Values.clickhouse.zones) }}
          shardsCount: {{ .Values.clickhouse.shardsCount | default 1 }}
          replicasCount: {{ .Values.clickhouse.replicasCount | default 1 }}
          {{- else }}
          shards:
          {{- $originalContext := . -}}
          {{- $shardsCount := .Values.clickhouse.shardsCount | default 1 | int -}}
          {{- range $shardIndex := until $shardsCount }}
            - name: shard{{ $shardIndex }}
              replicas:
                {{- range $zone :=  $originalContext.Values.clickhouse.zones }}
                - templates:
                    podTemplate: {{ include "clickhouse.podTemplateName" $originalContext }}-{{ $zone }}
                {{- end -}}
          {{- end -}}
          {{- end -}}
    {{- $keeper_host := tpl (include "clickhouse.keeper.host" . ) . -}}
    {{- if not (empty $keeper_host) }}
    zookeeper:
        nodes:
          - host: {{ $keeper_host }}
            port: {{ .Values.clickhouse.keeper.port }}
    {{- end }}
    {{- $extra_config := tpl (include "clickhouse.extra_config" . ) . -}}
    {{- if not (empty $extra_config) }}
    files:
        config.d/extra_config.xml: |
          {{- tpl $extra_config . | nindent 10 }}
    {{- end }}

{{ include "validate.clickhouse.keeper" . }}

  # Optional, allows tuning reconciling cycle for ClickhouseInstallation from clickhouse-operator side
  reconciling:
    # DISCUSSED TO BE DEPRECATED
    # Syntax sugar
    # Overrides all three 'reconcile.host.wait.{exclude, queries, include}' values from the operator's config
    # Possible values:
    #  - wait - should wait to exclude host, complete queries and include host back into the cluster
    #  - nowait - should NOT wait to exclude host, complete queries and include host back into the cluster
    policy: "nowait"

    # Timeout in seconds for `clickhouse-operator` to wait for modified `ConfigMap` to propagate into the `Pod`
    # More details: https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically
    configMapPropagationTimeout: 90

    # Optional, defines behavior for cleanup Kubernetes resources during reconcile cycle
    cleanup:
      # Describes what clickhouse-operator should do with found Kubernetes resources which should be managed by clickhouse-operator,
      # but do not have `ownerReference` to any currently managed `ClickHouseInstallation` resource.
      # Default behavior is `Delete`"
      unknownObjects:
        # Behavior policy for unknown PVC, `Delete` by default
        statefulSet: Retain
        # Behavior policy for unknown PVC, `Delete` by default
        pvc: Retain
        # Behavior policy for unknown ConfigMap, `Delete` by default
        configMap: Retain
        # Behavior policy for unknown Service, `Delete` by default
        service: Retain
      # Describes what clickhouse-operator should do with Kubernetes resources which are failed during reconcile.
      # Default behavior is `Retain`"
      reconcileFailedObjects:
        # Behavior policy for failed StatefulSet, `Retain` by default
        statefulSet: Retain
        # Behavior policy for failed PVC, `Retain` by default
        pvc: Retain
        # Behavior policy for failed ConfigMap, `Retain` by default
        configMap: Retain
        # Behavior policy for failed Service, `Retain` by default
        service: Retain
---
{{- if .Values.clickhouse.persistence.enabled }}
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: {{ include "clickhouse.volumeClaimTemplateName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    volumeClaimTemplates:
      - name: {{ include "clickhouse.volumeClaimTemplateName" . }}
        spec:
          reclaimPolicy: Retain
          {{- with .Values.clickhouse.persistence.accessMode }}
          accessModes:
            - {{ . }}
          {{- end }}
          {{- with .Values.clickhouse.persistence.storageClass }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.clickhouse.persistence.size }}
{{- end }}
{{- if .Values.clickhouse.persistence.logs.enabled }}
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: {{ include "clickhouse.logsVolumeClaimTemplateName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    volumeClaimTemplates:
      - name: {{ include "clickhouse.logsVolumeClaimTemplateName" . }}
        reclaimPolicy: Retain
        spec:
          {{- with .Values.clickhouse.persistence.logs.accessMode }}
          accessModes:
            - {{ . }}
          {{- end }}
          {{- with .Values.clickhouse.persistence.logs.storageClass }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.clickhouse.persistence.logs.size }}
{{- end }}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: {{ include "clickhouse.podTemplateName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    podTemplates:
      - name: {{ include "clickhouse.podTemplateName" . }}
        {{ include "clickhouse.podTemplateBase" . }}
        metadata:
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/port: '8888'
            prometheus.io/path: '/metrics'
            # need separate prometheus scrape config, look to https://github.com/prometheus/prometheus/issues/3756
            clickhouse.backup/scrape: 'true'
            clickhouse.backup/port: '7171'
            clickhouse.backup/path: '/metrics'
      {{- if not (empty .Values.clickhouse.zones) -}}
      {{- $originalContext := . -}}
      {{- range .Values.clickhouse.zones }}
      - name: {{ include "clickhouse.podTemplateName" $originalContext }}-{{ . }}
        {{ include "clickhouse.podTemplateBase" $originalContext }}
        zone:
          values:
            - {{ . }}
      {{- end -}}
      {{- end -}}
{{- $service_name := tpl (include "clickhouse.serviceTemplateName" . ) . -}}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: {{ $service_name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    serviceTemplates:
      - name: "{{ $service_name }}"
        metadata:
          {{- with .Values.clickhouse.service.serviceAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "clickhouse.labels" . | nindent 12 }}
            {{- with .Values.clickhouse.service.serviceLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
        spec:
          type: {{ .Values.clickhouse.service.type }}
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
          selector:
            {{- include "clickhouse.selectorLabels" . | nindent 12 }}
{{- if .Values.clickhouse.lbService.enabled }}
---
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallationTemplate
metadata:
  name: "{{ $service_name }}-lb"
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  templates:
    serviceTemplates:
      - name: "{{ $service_name }}-lb"
        metadata:
          labels:
            {{- include "clickhouse.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- with .Values.clickhouse.lbService.serviceLabels }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.clickhouse.lbService.serviceAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          type: "LoadBalancer"
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
          selector:
            {{- include "clickhouse.selectorLabels" . | nindent 12 }}
{{- end }}
{{- if .Values.keeper.enabled }}
{{- $cluster_name := tpl (include "clickhouse.clustername" . ) . -}}
{{- $keeper_host := tpl (include "clickhouse.keeper.host" . ) . -}}
{{- $count := (.Values.keeper.replicaCount | int) -}}
---
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  configuration:
    clusters:
      - name: "{{ $cluster_name }}"
        layout:
          replicas:
        {{- range $i, $e := until $count }}
            - name: "keeper-{{ $i }}"
              templates:
                podTemplate: "keeper-{{ $i }}"
                dataVolumeClaimTemplate: "keeper-{{ $i }}"
                replicaServiceTemplate: "keeper-{{ $i }}"
        {{- end }}
    {{- if not (empty .Values.keeper.settings) }}
    settings:
    {{- range $k, $v := .Values.keeper.settings }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
  defaults:
    storageManagement:
      provisioner: Operator
      reclaimPolicy: Retain
  templates:
    serviceTemplates:
    {{- range $i, $e := until $count }}
      - name: "keeper-{{ $i }}"
        generateName: "{{ $keeper_host }}-{{ $i }}"
        spec:
          type: ClusterIP
          publishNotReadyAddresses: true
          ports:
            - name: zk
              port: 2181
              targetPort: 2181
            - name: raft
              port: 9444
              targetPort: 9444
            {{- if not (empty $.Values.keeper.metricsPort) }}
            - name: metrics
              port: {{ $.Values.keeper.metricsPort }}
              targetPort: {{ $.Values.keeper.metricsPort }}
            {{- end }}
    {{- end }}
    volumeClaimTemplates:
      {{- range $i, $e := until $count }}
      - name: "keeper-{{ $i }}"
        spec:
          reclaimPolicy: Retain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ $.Values.keeper.localStorage.size }}
          {{- if $.Values.keeper.localStorage.storageClass }}
          storageClassName: "{{ $.Values.keeper.localStorage.storageClass }}"
          {{- end }}
      {{- end }}
    podTemplates:
    {{- range $i, $e := until $count }}
      - name: "keeper-{{ $i }}"
        generateName: "{{ $keeper_host }}-{{ $i }}"
        {{- with $.Values.keeper.podAnnotations }}
        metadata:
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
          {{- if $.Values.keeper.nodeSelector }}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      {{- range $k, $v := $.Values.keeper.nodeSelector }}
                      - key: {{ $k }}
                        operator: In
                        values:
                          - {{ $v }}
                      {{- end }}
          {{- end }}
          topologySpreadConstraints:
          {{- if $.Values.keeper.zoneSpread }}
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                clickhouse-keeper.altinity.com/cluster: "{{ $cluster_name }}"
          {{- end }}
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                clickhouse-keeper.altinity.com/cluster: "{{ $cluster_name }}"
          {{- with $.Values.keeper.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: clickhouse-keeper
              image: "{{ $.Values.keeper.image }}:{{ $.Values.keeper.tag }}"
              {{- if not (empty $.Values.keeper.metricsPort) }}
              ports:
              - name: metrics
                containerPort: {{ $.Values.keeper.metricsPort }}
              {{- end }}
              resources:
                requests:
                  cpu: "{{ $.Values.keeper.resources.cpuRequestsMs }}"
                  memory: "{{ $.Values.keeper.resources.memoryRequestsMiB }}"
                limits:
                  cpu: "{{ $.Values.keeper.resources.cpuLimitsMs }}"
                  memory: "{{ $.Values.keeper.resources.memoryLimitsMiB }}"
    {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.credentialsName" . }}
type: Opaque
stringData:
  user: "{{ .Values.clickhouse.defaultUser.user }}"
  password: "{{ .Values.clickhouse.defaultUser.password }}"

```
