### ISSUE TITLE
Add Image Version Configuration Support for ClickHouse-Keeper StatefulSet Deployment

### ISSUE THREAD

**Issue by swamp5** [Altinity/clickhouse-operator#1693]
When using ClickHouseKeeperInstallation to create a clickhouse-keeper cluster, I cannot directly specify the image version. The generated StatefulSet pulls the latest image by default. Could this be improved?

**Comment by Slach** [comment]
you can use podTemplates
```yaml
spec:
  defaults:
    templates:
      podTemplate: keeper-25.3
  templates:
    podTemplates:
    - name: keeper-25.3
      spec:
        containers:
        - name: clickhouse-keeper
          image: clickhouse/clickhouse-keeper:25.3
```
