### ISSUE TITLE
PVCs not deleted with "reclaimPolicy" set to "Delete"

### ISSUE THREAD

**Issue by dkmorgan** [Altinity/clickhouse-operator#1695]
I currently have a ClickHouse cluster running on AWS.
The cluster configuration was based on the following examples:
- [server](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/04-replication-zookeeper-04-medium-AWS-persistent-volume.yaml)
- [keeper](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chk-examples/02-extended-3-nodes.yaml)

The cluster runs fine and I can create a database, etc.
When I delete the "ClickHouseInstallation" and "ClickHouseKeeperInstallation" from the cluster, I very often get PVC leftovers together with the PV and consequently the EBS volume despite setting `reclaimPolicy` to "Delete".

The `volumeClaimTemplates` section is as follows (same for both server and keeper except the name):

```yaml
    volumeClaimTemplates:
      - name: ch-server-vct
        reclaimPolicy: Delete
        spec:
          storageClassName: ebs-gp3-delete
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
```

The `StorageClass` definition for "ebs-gp3-delete" is as follows:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-delete
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

I haven't been able to figure out why I am getting these random leftover PVCs.
Has anyone run into a similar situation?
I would greatly appreciate any pointers that may be causing this.

**Comment by dkmorgan** [comment]
Been comparing the PVC's created against a PVC created when deploying a `RabbitmqCluster` and may have found what could be leading to the issue.
The PVC's created by the clickhouse-operator does not set the `ownerRefs`:
```
kubectl get pvc -o json | jq '.items[] | {name: .metadata.name, ownerRefs: .metadata.ownerReferences}'
{
  "name": "ch-keeper-vct-chk-ch-keeper-0-0-0",
  "ownerRefs": null
}
{
  "name": "ch-keeper-vct-chk-ch-keeper-0-1-0",
  "ownerRefs": null
}
{
  "name": "ch-keeper-vct-chk-ch-keeper-0-2-0",
  "ownerRefs": null
}
{
  "name": "ch-server-vct-chi-ch-server-0-0-0",
  "ownerRefs": null
}
{
  "name": "ch-server-vct-chi-ch-server-0-1-0",
  "ownerRefs": null
}
{
  "name": "persistence-rabbitmq-cluster-server-0",
  "ownerRefs": [
    {
      "apiVersion": "rabbitmq.com/v1beta1",
      "blockOwnerDeletion": false,
      "controller": true,
      "kind": "RabbitmqCluster",
      "name": "rabbitmq-cluster",
      "uid": "***"
    }
  ]
}
```

Is this behavior expected?
Or have I missed something that is preventing the `ownerRefs` to be set?

**Comment by manishrawat1992** [comment]
I think it is a bug with operator, 
function of reclaimPolicy retain and delete is jumbled

**Comment by zbialik** [comment]
We're also seeing this issue and are using quite large EBS volumes which we'd prefer get cleaned up automatically by the operator (as advertised). Setting `reclaimPolicy` to `Delete` seems to have no effect.

**Comment by zbialik** [comment]
It appears that the `StatefulSets` provisioned by the `ClickhouseInstallation` are created with:
```
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
```

This is why, on delete of `ClickhouseInstallation`, the PVCs still live on. I think the clickhouse-operator should make use of the newer feature for `Statefulset.spec.persistentVolumeClaimRetentionPolicy` ([documented here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention)) so that the handling of the PVCs can be customized.
