### ISSUE TITLE
default: Authentication failed: password is incorrect, or there is no user with such name

### ISSUE THREAD

**Issue by minhtd1981** [Altinity/clickhouse-operator#1709]
I've moved our CH clusters to the new node pool and suddenly I got this error whenever using the function clusterAllReplicas. Restarting CH clusters did not help.

It took me for a while to see that the error came from the IP of clickhouse keepers in another node pool.

Here is my users.xml
```
<users>
   <default>
       <password></password>
       <networks>
                <ip>::/0</ip>
       </networks>
   </default>
</users>
```

and my users.d/chop-generated-users.xml
```
<users>
   <default>
       <networks>
                <ip>::/0</ip>
                <ip>127.0.0.1</ip>
                <ip>10.0.20.156</ip>
                <ip>10.0.20.13</ip>
                <ip>10.0.20.43</ip>
       </networks>
   </default>
</users>
```

and here is my system.users
```
name:                 default
id:                   94309d50-4f52-5250-31bd-74fecac179db
storage:              users_xml
auth_type:            plaintext_password
auth_params:          {}
host_ip:              ['10.0.20.156','10.0.20.13','10.0.20.43']
host_names:           ['localhost']
...
default_database:
```

I currently need to update my ClickHouseInstallation
```
default/networks/ip:
      - ::1
      - 127.0.0.1
      - 10.0.20.0/24
```
so that the error is temporarily fixed but it is not good.

If there is no other workaround, I'm afraid that I need to create another user and update remote_users but tbh I am not sure if it is recommended to do so.

Thanks,

**Comment by Slach** [comment]
which `clickhouse-operator` version do you use?

how did you install it?

>  <ip>::/0</ip>
is your k8s cluster support ipv6 pod network?

> 10.0.20.156 10.0.20.13 10.0.20.43

did you add these IP addresses manually to `kind: ClickHouseInstallation`?

could you share

`kubectl get chi --all-namespaces` ?

**Comment by minhtd1981** [comment]
My cluster works for years but lately I moved them to the new subnet by **kubectl drain** without changing the existing ClickHouseInstallation.

Here is my ClickHouseInstallation

```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
...
spec:
  configuration:
    clusters:
    - layout:
        replicas:
        - templates:
            podTemplate: clickhouse-in-zone-westeurope-1
        - templates:
            podTemplate: clickhouse-in-zone-westeurope-2
        - templates:
            podTemplate: clickhouse-in-zone-westeurope-3
      name: cluster
  ...
  users:
      admin/access_management: 1
      admin/k8s_secret_password_sha256_hex: clickhouse-credentials/admin_password
      admin/networks/ip: 0.0.0.0/0
      admin/profile: default
      admin/quota: default
      backup/access_management: 1
      backup/k8s_secret_password_sha256_hex: clickhouse-credentials/backup_password
      backup/networks/ip: 0.0.0.0/0
      default/networks/ip:
      - ::1
      - 127.0.0.1
      - 10.0.20.0/24
  ...
  zookeeper:
      nodes:
      - host: clickhouse-keepers.clickhouse
      operation_timeout_ms: 5000
      session_timeout_ms: 5000
  ...
``` 
fyi. I've added default/networks/ip so that the issue has been temporarily resolved.

and here is the error log before the change
```
While executing Remote. (AUTHENTICATION_FAILED) (version 23.8.15.35 (official build)) (from [::ffff:10.0.20.39]:46020) (in query: SELECT type FROM clusterAllReplicas(cluster, system.query_log) WHERE query_id = 'f7d1072a-96fc-4a2d-9eb3-a47787751129' AND event_date >= addDays(today(), -1) AND event_time >= addMinutes(now(), -30) AND type IN ('ExceptionBeforeStart','ExceptionWhileProcessing','QueryFinish') FORMAT JSONEachRow)
```
10.0.20.39 is the IP of one of the clickhouse keeper pod.

Thanks,
