### ISSUE TITLE
Changing reclaimPolicy on existing volumeClaimTemplate from Retain to Delete has no effect

### ISSUE THREAD

**Issue by janeklb** [Altinity/clickhouse-operator#1711]
In my `ClickHouseInstallation` I have the following

```yaml
  defaults:
    storageManagement:
      reclaimPolicy: Retain
      provisioner: Operator

  templates:
    volumeClaimTemplates:
      - name: data-1-volume
        provisioner: Operator
        spec:
          storageClassName: clickhouse-data-v1
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```

If I add `reclaimPolicy: Delete` 

```yaml
  templates:
    volumeClaimTemplates:
      - name: data-1-volume
        provisioner: Operator
        reclaimPolicy: Delete
        spec:
          storageClassName: clickhouse-data-v1
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```

The operator seems to process it successfully (and the CHI status goes to `InProgress` and then `Completed`); however, the underlying/relevant PV's `reclaimPolicy` is never updated (and remains as `Retain`)
