### ISSUE TITLE
Consider moving Prometheus scrape configs to PodMonitor relabelings

### ISSUE THREAD

**Issue by macrokernel** [Altinity/clickhouse-operator#1720]
At present Prometheus scrape configs are defined in [prometheus-template.yaml](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-template.yaml). This is fine for setting up a dedicated Prometheus server specially for ClickHouse. However if Prometheus is already up and running it it is more convenient  to configure Prometheus label replacements in a `PodMonitor` Kubernetes object as below.

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: myclickhouse
  namespace: "clickhouse"
  labels:
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: "metrics"
      scheme: http
    - relabelings:
      - action: drop
        sourceLabels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_ip
          - __meta_kubernetes_pod_annotation_prometheus_io_port
        regex: "(.+);(.+)"
        replacement: "$1:$2"
        targetLabel: __address__
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
        regex: "()"
        replacement: "/metrics"
        targetLabel: __meta_kubernetes_pod_annotation_prometheus_io_path
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
        targetLabel: __metrics_path__
      - action: replace
        sourceLabels:
          - __meta_kubernetes_namespace
        targetLabel: namespace
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_name
        targetLabel: pod_name
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_container_name
        targetLabel: container_name
      - action: labelmap
        regex: "__meta_kubernetes_pod_label_(.+)"
      - action: labeldrop
        regex: "container_id|image_id|controller_revision_hash|pod_template_generation|pod_template_hash"
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
```
