### ISSUE TITLE
Clickhouse global service for cilium

### ISSUE THREAD

**Issue by carloss4dv** [Altinity/clickhouse-operator#1731]
Hi there im trying to deploy 2 clusters in two separate k3s clusters and trying to connect them with cilium clustermesh.

Is there a way to force the operator to create 1 single service that covers the whole clickhouse cluster?

Im trying to use serviceTemplates for this but without success

Thanks !!!

**Comment by Slach** [comment]
try to use something like that
```yaml
spec:
  defaults:
    clusterServiceTemplate: cillium-template
  templates:
    serviceTemplates:
    - name: cillium-template
      spec:
       ... your spec
```
