### ISSUE TITLE
is there a parameter that prevents me from reducing the number of replicas?

### ISSUE THREAD

**Issue by monadbobo** [Altinity/clickhouse-operator#1735]
After I increase the number of replicas and shards, is there a parameter that can prevent me from updating the replicas and shards when I update (for example, updating some configuration)?

**Comment by Slach** [comment]
Unfortunately, no way to prevent from reducing inside `clickhouse-operator` ;)

Try to use
https://github.com/kyverno/kyverno/

with something like that

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-decrease-clickhouse-replicas
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: block-replicasCount-decrease
      match:
        resources:
          kinds:
            - ClickHouseInstallation
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: Equals
            value: UPDATE
      validate:
        message: "Decreasing clusters[].layout.replicasCount is not allowed."
        deny:
          conditions:
            any:
              - key: "{{ length(oldObject.spec.configuration.clusters) }}"
                operator: GreaterThan
                value: 0
              - key: "{{ length(request.object.spec.configuration.clusters) }}"
                operator: GreaterThan
                value: 0
              # Core comparison logic: for each cluster, deny if new replicasCount < old replicasCount
              - key: "{{ regex_match('.*true.*', '{{ request.object.spec.configuration.clusters | zip(oldObject.spec.configuration.clusters) | map(`(x, y) => x.layout.replicasCount < y.layout.replicasCount`) | join(`,`) }}') }}"
                operator: Equals
                value: "true"
```
