### ISSUE TITLE
Rendered Users.xml missing new settings for access_management

### ISSUE THREAD

**Issue by MclellandG** [Altinity/clickhouse-operator#1754]
In order to enable [SQL user mode](https://clickhouse.com/docs/operations/access-rights) you need to now set the following on the default user (and are apparently [required](https://github.com/ClickHouse/ClickHouse/issues/47092#issuecomment-1485052499) to enable the feature).    

My installation previously only  have the line `default/access_management: "1"`  and the feature was enabled.  At some point the additional values were added and are required to enable the feature.  

Added the following to `chi.yaml` to enable the feature
```
   spec:
      ...
      configuration:
         users:
            default/access_management: 1
            default/named_collection_control: 1
            default/show_named_collections: 1
            default/show_named_collections_secrets: 1
        ...
```
However, the generated `users.xml` file does not contain all of the values
```
 <!-- User can create other users and grant rights to them. -->
            <access_management>1</access_management>

            <!-- User can manipulate named collections. -->
            <named_collection_control>1</named_collection_control>

            <!-- User permissions can be granted here -->
            <!--
            <grants>
                <query>GRANT ALL ON *.*</query>
            </grants>
            -->
```

The `show_named_collections` and `show_named_collections_secrets` are not added to the generated `users.xml` file.  The result is that the SQL user mode is not enabled and I am not able to add new users or modify user permissions via SQL.
