### ISSUE TITLE
Disabling Loadbalancer using serviceTemplate

### ISSUE THREAD

**Issue by shawel** [Altinity/clickhouse-operator#198]
Hi 

Can you please tell me how to disable clickhouse-operater from creating a public load balancer. I have a separate service that creates an internal load balancer (AWS) Currently I am trying to override the serviceTemplate to disable ELB bit it is not working (using v 0.6)

```
serviceTemplates:
      - name: chi-service-template
        metadata:
          name: clickhouse-service-tdd-{chi}
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
            - name: mysql
              port: 9001
          type: ClusterIP
          ClusterIP: None
```
Thanks
