### ISSUE TITLE
ExternalIP for every chi-service

### ISSUE THREAD

**Issue by DTvGe45vc** [Altinity/clickhouse-operator#199]
Hello

Help me please. I can't deploy chi-services with external IP.
How can I do it?

Thanks

**Comment by DTvGe45vc** [comment]
yea

**Comment by DTvGe45vc** [comment]
example

**Comment by sunsingerus** [comment]
Can you, please, elaborate what are exact issues you are struggling with?
Provided .yaml is expected to produce one CHI-level LoadBalancer service. However, I do not have OpenStack available and can't check exact OpenStack's reaction.

**Comment by DTvGe45vc** [comment]
Hello @sunsingerus 

Today I have one service CHI LoabBalancer and 6 CHI ClusterIP (ClusterIP: None) services for every clickhouse shard. How can I get cluster IP-address for every CHI ClusterIP service?

**Comment by sunsingerus** [comment]
ClusterIP does not have external IP, intenal only, it is its main point. If you need real external IP you have to use LoadBalancer only. More info is available in [kube docs](https://kubernetes.io/docs/concepts/services-networking/service/)
`serviceTemplates`can be used to customize what `Service` object would be associated with `cluster/shard/replica`, like the following (**IMPORTATNT** - this is **NOT the full spec**, check [multiple examples](https://github.com/Altinity/clickhouse-operator/tree/master/docs) available and setup your needed configuration):
```yaml
spec:
  configuration:
    clusters:
      - name: customized
        templates:
          clusterServiceTemplate: cluster-service-template 
        layout:
          shards:
            - name: shard2
              templates:
                shardServiceTemplate: stard-service-template
              replicas:
                - name: replica0
                  templates:
                    replicaServiceTemplate: replica-service-template

  templates:
    serviceTemplates:
      - name: cluster-service-template 
        metadata:
          annotations:
            # For more details on Internal Load Balancer check
            # https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          type: LoadBalancer
      - name: stard-service-template 
        metadata:
          annotations:
            # For more details on Internal Load Balancer check
            # https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          type: LoadBalancer
      - name: replica-service-template
        metadata:
          annotations:
            # For more details on Internal Load Balancer check
            # https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          type: LoadBalancer
```
