### ISSUE TITLE
PVC not found

### ISSUE THREAD

**Issue by yyfrankyy** [Altinity/clickhouse-operator#202]
https://github.com/Altinity/clickhouse-operator/blob/0.6.0/docs/custom_resource_explained.md

Follow the instruction here and cannot allocate specific PVC, fail to create specific Pod.

**Comment by sunsingerus** [comment]
Any details available?

**Comment by yyfrankyy** [comment]
it's my mistake.

After I added the `volumeClaimTemplates` named: `chpvc`, 

```
volumeClaimTemplates:
  - name: chpvc
    reclaimPolicy: Retain
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 5Ti
      storageClassName: clickhouse-storage
```

I added the template named `chpvc` in the `podTemplates` block,

```
volumes:
  - name: chpvc
    persistentVolumeClaim:
      claimName: chpvc
```

instead of this inside `containers` block.

```
volumeMounts:
  - name: chpvc
    mountPath: /var/lib/clickhouse
```

it worked just fine after I remove the `volumes` part.
