### ISSUE TITLE
User Configuration

### ISSUE THREAD

**Issue by whelan9453** [Altinity/clickhouse-operator#226]
Hi, I'm trying out ClicHouse Operator recently and have some problems figuring out the user configuration.

My approach is creating a YAML file like the one below and use  ``kubectl apply -f myfile.yaml --namespace myspace`` to deploy it. 
  
```YAML
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "test"

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.6
  configuration:
    users:
      admin/password_sha256_hex: 85fe7e87fc89408f80fdd936c3967c4cd040c4ad676d2e5ec37017c7f5167345
      default/password_sha256_hex: 7388286b8d0a085d1fb57a8a4a164005d228cdb305d2f04f84090c077d2be8ce
      default/networks/ip:
        - "127.0.0.1"
    settings:
      compression/case/method: zstd
    zookeeper:
      nodes:
      - host: zookeeper.zoons
    clusters:
      - name: test
        layout:
          shardsCount: 3
          replicasCount: 2
    
  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
    podTemplates:
      - name: clickhouse:19.6
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.6.2.11
              resources:
                requests:
                  memory: 4Gi
                  cpu: 2
```

I check the ``user.xml`` file and it looks alright.

```XML
<yandex>
    <users>
        <admin>
            <networks>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>85fe7e87fc89408f80fdd936c3967c4cd040c4ad676d2e5ec37017c7f5167345</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <default>
            <networks>
                <ip>127.0.0.1</ip>
            </networks>
            <password_sha256_hex>7388286b8d0a085d1fb57a8a4a164005d228cdb305d2f04f84090c077d2be8ce</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <test>
            <networks>
                <ip>::/0</ip>
            </networks>
            <password>default</password>
            <profile>default</profile>
            <quota>default</quota>
        </test>
    </users>
</yandex>
```

The problem is the password_sha256_hex settings seem to function incorrectly.
admin and default should have different passwords but I can log in with the same password.
```bash
root@chi-smart-medic-smart-medic-2-1-0:/etc/clickhouse-server/users.d# clickhouse-client -u admin --password ZHJ5Y2FyZWVzc2VudGlhbDEyMw==
ClickHouse client version 19.6.2.11 (official build).
Connecting to localhost:9000 as user admin.
Code: 193. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Wrong password for user admin. 

root@chi-test-2-1-0:/etc/clickhouse-server/users.d# clickhouse-client -u admin --password ZHJ5Y2FyZWVzc2VudGlhbA==
ClickHouse client version 19.6.2.11 (official build).
Connecting to localhost:9000 as user admin.
Connected to ClickHouse server version 19.6.2 revision 54418.

chi-test-2-1-0.chi-test-2-1.clickhouse.svc.cluster.local :) exit
Happy new year.
root@chi-test-2-1-0:/etc/clickhouse-server/users.d# clickhouse-client --password ZHJ5Y2FyZWVzc2VudGlhbA==
ClickHouse client version 19.6.2.11 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.6.2 revision 54418.

chi-test-2-1-0.chi-smart-medic-smart-medic-2-1.clickhouse.svc.cluster.local :) exit
Bye.
```

Another problem is the test user has generated automatically and I don't want it.

Any suggestions would be great. Thanks.
