### ISSUE TITLE
password of default user is not propagated to shards

### ISSUE THREAD

**Issue by ralfbecher** [Altinity/clickhouse-operator#265]
Hi,

when creating a cluster where the password of default user is set in the manifest, it will not be propagated to remote_servers.xml. This leads to errors using umbrella tables:

From this example: [https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md](https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md)

```
SELECT * FROM events;
```
`Code: 194, e.displayText() = DB::Exception: Received from chi-test-cho-with-shards-simple-1-0:9000. DB::Exception: Password required for user default. (version 20.1.4.14 (official build))
`

This is my manifest file:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test-cho-with-shards"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    users:
      default/password: secret
    zookeeper:
      nodes:
        - host: zookeeper.zoons
    clusters:
      - name: "simple"
        layout:
          shardsCount: 3
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

I think I could insert user/password manually but am applied change in manifest will remove it again.
