### ISSUE TITLE
ReplicateTable are not getting created in the new Replica

### ISSUE THREAD

**Issue by phatak-dev** [Altinity/clickhouse-operator#268]
Whenever we increase replication, from operator logs i see that it's running below query to find which tables to create in new replica
```
] running query SELECT DISTINCT
        database AS name,
        concat('CREATE DATABASE IF NOT EXISTS ', name) AS create_db_query
```
It often results in a message like
```
Creating replicated objects: []
```
Even though there are many replicated tables, it doesn't create any. Manually running the generated query in clickhouse gives the correct result. 

Can someone point out what may be the issue here?

**Comment by alex-zaitsev** [comment]
@phatak-dev , what is your operator version and ClickHouse version? There was a bug in operator 0.7.0 an earlier, but it should be good now.

**Comment by phatak-dev** [comment]
@alex-zaitsev I am using latest (0.9) operator version and clickhouse version 19.6.2.11

**Comment by alex-zaitsev** [comment]
@phatak-dev , that could be an issue with the old ClickHouse version you are using.

We recommend using Altinity stable versions, see releases there: https://www.altinity.com/blog/tag/Releases

We have not tested operator extensively for ClickHouse before 19.11 version. I will test with 19.6.2.11 to see if we can reproduce the problem.

**Comment by alex-zaitsev** [comment]
@phatak-dev , I could not reproduce it in 19.6.2.11 version. Could you give me an example of Replicated table you are using?

**Comment by phatak-dev** [comment]
Below are the tables. One is replicated and one is distributed
```
CREATE TABLE events_local on cluster '{cluster}' (
    event_date  Date,
    event_type  Int32,
    article_id  Int32,
    title       String
) engine=ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}')
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_date, intHash32(article_id))
SAMPLE BY intHash32(article_id);
```

```
CREATE TABLE events on cluster '{cluster}' AS events_local
ENGINE = Distributed('{cluster}', default, events_local, rand());
```
It works the first time when I increase from 1 to 2 replicas. But when I reduce to 1 and increase to 2 again the tables will be not created.

**Comment by phatak-dev** [comment]
@alex-zaitsev Tested with 19.16.12.49 also. It has same issue. I am running the operator on a AWS kops cluster.

**Comment by phatak-dev** [comment]
@alex-zaitsev Is the below bug may be causing the issue?
https://github.com/ClickHouse/ClickHouse/issues/7268

**Comment by phatak-dev** [comment]
@alex-zaitsev With the new version of clickhouse, I see below error at the creation of the new replica
```
2020.02.25 09:30:53.616041 [ 25 ] {} <Error> Cluster: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Host not found: chi-
repl-05-replicated-0-1 (version 19.16.12.49 (official build)
2020.02.25 09:30:53.618419 [ 25 ] {} <Error> Cluster: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Host not found: chi-
repl-05-replicated-0-1 (version 19.16.12.49 (official build)
2020.02.25 09:30:53.620209 [ 25 ] {} <Error> Cluster: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Host not found: chi-
repl-05-replicated-0-1 (version 19.16.12.49 (official build)
```

**Comment by phatak-dev** [comment]
@alex-zaitsev In the newly created pod, I see below error
```
2020.02.25 09:53:44.849122 [ 6 ] {} <Debug> DDLWorker: Will not execute task query-0000000000: There is no a local address in host list
```

**Comment by alex-zaitsev** [comment]
@phatak-dev , could you share your ClickHouseInstallation resource, please?

**Comment by phatak-dev** [comment]
@alex-zaitsev 
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "repl-05"

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.16
 configuration:
    zookeeper:
      nodes:
      - host: zookeeper.zoo1ns
    clusters:
      - name: replicated
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    volumeClaimTemplates:
      - name: default
        reclaimPolicy: Delete
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
                    storage: 300Mi
    podTemplates:
      - name: clickhouse:19.16
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.16.12.49
```
