### ISSUE TITLE
Why not use pod annotations to scrape metrics?

### ISSUE THREAD

**Issue by Nklya** [Altinity/clickhouse-operator#269]
Hello.

I've found that it's supposed to monitor clickhouse with ServiceMonitor  https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-clickhouse-operator-service-monitor.yaml

But why not use pod annotations to scrape metrics? This is the part of clickhouse-operator-install-template.yaml file with two lines added in the end.

```
---
# Possible Template Parameters:
#
# clickhouse-demo
# altinity/clickhouse-operator:0.9.1
# altinity/metrics-exporter:0.9.1
#
# Setup Deployment for clickhouse-operator
# Deployment would be created in kubectl-specified namespace
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clickhouse-operator
  namespace: clickhouse-demo
  labels:
    app: clickhouse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-operator
  template:
    metadata:
      annotations:
        prometheus.io/port: '8888'
        prometheus.io/scrape: 'true'
```

**Comment by sunsingerus** [comment]
Can you please elaborate in more details your proposition?

**Comment by sunsingerus** [comment]
What is the expected sequence of actions around these annotations?

**Comment by Nklya** [comment]
prometheus-operator is able to automatically discover pods to scrape metrics based on SD.
At least the one installed with helm chart https://github.com/helm/charts/blob/bd99f09e27785d2ca85f7a5b0c4be17db485b52e/stable/prometheus/values.yaml#L1478

So if you add these two lines with annotations to deployment, monitoring will be added automatically without need to add ServiceMonitor
```
annotations:
        prometheus.io/port: '8888'
        prometheus.io/scrape: 'true'
```

**Comment by sunsingerus** [comment]
Ok, that makes sense, we'll take a look into this. Thanks for suggestion!

**Comment by jordivilaseca** [comment]
I am working in exposing ClickHouse metrics to DataDog using a similar approach (creating annotations), right now it is not possible to create pod annotations using clickhouse-operator (or at least I was not able to do it). I was thinking if at the same time of implementing that for prometheus, maybe the solution could be general enough to be able to do that for other metric collectors

**Comment by sunsingerus** [comment]
@jordivilaseca it is still not clear for me - would you like to add custom annotation to operator's pod (because metrics-exporter lives there, however metrics exporter exports metrics in Prometheus format only so far and I have doubts that is useful to DataDog) OR would you like to add custom annotation to pods where clickhouse runs (and in this case DataDog has to know how to fetch metrics from clickhouse directly). Can you, please clarify a little?

**Comment by jordivilaseca** [comment]
@sunsingerus Thanks for the replay and sorry for the confusion. I originally wrote here because I thought it was the same case but I found out afterward that were different things. 

Datadog agent recently implemented an [integration](https://docs.datadoghq.com/integrations/clickhouse/) to export metrics (and logs) from Clickhouse. Apart from that, they also have what they call [Autodiscovery](https://docs.datadoghq.com/agent/autodiscovery/integrations/?tab=kubernetes), that is a way to tell the agent what integration use for each pod using its annotations. So the idea would be to implement a way to add custom annotations to pods where clickhouse runs.

**Comment by sunsingerus** [comment]
@jordivilaseca thanks for clarification. You'd like to add custom labels/annotations to pods, managed by `clickhouse-operator`. Here is another issue #281 about custom labels. We'll consider the best way to add custom labels.
However, `clickhouse-operator` allows to specify custom labels/annotations for CHI object as ususal:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-installation-max"
  labels:
YOUR LABELS GO HERE
```
due to `CHI` being specified as:
```go
type ClickHouseInstallation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" yaml:"metadata"`
	Spec              ChiSpec   `json:"spec"     yaml:"spec"`
	Status            ChiStatus `json:"status"`
}
```
and `clickhouse-operator` applies custom labels from `chi` to all managed pods. This feature is not properly documented ATM, and it is like in development state, but you can test whether it works (probably as temp workaround) for you.
