### ISSUE TITLE
CR Grafana + service, type: LoadBalancer, kops/AWS service stay in pending external-ip status

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-operator#293]
I have kops/AWS k8s 1.11.x without installed ingress deployment
I need create kind: Service with type: LoadBalancer for allow access to grafana outside from k8s cluster

I tried `grafana-operator:latest` and `grafana-operator:3.1.0`
with following custom Grafana resource 

```
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: "grafana"
spec:
  ingress:
    enabled: False
  service:
    type: LoadBalancer
  client:
    timeout: 30
    preferService: True
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "admin"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    # require for Dashboard Installation - https://github.com/integr8ly/grafana-operator/issues/92
    auth.basic:
      enabled: True
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
  - matchExpressions:
    - {key: app, operator: In, values: [grafana]}
```

service `grafana-service` was created 
but 
kubectl describe -n my-namespace service/grafana-service

show following error:
```
Name:                     grafana-service
Namespace:                my-namespace
Labels:                   <none>
Annotations:              <none>
Selector:                 app=grafana
Type:                     LoadBalancer
IP:                       100.66.199.39
Port:                     grafana  3000/TCP
TargetPort:               grafana-http/TCP
NodePort:                 grafana  30120/TCP
Endpoints:                100.96.11.188:3000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                    From                Message
  ----     ------                      ----                   ----                -------
  Normal   EnsuringLoadBalancer        2m16s (x9 over 2m23s)  service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer         2m16s (x8 over 2m21s)  service-controller  Ensured load balancer
  Warning  CreatingLoadBalancerFailed  2m16s (x8 over 2m21s)  service-controller  Error creating load balancer (will retry): not persisting update to service 'altinity-kube/grafana-service' that has been changed since we received it: Operation cannot be fulfilled on services "grafana-service": the object has been modified; please apply your changes to the latest version and try again
```

what i need add to `service` section of Grafana Custom resource to solve this problem?
