### ISSUE TITLE
changing shard count is not creating or deleteing new required pods

### ISSUE THREAD

**Issue by boraozkan** [Altinity/clickhouse-operator#318]
Hi All,

I just want to increase my shard count in my cluster  and expect to create new shards in new pods across the cluster. When I check I only see my new shards name and new host name in **system.clusters** table as expected but I couldn't see any fresh created pods in namespace that listed newly named in table.

My operator version is 0.9.5
My manifest for cluster:

```

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "vizlib-dashboard-sharded"
  namespace: ch-test03
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoons
    clusters:
      - name: "ch-test03"
        templates:
          podTemplate: clickhouse-with-empty-dir-volume-template
        layout:
          shardsCount: 6
    settings:
      http_port: 8124
      tcp_port: 9001
      interserver_http_port: 9010
      ssh_port: 22
templates:
    podTemplates:
        - name: clickhouse-with-empty-dir-volume-template
          spec:
            containers:
              - name: clickhouse-pod
                image: yandex/clickhouse-server:latest
                ports:
                  - name: http
                    containerPort: 8123
                  - name: tcp
                    containerPort: 9000
                  - name: interserver
                    containerPort: 9009
                  - name: ssh
                    containerPort: 22
                volumeMounts:
                  - name: azure
                    mountPath: /mnt/azure
            volumes:
              - name: azure
                azureFile:
                   secretName: azure-secret
                   shareName: datasourceforclickhouse
                   readOnly: false
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```

and my table output from one of the existed pod

```
chi-vizlib-dashboard-sharded-ch-test03-0-0-0.chi-vizlib-dashboard-sharded-ch-test03-0-0.ch-test03.svc.cluster.local :) select * from system.clusters

SELECT *
FROM system.clusters

┌─cluster───────────────────────────┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name──────────────────────────────────┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─estimated_recovery_time─┐
│ all-replicated                    │         1 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-0-0 │ 127.0.0.1    │ 9001 │        1 │ default │                  │            0 │                       0 │
│ all-replicated                    │         1 │            1 │           2 │ chi-vizlib-dashboard-sharded-ch-test03-1-0 │ 10.240.0.22  │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-replicated                    │         1 │            1 │           3 │ chi-vizlib-dashboard-sharded-ch-test03-2-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-replicated                    │         1 │            1 │           4 │ chi-vizlib-dashboard-sharded-ch-test03-3-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-replicated                    │         1 │            1 │           5 │ chi-vizlib-dashboard-sharded-ch-test03-4-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-replicated                    │         1 │            1 │           6 │ chi-vizlib-dashboard-sharded-ch-test03-5-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-sharded                       │         1 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-0-0 │ 127.0.0.1    │ 9001 │        1 │ default │                  │            0 │                       0 │
│ all-sharded                       │         2 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-1-0 │ 10.240.0.22  │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-sharded                       │         3 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-2-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-sharded                       │         4 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-3-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-sharded                       │         5 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-4-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ all-sharded                       │         6 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-5-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ ch-test03                         │         1 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-0-0 │ 127.0.0.1    │ 9001 │        1 │ default │                  │            0 │                       0 │
│ ch-test03                         │         2 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-1-0 │ 10.240.0.22  │ 9001 │        0 │ default │                  │            0 │                       0 │
│ ch-test03                         │         3 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-2-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ ch-test03                         │         4 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-3-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ ch-test03                         │         5 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-4-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ ch-test03                         │         6 │            1 │           1 │ chi-vizlib-dashboard-sharded-ch-test03-5-0 │              │ 9001 │        0 │ default │                  │            0 │                       0 │
│ test_cluster_two_shards           │         1 │            1 │           1 │ 127.0.0.1                                  │ 127.0.0.1    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_cluster_two_shards           │         2 │            1 │           1 │ 127.0.0.2                                  │ 127.0.0.2    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_cluster_two_shards_localhost │         1 │            1 │           1 │ localhost                                  │ 127.0.0.1    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_cluster_two_shards_localhost │         2 │            1 │           1 │ localhost                                  │ 127.0.0.1    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_shard_localhost              │         1 │            1 │           1 │ localhost                                  │ 127.0.0.1    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_shard_localhost_secure       │         1 │            1 │           1 │ localhost                                  │ 127.0.0.1    │ 9440 │        0 │ default │                  │            0 │                       0 │
│ test_unavailable_shard            │         1 │            1 │           1 │ localhost                                  │ 127.0.0.1    │ 9000 │        0 │ default │                  │            0 │                       0 │
│ test_unavailable_shard            │         2 │            1 │           1 │ localhost                                  │ 127.0.0.1    │    1 │        0 │ default │                  │            0 │                       0 │
└───────────────────────────────────┴───────────┴──────────────┴─────────────┴────────────────────────────────────────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────────────┘

26 rows in set. Elapsed: 0.055 sec. 

```

And after changing shard count my pod lists same before
```
kubectl get pods -n ch-test03
NAME                                           READY   STATUS    RESTARTS   AGE
chi-vizlib-dashboard-sharded-ch-test03-0-0-0   1/1     Running   0          16d
chi-vizlib-dashboard-sharded-ch-test03-1-0-0   1/1     Running   0          16d
```
