### ISSUE TITLE
How to add Kafka config in .spec.configuration 

### ISSUE THREAD

**Issue by ralfbecher** [Altinity/clickhouse-operator#352]
Hi,

I would like to add Kafka config on a deployed cluster. I already added a Kafka section in .spec.configuration with no effect.

What would be the right way to do?

**Comment by alex-zaitsev** [comment]
@ralfbecher, could you provide an example of what you are doing? 

Probably, the most convenient way is to use 'files' section of the configuration. See example here: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-02-dictionary.yaml

**Comment by ralfbecher** [comment]
@alex-zaitsev thx for quick answer!

I tried this according to documentation:
.spec.configuration.zookeeper refers to <yandex><zookeeper></zookeeper></yandex> config section

yaml example:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "dashboard-sharded"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoons
    clusters:
      - name: "dashboard03"
        templates:
          podTemplate: clickhouse-with-volume-template
        layout:
          shardsCount: 4
    kafka:
      sasl_mechanism: PLAIN
      security_protocol: SASL_SSL
      sasl_username: someuser
      sasl_password: somepassword
      debug: all
...
```

**Comment by alex-zaitsev** [comment]
No, it does not work this way. Kafka settings under the general section. So you can use it as:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "dashboard-sharded"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoons
    clusters:
      - name: "dashboard03"
        templates:
          podTemplate: clickhouse-with-volume-template
        layout:
          shardsCount: 4
    settings:
      kafka.sasl_mechanism: PLAIN
      kafka.security_protocol: SASL_SSL
      kafka.sasl_username: someuser
      kafka.sasl_password: somepassword
      kafka.debug: all
```

**Comment by ralfbecher** [comment]
@alex-zaitsev thanks! This created the right xml structure:
```
settings:
  kafka/sasl_mechanism: PLAIN
  kafka/security_protocol: SASL_SSL
  kafka/sasl_username: someuser
  kafka/sasl_password: somepassword
  kafka/debug: all
```
