### ISSUE TITLE
Customize macros using operator

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#355]
I want to customize some parameters in `macros`.
I tried to add a to the configuration:
```
configuration:
  macros:
    layer: 01
```
but it didn't work.
Can clickhouse-operator support this functionality?
The reason I need it was that I want to add replicas in k8s to the external original cluster.

**Comment by alex-zaitsev** [comment]
@winter7 , there is no special section, you can set it via settings:
```
spec:
  configuration:
    settings:
      macros/layer: "01"
```
