### ISSUE TITLE
Add cluster based on existing instances

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#362]
How to add clusters based on existing instances?
In my CRD:
```
   clusters:
      - name: clickhouse
        layout:
          shards:
            - name: shard0
              replicas:
                - name: replica0
                  port: 9000
                  templates:
                    podTemplate: replica-00
                - name: replica1
                  port: 9000
                  templates:
                    podTemplate: replica-01
            - name: shard1
              replicas:
                - name: replica0
                  port: 9000
                  templates:
                    podTemplate: replica-00
                - name: replica1
                  port: 9000
                  templates:
                    podTemplate: replica-01
```
and I got this `2 * 2` clickhouse cluster in `<remote_servers>` and `all-shards` & `all-replicas` clusters by default.
I want to create other clusters based on these 4 instances, for example, using different replica order.
Or, apply different settings (eg, replica order) on different replicas.
Have I made myself clear?

**Comment by sunsingerus** [comment]
>..and I got this 2 * 2 clickhouse cluster in <remote_servers> and all-shards & all-replicas clusters by default...

Yes, this is exactly behavior expected.

>...create other clusters based on these 4 instances...

It is very tangled task to describe multiple clusters over the same set of instances, so it is not directly supported by the operator. At least at the moment. May be sometime in the future, in case convenient way to describe `multiple-clusters overs the same set of instances` would be proposed, this can be reconciled. Additional `all-shards` and `all-replicas` clusters cover most needs so far.

However, there is a way to manually build any clusters configuration desired - via custom `<remote_servers>`. So feel free to construct additional `<remote_servers>` and place it as additional config file consumed by `ClickHouseInstallation`. Good example of how to introduce custom config files in available in examples, for [custom dictionary](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-02-dictionary.yaml) and general [overview example](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-01-overview.yaml)

**Comment by winter7** [comment]
Thanks! @sunsingerus 
Btw, can I just set it via settings?
```
spec:
  configuration:
    settings:
      remote_servers/new_cluster/shard/replica/host: "xx"
      remote_servers/new_cluster/shard/replica/port: "900"
```


And what's more next, can I apply different cluster settings on different replicas?
the reason I need it is that different replicas use different types of ebs, and in different available zones, I want each replica to be able to prioritize the shard of the same copy during load balancing, so that when all `load_balancing` configs are `in_order`, the replica order of `<remote_servers>` on different replicas needs to be different from each other.
