### ISSUE TITLE
unexpected spec replica=1 in statefulset

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#381]
I applied my cluster by
```
    clusters:
      - name: clickhouse
        layout:
          shards:
            {{- range $shardIndex := until (int .Values.shards) }}
            - name: shard{{$shardIndex}}
              replicas:
                - name: replica0
                  port: 9000
                  templates:
                    podTemplate: replica-00
                - name: replica1
                  port: 9000
                  templates:
                    podTemplate: replica-01
            {{- end }}
```
My `values.shards`=`6` and I got only 2 pod (replica0 and replica1).
And when I looked up to `statefulset.apps/chi-xxx-clickhouse-replica0`, I found
```
spec:
  replicas: 1
```
When I queried `select * from system.clusters` on one host and I could find other hosts' records.
But I only got 2 real clickhouse-server pods.
Why is that?

**Comment by alex-zaitsev** [comment]
Hi @winter7 ,

You need to change it as follows:
```
    clusters:
      - name: clickhouse
        layout:
          shards:
            {{- range $shardIndex := until (int .Values.shards) }}
            - name: shard{{$shardIndex}}
              replicas:
                - name: replica{{$shardIndex}}-0
                  port: 9000
                  templates:
                    podTemplate: replica-00
                - name: replica{{$shardIndex}}-1
                  port: 9000
                  templates:
                    podTemplate: replica-01
            {{- end }}
```

Replica name is unique across the cluster. It looks like a bug, and we will fix that, but for now you can use workaround above. Let me know if it works.
