### ISSUE TITLE
Authentication failed when clickhouse cluster is using with nginx ingress as TCP proxy

### ISSUE THREAD

**Issue by mr-yaky** [Altinity/clickhouse-operator#383]
Hi guys,

I played with this k8s operator and it's really nice! Thank you for the awesome work!
We want to make some benchmarks for our use cases for ClickHouse on Kubernetes with multiply replicas. We have only Kubernetes on Baremetal. Therefore, we can't use LoadBalancer type of service. 
So, I tried to use the CH cluster  behind nginx-ingress with TCP proxy feature but it doesn't work somehow. Also with NodePort it doesn't work for us.

The main problem always with authentication:

working example with connecting inside k8s cluster:
```
root@chi-test-replcluster-0-0-0:/# clickhouse-client -h clickhouse-test.playground.svc.cluster.local -u test --password password
ClickHouse client version 20.3.8.53 (official build).
Connecting to clickhouse-test.playground.svc.cluster.local:9000 as user test.
Connected to ClickHouse server version 20.3.8 revision 54433.
chi-test-replcluster-0-3-0.chi-test-replcluster-0-3.playground.svc.cluster.local :) Bye.
```
problem example with using nginx ingress and TCP proxy for 9000 port:
```
root@chi-test-replcluster-0-0-0:/# clickhouse-client -h ch-test.domain.com -u test --password password
ClickHouse client version 20.3.8.53 (official build).
Connecting to ch-test.domain.com:9000 as user test.
Code: 516. DB::Exception: Received from ch-test.domain.com:9000. DB::Exception: test: Authentication failed: password is incorrect or there is no user with such name.
```

I have tested with following cluster config:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test"
spec:
  configuration:
    users:
      test/password: password
      test/networks/ip:
        - "0.0.0.0"
        - "127.0.0.1"
    zookeeper:
      nodes:
        - host: zookeeper
    clusters:
      - name: replcluster
        templates:
          podTemplate: clickhouse-mem-limit
        layout:
          shardsCount: 1
          replicasCount: 4
  templates:
    podTemplates:
      - name: clickhouse-mem-limit
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:latest
              resources:
                requests:
                  memory: "12Gi"
                limits:
                  memory: "12Gi"

```
Also we have the same problem with authentication for CH rest api behind nginx-ingress (http) for using it with Tabix web UI. 

The working ways for us are only `kubectl port-forward` and connection inside k8s cluster. But we can't do our first benchmarks with this options. 
Is there any way to get it works with `NodePort` or behind nginx-ingress with using TCP proxy feature ? Or maybe any other ingress controllers which can be used for this ?
