### ISSUE TITLE
add ability to disable host_regexp in users config

### ISSUE THREAD

**Issue by nejtr0n** [Altinity/clickhouse-operator#399]
Operator create this host_regexp option for user by default.
So we could not connect to clickhouse server by custom service name.
For example:
```
                serviceTemplates:
                  - name: clickhouse-service-template
                    generateName: "{chi}"
                    spec:
                      ports:
                        - name: http
                          port: 8123
                        - name: tcp
                          port: 9000
                      type: ClusterIP
```
I've got this service fqdn: dev-clickhouse.dev-clickhouse-operator
And i could not connect to it.
