### ISSUE TITLE
Pod often restart,  Back-off restarting failed container

### ISSUE THREAD

**Issue by SalleryWang** [Altinity/clickhouse-operator#402]

**Comment by Slach** [comment]
could you provide more context?
- which Pod is restarts? 
- what is your kubernetes setup?
- did you run
kubectl describe <your pod>
and look at status ?

do you have enough memory in your kubernetes nodes?

**Comment by SalleryWang** [comment]
> could you provide more context?
> 
> * which Pod is restarting?
> * what is your kubernetes setup?
> * did you run
>   `kubectl describe --namespace your_namespace your_pod`
>   and look at status?
> * do you have enough memory in your kubernetes nodes?

![image](https://user-images.githubusercontent.com/45587738/82983796-6199f280-a023-11ea-95d2-62a7bb2f54eb.png)

**Comment by SalleryWang** [comment]
always oomkilled

**Comment by Slach** [comment]
how much free RAM do you have in your kubernetes worker nodes?

**Comment by SalleryWang** [comment]
the problem is running to oom，we don‘t write any data or any operation




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/27/2020 17:36, Eugene Klimov wrote:

how much free RAM do you have in your kubernetes worker nodes?

**Comment by Slach** [comment]
could you answer to my question?
- how much free RAM do you have in your kubernetes worker nodes?
- which pod killed by OOM? it's a clickhouse-operator pod or clickhouse-server pod?

**Comment by SalleryWang** [comment]
i dont see the free ram，clickhouse sever pod！




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/27/2020 21:37, Eugene Klimov wrote:

could you answer to my question?

how much free RAM do you have in your kubernetes worker nodes?
which pod killed by OOM? it's a clickhouse-operator pod or clickhouse-server pod?

**Comment by Slach** [comment]
which kubernetes provider doyou use?
AliCloud? AWS? Azure? Google Cloud?
or you run clickhouse-operator inside local kubernetes cluster?

**Comment by SalleryWang** [comment]
jdcloud




| |
ThanosWei
邮箱：ThanosWei@163.com
|

签名由 网易邮箱大师 定制

On 05/27/2020 21:51, Eugene Klimov wrote:

which kubernetes provider doyou use?
AliCloud? AWS? Azure? Google Cloud?
or you run clickhouse-operator inside local kubernetes cluster?

**Comment by Slach** [comment]
@SalleryWang could you run
`kubectl top nodes` ?

**Comment by alex-zaitsev** [comment]
@SalleryWang , are you restricting memory settings for ClickHouse? Not a pod memory, but ClickHouse itself. It is configured in profile settings, usually in default. E.g. these are typical settings for pod with 100Gi RAM:

```
    profiles:
      default/max_bytes_before_external_group_by: '51539607552'
      default/max_bytes_before_external_sort: '51539607552'
      default/max_memory_usage: '92771293593'
      default/max_memory_usage_for_all_queries: '92771293593'
      default/max_memory_usage_for_user: '92771293593'
```
