### ISSUE TITLE
User-specified shards-only clusters shard.internal_replication is true

### ISSUE THREAD

**Issue by yuzhichang** [Altinity/clickhouse-operator#421]
Applying following manifest
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: uat
spec:
  configuration:
    clusters:
      - name: cdp
        templates:
          podTemplate: clickhouse:20.4
        layout:
          shardsCount: 7
    settings:
      logger/level: debug
      query_log/flush_interval_milliseconds: 30000
      timezone: Asia/Shanghai
      max_table_size_to_drop: 0
      max_partition_size_to_drop: 0
    profiles:
      default/max_query_size: 1073741824
      default/distributed_aggregation_memory_efficient: 1
      default/max_bytes_before_external_group_by: 9000000000
      default/max_memory_usage: 20000000000
      default/max_memory_usage_for_all_queries: 24000000000
      default/joined_subquery_requires_alias: 0
      default/log_queries: 1
      default/log_query_threads: 0
    users:
      default/networks/host_regexp: '(chi-uat-[^.]+\d+-\d+|clickhouse\-uat|ck\-nodeport.*)\.uat\.svc\.cluster\.local$'
      cdp_user/networks/ip:
        - "::/0"
    zookeeper: 
      nodes:
        - host: zookeeper-0.zookeepers
          port: 2181
  templates:
    podTemplates:
      - name: clickhouse:20.4
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.4
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
              resources:
                requests:
                  memory: 28Gi
                  cpu: 12
                limits:
                  memory: 28Gi
                  cpu: 15
          nodeSelector:
            env: stg
          tolerations:
            - effect: NoSchedule
              key: stg
    volumeClaimTemplates:
      - name: data-storage-vc-template
        reclaimPolicy: Retain
        spec:
          storageClassName: csi-rbd-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2000Gi
      - name: log-storage-vc-template
        reclaimPolicy: Retain
        spec:
          storageClassName: csi-rbd-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

generates /etc/clickhouse-server/config.d/remote_servers.xml:

```
<yandex>
    <remote_servers>
        <!-- User-specified clusters -->
        <cdp>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-0-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-1-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-2-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-3-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-4-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-5-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-6-0</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cdp>
        <!-- Autogenerated clusters -->
        <all-replicated>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-uat-cdp-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-2-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-3-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-4-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-5-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-uat-cdp-6-0</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-replicated>
        <all-sharded>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-0-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-1-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-2-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-3-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-4-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-5-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chi-uat-cdp-6-0</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-sharded>
    </remote_servers>
</yandex>
```

The query
```
alter table cdp_mop_user_data on cluster cdp DROP PARTITION ID '20200604'
```
gets error:
```
DB::Exception: Received from 10.126.144.158:30900. DB::Exception: There was an error on [chi-uat-cdp-1-0:9000]: An error occurred before execution: Code: 371, e.displayText() = DB::Exception: Table `cdp_mop_user_data` isn't replicated, but shard #2 is replicated according to its cluster definition (version 20.4.4.18 (official build)). 
```

I expect user-specified shards-only clusters shard.internal_replication be `false`.
operator version: 0.9.9
