### ISSUE TITLE
How can I change hostAliases parameter?

### ISSUE THREAD

**Issue by chelsEg** [Altinity/clickhouse-operator#444]
I have problem with queries `on cluster`.

I found, this trouble because generated parameter **hostAliases** is something like this:
```
hostAliases:
      - hostnames:
        - chi-dmp-backend-clickhouse-dmp-0-1
        ip: 127.0.0.1
```
It's bad for Clickhouse `on cluster` queries...

How can I disable or remove this parameter?
