### ISSUE TITLE
Use labels to restrict pod to nodes

### ISSUE THREAD

**Issue by fiddlerwoaroof** [Altinity/clickhouse-operator#450]
Is there any quick way to create a clickhouse installation where the clickhouse pods are restricted to particular nodes based on labels?  I'd like to setup an EKS cluster with a nodegroup for clickhouse and another nodegroup for zookeeper and use labels to allocate the pods to the appropriate nodes, but I can't find any documentation about how to set this up.

Here's the relevant portions of my current manifest:

```apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "the-cluster-installation"
spec:
  configuration:
    clusters:
      - name: "main"
        layout:
          shards:
            - replicas:
              - templates:
                  podTemplate: clickhouse-az1
              - templates:
                  podTemplate: clickhouse-az2
            - replicas:
              - templates:
                  podTemplate: clickhouse-az1
              - templates:
                  podTemplate: clickhouse-az2
            - replicas:
              - templates:
                  podTemplate: clickhouse-az1
              - templates:
                  podTemplate: clickhouse-az2

  templates:
    podTemplates:
      - name: clickhouse-az1
        zone:
          values:
            - "us-west-2a"
        podDistribution:
          - type: ClickHouseAntiAffinity
      - name: clickhouse-az2
        zone:
          values:
            - "us-west-2b"
        podDistribution:
          - type: ClickHouseAntiAffinity
      - name: clickhouse-az3
        zone:
          values:
            - "us-west-2c"
        podDistribution:
          - type: ClickHouseAntiAffinity
```

**Comment by alex-zaitsev** [comment]
@fiddlerwoaroof , this looks correct. You may use full affinity/anti-affinity syntax in order to attach pod to the nodegroup:
```
    podTemplates:
      - name: clickhouse-az1
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "eks.amazonaws.com/nodegroup"
                        operator: In
                        values:
                          - "my-NG"
                      - key: "failure-domain.beta.kubernetes.io/zone"
                        operator: In
                        values:
                          - "us-west-2a"
```

**Comment by alex-zaitsev** [comment]
Another way is to use nodeSelector.
```
    podTemplates:
      - name: clickhouse-az1
         spec:
          nodeSelector:
            failure-domain.beta.kubernetes.io/zone: "us-west-2a"
```
