### ISSUE TITLE
Disable load balancer

### ISSUE THREAD

**Issue by petqa** [Altinity/clickhouse-operator#455]
Hello, I can't turn off the load balancer.
when I override one service the operator creates 2 services

```
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
chi-cluster-cluster-0-0   ClusterIP   None             <none>        8123/TCP,9000/TCP,9009/TCP   14m
clickhouse-cluster        ClusterIP   192.168.202.38   <none>        8123/TCP,9000/TCP,9009/TCP   14m
```

```
spec:
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: chi-service-template
  configuration:
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 1

  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: "clickhouse-{chi}"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None
```

operator version 0.10.0
kubernetes on aws
