### ISSUE TITLE
Host_regexp not allowing cluster-internal connections in EKS

### ISSUE THREAD

**Issue by mcgrawia** [Altinity/clickhouse-operator#469]
Hi,

I'm trying to connect to a clickhouseinstallation cluster with the default user and the following resource definition. I'm not sure if it matters, but I'm running this in an EKS cluster with operator `0.10.0`.

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test
  namespace: dev
spec:
  configuration:
    clusters:
      - layout:
          replicasCount: 1
          shardsCount: 1
        name: test
  defaults:
    podTemplate: pod-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - image: 'yandex/clickhouse-server:20.5.2.7'
              name: clickhouse
```

It seems like the `host_regexp` should allow for cluster-internal connections from the installation-level service. The `host_regexp` is set as: 

```xml
<yandex>
    <users>
        <default>
            <networks>
                <host_regexp>(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.dev\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
    </users>
</yandex>
```

It seems like I should be able to connect to the service at `clickhouse-test.dev.svc.cluster.local` but no matter how I try to connect from within Kubernetes, I get an access denied exception:

```
# clickhouse-client -h clickhouse-test.dev.svc.cluster.local
ClickHouse client version 20.5.2.7 (official build).
Connecting to clickhouse-test.dev.svc.cluster.local:9000 as user default.
Code: 516. DB::Exception: Received from clickhouse-test.dev.svc.cluster.local:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name.
```

```
# clickhouse-client -h clickhouse-test
ClickHouse client version 20.5.2.7 (official build).
Connecting to clickhouse-test:9000 as user default.
Code: 516. DB::Exception: Received from clickhouse-test:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name.
```

```
# clickhouse-client -h aaaeedf642d014c80aa6954469de75bd-1523752659.us-east-2.elb.amazonaws.com
ClickHouse client version 20.5.2.7 (official build).
Connecting to aaaeedf642d014c80aa6954469de75bd-1523752659.us-east-2.elb.amazonaws.com:9000 as user default.
Code: 516. DB::Exception: Received from aaaeedf642d014c80aa6954469de75bd-1523752659.us-east-2.elb.amazonaws.com:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name.
```

<strike>Additionally, it doesn't seem like the host-regexp `(chi-test-[^.]+\d+-\d+|clickhouse\-test)\.dev\.svc\.cluster\.local$` will match the replica hostnames because of `[^.]`. For example: `chi-test-test-0-0-0.chi-test-test-0-0.dev.svc.cluster.local`.</strike>

Edit: I realized the regex does match individual node hosts because it is not prefix-anchored, but still having trouble getting it to match the CHI service.

Thanks for the help
