### ISSUE TITLE
chi resource got 'created' but without anything in it!

### ISSUE THREAD

**Issue by gimpiron** [Altinity/clickhouse-operator#486]
Hey, so i have deployed my yml file and got:
![image](https://user-images.githubusercontent.com/60313280/89193706-0ea66380-d5af-11ea-991c-3e3d367bfd60.png)

and then i tried to check for the resource and got this:
![image](https://user-images.githubusercontent.com/60313280/89193652-f7677600-d5ae-11ea-8039-09ecf4451ce9.png)

How ever, i cant see any resources! no pods, no services and more importantly _no logs what so ever_, even with kubectl describe command.

I susspect my 'ch.ymlֿ  but cant verify since nothing gets at stdout;

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
---

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-rontest" #inject <env_name> here

spec:
  metadata:
    name: "ron-chi-cluster"
    labels:
      app: clickhouse
      environmnet_version: prod
      aws_environment_account: dev
      environment_name: ron
      aws_region: us-east-1
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: chi-service-template
      dataVolumeClaimTemplate: clickhouse-data
      logVolumeClaimTemplate: clickhouse-logs
  configuration:
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 2

  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: "ch-service" #metadata.name
        spec:
          type: NodePort
          ports:
            - name: http
              port: 8123
              targetPort: 8123
              nodePort: 30123
            - name: tcp
              port: 9000
              targetPort: 9000
              nodePort: 30900
            - name: internal
              port: 9009
              targetPort: 9009
              targetPort: 30009

    podTemplates:
      - name: pod-template
        spec:
          containers:
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "500m"
    volumeClaimTemplates:
      - name: clickhouse-data
        spec:
          storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      - name: clickhouse-logs
        storageClassName: gp2-resizable
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

Can some one see my problem that i cant see? 
If needed, this is **kubectl describe chi/clickhouse-rontest** output:
```
Name:         clickhouse-rontest
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"clickhouse.altinity.com/v1","kind":"ClickHouseInstallation","metadata":{"annotations":{},"name":"clickhouse-rontest","names...
API Version:  clickhouse.altinity.com/v1
Kind:         ClickHouseInstallation
Metadata:
  Creation Timestamp:  2020-08-03T13:32:41Z
  Generation:          1
  Resource Version:    929482
  Self Link:           /apis/clickhouse.altinity.com/v1/namespaces/default/clickhouseinstallations/clickhouse-rontest
  UID:                 ce58ca52-d58d-11ea-8f3a-025476f88afd
Spec:
  Configuration:
    Clusters:
      Layout:
        Replicas Count:  2
        Shards Count:    1
      Name:              clickhouse
  Defaults:
    Templates:
      Data Volume Claim Template:  clickhouse-data
      Log Volume Claim Template:   clickhouse-logs
      Pod Template:                pod-template
      Service Template:            chi-service-template
  Metadata:
    Labels:
      App:                      clickhouse
      aws_environment_account:  dev
      aws_region:               us-east-1
      environment_name:         ron
      environmnet_version:      prod
    Name:                       ron-chi-cluster
  Templates:
    Pod Templates:
      Name:  pod-template
      Spec:
        Containers:
          Resources:
            Limits:
              Cpu:     500m
              Memory:  512Mi
            Requests:
              Cpu:     500m
              Memory:  512Mi
    Service Templates:
      Generate Name:  ch-service
      Name:           chi-service-template
      Spec:
        Ports:
          Name:         http
          Node Port:    30123
          Port:         8123
          Target Port:  8123
          Name:         tcp
          Node Port:    30900
          Port:         9000
          Target Port:  9000
          Name:         internal
          Port:         9009
          Target Port:  30009
        Type:           NodePort
    Volume Claim Templates:
      Name:  clickhouse-data
      Spec:
        Access Modes:
          ReadWriteOnce
        Resources:
          Requests:
            Storage:         2Gi
        Storage Class Name:  gp2-resizable
      Name:                  clickhouse-logs
      Spec:
        Access Modes:
          ReadWriteOnce
        Resources:
          Requests:
            Storage:       1Gi
      Storage Class Name:  gp2-resizable
Events:                    <none>
```
