### ISSUE TITLE
Feature Request: metadata in podTemplates

### ISSUE THREAD

**Issue by slimtom95** [Altinity/clickhouse-operator#554]
Our network plugin needs a specific annotation in pod to support reserved ip. It would be very helpful if we support metadata field in podTemplates.

```
podTemplates:
          - name: mypod
            metadata:
              annotations:
                reserveIP: "true"
            spec:
```
