### ISSUE TITLE
Resources not cleaned up

### ISSUE THREAD

**Issue by incognick** [Altinity/clickhouse-operator#56]
I'm having difficulty using the operator.  The first thing I notice is that resources are not cleaned up even when I delete the ClickHouseInstallation. The main problem I'm having is setting up a cluster with a specific disk size and a specific docker image. 

Here is my resource:  

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: dev
  namespace: timeseries
spec:
  defaults:
    deployment:
      podTemplate: clickhouse-v19.4.3.11
      volumeClaimTemplate: default
  templates:
    volumeClaimTemplates:
    - name: default
      persistentVolumeClaim:
        metadata:
          name: USE_DEFAULT_NAME
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    podTemplates:
    - name: clickhouse-v19.4.3.11
      containers:
      - name: clickhouse
        volumeMounts:
        - name: default
          mountPath: /var/lib/clickhouse
        image: yandex/clickhouse-server:19.4.3.11
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2
  configuration:
    zookeeper:
      nodes:
        - host: ts-zoo0
          port: 2181
        - host: ts-zoo1
          port: 2181
        - host: ts-zoo2
          port: 2181
    clusters:
    - name: ts1
      layout:
        type: Standard
        shardsCount: 1
        replicasCount: 1

```

The pod fails to start with the error:  

```
create Pod chi-1de443-1579-0-0-0 in StatefulSet chi-1de443-1579-0-0 failed error: Pod "chi-1de443-1579-0-0-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "clickhouse-data-test", spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/var/lib/clickhouse": must be unique]
```

Checking the statefulset, there are in fact two conflicting mount paths:  

```
Mounts:
      /etc/clickhouse-server/conf.d/ from chi-1de443-deploy-confd-1579-0-0 (rw)
      /etc/clickhouse-server/config.d/ from chi-1de443-common-configd (rw)
      /etc/clickhouse-server/users.d/ from chi-1de443-common-usersd (rw)
      /var/lib/clickhouse from clickhouse-data-test (rw)
      /var/lib/clickhouse from clickhouse-data (rw)
```

Not sure why there are two mounts there.

**Comment by hodgesrm** [comment]
@incognick thanks for the bug report including the complete description.  We'll try to reproduce and get back to you.

**Comment by incognick** [comment]
Thanks for the quick response, let me know if I can help with anything and thanks for providing the operator. These are definitely a lot of work!

**Comment by incognick** [comment]
@hodgesrm I resolved the issue by commenting out the `volumeMounts` section:

```yaml
podTemplates:
    - name: clickhouse-v19.4.3.11
      containers:
      - name: clickhouse
        # volumeMounts:
        # - name: default
        #   mountPath: /var/lib/clickhouse
        image: yandex/clickhouse-server:19.4.3.11
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2
```

What does `USE_DEFAULT_NAME` do in the PVC?

**Comment by sunsingerus** [comment]
@incognick thanks for the report!
>The first thing I notice is that resources are not cleaned up even when I delete the ClickHouseInstallation.

Can you please explain how exactly do you install the operator? I am asking this because there really is a known issue with operator not deleting resources upon `ClickHouseInstallation` object being deleted. However, we hope it is fixed with `0.2beta` version which is currently being prepared for release. See `release-0.2beta` branch. Also what resources are not being deleted? Can you, please, provide more details, if possible?

Regarding `yaml` manifest.
I'd suggest either to:
1. delete/comment `volumeMounts` section (as you already did) or
1. modify `yaml` as following:
```yaml
  templates:
    volumeClaimTemplates:
    - name: default-volume-claim-template
      persistentVolumeClaim:
        metadata:
          name: default-pvc
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    podTemplates:
    - name: clickhouse-v19.4.3.11
      containers:
      - name: clickhouse
        volumeMounts:
        - name: default-pvc
          mountPath: /var/lib/clickhouse
        image: yandex/clickhouse-server:19.4.3.11
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2
```

**Comment by incognick** [comment]
I used the command from the Quick Start Guide:  

`kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/manifests/operator/clickhouse-operator-install.yaml`

After deleting the `ClickHouseInstallation` resource, the following resources were left: 

```
ConfigMap
StatefulSet
Services
```

This might have been due to the fact that the statefulset was in an error state and was never "running".  I have not tried to delete the resource once the cluster is running properly.

**Comment by sunsingerus** [comment]
`volumeClaimTemplates` is a little vague at the moment, and, actually, we are thinking about simplification over this, but at the moment logic is the following (it still may be changed):
 - `deployment` specified what `podTemplate`s and `volumeClaimTemplate`s are bundled - a.k.a go together. So having:
```yaml
    deployment:
      podTemplate: clickhouse-v19.4.3.11
      volumeClaimTemplate: default-volume-claim-template
```
we specify that `podTemplate: clickhouse-v19.4.3.11` can access volumes specified in `volumeClaimTemplate: default-volume-claim-template`
 - So, having in `podTemplate`
```yaml
        volumeMounts:
        - name: default-pvc
          mountPath: /var/lib/clickhouse
```
this means: look for `persistentVolumeClaim` with
```yaml
        metadata:
          name: default-pvc
```
but (taking into account `deployment` bundling) only within
```yaml
volumeClaimTemplates:
    - name: default-volume-claim-template
```

**Comment by sunsingerus** [comment]
As to **USE_DEFAULT_NAME**. It is some kind of a shortcut and work like the following:
In case you omit in `podTempates.containers` any `volumeMounts`, operator will silently introduce one `volumeMount` to container. And this `volumeMount` would reference `volumeClaimTemplate` with
```yaml
        metadata:
          name: USE_DEFAULT_NAME
```
So, minimal example would be like:
```yaml
spec:
  defaults:
    deployment:
      volumeClaimTemplate: default
  configuration:
    clusters:
      - name: "sharded-non-replicated"
        layout:
          type: Standard
          shardsCount: 3
  templates:
    volumeClaimTemplates:
    - name: default
      persistentVolumeClaim:
        metadata:
          name: USE_DEFAULT_NAME
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
```
Take into account - no `podTemplate` specified at all (meaning would be created default internally by operator) and this internal template would use specified `volumeClaimTemplate`
