### ISSUE TITLE
New replicas start accepting traffic before data/tables are created

### ISSUE THREAD

**Issue by mcgrawia** [Altinity/clickhouse-operator#561]
When increasing the replicas of an existing cluster, the new replicas are opened to traffic before the replicated tables and data are found on the node.

Steps to reproduce using docker-for-mac Kubernetes:

1. Apply a single replica CH installation with Zookeeper settings (setup zookeeper first):
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test-scaling
spec:
  configuration:
    users:
      default/networks/ip: ::/0
    clusters:
      - name: test-scaling
        layout:
          shardsCount: 1
          replicasCount: 1
    zookeeper:
      nodes:
        - host: scaling-clickhouse-zookeeper
          port: 2181
```

2. Start some load on the cluster service:
```bash
while [ 1 -eq 1 ]
      do echo 'select count() from test_scaling' | curl 'http://localhost:8123/' --data-binary @- >> out.txt ; sleep 0.5
      done
```

3. Write some data to the single replica
```sql
CREATE TABLE test_scaling (num UInt32)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test_scaling', '{replica}') ORDER BY tuple();

insert into test_scaling
select * from system.numbers
limit 100000000;
```

4. Apply yaml update to increase replicas to 2:
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test-scaling
spec:
  configuration:
    users:
      default/networks/ip: ::/0
    clusters:
      - name: test-scaling
        layout:
          shardsCount: 1
          replicasCount: 2
    zookeeper:
      nodes:
        - host: scaling-clickhouse-zookeeper
          port: 2181
```

5. View output:
```bash
cat out.txt
```

Results:
```bash
# section where initial table did not exist yet
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
...
# section where table was created and populated with one replica
0
0
0
0
0
0
0
9436905
29359260
51378705
75495240
100000000
100000000
100000000
100000000
...
100000000
100000000
100000000
100000000
100000000
100000000
# second replica came online and started serving traffic before all the tables and data were copied. 
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
100000000
100000000
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
Code: 60, e.displayText() = DB::Exception: Table default.test_scaling doesn't exist. (version 20.9.2.20 (official build))
100000000
0
9825130
26601850
100000000
100000000
100000000
100000000
100000000
100000000
100000000
100000000
```

This is an example with a single table and small data set but this problem causes significant outages for us when adding a replica.
