### ISSUE TITLE
Operator does not copy SQL users when adding replicas

### ISSUE THREAD

**Issue by mcgrawia** [Altinity/clickhouse-operator#562]
When increasing the replicas of an existing cluster, the new replicas are missing users created via SQL access management on the previous cluster replicas.

Steps to reproduce using docker-for-mac Kubernetes:

1. Apply a single replica CH installation with Zookeeper settings (setup zookeeper first):
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test-user
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    users:
      default/networks/ip: ::/0
      default/access_management: '1'
    clusters:
      - name: test-user
        layout:
          shardsCount: 1
          replicasCount: 1
    zookeeper:
      nodes:
        - host: scaling-clickhouse-zookeeper
          port: 2181
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: "yandex/clickhouse-server:20.9.2.20"
```

2. Create a sample user on the cluster:
```sql
CREATE ROLE IF NOT EXISTS test_role ON CLUSTER '{cluster}';
GRANT SELECT ON default.* TO test_role ON CLUSTER '{cluster}';
GRANT SHOW ON default.* TO test_role ON CLUSTER '{cluster}';
CREATE USER IF NOT EXISTS test_user ON CLUSTER '{cluster}' IDENTIFIED WITH SHA256_HASH BY '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8'  DEFAULT ROLE test_role;
show users;
```

Result of show users:
```bash
clickhouse_operator
default
test_user
```

3. Add another replica with a yaml update:
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test-user
spec:
  defaults:
    templates:
      podTemplate: pod-template
  configuration:
    users:
      default/networks/ip: ::/0
      default/access_management: '1'
    clusters:
      - name: test-user
        layout:
          shardsCount: 1
          replicasCount: 2
    zookeeper:
      nodes:
        - host: scaling-clickhouse-zookeeper
          port: 2181
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: "yandex/clickhouse-server:20.9.2.20"
```

4. Query for users (run multiple times):
```bash
echo 'show users' | curl 'http://localhost:8123/' --data-binary @-
```

Results:
```bash
# First replica result
clickhouse_operator
default
test_user
# Second replica result
clickhouse_operator
default
```

Also if you try to query CH using the sql managed user, some queries will fail when they hit the second replica:
```
# First replica result
echo "show tables" | curl "http://test_user:password@localhost:8123/" --data-binary @-

# Second replica result
echo "show tables" | curl "http://test_user:password@localhost:8123/" --data-binary @-
Code: 516, e.displayText() = DB::Exception: test_user: Authentication failed: password is incorrect or there is no user with such name (version 20.9.2.20 (official build))
```
