### ISSUE TITLE
Can't apply tolerations to podTemplate

### ISSUE THREAD

**Issue by mohamedelbahr** [Altinity/clickhouse-operator#583]
I need to add tolerations to the created statefulsets of the cluster, can you guide me through the syntax?
My installation file contains podTemplate follows
```
    podTemplates:
      - name: analytics-pod
        zone:
          key: "lifecycle"
          values:
            - "primitive"
        podDistribution:
          - type: ShardAntiAffinity
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "clickhouse"
            effect: "NoSchedule"
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:19.11.3.11
              resources:
                requests:
                  memory: "300Mi"
                  cpu: "100m"
                limits:
                  memory: "500Mi"
                  cpu: "150m"
```

**Comment by alex-zaitsev** [comment]
@mohamedelbahr , tolerations should be a part of podTemplates.[].spec. Here is an example from working app:

```
  templates:
    podTemplates:
      - name: clickhouse-replica-1
        podDistribution:
          - scope: ClickHouseInstallation
            type: ClickHouseAntiAffinity
        spec:
          containers:
            - image: 'yandex/clickhouse-server:20.8.7.15'
              name: clickhouse-pod
              resources:
                limits:
                  cpu: '2'
                  memory: 6700Mi
                requests:
                  cpu: '1'
                  memory: 6700Mi
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: default
          nodeSelector:
            beta.kubernetes.io/instance-type: m5.large
          tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: clickhouse
        zone:
          values:
            - us-east-1a
```
