### ISSUE TITLE
Grant or revoke privileges in CHI

### ISSUE THREAD

**Issue by winter7** [Altinity/clickhouse-operator#588]
I configured this in my `chi.yaml` code:
```
spec:
  configuration:
    users:
      admin/access_management: 1
```
And I logged on my CHI client and executed:
```
REVOKE SELECT ON my_table FROM john
```
Then I got:
```
Code: 495. DB::Exception: Received from localhost:9000. DB::Exception: Cannot update User `john` in users.xml because this storage is readonly. (version 20.4.4.18 (official build))
```
It seems that users cannot manage access privilege in an operator-created ClickHouseInstallation because config files are all readonly. Do you have any idea how I should manage user access in CHI? 
Since it has something to do with `users.xml`, what exactly should be configured in `users.xml` if I want to grant or revoke a user's privilege? I can set it from the beginning.

**Comment by alex-zaitsev** [comment]
Priveleges currently do not work due to readonly config files. This is in our todo list to fix (on ClickHouse or operator side)

**Comment by petergvizd-s1** [comment]
@winter7 you can still set up privileges via
```
    users:
      test/grants/query: GRANT SELECT ON test.*
      test/profile: default
      test/quota: default
```

if you do not need to run GRANT/REVOKE queries on fly
