### ISSUE TITLE
CircularReplication with 3 shard / 2 replicas on a 3 node cluster

### ISSUE THREAD

**Issue by kushagra391** [Altinity/clickhouse-operator#589]
Hi, 

Can we set `CircularReplication` on a 3 node k8-cluster, with 3 shards and 2 replicas ? 
similar to https://altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

<img width="663" alt="Screen Shot 2020-11-08 at 9 56 24 PM" src="https://user-images.githubusercontent.com/8533562/98505085-44da2b80-220d-11eb-9e39-5c1a0ca811d5.png">

Am trying with, 

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "circular"
spec:
  defaults:
    templates:
      podTemplate: dist-template
  configuration:
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 3
          replicasCount: 2
  templates:
    podTemplates:
      - name: dist-template
        podDistribution:
          - type: CircularReplication
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.7.2.30
```

All pods except `chi-circular-cluster-1-1-0` get attached,  1-1-0 gets stuck with,  
```
Warning  FailedScheduling  <unknown>  default-scheduler  
0/4 nodes are available: 
1 node(s) didn't match pod affinity rules, 
1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 
2 node(s) didn't satisfy existing pods anti-affinity rules, 3 node(s) didn't match pod affinity/anti-affinity.
```

It does work if i use 3 shards and 3 replicas, but not for 2 replicas

Details
- operator v0.12
- AWS EKS / Kind: v0.18

Thanks !

**Comment by Slach** [comment]
@kushagra391 do you have k8s cluster with 1 master + 3 worker nodes? or 1 master + 2 workers?

**Comment by kushagra391** [comment]
i tested both on 
- kind: 1 master and 3 nodes
- AWS EKS: 1 master with 12 nodes

on EKS am getting, 

```
Warning  FailedScheduling  11s   default-scheduler  
0/12 nodes are available: 
10 node(s) didn't match pod affinity rules, 
12 node(s) didn't match pod affinity/anti-affinity, 
2 node(s) didn't satisfy existing pods anti-affinity rules.
```

and similar to kind, 3 * 3 setup works in EKS as well.

**Comment by Slach** [comment]
could you share
`kubectl get sts -n <your_namespace> chi-circular-cluster-0-1 -o yaml`
`kubectl get sts -n <your_namespace> chi-circular-cluster-0-1 -o yaml`
`kubectl get sts -n <your_namespace> chi-circular-cluster-1-1 -o yaml`
?

clickhouse-operator doesn't schedule `stateful set` itself, it just translates `Kind: ClickHouseInstallation` affinity rules to standart kubernetes pod affinity/anti-affinity rules via kube-scheduler and controller-manager

**Comment by Slach** [comment]
@kushagra391
also let's try another combination of pod distributions in ClickHouseInstallation
```
    podDistribution:
          - type: ShardAntiAffinity
          - type: ReplicaAntiAffinity
          - type: ClickHouseInstallationAffinity
          - type: PreviousTailAffinity
```

**Comment by kushagra391** [comment]
@Slach sure, i pasted all 3 outputs into https://gist.github.com/kushagra391/a1f16c7d7fc1ca852cc379f454bba719

am using [kind](https://kind.sigs.k8s.io/), hopefully you can recreate this setup, 

```
kind create cluster --config cluster-config.yaml
```
```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.12.0/deploy/operator/clickhouse-operator-install.yaml
kubectl create ns clickhouse
kubectl -n clickhouse apply -f clickhouse_config.yaml
```

--- 

with the other set of combination ShardAntiAffinity / ReplicaAntiAffinity / ...
chi-circular-cluster-2-1-0 is getting stuck. 
```
kubectl -n clickhouse2 get pods -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE           NOMINATED NODE   READINESS GATES
chi-circular-cluster-0-0-0   1/1     Running   0          77s   10.244.3.102   kind-worker3   <none>           <none>
chi-circular-cluster-0-1-0   1/1     Running   0          71s   10.244.1.103   kind-worker    <none>           <none>
chi-circular-cluster-1-0-0   1/1     Running   0          65s   10.244.1.105   kind-worker    <none>           <none>
chi-circular-cluster-1-1-0   1/1     Running   0          55s   10.244.3.104   kind-worker3   <none>           <none>
chi-circular-cluster-2-0-0   1/1     Running   0          44s   10.244.2.65    kind-worker2   <none>           <none>
chi-circular-cluster-2-1-0   0/1     Pending   0          31s   <none>         <none>         <none>           <none>
```

**Comment by Slach** [comment]
@kushagra391 did you try to change podDistribution: ?

**Comment by kushagra391** [comment]
i tried, 

```
- type: ShardAntiAffinity
          - type: ReplicaAntiAffinity
          - type: PreviousTailAffinit

**Comment by kushagra391** [comment]
as a workaround, this is working. 
I guess, this is close enough :) 
```
        podDistribution:
          - type: ShardAntiAffinity
          - type: ReplicaAntiAffinity
          - type: MaxNumberPerNode
            number: 2
```
```
kubectl -n cht get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
chi-rollworks-test-0-0-0   1/1     Running   0          51s   10.244.2.75   kind-worker3   <none>           <none>
chi-rollworks-test-0-1-0   1/1     Running   0          40s   10.244.1.75   kind-worker    <none>           <none>
chi-rollworks-test-1-0-0   1/1     Running   0          29s   10.244.2.62   kind-worker2   <none>           <none>
chi-rollworks-test-1-1-0   1/1     Running   0          23s   10.244.2.77   kind-worker3   <none>           <none>
chi-rollworks-test-2-0-0   1/1     Running   0          18s   10.244.1.77   kind-worker    <none>           <none>
chi-rollworks-test-2-1-0   1/1     Running   0          7s    10.244.2.64   kind-worker2   <none>           <none>
```
