### ISSUE TITLE
Clickhouse Cluster not running with Restricted Pod security policy

### ISSUE THREAD

**Issue by jatinder91** [Altinity/clickhouse-operator#600]
I was trying to run clickhouse containers as non root. However, its not working. I am using below template to bring up the cluster.
### ClickHouse distributiion installation template

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: distributed
spec:
  defaults:
    templates:
      podTemplate: dist-template
  configuration:
    zookeeper:
      nodes:
        - host: zk-01.cloud.in.example.com
          port: 2181
        - host: zk-01.cloud.in.example.com
          port: 2181
        - host: zk-02.cloud.in.example.com
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
    clusters:
      - name: distributed
        layout:
          shardsCount: 1
          replicasCount: 3
  templates:
    podTemplates:
      - name: dist-template
        podDistribution:
          - type: ShardAntiAffinity
          - type: ReplicaAntiAffinity
          - type: MaxNumberPerNode
            number: 1
          - type: NamespaceAffinity
          - type: ClickHouseInstallationAffinity
          - type: ClusterAffinity
          - type: PreviousTailAffinity
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:19.16
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
```

### Restricted PSP
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

### Error 

```
kubectl get pods -n clickhouse-operator -o wide
NAME                                   READY   STATUS    RESTARTS   AGE   IP               NODE                NOMINATED NODE   READINESS GATES
chi-distributed-distributed-0-0-0      0/1     Error     2          24s   10.244.123.181   clickhouse-infra-03   <none>           <none>
clickhouse-operator-766b6b8947-2rmcn   2/2     Running   0          11d   10.244.248.214   clickhouse-infra-01   <none>           <none>

# kubectl logs -f chi-distributed-distributed-0-0-0 -n clickhouse-operator
Necessary directory '/var/lib/clickhouse/' isn't owned by user with id '1000'
```

### Expected Result
Clickhouse cluster should be able to run in secured Kubernetes cluster.

**Comment by mcgrawia** [comment]
Hi operator team, my team and I are also running into this issue using ClickHouse for a customer that does not allow containers to run as root. I see in this issue that was filed in May, it seems to be working: https://github.com/Altinity/clickhouse-operator/issues/691

But I am still facing the same issue described here. Does anyone know the current status of this? Or what issue https://github.com/Altinity/clickhouse-operator/issues/691 did to get it to work successfully?

thanks

**Comment by mcgrawia** [comment]
Update. It looks like this issue comes up when mounting a PVC at `/var/lib/clickhouse` and `/var/log/clickhouse-server`. Even with fsGroup set to 101, the filesystem still has root as the owner:
```
ls -la /var/lib
drwxrwsr-x 3 root clickhouse   4096 Aug 24 13:10 clickhouse-server
```

This fails the ClickHouse start script check:
```bash
    elif [ "$(stat -c %u "$dir")" != "$USER" ]; then
        echo "Necessary directory '$dir' isn't owned by user with id '$USER'"
        exit 1
    fi
```

To get around this, you can nest the ClickHouse data and log directories inside the root of the PVC. ClickHouse will create them since they do not exist, and then they will be owned by the CH user.
```yaml
settings:
      path: /var/lib/clickhouse/data/
      logger/log: /var/log/clickhouse-server/log/clickhouse-server.log
      logger/errorlog: /var/log/clickhouse-server/log/clickhouse-server.err.log
```
