### ISSUE TITLE
Clusters doesn't apply new VolumeClaimTemplate

### ISSUE THREAD

**Issue by aksenk** [Altinity/clickhouse-operator#601]
I have one clickhouse installation with following config (cropped for simplicity):

```
defaults:
  templates:
    dataVolumeClaimTemplate: data-claim-template
    logVolumeClaimTemplate: log-claim-template
    serviceTemplate: service-template
    clusterServiceTemplate: cluster-service-template

configuration:
  clusters:
    - name: cluster-01
      layout:
        shardsCount: 1
        replicasCount: 1
      templates:
        podTemplate: clickhouse-20.5.4.40

templates:
  volumeClaimTemplates:
    - name: data-claim-template
      spec:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
    - name: log-claim-template
      spec:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
```

Now I want to add new cluster with another volumeClaimTemplates.

I change my configuration (add new volumeClaimTemplates and second cluster with this new template):

```
defaults:
  templates:
    dataVolumeClaimTemplate: data-claim-template
    logVolumeClaimTemplate: log-claim-template
    serviceTemplate: service-template
    clusterServiceTemplate: cluster-service-template

configuration:
  clusters:
    - name: cluster-01
      layout:
        shardsCount: 1
        replicasCount: 1
      templates:
        podTemplate: clickhouse-20.5.4.40
    - name: cluster-02
      layout:
        shardsCount: 1
        replicasCount: 1
      templates:
        podTemplate: clickhouse-20.5.4.40
        dataVolumeClaimTemplate: data-claim-template-300gb

templates:
  volumeClaimTemplates:
    - name: data-claim-template
      spec:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
    - name: data-claim-template-300gb
      spec:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
    - name: log-claim-template
      spec:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
```

### Result

New cluster still use old VolumeClaimTemplate (data-claim-template specified in default section)

### Expected Result

New cluster use new VolumeClaimTemplate (data-claim-template-300gb)
