### ISSUE TITLE
how do I set imagePullSecrets for statefulsets?

### ISSUE THREAD

**Issue by rusenask** [Altinity/clickhouse-operator#614]
Hi, thanks for the operator! How can I set the imagePullSecrets for the statefulsets?

**Comment by sunsingerus** [comment]
You can set `imagePullSecrets` via a `podTemplate` in your CHI spec. The operator passes the full pod spec through, so any standard Kubernetes pod field is supported:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: example
spec:
  templates:
    podTemplates:
      - name: with-pull-secret
        spec:
          imagePullSecrets:
            - name: my-registry-secret
          containers:
            - name: clickhouse
              image: my-private-registry/clickhouse-server:24.3
  configuration:
    clusters:
      - name: default
        templates:
          podTemplate: with-pull-secret
        layout:
          shardsCount: 1
          replicasCount: 1
```

The secret itself must be a `kubernetes.io/dockerconfigjson` type and exist in the same namespace as the CHI. See the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) for how to create it.

More pod template examples can be found in [`chi-examples/`](https://github.com/Altinity/clickhouse-operator/tree/master/docs/chi-examples) in the repository.
