### ISSUE TITLE
after reducing the shards from 2 to 1, operator terminated the wrong statefulset

### ISSUE THREAD

**Issue by rusenask** [Altinity/clickhouse-operator#615]
I might just be misunderstanding something regarding the config changes and what's supported/not supported by design. Please ignore if it's not supposed to work.  

I tried initially with two shards:

```
kubectl get sts
NAME                           READY   AGE
chi-clickhouse-pv-shards-0-0   1/1     14m
chi-clickhouse-pv-shards-1-0   0/1     9m58s
```

(second sts was stuck with image pull errors)

Decided to try updating the CR shards from 2 to 1:

```
kubectl get pods
NAME                                   READY   STATUS             RESTARTS   AGE
chi-clickhouse-pv-shards-0-0-0         2/2     Terminating        0          13m
chi-clickhouse-pv-shards-1-0-0         0/2     ImagePullBackOff   0          2m52s
clickhouse-operator-57b86784d5-ptjgl   2/2     Running            0          36m
```

Operator, instead of terminating the second statefulset which was already failing, removed the first one.

**Comment by Slach** [comment]
@rusenask could help us and describe steps to reproduce behavior?
1) do you successfully create clusters with 2 shards x 1 replica in each shard?
2) do you tried to change the image on `1-0` shard with wrong image name? how exactly?
3) do you change `kind: ClickHouseInstallation` manifest to decrease shard numbers, how exactly? just change shardCount in layout? or something else way?

could you share YAML manifests with `kind: ClickHouseInstallation` for 3 states
1) before any manipulation 
2) manifest which come to status ImagePullBackOff (with changed image name?)
3) manifest with changed cluster state from 2 shards to 1 shard

**Comment by rusenask** [comment]
1. I went for 2 shards only, no replicas specified
2. it wasn't the image name issue, it was dockerhub pull rate limits. I have manually updated statefulset to include imagePullSecrets as I couldn't find it in the CRD.
3. I have the CR file, I just do `kubectl apply -f <filename>` after the changes.

--- 

1. Before:

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-pv"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: ch-volume-template
      logVolumeClaimTemplate: ch-volume-template
  configuration:
    clusters:
      - name: "shards"
        layout:
          shardsCount: 2
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          imagePullSecrets:
           - name: dockerio-registry
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.8.7
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
    volumeClaimTemplates:
      - name: ch-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
```

2. It couldn't start the first shard, had to update statefulset. After updating the first one, it successfully started and the second one appeared. Didn't want to update manually statefulset again, so I updated the CR to have only 1 shard.

3. Updating to 1 shard:

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-pv"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: ch-volume-template
      logVolumeClaimTemplate: ch-volume-template
  configuration:
    clusters:
      - name: "shards"
        layout:
          shardsCount: 1
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          imagePullSecrets:
           - name: dockerio-registry
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.8.7
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
    volumeClaimTemplates:
      - name: ch-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

```
