### ISSUE TITLE
operator  whether to support easy configuration ssl

### ISSUE THREAD

**Issue by Sallery-X** [Altinity/clickhouse-operator#629]

**Comment by Slach** [comment]
@Sallery-X could you explain what exactly do you mean?

currently, clickhouse-operator already supports easy SSL configuration 
you can generate certificates via openssl
```
openssl dhparam -out dhparam.pem 4096

openssl req -nodes -newkey rsa:2048 -keyout node.key -out node.csr -subj "/C=YOUR_COUNTRY/O=YOUR_ORGANIZATION_NAME/OU=YOUR_ORGANIZATION_UNIT/CN=kubernetes-clickhouse"

openssl x509 -req -sha256 -days 365 -in node.csr -signkey node.key -out node.crt
```

and you can use ClickHouseInstallation custom resource with the following content:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: your_ssl_test
spec:
  configuration:
    clusters:
    - name: test
      layout:
        shardsCount: 1
        replicasCount: 2 
      
  defaults:
    templates:
      serviceTemplate: loadbalancer-with-ssl-service-template
  templates:
    serviceTemplates:
    - name: loadbalancer-with-ssl-service-template
      generateName: clickhouse-ssl-{chi}
      spec:
        ports:
        - name: https
          port: 8443
        - name: secureclient
          port: 9440
        type: LoadBalancer
        
    files:
      dhparam.pem: |
        ### .... CONTENT GENERATED BY OPENSSL FOR dhparam.pem ... ###
      node.crt: |
        ### .... CONTENT GENERATED BY OPENSSL FOR node.crt... ###
      node.key: |
        ### .... CONTENT GENERATED BY OPENSSL FOR node.key... ###
      ssl.xml: |
        <yandex>
          <https_port>8443</https_port>
          <tcp_port_secure>9440</tcp_port_secure>
          <openSSL>
            <server>
              <cacheSessions>true</cacheSessions>
              <certificateFile>/etc/clickhouse-server/config.d/node.crt</certificateFile>
              <dhParamsFile>/etc/clickhouse-server/config.d/dhparam.pem</dhParamsFile>
              <disableProtocols>sslv2,sslv3</disableProtocols>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <preferServerCiphers>true</preferServerCiphers>
              <privateKeyFile>/etc/clickhouse-server/config.d/node.key</privateKeyFile>
              <verificationMode>none</verificationMode>
            </server>
          </openSSL>
        </yandex>
```
