### ISSUE TITLE
Is there is available a telegram chat?

### ISSUE THREAD

**Issue by ArtemChekunov** [Altinity/clickhouse-operator#636]
Is there is available a telegram community?

**Comment by alex-zaitsev** [comment]
Use https://t.me/clickhouse_en
If it gets too noisy we can open a separate channel.

**Comment by ArtemChekunov** [comment]
@alex-zaitsev I tried to ask questions about clickhouse-operator in https://t.me/clickhouse_ru 
however, they have been ignored 

Probably it makes sense  to create a separate channel 
then questions about clickhouse-operator will not be lost in the clickhouse message flow

**Comment by Slach** [comment]
@ArtemChekunov 

according to https://t.me/clickhouse_ru/200675
implementation of custom `kind: Service type: LoadBalancer`, for each clickhouse Cluster defined in `.spec.configuration.clusters` in already implements in operator sources, 

but, unfortunatelly we miss implements `.spec.templates.clusterServiceTemplates[]`, `.spec.templates.shardServiceTemplates[]` and `.spec.templates.replicaServiceTemplates[]` in custom resource `ClickhouseInstallation` and `ClickHouseInstallationTemplate`

**Comment by Slach** [comment]
@ArtemChekunov but you can implements mutiple clusters via following manifest
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "adv-layout-multiple-clusters"
spec:
  defaults:
    templates:
      clusterServiceTemplate: cluster-loadbalancer

  configuration:
    clusters:
      - name: c3-2
        templates:
          podTemplate: clickhouse:20.3
        layout:
          shardsCount: 3
          replicasCount: 2

      - name: c2-3
        templates:
          podTemplate: clickhouse:20.8
        layout:
          shardsCount: 2
          replicasCount: 3

  templates:
    serviceTemplates:
      - name: cluster-loadbalancer
        generateName: chendpoint-{cluster}-{chi}
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
    podTemplates:
      - name: clickhouse:20.3
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.3

      - name: clickhouse:20.8
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.8

```

**Comment by ArtemChekunov** [comment]
@Slach 

I yeah 
I went through the source code and made the proper configuration 

however, I get confused that all service templates are defined in serviceTemplates
because some of them get defined as serviceTemplate and some as clusterServiceTemplate

and I didn't find the way to completely disable CHI-level load balancer
there is only one workaround to stop allocating IP's https://github.com/Altinity/clickhouse-operator/issues/198

**BTW:**
I would add to the example ^:
```
        generateName: "{cluster}"
        spec:
          selector:
            clickhouse.altinity.com/app: "chop"
            clickhouse.altinity.com/chi: "{chi}"
            clickhouse.altinity.com/cluster: "{cluster}"
```
because requests should go to the specific cluster but not to any instance of the CHI

+ this is kind of weird that users/profiles/quotas are defined on CHI level
so they'll get applied to all clusters within the CHI


P.S.:
In general, I am excited about the clickhouse-operator

**You Rock!**
![image](https://media4.giphy.com/media/cn355kwNmtyblxBjXQ/giphy.gif)
