### ISSUE TITLE
ZooKeeper: Host not found

### ISSUE THREAD

**Issue by dav1d992** [Altinity/clickhouse-operator#638]
I have the [clickhouse operator ](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml) running inside my cluster and I'm trying to configure it with a ClickHouseInstallation inspired by [this chi example](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/04-replication-zookeeper-04-medium-AWS-persistent-volume.yaml).

The issue I'm receiving when running my clickhouse installation is 
```
<Error> ZooKeeper: Cannot use ZooKeeper host zookeeper-0.zookeepers.zoo3ns:2181, reason: Host not found: zookeeper-0.zookeepers.zoo3ns
```
**What could the reason be for that?** 

---

My installation.yaml
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "tornado" 
spec:
  defaults: 
    templates:
      podTemplate: clickhouse-template
      serviceTemplate: chi-service-template
      volumeClaimTemplate: clickhouse-storage-template
  configuration:
    users:      
      default/password: 12345
      storm/access_management: 1  
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo1ns
          port: 2181
    clusters:
      - name: tornado-db
        templates:
          podTemplate: clickhouse-template
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse  
    serviceTemplates:
      - name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
