### ISSUE TITLE
How to overwrite the default ports of my ClickHouse pod

### ISSUE THREAD

**Issue by dav1d992** [Altinity/clickhouse-operator#639]
I have the [clickhouse operator ](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml) running inside my cluster and I'm trying to configure it with a ClickHouseInstallation which is show below. 

I'm trying to overwrite the default tcp port number to 8321 by doing this

```
    layout:
      shardsCount: 1
      replicas:
        - templates:
            podTemplate: clickhouse-template
          httpPort: 8123
          tcpPort: 8321
          interserverHTTPPort: 9009   
```

```
NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
chi-tornado-tornado-db-0-0               ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP
```

I can't seem to overwrite the ports of my clickhouse pod. 
**What could the reason be for that?** 

---

Full installation.yaml
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "tornado" 
spec:
  defaults: 
    templates:
      podTemplate: clickhouse-template
      serviceTemplate: chi-service-template
      volumeClaimTemplate: clickhouse-storage-template
  configuration:
    users:      
      default/password: 12345
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo1ns
          port: 2181
    clusters:
      - name: tornado-db
        templates:
          podTemplate: clickhouse-template
        layout:
          shardsCount: 1
          replicas:
            - templates:
                podTemplate: clickhouse-template
              httpPort: 8123
              tcpPort: 8321
              interserverHTTPPort: 9009   
  templates:
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse  
    serviceTemplates:
      - name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

**Comment by Slach** [comment]
@dav1d992  reason for it is only one
you still using `serviceTemplate: chi-service-template` which generate kind: Service with ports 8123, 9000, 9009

**Comment by dav1d992** [comment]
Thanks for your reply. 
I think I forgot to mention that I had two seperate clusterIPs so the output of `kubectl get services` is 

```
NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
chi-tornado-tornado-db-0-0               ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP
clickhouse-tornado                       ClusterIP      10.43.24.110    172.26.1.2    8123/TCP,9000/TCP,9009/TCP
```
The serviceTemplate is there because I need to prevent the CH-operator from creating a loadbalancer. 
I tried removing it as well so that there was no reference to any serviceTemplate but my chi-tornado-tornado-db-0-0  service still was pointing at the same default ports.

**Comment by Slach** [comment]
@dav1d992 look like you should use `clusterServiceTemplate` instead of `serviceTemplate`

```
spec:
  defaults: 
    templates:
      clusterServiceTemplate: chi-service-template
```
and try to remove ports in following fragment  or define ports same as replicas section
```
serviceTemplates:
      - name: chi-service-template
        spec:
          type: ClusterIP
```

**Comment by dav1d992** [comment]
@Slach Thanks for your reply. I just tried that and it looks like if serviceTemplate is replaced by clusterServiceTemplate the loadbalancer will be created which I'd like to avoid. Also removing the port specifications in the serviceTemplate changed the ports on the clickhouse-tornado ClusterIP. But didn't change the ports on the pod I wanted to change. 

```
NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
chi-tornado-tornado-db-0-0               ClusterIP      None            <none>        8123/TCP,9000/TCP,9009/TCP
clickhouse-tornado                       ClusterIP      10.43.24.110    172.26.1.2    8123:32128/TCP,9000:30441/TCP

**Comment by alex-zaitsev** [comment]
Hi @dav1d992 , you may need to override host ports first, look at this example:
https://github.com/Altinity/clickhouse-operator/blob/master/tests/configs/test-015-host-network.yaml

**Comment by dav1d992** [comment]
@alex-zaitsev Thank you for your answer. Your suggested changes worked the way I wanted it to. Here's my final ClickHouseInstallation:

Full installation.yaml
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "tornado" 
spec:
  defaults: 
    templates:
      podTemplate: clickhouse-template
      serviceTemplate: chi-service-template
      volumeClaimTemplate: clickhouse-storage-template
  configuration:
    users:      
      default/password: 12345
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo1ns
          port: 2181
    clusters:
      - name: tornado-db
        templates:
          podTemplate: clickhouse-template
        layout:
          shardsCount: 1
          replicas:
            - templates:
                hostTemplate: clickhouse-host-template   
  templates:
    hostTemplates:
    - name: clickhouse-host-template
      spec:
        httpPort: 8123
        tcpPort: 8321
        interserverHTTPPort: 9009   
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse  
    serviceTemplates:
      - name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
