### ISSUE TITLE
Exposing the HTTPS port and the TCP Secure port 

### ISSUE THREAD

**Issue by dav1d992** [Altinity/clickhouse-operator#643]
I have the [clickhouse operator ](https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install.yaml) running inside my cluster and I'm trying to configure it with a ClickHouseInstallation which is shown below. 

I'm trying to expose the https port 8443 and the tcp secure port 9440, so that I can connect to my pod through those. What I've tried is: 

**Attempt 1** 
```

    hostTemplates:
    - name: clickhouse-host-template
      spec:
        httpPort: 8123
        tcpPort: 8321
        interserverHTTPPort: 9009   
        httpsPort: 8443 
        tcpPortSecure: 9440
```
**Attempt 2** 
```
  configuration:
    settings:
      https_port: 9441
      tcp_port_secure: 9440
```
**Attempt 3**
```
  configuration:
    files:
      settings.xml: |
        <yandex>
          <https_port>8443</https_port>
          <tcp_port_secure>9440</tcp_port_secure>
        </yandex>
```
**Attempt 4** inspired by [this ClickHouseInstallation](https://github.com/Altinity/clickhouse-operator/blob/df3351e4a668c3e18b039cce1f773ba011222f65/tests/configs/test-005-acm.yaml)
```
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              ports:
              - name: https
                containerPort: 8443
              - name: secureclient
                containerPort: 9440        
```
I'm expecting to see the https and the tcp secure port in the ports column below but I still just see the usual three ports which are set in the hostTemplate. 
```
NAME                         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
kubernetes                   ClusterIP   10.43.0.1     <none>        443/TCP                      5m22s
chi-tornado-tornado-db-0-0   ClusterIP   None          <none>        8123/TCP,8321/TCP,9009/TCP   2m58s
```

**How do I expose the https port and the tcp secure port correctly?** 

---

Full installation.yaml
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "tornado" 
spec:
  defaults: 
    templates:
      podTemplate: clickhouse-template
      serviceTemplate: chi-service-template
      volumeClaimTemplate: clickhouse-storage-template
  configuration:
    users:      
      default/password: 12345
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo1ns
          port: 2181
    clusters:
      - name: tornado-db
        templates:
          podTemplate: clickhouse-template
        layout:
          shardsCount: 1
          replicas:
            - templates:
                hostTemplate: clickhouse-host-template   
  templates:
    hostTemplates:
    - name: clickhouse-host-template
      spec:
        httpPort: 8123
        tcpPort: 8321
        interserverHTTPPort: 9009   
    podTemplates:
      - name: clickhouse-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse  
    serviceTemplates:
      - name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          ClusterIP: None
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

**Comment by Slach** [comment]
All your attempts are right, but you just change only ClickHouse server settings inside clickhouse Pod

you also need to change `serviceTemplate` which render `Kind: Service`

to allow Kubernetes pass traffic to your pods

```
    serviceTemplates:
      - name: chi-service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
            - name: https
              port: 8443
            - name: http
              port: 9440
          type: ClusterIP
          ClusterIP: None
```
