### ISSUE TITLE
SecurityContext lost "fsGroup" field

### ISSUE THREAD

**Issue by alexsuraykin** [Altinity/clickhouse-operator#664]
I am trying run ClickHouse cluster through operator with non root containers. I've already found issue about wrong fs owner with restricted PSP https://github.com/Altinity/clickhouse-operator/issues/600. But I have another problem:

- Operator version: altinity/clickhouse-operator:0.10.0
- podTemplate:

```yaml
podTemplates:
  - name: clickhouse-cluster
    spec:
      containers:
        - name: clickhouse-pod
          image: yandex/clickhouse-server:20.8.2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: clickhouse-pvc
              mountPath: /var/lib/clickhouse
            - name: clickhouse-pvc
              mountPath: /var/log/clickhouse-server
          securityContext:
            fsGroup: 101
            runAsGroup: 101
            runAsUser: 101
```

In StatefulSet:

```yaml
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 101
            runAsGroup: 101
```

There is no "fsGroup" field.

**Comment by Slach** [comment]
could you check issue on clickhouse-operator 0.13.5?
which kubernetes version do you use?

this example https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-07-do-not-chown.yaml works fine and checked under our k8s 1.17 (EKS) and 1.20.4 (minikube)

**Comment by alexsuraykin** [comment]
I will try to deploy operator 0.13.5.
K8s 1.18 and 1.20.2


Also, if I use  podTemplate:

```yaml
podTemplates:
  - name: clickhouse-cluster
    spec:
      containers:
        - name: clickhouse-pod
          image: yandex/clickhouse-server:20.8.2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: clickhouse-pvc
              mountPath: /var/lib/clickhouse
            - name: clickhouse-pvc
              mountPath: /var/log/clickhouse-server
          securityContext:
            fsGroup: 101
            runAsUser: 101
```

Pod is deployed with:

```yaml
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 101
            fsGroup: 101
```

**Comment by alex-zaitsev** [comment]
So, what is wrong @alexsuraykin? fsGroup is correctly passed to the pod. 

We use it in Altinity.Cloud as well.

**Comment by farr-slmn** [comment]
@alexsuraykin, the thing is you use fsGroup in a non applicable object - containers. You have to put it next to it:
```
podTemplates:
  - name: clickhouse-cluster
    spec:
      containers:
        - name: clickhouse-pod
          image: yandex/clickhouse-server:20.8.2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: clickhouse-pvc
              mountPath: /var/lib/clickhouse
            - name: clickhouse-pvc
              mountPath: /var/log/clickhouse-server
          securityContext:
            runAsGroup: 101
            runAsUser: 101
      securityContext:
        fsGroup: 101
```
Ref: [Set the security context for a Pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
