### ISSUE TITLE
Operator irregularly crashes and wipes all pods

### ISSUE THREAD

**Issue by aksdb** [Altinity/clickhouse-operator#671]
We are running the ClickHouse Operator 0.13.5, and every few hours to days, suddenly all ClickHouse pods are gone. A few up to 30 minutes later they are slowly recreated.

Around the time this happens, the operator itself also restarts. Here are the last log lines (in more or less random order since they are unstructured and can therefore be not parsed by filebeat):

```
	Mar 22, 2021 @ 09:42:27.530	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ConfigMap [recovered]
	Mar 22, 2021 @ 09:42:27.530		panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ConfigMap
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
	Mar 22, 2021 @ 09:42:27.530	panic(0x1384320, 0xc000630b40)
	Mar 22, 2021 @ 09:42:27.530		/usr/local/go/src/runtime/panic.go:679 +0x1b2
	Mar 22, 2021 @ 09:42:27.530	github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).addEventHandlers.func18(0x13e31c0, 0xc00105e820)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/controller.go:296 +0x220
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000669dd8, 0x0, 0x0)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000221f40)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
	Mar 22, 2021 @ 09:42:27.530	
	Mar 22, 2021 @ 09:42:27.530	k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	Mar 22, 2021 @ 09:42:27.530	k8s.io/client-go/tools/cache.(*processorListener).run(0xc000049980)
	Mar 22, 2021 @ 09:42:27.530	created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x1d6
	Mar 22, 2021 @ 09:42:27.530	goroutine 119 [running]:
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	Mar 22, 2021 @ 09:42:27.530	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/controller.go:209
	Mar 22, 2021 @ 09:42:27.530	k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0xc00d39aea567db7a, 0x183fe94e)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000669f40, 0xdf8475800, 0x0, 0x42d801, 0xc0004f60c0)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/wait.Until(...)
	Mar 22, 2021 @ 09:42:27.530	k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000442610, 0xc000346570)
	Mar 22, 2021 @ 09:42:27.530		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
	Mar 22, 2021 @ 09:42:27.522	goroutine 119 [running]:
	Mar 22, 2021 @ 09:42:27.522		/usr/local/go/src/runtime/panic.go:679 +0x1b2
	Mar 22, 2021 @ 09:42:27.522	k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0xc00d39aea567db7a, 0x183fe94e)
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00059bdd8, 0x0, 0x0)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
	Mar 22, 2021 @ 09:42:27.522	k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000221f40)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
	Mar 22, 2021 @ 09:42:27.522	created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1384320, 0xc000630b40)
	Mar 22, 2021 @ 09:42:27.522	github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).addEventHandlers.func18(0x13e31c0, 0xc00105e820)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/controller.go:296 +0x220
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x1d6
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00059bf40, 0xdf8475800, 0x0, 0x42d801, 0xc0004f60c0)
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/wait.Until(...)
	Mar 22, 2021 @ 09:42:27.522	k8s.io/client-go/tools/cache.(*processorListener).run(0xc000049980)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000442610, 0xc000346570)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
	Mar 22, 2021 @ 09:42:27.522	E0322 08:42:27.521562       1 runtime.go:73] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x134d320), concrete:(*runtime._type)(0x13e31c0), asserted:(*runtime._type)(0x15026a0), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ConfigMap)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
	Mar 22, 2021 @ 09:42:27.522	k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
	Mar 22, 2021 @ 09:42:27.522	panic(0x1384320, 0xc000630b40)
	Mar 22, 2021 @ 09:42:27.522	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/controller.go:209
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
	Mar 22, 2021 @ 09:42:27.522		/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
	Mar 22, 2021 @ 09:42:27.220	I0322 08:42:27.137045       1 announcer.go:215] updateCHI():analytics/clickhouse:reconcile started	
```

We are using Istio and therefore the operator and all pods get sidecars injected, in case this might be part of the problem.

**Comment by aksdb** [comment]
Here is the example from our dev environment:

```yaml
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: analytics
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 2
        shardsCount: 2
      name: replicated
    users:
      admin/access_management: "1"
      admin/networks/ip: ::/0
      admin/password_sha256_hex: ...
      analytics/allow_databases/database:
      - analytics
      analytics/networks/ip: ::/0
      analytics/password_sha256_hex: ...
    zookeeper:
      nodes:
      - host: zookeeper
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:stable
  templates:
    podTemplates:
    - name: clickhouse:stable
      podDistribution:
      - type: ClickHouseAntiAffinity
      spec:
        containers:
        - image: yandex/clickhouse-server:20.8.9.6
          name: clickhouse
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
    volumeClaimTemplates:
    - name: default
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
```

We also came a bit closer to figuring out what might happen: the created StatefulSets get annotated with
```
kustomize.toolkit.fluxcd.io/checksum: d47a5c946eb6f14281a46b45363fede3e73ea600
kustomize.toolkit.fluxcd.io/name: analytics
kustomize.toolkit.fluxcd.io/namespace: flux-system
```
(we are using flux, as you can see)

Therefore flux takes ownership and removed the statefulsets when applying changes. We are not (yet) sure, why the operator sets those annotations in the first place. Maybe they get copied over from the custom resource.
