### ISSUE TITLE
override chop-generated-users.xml

### ISSUE THREAD

**Issue by juanvasquezreyes** [Altinity/clickhouse-operator#685]
Is there a way to override the file that is being generate on the fly chop-generated-users.xml

I created my own file chop-generated-users.xml because I didnt want to have the passwords hardcoded in ClickHouseInstallation definition, so instead of that I am pulling the passwords from vault and generated a secret that has the same structure as chop-generated-users.xml, but when trying to mount it fails because that location is already being used

is there a way to dont create that file or override it?

**Comment by alex-zaitsev** [comment]
You can not override this file, but you can create another one and mount it inside users.d.

**Comment by juanvasquezreyes** [comment]
> You can not override this file, but you can create another one and mount it inside users.d.

thank you @alex-zaitsev, does the name matter?

**Comment by alex-zaitsev** [comment]
> > You can not override this file, but you can create another one and mount it inside users.d.
> 
> thank you @alex-zaitsev, does the name of the file matter?

Any XML file inside users.d will be merged to the configuration. Also look at this example https://github.com/Altinity/clickhouse-operator/blob/eb3fc4e28514d0d6ea25a40698205b02949bcf9d/tests/configs/test-016-settings-01.yaml -- there are multiple ways how users can be configured. It probably does not allow you to use secrets though.

**Comment by juanvasquezreyes** [comment]
@alex-zaitsev I was able to generate the file inside of the clickhouse pod, but I cannot add it in the existing directory because is mounted as read-only

so I have to mount it as read/write or modify the configmap on the fly somehow

this is my ClickHouseInstallation kind, as you can see my secret contains the users.xml and right now I'm mounting it in /tmp cause when using the correct directory is not working
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ include "clickhouse.fullname" . }}
spec:
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: volume-template
      logVolumeClaimTemplate: volume-template
      serviceTemplate: service-template
  configuration:    
    {{ if .Values.zookeeper.zookeeper.enabled }}
    zookeeper:
      nodes:
      - host: {{ include "clickhouse.fullname" . }}-zookeeper
    {{- end }}
    clusters:
      - name: {{ .Values.clickhouse.name }}
        layout:
          {{ if .Values.clickhouse.shardCount }}
          shardsCount: {{.Values.clickhouse.shardCount }}
          {{- end }}
          {{ if .Values.clickhouse.replicaCount }}
          replicasCount: {{.Values.clickhouse.replicaCount }}
          {{- end }}     
  templates:
    serviceTemplates:
      - name: service-template
        generateName: {{ include "clickhouse.fullname" . }}        
        spec:
          ports:
            - name: http
              port: {{.Values.clickhouse.service.port }}
            - name: tcp
              port: 9000            
          type: {{.Values.clickhouse.service.type }}   
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: {{.Values.clickhouse.image }} 
              volumeMounts:
                - name: {{ include "clickhouse.fullname" . }}
                  mountPath: /var/lib/clickhouse                
                - name: "users-xml"
                  mountPath: /tmp/users.xml
                  subPath: "users.xml"
              resources:
                {{- toYaml .Values.clickhouse.resources | nindent 16 }}
          volumes:
            - name: users-xml
              secret:
                secretName: {{ include "clickhouse.fullname" . }}-users
                items:
                - key: users.xml
                  path: users.xml
    volumeClaimTemplates:
      - name: {{ include "clickhouse.fullname" . }}
        spec:		  
          accessModes:
            - ReadWriteOnce
          storageClassName: {{ .Values.clickhouse.storageSpec.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.clickhouse.storageSpec.resources.requests.storage }}
```

**Comment by alex-zaitsev** [comment]
Hi @juanvasquezreyes,
ClickHouse allows to pass data to configuration via environment variables. See:
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/tests/integration/test_config_substitutions/configs/config_env.xml
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/tests/integration/test_config_substitutions/configs/config_include_from_env.xml

Would it work for secrets?

**Comment by Slach** [comment]
@juanvasquezreyes also, look to https://github.com/Altinity/clickhouse-operator/issues/700#issuecomment-841106068
you can add `files` section inside `ClickHouseInstallation.spec.clusters[]`
it will mount into /etc/clickhouse-server/conf.d/
and use `from_env` + env to allow data from your secrets inside clickhouse config

**Comment by juanvasquezreyes** [comment]
> @juanvasquezreyes also, look to [#700 (comment)](https://github.com/Altinity/clickhouse-operator/issues/700#issuecomment-841106068)
> you can add `files` section inside `ClickHouseInstallation.spec.clusters[]`
> it will mount into /etc/clickhouse-server/conf.d/
> and use `from_env` + env to allow data from your secrets inside clickhouse config

great!! this is what I was looking for, will give it a try

**Comment by jessezax** [comment]
> /etc/clickhouse-server/conf.d/

how can i change path "/etc/clickhouse-server/conf.d/" to "/etc/clickhouse-server/config.d/"?

**Comment by Slach** [comment]
@jessezax 
just use 

```yaml
spec:
   configuration:
     files:
        config.d/file_name.xml: |
           <xml>content</xml>
```        
look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-05-files-nested.yaml
to see all available options
