### ISSUE TITLE
Data not replicate

### ISSUE THREAD

**Issue by liamnv** [Altinity/clickhouse-operator#687]
I have deployed one cluster with 2 shards, 2 replicas with following configuration:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "clickhouse"

spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:19.6
 
  configuration:
    zookeeper:
      nodes:
      - host: zookeeper-0.zookeeper-headless.clickhouse.svc.cluster.local
      - host: zookeeper-1.zookeeper-headless.clickhouse.svc.cluster.local
      - host: zookeeper-2.zookeeper-headless.clickhouse.svc.cluster.local
    clusters:
      - name: replicated
        layout:
          shardsCount: 2
          replicasCount: 2

  templates:
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
```

But after that I connected with DBEaver, create a database but it affected only to one instance.
