### ISSUE TITLE
Add support for add custom affinity rules  for ClickHouse pods

### ISSUE THREAD

**Issue by johnpptz** [Altinity/clickhouse-operator#688]

**Comment by Slach** [comment]
which kind of affinity rules do you need?
Currently operator already have make affinity rules in `spec.tempates.podTemplates` 
https://github.com/Altinity/clickhouse-operator/search?q=affinity&type=code

**Comment by johnpptz** [comment]
For example i would like to create this rules

```
nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 'kubernetes.azure.com/mode'
          operator: NotIn
          values:
            - "system"
```
