### ISSUE TITLE
Feature request: Allow initializing users based on secrets

### ISSUE THREAD

**Issue by macobo** [Altinity/clickhouse-operator#700]
## Background 

Currently, when creating a `ClickhouseInstallation` you need to either pass the password or sha256 hex of the password in the k8s manifest. 

It would be great if it was possible to use secrets for this purpose as well, similar to how it's done with `config.yaml` and `chCredentialsSecretNamespace`/`chCredentialsSecretName`. This comes in handy when used in helm charts as it would allow for auto-generating passwords.

## Proposed solution

Let's use https://github.com/Altinity/clickhouse-operator/blob/581cf315fc85527e637bc08152d4edd5490a5099/docs/chi-examples/05-settings-01-overview.yaml#L9 as a basis

A possible solution might look something like this:

```yaml
    test/passwordSecret:
        namespace: default
        name: some-secret
        path: clickhouse-password
```

**Comment by Slach** [comment]
@macobo you can already store passwords into Secrets and use it inside clickhouse

look to following manifest:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-passwords
stringData:
  password1: my_password1
  password2: my_password2

---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: chi-with-password-secrets
spec:
  configuration:
    users:
      user1/password:
        valueFrom:
          envVarRef:
            name: secret-passwords
            key: password2
    clusters:
      - name: "your-cluster"
        layout:
          replicasCount: 1
          shardsCount: 1
        files:
          # will mounts to /etc/clickhouse-server/conf.d/
          user_passwords.xml: |
            <yandex>
              <users>
                <user1>
                  <password from_env="PASSWORD1" />
                  <profile>default</profile>
                </user1>
                <user2>
                  <password from_env="PASSWORD2" />
                  <profile>default</profile>
                </user2>
              </users>
            </yandex>

  defaults:
    templates:
      podTemplate: pod-with-mounted-secret

  templates:
    podTemplates:
      - name: pod-with-mounted-secret
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:latest
              env:
                - name: PASSWORD1
                  valueFrom:
                    secretKeyRef:
                      name: secret-passwords
                      key: password1
                - name: PASSWORD2
                  valueFrom:
                    secretKeyRef:
                      name: secret-passwords
                      key: password2

```
it should works for any clickhouse version (from_env availabil from 18.x) and clickhouse-operator v0.13.0+ (we recommends to use 0.14.0 for production)

**Comment by juanvasquezreyes** [comment]
@Slach its not working for me this is my configuration

```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:  
  name: clickhouse-test
  namespace: observability  
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 1
      name: test
    files:      
      user_passwords.xml: |
        <yandex>
          <users>
            <admin>
              <password from_env="ADMIN_PASSWORD" />
              <profile>default</profile>
            </admin>
            <readonly>
             <password from_env="READONLY_PASSWORD" />
              <profile>default</profile>
            </readonly>
          </users>
        </yandex>
    users:
      admin/access_management: "1"
      admin/password:
        valueFrom:
          envVarRef:
            name: clickhouse-users
            key: admin
      admin/networks/ip: ::/0
      admin/profile: default
      admin/quota: default
      readonly/profile: readonly
      readonly/quota: default
      readonly/password: 
        valueFrom:
          envVarRef:
            name:  clickhouse-users
            key: readonly
    zookeeper:
      nodes:
      - host: kafka-zookeeper
  defaults:
    templates:
      dataVolumeClaimTemplate: volume-template
      logVolumeClaimTemplate: volume-template
      podTemplate: pod-template
      serviceTemplate: service-template
  templates:
    podTemplates:
    - distribution: ""
      metadata:
        creationTimestamp: null
      name: pod-template
      spec:
        containers:
        - env:
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin
                name: clickhouse-users
          - name: READONLY_PASSWORD
            valueFrom:
              secretKeyRef:
                key: readonly
                name: clickhouse-users
          image: registry.devops.ohlogistics.com/yandex/clickhouse-server:21.3
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - /scripts/clickhouse.sh
          name: clickhouse
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: clickhouse
          - mountPath: /scripts
            name: scripts
        - command:
          - /bin/sh
          - -c
          - /bin/clickhouse-backup -c /etc/clickhouse-server/config.d/ch-backup.yaml
            server
          image: registry.devops.ohlogistics.com/alexakulov/clickhouse-backup:0.6.5
          imagePullPolicy: Always
          name: clickhouse-backup
          ports:
          - containerPort: 7171
            name: backup-rest
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: clickhouse
        volumes:
        - configMap:
            defaultMode: 365
            name: clickhouse-scripts
          name: scripts
      zone: {}
    serviceTemplates:
    - generateName: clickhouse
      metadata:
        creationTimestamp: null
      name: service-template
      spec:
        ports:
        - name: http
          port: 8123
          targetPort: 0
        - name: tcp
          port: 9000
          targetPort: 0
        - name: backup
          port: 7171
          targetPort: 0
        type: ClusterIP
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
      name: clickhouse
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: vsphere-volumes
        
---
apiVersion: v1
data:
  admin: cXVlcnR5
  readonly: cmVhZG9ubHk=
  readwrite: cmVhZHdyaXRl
kind: Secret
metadata:  
  name: clickhouse-users  
type: Opaque
```

it is setting the default password for the two users 37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f

for clickhouse I'm using this version yandex/clickhouse-server:21.3 and for clickhouse-operator altinity/clickhouse-operator:0.14.0, both are using imagePullPolicy: Always

**Comment by filimonov** [comment]
Hm. Please TRY removing those fragments:

```yaml
      admin/password:
        valueFrom:
          envVarRef:
            name: clickhouse-users
            key: admin
```

And
```yaml
      readonly/password: 
        valueFrom:
          envVarRef:
            name:  clickhouse-users
            key: readonly
```

**Comment by juanvasquezreyes** [comment]
@filimonov I just changed it, and still cannot get inside using the secret password, this is my new clickhouseinstallation

```
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 1
      name: posthog
    files:      
      user_passwords.xml: |
        <yandex>
          <users>
            <admin>
              <password from_env="ADMIN_PASSWORD" />
              <profile>default</profile>
            </admin>
            <readonly>
             <password from_env="READONLY_PASSWORD" />
              <profile>default</profile>
            </readonly>
          </users>
        </yandex>
    users:
      admin/access_management: "1"
      admin/networks/ip: ::/0
      admin/profile: default
      admin/quota: default
      readonly/profile: readonly
      readonly/quota: default
    zookeeper:
      nodes:
      - host: kafka-zookeeper
  defaults:
    templates:
      dataVolumeClaimTemplate: volume-template
      logVolumeClaimTemplate: volume-template
      podTemplate: pod-template
      serviceTemplate: service-template
  templates:
    podTemplates:
    - distribution: ""
      metadata:
        creationTimestamp: null
      name: pod-template
      spec:
        containers:
        - env:
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin
                name: clickhouse-posthog-users
          - name: READONLY_PASSWORD
            valueFrom:
              secretKeyRef:
                key: readonly
                name: clickhouse-posthog-users
          image: registry.devops.ohlogistics.com/yandex/clickhouse-server:21.3
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - /scripts/posthog-clickhouse.sh
          name: clickhouse
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: clickhouse-posthog
          - mountPath: /scripts
            name: scripts        
        volumes:
        - configMap:
            defaultMode: 365
            name: clickhouse-posthog-scripts
          name: scripts
      zone: {}
    serviceTemplates:
    - generateName: clickhouse-posthog
      metadata:
        creationTimestamp: null
      name: service-template
      spec:
        ports:
        - name: http
          port: 8123
          targetPort: 0
        - name: tcp
          port: 9000
          targetPort: 0
        - name: backup
          port: 7171
          targetPort: 0
        type: ClusterIP
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
      name: clickhouse-posthog
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: vsphere-volumes
```


And in the logs I see it got merged
```
kubectl logs chi-clickhouse-posthog-posthog-0-0-0 -c clickhouse

Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-macros.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-zookeeper.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-listen.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/02-clickhouse-logger.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/03-clickhouse-querylog.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/04-clickhouse-partlog.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/user_passwords.xml'.
Logging debug to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging debug to console
```

```

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@chi-clickhouse-posthog-posthog-0-0-0:/# env | grep PASS
ADMIN_PASSWORD=querty
READONLY_PASSWORD=readonly


root@chi-clickhouse-posthog-posthog-0-0-0:/# cat /etc/clickhouse-server/config.d/user_passwords.xml
<yandex>
  <users>
    <admin>
      <password from_env="ADMIN_PASSWORD" />
      <profile>default</profile>
    </admin>
    <readonly>
     <password from_env="READONLY_PASSWORD" />
      <profile>default</profile>
    </readonly>
  </users>
</yandex>


root@chi-clickhouse-posthog-posthog-0-0-0:/# cat /etc/clickhouse-server/users.d/chop-generated-users.xml
<yandex>
    <users>
        <admin>
            <access_management>1</access_management>
            <networks>
                <host_regexp>(chi-clickhouse-posthog-[^.]+\d+-\d+|clickhouse\-clickhouse-posthog)\.observability\.svc\.cluster\.local$</host_regexp>
                <ip>::/0</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>default</profile>
            <quota>default</quota>
        </admin>
        <default>
            <networks>
                <host_regexp>(chi-clickhouse-posthog-[^.]+\d+-\d+|clickhouse\-clickhouse-posthog)\.observability\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
        <readonly>
            <networks>
                <host_regexp>(chi-clickhouse-posthog-[^.]+\d+-\d+|clickhouse\-clickhouse-posthog)\.observability\.svc\.cluster\.local$</host_regexp>
                <ip>::1</ip>
                <ip>127.0.0.1</ip>
            </networks>
            <password_sha256_hex>37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f</password_sha256_hex>
            <profile>readonly</profile>
            <quota>default</quota>
        </readonly>
    </users>
</yandex>
```
