### ISSUE TITLE
How to downlink the specified node？

### ISSUE THREAD

**Issue by Pupti** [Altinity/clickhouse-operator#708]
## version

k8s v1.17.5
clickhouse-operator  0.11.0
clickhouse  21.5.5.12

## Expectations and attempts

I have three nodes in my ch cluster and I want to offline the `node1` node, but when I change the `shardsCount` to 2 and change the scheduling conditions so that the pod is not scheduled to `node1`

```shell

kubectl get pod -n clickhouse-cluster -o wide
NAME                                        READY   STATUS    RESTARTS   AGE     IP             NODE                   NOMINATED NODE   READINESS GATES
chi-clickhouse-test-ch-test-0-0-0     2/2     Running   0          26m     server1    node1   <none>           <none>
chi-clickhouse-test-ch-test-1-0-0     2/2     Running   0          21m     server2    node2   <none>           <none>
chi-clickhouse-test-ch-test-2-0-0     2/2     Running   0          21m     server3    node3   <none>           <none>

```
The scheduling strategy is as follows, `node3` has the tag `status : offline`

```yaml
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: "status"
                      operator: NotIn
                      values:
                        - "offline"
```

After I changed the `clickhouse-test.yaml` file, I restarted the cluster using `kubectl replace -f clickhouse-test.yaml`

## Results and Conjectures

When I restart the ck cluster, the clickhouse-operator seems to only be able to offline the last node, and the scheduling policy I set does not take effect.

```shell

kubectl get pod -n clickhouse-cluster -o wide

NAME                                        READY   STATUS    RESTARTS   AGE     IP             NODE                   NOMINATED NODE   READINESS GATES
chi-clickhouse-test-ch-test-0-0-0     2/2     Running   0          26m     server1    node1   <none>           <none>
chi-clickhouse-test-ch-test-1-0-0     2/2     Running   0          21m     server2    node2   <none>           <none>

```

How can I downlink the specified node?
