### ISSUE TITLE
<Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below)

### ISSUE THREAD

**Issue by intfish123** [Altinity/clickhouse-operator#714]
<Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11d0c84e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11d0eac6 in /usr/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0xe8de1ad in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0xf64c6be in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0xf65f879 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x11d138af in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x11d152c1 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x11e4b9e9 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e4784a in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.12.2 (official build))

**Comment by intfish123** [comment]
What's wrong? Clickhouse server print this error infomation every second, Can any body help me?

**Comment by Slach** [comment]
did you deploy clickhouse sever inside kubernetes with clickhouse-operator?
could you share your `kind: ClickhouseInstallation`  manifest?

**Comment by intfish123** [comment]
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch1"
spec:
  defaults:
    templates:
      podTemplate: default
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:21.3
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: alicloud-nas-subpath
          resources:
            requests:
              storage: 400Gi
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: alicloud-nas-subpath
          resources:
            requests:
              storage: 10Gi
  configuration:
    clusters:
      - name: "c1"
        layout:
          shardsCount: 1
```
@Slach
