### ISSUE TITLE
PV was not created automatically

### ISSUE THREAD

**Issue by kevinbin** [Altinity/clickhouse-operator#716]
https://docs.altinity.com/clickhouseonkubernetes/kubernetesquickstartguide/quickpersistentstorage/
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "demo-01"
spec:
  defaults:
    deployment:
      podTemplate: clickhouse-stable
      volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
    - name: clickhouse-stable
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:latest
    volumeClaimTemplates:
    - name: storage-vc-template
      persistentVolumeClaim:
        metadata:
          name: storage-demo
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  configuration:
    zookeeper:
        nodes:
        - host:  zookeeper-0.zookeepers.test
          port: 2181
    clusters:
      - name: "demo-01"
        layout:
          shardsCount: 1
          replicasCount: 1
```
