### ISSUE TITLE
pod status is CrashLoopBackoff

### ISSUE THREAD

**Issue by rgangoni** [Altinity/clickhouse-operator#717]
when i have mounted volume in clickhouse shard ,mounted successfuly but in my setup the other pod status is changed to CrashLoopBackoff.

with out making this change the setup is working fine means all pods are in Running state.T

Clickhouse Operator Version : 0.14.0
Clickhouse Server verrsion : 20.7

when i see the logs of the pod it is showing like this

```
 <Error> Application: Caught exception while loading metadata: Code: 62, e.displayText() = DB::Exception: Incorrect user[:password]@host:port#default_database format detached, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x12723a80 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa3f52bd in /usr/bin/clickhouse
2. ? @ 0xf291887 in /usr/bin/clickhouse
3. DB::StorageDistributedDirectoryMonitor::createPool(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageDistributed const&) @ 0xfb69893 in /usr/bin/clickhouse
4. DB::StorageDistributed::requireDirectoryMonitor(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf95e41e in /usr/bin/clickhouse
5. DB::StorageDistributed::createDirectoryMonitors(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf963c3e in /usr/bin/clickhouse
6. DB::StorageDistributed::startup() @ 0xf963f70 in /usr/bin/clickhouse
7. ? @ 0xf3202d2 in /usr/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4235c7 in /usr/bin/clickhouse
9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0xa423d3a in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa422ad7 in /usr/bin/clickhouse
11. ? @ 0xa421023 in /usr/bin/clickhouse
12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
13. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.7.4.11 (official build))
2021.06.09 03:56:50.789018 [ 1 ] {} <Information> Application: Shutting down storages.
2021.06.09 03:56:51.217249 [ 62 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 8.32 TiB.
2021.06.09 03:56:51.222383 [ 66 ] {} <Debug> system.metric_log (MergerMutator): Selected 2 parts from 202106_207328_209821_460 to 202106_209822_209822_0
2021.06.09 03:56:51.222491 [ 66 ] {} <Debug> DiskLocal: Reserving 2.14 MiB on disk `default`, having unreserved 8.32 TiB.
2021.06.09 03:56:51.222552 [ 66 ] {} <Debug> system.metric_log (MergerMutator): Merging 2 parts: from 202106_207328_209821_460 to 202106_209822_209822_0 into Wide
2021.06.09 03:56:51.223163 [ 66 ] {} <Debug> system.metric_log (MergerMutator): Selected MergeAlgorithm: Horizontal
2021.06.09 03:56:51.328411 [ 66 ] {} <Debug> MemoryTracker: Peak memory usage: 279.08 MiB.
2021.06.09 03:56:51.328525 [ 66 ] {} <Information> system.metric_log: Cancelled merging parts
2021.06.09 03:56:51.328658 [ 1 ] {} <Debug> system.metric_log: Removing part from filesystem 202106_207328_209808_459
2021.06.09 03:56:51.387037 [ 1 ] {} <Debug> system.metric_log: Removing part from filesystem 202106_209809_209821_3
2021.06.09 03:56:51.429711 [ 1 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 4.01 MiB.
2021.06.09 03:56:51.430130 [ 1 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 20.00 MiB.
2021.06.09 03:56:51.430183 [ 1 ] {} <Debug> Application: Shut down storages.
2021.06.09 03:56:51.435317 [ 1 ] {} <Debug> Application: Destroyed global context.
2021.06.09 03:56:51.435620 [ 1 ] {} <Error> Application: DB::Exception: Incorrect user[:password]@host:port#default_database format detached
2021.06.09 03:56:51.435683 [ 1 ] {} <Information> Application: shutting down
2021.06.09 03:56:51.435705 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.06.09 03:56:51.437298 [ 47 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

**Comment by alex-zaitsev** [comment]
@rgangoni , something is wrong with your configuration, would you mind posting the full ClickHouseInstallation object?

Also note that 20.7 ClickHouse version is not recommended. We test operator mainly with Altinity Stable versions of ClickHouse:
https://docs.altinity.com/altinitystablerelease/releasenotes/

**Comment by rgangoni** [comment]
Please find my ClickhouseInstallation file
          
          ```
          apiVersion: "clickhouse.altinity.com/v1"
          kind: "ClickHouseInstallation"
          
          metadata:
            name: "test"
          
          spec:
            defaults:
              templates:
                dataVolumeClaimTemplate: default
                podTemplate: clickhouse:20.7
          
            configuration:
              zookeeper:
                nodes:
                #- host: zookeeper.zoo1ns
                - host: zookeeper.zoo3ns
              session_timeout_ms: 30000
              operation_timeout_ms: 10000
          
              clusters:
                - name: replicated
                  layout:
                    shardsCount: 4
                    replicasCount: 2
              users:
                admin/password: xxx
                readonly/password: readonly_password
                readonly/profile: readonly
                admin/networks/ip: 0.0.0.0/0
              profiles:
                default/format_avro_schema_registry_url: 
                readonly/readonly: "1"
          
            templates:
              volumeClaimTemplates:
                - name: default
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 100Gi
                    storageClassName: "local-storage"
              podTemplates:
                - name: clickhouse:20.7
                  podDistribution:
                    - type: ShardAntiAffinity
                    - type: MaxNumberPerNode
                      number: 2
                  spec:
                    volumes:
                      # Specify volume as path on local filesystem as a directory which will be created, if need be
                      - name: local-path
                        hostPath:
                          path: /data/backup
                          type: DirectoryOrCreate
                    containers:
                      - name: clickhouse-pod
                        image: yandex/clickhouse-server:20.7
                        volumeMounts:
                          # Specify reference to volume on local filesystem
                          - name: local-path
                            mountPath: /backupstore
          ```
