### ISSUE TITLE
Unable to specify per-CHI settings

### ISSUE THREAD

**Issue by marcioapm** [Altinity/clickhouse-operator#732]
I am trying to setup the operator such that base settings for all clusters are specified in the XML templates as seen in the deployment folder, and to have per-cluster settings specified in the CHI manifest.
This doesn't seem to be working. I tried with "allow_experimental_database_replicated" and a few others, setting them in various ways, but nothing works:

```
spec:
  configuration:
    profiles:
      default:
        allow_experimental_database_replicated: 1
```

Also tried directly in the settings:
```
spec:
  configuration:
    settings:
      allow_experimental_database_replicated: 1
```

Also doesn't work.

Not sure if I misinterpreted the documentation or if it's just not working.

I am using the 0.14 operator, with yandex 21.6.5 image.

**Comment by marcioapm** [comment]
It seems like one must flatten any nested objects:

```
spec:
  configuration:
    profiles:
      default:
        allow_experimental_database_replicated: 1
        allow_experimental_bigint_types: 1
```
should instead be:
```
spec:
  configuration:
    profiles:
      default/allow_experimental_database_replicated: 1
      default/allow_experimental_bigint_types: 1
```

This works, but wasn't expecting to have to do this.

Thanks!
