### ISSUE TITLE
Data lost when a pod restarts

### ISSUE THREAD

**Issue by pulkitkalia1994** [Altinity/clickhouse-operator#749]
Hello,
I setup a cluster with 2 shards and 2 replicas. I had some data on one of the shards and the data was replicated successfully to other node(replica node). But one of the replica was restarted which resulted in loss of data on that node. I was expecting the data to be replicated automatically to this node as well but didn't happen. 
Am I missing anything?

**Comment by Slach** [comment]
@pulkitkalia1994 could you provide your `kind: ClickhouseInstallation` manifest?

**Comment by pulkitkalia1994** [comment]
@Slach 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "shard2-repl2"
  namespace: clickhouse-operator
spec:
  configuration:
    zookeeper:
        nodes:
          - host: zookeeper-0.zookeepers.zookeeper
            port: 2181
    clusters:
      - name: "shard2-repl2"
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

**Comment by Slach** [comment]
@pulkitkalia1994 
you miss
`spec.defaults.temlates` section in your manifest

and your volumeClaimTemplates didn't apply to your pods inside clickhouse cluster

so every time when you restart clickhose pod
/var/lib/clickhouse will created from scratch 
and your pod will not contains any `ReplicatedMergeTree` table definition in `/var/lib/clickhouse/metadata/`

try to apply the following manifest, `CREATE TABLE ... ON CLUSTER 'all-sharded' ENGINE=ReplicatedMergeTree(..)`  and try to kill one of your clickhouse pod

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "shard2-repl2"
  namespace: clickhouse-operator
spec:
  # ---------- this section was missed ---------------------
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
     
  сonfiguration:
    zookeeper:
      nodes:
      - host: zookeeper-0.zookeepers.zookeeper
        port: 2181
  clusters:
    - name: "shard2-repl2"
       layout:
         shardsCount: 2
         replicasCount: 2
templates:
  volumeClaimTemplates:
  - name: data-volume-template
      spec:
        accessModes:
         - ReadWriteOnce
        resources:
           requests:
              storage: 1Gi
  - name: log-volume-template
    spec:
       accessModes:
- ReadWriteOnce
resources:
requests:
storage: 1Gi
```
