### ISSUE TITLE
Operator CRD is missing metadata for pod templates

### ISSUE THREAD

**Issue by ericisco** [Altinity/clickhouse-operator#756]
My installation makes use of pod template annotations to enable things like monitoring, for example:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: test
  namespace: chop
spec:
  templates:
    podTemplates:
    - name: foo
      metadata:
        baz: qux
```

In practice the operator uses the metadata when creating the stateful sets and it works perfectly.

We recently changed our deployment to use Kubernetes Server-Side Apply which is validating against the CRD and now the installations fail.  It looks like it was mistakenly left out and this trivial change resolves it:

```
--- clickhouse-operator-install-crd.yaml.orig	2021-08-13 10:26:30.000000000 -0400
+++ clickhouse-operator-install-crd.yaml	2021-08-13 10:35:33.000000000 -0400
@@ -765,6 +765,9 @@
                               type: integer
                               minimum: 0
                               maximum: 65535
+                      metadata:
+                        type: object
+                        nullable: true
                       spec:
                         # TODO specify PodSpec
                         type: object
@@ -1600,6 +1603,9 @@
                               type: integer
                               minimum: 0
                               maximum: 65535
+                      metadata:
+                        type: object
+                        nullable: true
                       spec:
                         # TODO specify PodSpec
                         type: object
```

**Comment by alex-zaitsev** [comment]
@Slach , please look

**Comment by Slach** [comment]
@ericisco which clickhouse-operator do you use?
@alex-zaitsev 
I tried following manifest
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: issue-756
  namespace: test
spec:
  defaults:
    templates:
       podTemplate: foo
  templates:
    podTemplates:
    - name: foo
      metadata:
        labels:	
          baz: qux
      spec:
        containers:
          - name: clickhouse
            image: yandex/clickhouse-server:21.8   
```        

in 0.15.1 and 0.16.0
all works as expected

labels is present on created Pod

![image](https://user-images.githubusercontent.com/105560/134820466-ef837296-8385-4b08-aa16-52974165c81f.png)

@ericisco is issue still relevant for you?
if yes, could you share your `ClickHouseInstallation` manifest?
