### ISSUE TITLE
getting cannot set blockOwnerDeletion, ownerReference resource you can't set finalizers

### ISSUE THREAD

**Issue by zeagur** [Altinity/clickhouse-operator#759]
Hi,

I'm trying to install clickhouse-operator in Openshift 4.2 cluster, following the doc provided in this github [here](https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md#clickhouse-operator-installation)

however, after apply a simple `ClickHouseInstallation` I got some error event about unable to set finalizers on certain resources and stuck there, no pod spawned.

Can you help on this one?

![image](https://user-images.githubusercontent.com/43737901/130057098-83ea6e09-89a1-4066-a3cb-b3e317c7e6bd.png)

**Comment by zeagur** [comment]
it seems I have to manually update operator cluster role with the following finalizers in order to make this works.

```
  - verbs:
      - update
    apiGroups:
      - clickhouse.altinity.com
    resources:
      - clickhouseinstallations/finalizers
      - clickhouseinstallationtemplates/finalizers
      - clickhouseoperatorconfigurations/finalizers
```
