### ISSUE TITLE
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

### ISSUE THREAD

**Issue by rsaphala** [Altinity/clickhouse-operator#762]
I get this warning when running the below script:

```
kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/0.15.0/deploy/operator/clickhouse-operator-install.yaml
```

```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

Any way to turn off this warning? I'm using k8s 1.19

**Comment by rolinh** [comment]
The CRD definition needs to be updated to use `apiextensions.k8s.io/v1` instead of `apiextensions.k8s.io/v1beta1`. The list if required changes are [documented in the Kubernetes doc](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122). I don't know if someone is already working on this but this means that the ClickHouse operator doesn't run on Kubernetes 1.22+, which is rather unfortunate.

**Comment by Slach** [comment]
@rolinh i tried to make changes, but got something strange results
everything works except `spec.versions[*].additionalPrinterColumns`
when I try to `kubectl get chi` i get empty custom columns value
when I try to `kubectl get chi chi-name -o yaml` status missing
look like "status" doesn't expect in custom resource anymore, could you suggest anything?

**Comment by su-houzhen** [comment]
@Slach In my mind: 
When use `apiextensions.k8s.io/v1`, when storing CR into `etcd` / getting CR  from `etcd`, it strictly implements openAPIV3Schema to trim CR.
It is, the fields not specified in openAPIV3Schema would be trimmed, unless you specify it or use `x-kubernetes-preserve-unknown-fields: true`.Therefore, undefined fields will be trimmed, and the information stored in CR will become incomplete.
Attention: `x-kubernetes-preserve-unknown-fields` is only valid in the current field, and the fields contained in the current field will continue to be trimmed.

I am also tring to do this.

**Comment by Slach** [comment]
@su-houzhen , @bmcustodio, @rolinh 
may you suggest a properly solution

I tried to add following
```yaml
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
```
without any success (I tried `subresources` and `properties -> status` both and separately in any combination)
after the creation of custom resources `status` field is still not present on `clickhouse describe chi <chi-name>`
but clickhouse-operator reports successful updates of custom resources `kind: ClickhouseInstallaion` and successful add events to describe

**Comment by su-houzhen** [comment]
maybe should add another `x-kubernetes-preserve-unknown-fields: true`. like this:
```yaml
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
```

**Comment by Slach** [comment]
@su-houzhen it doesn't help

**Comment by su-houzhen** [comment]
emmm, but it works on my environment. This is my complete CRD.

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clickhouseinstallations.clickhouse.altinity.com
spec:
  group: clickhouse.altinity.com
  scope: Namespaced
  names:
    kind: ClickHouseInstallation
    singular: clickhouseinstallation
    plural: clickhouseinstallations
    shortNames:
      - chi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: version
          type: string
          description: Operator version
          priority: 1 # show in wide view
          jsonPath: .status.version
        - name: clusters
          type: integer
          description: Clusters count
          priority: 0 # show in standard view
          jsonPath: .status.clusters
        - name: shards
          type: integer
          description: Shards count
          priority: 1 # show in wide view
          jsonPath: .status.shards
        - name: hosts
          type: integer
          description: Hosts count
          priority: 0 # show in standard view
          jsonPath: .status.hosts
        - name: status
          type: string
          description: CHI status
          priority: 0 # show in standard view
          jsonPath: .status.status
        - name: updated
          type: integer
          description: Updated hosts count
          priority: 1 # show in wide view
          jsonPath: .status.updated
        - name: added
          type: integer
          description: Added hosts count
          priority: 1 # show in wide view
          jsonPath: .status.added
        - name: deleted
          type: integer
          description: Hosts deleted count
          priority: 1 # show in wide view
          jsonPath: .status.deleted
        - name: delete
          type: integer
          description: Hosts to be deleted count
          priority: 1 # show in wide view
          jsonPath: .status.delete
        - name: endpoint
          type: string
          description: Client access endpoint
          priority: 1 # show in wide view
          jsonPath: .status.endpoint
```
