### ISSUE TITLE
is it possible to use gp3-encrypted SC as pcv for the clickhouse pods? ?

### ISSUE THREAD

**Issue by roimor** [Altinity/clickhouse-operator#763]

**Comment by alex-zaitsev** [comment]
Yes, you need to add a corresponding storage class and refer it in PVC.
Here is an example:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3-encrypted
provisioner: ebs.csi.aws.com
parameters:
  encrypted: 'true'
  fsType: ext4
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

And then in PVC template of ClickHouseInstallation:
```
    volumeClaimTemplates:
       - name: default
         spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
          storageClassName: gp3-encrypted
```
