### ISSUE TITLE
What is the best way to add more Gigs to PVC ? without any downtime

### ISSUE THREAD

**Issue by roimor** [Altinity/clickhouse-operator#764]
for example i have this volume claim already mounted:
```
    volumeClaimTemplates:
      - name: data-storage-vc
        persistentVolumeClaim:
          metadata:
            name: USE_DEFAULT_NAME
        spec:
          storageClassName: encrypted-gp2 # USING AN ENCRYPTED EBS VOLUME
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 900Gi
```

what is the best way to increase/add storage request without any downtime?
