### ISSUE TITLE
Help with settings

### ISSUE THREAD

**Issue by ben-pr-p** [Altinity/clickhouse-operator#768]
I am trying to use the [`MaterializedPostgreSQL`](https://clickhouse.tech/docs/en/engines/database-engines/materialized-postgresql/?) table engine, but getting:
```sql
:) CREATE DATABASE spoke_stoptherecall_materialized
:-] ENGINE = MaterializedPostgreSQL(
:-]   'host:port', 
:-]   'database',
:-]   'user', 
:-]    'password'
:-] )
:-] SETTINGS materialized_postgresql_tables_list = 'my_table';

Code: 336. DB::Exception: Received from localhost:9000. DB::Exception: MaterializedPostgreSQL is an experimental database engine. Enable allow_experimental_database_postgresql_replica to use it.. 
```
Here is my `ClickhouseInstallation` definition:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-stoptherecall"
  namespace: "data-engineering"
spec:
  usesTemplates:
    - name: clickhouse-latest
  defaults:
    templates:
      dataVolumeClaimTemplate: volume-template
      logVolumeClaimTemplate: volume-template
  configuration:
    profiles:
      allow_experimental_database_postgresql_replica: true
    settings:
      allow_experimental_database_postgresql_replica: true
    clusters:
      - name: "stoptherecall"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    volumeClaimTemplates:
      - name: "clickhouse-stoptherecall-volume-template"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```
How can I properly enable this setting?
