### ISSUE TITLE
k8s 1.20.10 clickhouse-operator-0.15.0: clickhouse-operator can not read Username|Password from Secret 

### ISSUE THREAD

**Issue by engineater** [Altinity/clickhouse-operator#774]
Click-operator does not use Secret for USER/PASSWORD  chUsername/chPassword.
It is look that it can't read Secret from namespace.

kubernetes 1.20.10
clickhouse-operator-0.15.0

```yaml
#clickhouse-operator-0.15.0/config/config.yaml

# List of namespaces where clickhouse-operator watches for events.
# Concurrently running operators should watch on different namespaces
watchNamespaces:
  - clickhouse
  - clickhouse-operator


#### there is more settings here

# when i use with this, that will be no DB::Exception
#chUsername: click_operator
#chPassword: asdfghj123456

# Location of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
# Can be used instead of explicitly specified username and password
chCredentialsSecretNamespace: "clickhouse"
chCredentialsSecretName: "chop-clickhouse-credentials"
```

```yaml
# clickhouse-operator-0.15.0/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: clickhouse
  name: chop-clickhouse-credentials
type: Opaque
stringData:
  username: click_operator
  password: asdfghj123456
```
```shell
$ kubectl create ns clickhouse
$ kubectl apply -f ~/repo/clickhouse/clickhouse-operator-0.15.0/config/secret.yaml -n=clickhouse
$ cd ~/repo/clickhouse/clickhouse-operator-0.15.0/deploy/operator/
$ cat clickhouse-operator-install.sh | OPERATOR_NAMESPACE=clickhouse-operator bash
$ kubectl apply -f ~/repo/clickhouse/superbase.yaml -n=clickhouse
```

It is look like it try login from DEFAULT user. Damn!!! But where is my "click_operator" user?
```
#clickhouse-operator log
W0911 03:11:04.820074       1 announcer.go:245] cluster.go:89:QueryAny():FAILED to run query on: chi-superbase-big-0-0.clickhouse.svc.cluster.local of [chi-superbase-big-0-0.clickhouse.svc.cluster.local chi-superbase-big-0-1.clickhouse.svc.cluster.local chi-superbase-big-0-2.clickhouse.svc.cluster.local] skip to next. err: clickhouse: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 20.7.4.11 (official build))
```

**Comment by sunsingerus** [comment]
Probably I am missing something, but in provided code snippet I do not see specified config file (`clickhouse-operator-0.15.0/config/config.yaml`) being actually applied.

**Comment by engineater** [comment]
> Probably I am missing something, but in provided code snippet I do not see specified config file (`clickhouse-operator-0.15.0/config/config.yaml`) being actually applied.
```shell
$ cd ~/repo/clickhouse/clickhouse-operator-0.15.0/deploy/operator/
$ cat clickhouse-operator-install.sh | OPERATOR_NAMESPACE=clickhouse-operator bash
```
clickhouse-operator-0.15.0/deploy/operator/clickhouse-operator-install.sh
      OPERATOR_NAMESPACE="${OPERATOR_NAMESPACE}" ${CUR_DIR}/build-clickhouse-operator-install-yaml.sh
            generate "clickhouse-operator-0.15.0/deploy/operator/clickhouse-operator-install.yaml" from config files (also from clickhouse-operator-0.15.0/config/config.yaml)
      kubectl apply --validate=${VALIDATE_YAML} --namespace="${OPERATOR_NAMESPACE}" -f "${CUR_DIR}/**clickhouse-operator-install.yaml**"


in  clickhouse-operator-0.15.0/deploy/operator/**clickhouse-operator-install.yaml** we can see this part of code
```yaml
---
# Possible Template Parameters:
#
# clickhouse-operator
# altinity/clickhouse-operator:0.15.0
# etc-clickhouse-operator-files
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-clickhouse-operator-files
  namespace: clickhouse-operator
  labels:
    app: clickhouse-operator
data:
  config.yaml: |
      ### here we see
      # Location of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
      # Can be used instead of explicitly specified username and password
      chCredentialsSecretNamespace: "clickhouse"
      chCredentialsSecretName: "chop-clickhouse-credentials"

```

**Comment by alex-zaitsev** [comment]
@engineater , try to restart operator pod, just in case. It does not pick up any configuration changes that were done after the pod has started.

**Comment by engineater** [comment]
> @engineater , try to restart operator pod, just in case. It does not pick up any configuration changes that were done after the pod has started.

I have tried and haves same 
```log
W0914 01:28:38.134265       1 announcer.go:245] exec():chi-superbase-big-0-0.clickhouse.svc.cluster.local:FAILED single try. No retries will be made for Applying sqls
E0914 01:28:38.143446       1 announcer.go:265] connection.go:177:Exec():FAILED Exec(http://***:***@chi-superbase-big-0-1.clickhouse.svc.cluster.local:8123/) clickhouse: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 20.7.4.11 (official build))
 for SQL: SYSTEM DROP DNS CACHE
```

Well I have only one decision for me is add some print log in this part of code:
```go
// clickhouse-operator-0.15.0/pkg/chop/config_manager.go


	// Figure out namespace where to look for the secret
	namespace := cm.config.CHCredentialsSecretNamespace
	if namespace == "" {
		// No namespace explicitly specified, let's look into namespace where pod is running
		if cm.HasRuntimeParam(chiv1.OPERATOR_POD_NAMESPACE) {
			// Unable to figure out namespace where pod is running, can not continue
            // HERE
			return
		}
		namespace, _ = cm.GetRuntimeParam(chiv1.OPERATOR_POD_NAMESPACE)
	}

	// Sanity check
	if (namespace == "") || (name == "") {
        // HERE
		return
	}

	secret, err := cm.kubeClient.CoreV1().Secrets(namespace).Get(context.TODO(), name, metav1.GetOptions{})
	if err != nil {
        // HERE
		return
	}
```

Could anyone help me how can I build docker file by myself ???

P.S. Go is not my programming language ;)

**Comment by Slach** [comment]
@engineater short instruction

```bash
git clone https://github.com/Altinity/clickhouse-operator/ /opt/clickhouse-opeartor
cd /opt/clickhouse-operator
# change files and run build script
# add MINIKUBE=yes if you have minikube kubernetes cluster runned locally
TAG=altinity/clickhouse-operator:0.15.0 bash -x ./dev/image_build_operator_universal.sh
# check image 0.15.0 exists
docker image ls | grep clickhouse-operator
```

**Comment by alex-zaitsev** [comment]
@engineater , could you try installing operator and chi in the same namespace, please. Probably there is something with access permissions cross namespaces.

**Comment by engineater** [comment]
I add new code """log.V(1).Info("!!!!! some text")""" and create my Docker image.
```go
// pkg/chop/config_manager.go

// fetchSecretCredentials
func (cm *ConfigManager) fetchSecretCredentials() {
	// Secret name where to look for credentials
	name := cm.config.CHCredentialsSecretName

	// Do we need to fetch credentials from the secret?
	if name == "" {
		log.V(1).Info("!!!!! name is empty")
		// No name specified, no need to read secret
		return
	}

	// We have secret name specified, let's move on and read credentials

	// Figure out namespace where to look for the secret
	namespace := cm.config.CHCredentialsSecretNamespace
	if namespace == "" {
		log.V(1).Info("!!!!! %s", "namespace is empty")
		// No namespace explicitly specified, let's look into namespace where pod is running
		if cm.HasRuntimeParam(chiv1.OPERATOR_POD_NAMESPACE) {
			// Unable to figure out namespace where pod is running, can not continue
			log.V(1).Info("!!!!! %s", "Unable to figure out namespace where pod is running, can not continue")
			return
		}
		namespace, _ = cm.GetRuntimeParam(chiv1.OPERATOR_POD_NAMESPACE)
		log.V(1).Info("!!!!! now namespace is %s", namespace)
	}

	// Sanity check
	if (namespace == "") || (name == "") {
		log.V(1).Info("!!!!! namespace is empty and name is empty")
		return
	}

	secret, err := cm.kubeClient.CoreV1().Secrets(namespace).Get(context.TODO(), name, metav1.GetOptions{})
	if err != nil {
		log.V(1).Info("!!!!! error on get secret: %s", err)
		return
	}

	log.V(1).Info("!!!!! everything is fine")

	// Find username and password from credentials
	for key, value := range secret.Data {
		switch key {
		case "username":
			cm.config.CHCredentialsSecretUsername = string(value)
			log.V(1).Info("!!!!! cm.config.CHCredentialsSecretUsername = %s", cm.config.CHCredentialsSecretUsername)
		case "password":
			cm.config.CHCredentialsSecretPassword = string(value)
			log.V(1).Info("!!!!! cm.config.CHCredentialsSecretPassword = %s", cm.config.CHCredentialsSecretPassword)
		}
	}
}
```

Now logs of pod clickhouse-operator I see
```log
I0920 07:15:38.895457       1 announcer.go:218] !!!!! error on get secret: secrets "chop-clickhouse-credentials" is forbidden: User "system:serviceaccount:clickhouse-operator:clickhouse-operator" cannot get resource "secrets" in API group "" in the namespace "clickhouse-operator"
```

**Comment by Slach** [comment]
Please look to
`kubectl get clusterrole (kubectl get clusterrole | grep clickhouse-operator) -o yaml`

save output to file clusterole.yaml
edit it and add in the end
```
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
```
and run
`kubectl apply -f clusterrole.yaml`

thanks for reporting, we will fix it on 0.16.0 release

**Comment by engineater** [comment]
Cheers @Slach 
In deploy/dev/clickhouse-operator-install-yaml-template-02-section-rbac.yaml I added secrets section
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-operator-${OPERATOR_NAMESPACE}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - secrets
```

Works perfect.
Thanks for everyone!
