### ISSUE TITLE
Проблема с VolumeClaimTemplate

### ISSUE THREAD

**Issue by RadikSeyfullin** [Altinity/clickhouse-operator#782]
Проблема заключается в том, что при создании экземпляра Clickhouse кластера (1 реплика 1 шард) не создаются указанные pvc.

Манифест для создания standalone click house
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "single-dev"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessMode:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

При применении этого манифеста создаётся объект chi `single-dev` и стейтфулсет `chi-single-dev-...` (который не создаёт под). Ошибка, которая видна в `describe statefulset`.
```
create Claim data-volume-template-chi-single-dev-single-dev-0-0-0 for Pod chi-single-dev-single-dev-0-0-0 in StatefulSet chi-single-dev-single-dev-0-0 failed error: PersistentVolumeClaim "data-volume-template-chi-single-dev-single-dev-0-0-0" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]
```
При этом в манифесте я всё это указываю
Если посмотреть на манифест стейтфулсета как yaml, то в `volumeClaimTemplates.[0].spec` пусто (нет тех значений, которые я указал при создании).
PVC тоже не создаёт.

**Важное уточнение**
Я обновил CRD до версии api `"apiextensions.k8s.io/v1"`
Всё что я сделал: 
- занёс `additionalPrinterColumns` и validation (изменил на schema) в новую переменную в spec versions (убрал старый version)
- А также заменил `JSONPath` на `jsonPath`

Файл с CRD могу прислать по запросу

---

Несколько скриншотов: 

Ошибка от statefulset:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/25140510/134332960-bff36988-f81d-49a2-bb5f-4d87c1f2abfa.png)

Statefulset как yaml, раздел volumeClaimTemplates
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/25140510/134332968-77c3bd96-1fd7-4162-be64-025dc5116fc7.png)

Kubernetes: v1.18.17
Storage provider: Ceph

**Comment by RadikSeyfullin** [comment]
Проблема повторяется на:
- minikube k8s v1.22.1 (с переделанным crd под v1)
- minikube k8s v1.18.17 (с переделанным crd под v1)
- minikube k8s v1.18.17 (без изменения crd)

**Comment by Slach** [comment]
в манифесте у вас "accessMode:"
а спецификация требует "accessModes"

**Comment by Slach** [comment]
У меня ваш манифест после смены accessMode на accessModes
прекрасно работает

установка оператора в kube-system
```
kubectl apply -f https://github.com/Altinity/clickhouse-operator/raw/0.16.0/deploy/operator/clickhouse-operator-install-bundle.yaml
```

sinfle-dev.yaml
```
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: single-dev
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```              

kubectl apply -f single-dev.yaml

показывает все PVC с нормальными статусами
