### ISSUE TITLE
Multiple disks configuration

### ISSUE THREAD

**Issue by Zeka13** [Altinity/clickhouse-operator#789]
Hello! Thanks for a great operator. 

I am kinda new in Clickhouse and trying to understand how I can configure multiple disk in it.

I found this example https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/03-persistent-volume-07-multiple-resizable-volumes-3.yaml and it works perfectly from Kubernetes perspective,

```
              volumeMounts:
                - name: data-storage-vc-template-1
                  mountPath: /data/clickhouse-01
                - name: data-storage-vc-template-2
                  mountPath: /data/clickhouse-02
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
```

but in Clickhouse I don't see any of this volumes, only default filesystem clickhouse sees as /var/lib/clickhouse

```
SELECT
    name,
    path,
    formatReadableSize(free_space) AS free,
    formatReadableSize(total_space) AS total,
    formatReadableSize(keep_free_space) AS reserved
FROM system.disks
```

Can you please point me to the part I am missing?

Thanks in advance
