### ISSUE TITLE
bi-level sharding

### ISSUE THREAD

**Issue by lukeSky3434** [Altinity/clickhouse-operator#794]
Hello,

in the clickhouse documentation there is a description, that you can setup the cluster with bi-level sharding - to divide the entire cluster into layers.

I found that you can define these macros over the setting, but that means, that every shard has the same layer:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  configuration:
    clusters:
      - name: "dwh"
        layout:
          shardsCount: 2
          replicasCount: 3 
          internalReplication: Enabled
    settings:
      macros/layer: 2
```

How can I handle such bi-level shards with the operator?

Greetings,
Luke
