### ISSUE TITLE
Operator update with helm chart with new files does not create new files

### ISSUE THREAD

**Issue by bobmorley** [Altinity/clickhouse-operator#800]
When we push out this new helmchart the files that are created in the spec do not get created. The previous version did not have the two new proto files. So when operator creates new pods based on this installation, it ultimately attempts to do the mkdir/cp that is down in `initContainers` and fails because the new fields do not exist.

I am not familiar with how and when the files that are contained in the spec get invoked by the operator. Is there a special mode or something that can ensure these execute as part of the clickhouse pod initialization?

```
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: {{ include "common-clickhouse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common-clickhouse.name" . }}
    helm.sh/chart: {{ include "common-clickhouse.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  defaults:
    templates:
      serviceTemplate: clickhouse-service
  configuration:
    zookeeper:
      nodes:
        - host: {{ .Values.zookeeper.servers }}
          port: 2181
    settings:
      logger/level: "warning"
      max_table_size_to_drop: 1000000000
      max_partition_size_to_drop: 1000000000
    files:
      users.d/admin.xml: |
        <yandex>
          <users>
            <admin>
              <password from_env="CLICKHOUSE_ADMIN_PASSWORD" />
              <profile>default</profile>
              <quota>default</quota>
              <access_management>1</access_management>
              <networks>
                <ip>::/0</ip>
              </networks>
             </admin>
          </users>
        </yandex>
      entity.proto: |
        {{ range .Files.Lines "schemas/entity.proto" }}
        {{ . }}{{ end }}
      service.proto: |
        {{ range .Files.Lines "schemas/service.proto" }}
        {{ . }}{{ end }}
    clusters:
      - name: clickhouse
        # Templates are specified for this cluster explicitly
        templates:
          podTemplate: clickhouse
          podVolumeClaimTemplate: data
        layout:
          shardsCount: {{ .Values.clickhouse.shards }}
          replicasCount: {{ .Values.clickhouse.replicas }}
  templates:
    serviceTemplates:
      - name: clickhouse-service
        generateName: clickhouse
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
          type: {{ .Values.clickhouse.service.type }}
        {{- with .Values.clickhouse.service.selector }}
          selector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    podTemplates:
      - name: clickhouse
        generateName: "{chi}-{host}"
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:{{ .Values.clickhouse.version }}
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
              envFrom:
              - secretRef:
                  name: clickhouse
            {{- with .Values.clickhouse.env }}
              env:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.container.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
            {{- end }}
              volumeMounts:
                - name: data
                  mountPath: /var/lib/clickhouse
          initContainers:
            - name: copy
              image: alpine:latest
              command: ["sh", "-xc", "mkdir -p /var/lib/clickhouse/format_schemas/; cp -L -rfv /etc/clickhouse-server/config.d/*.proto /var/lib/clickhouse/format_schemas/"]
              volumeMounts:
                - name: data
                  mountPath: /var/lib/clickhouse
                - name: chi-clickhouse-common-configd
                  mountPath: /etc/clickhouse-server/config.d
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    volumeClaimTemplates:
      - name: data
        # Adding this option forces the operator to NOT delete the PVC after a resize is performed
        # and a pod is not needed anymore. Data will only be deleted if it is manually removed.
        reclaimPolicy: Retain
        spec:
          storageClassName: {{ .Values.clickhouse.volume.storageClassName }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.volume.capacity }}
```
