### ISSUE TITLE
Replica data inconsistent if kill pod when writing data

### ISSUE THREAD

**Issue by su-houzhen** [Altinity/clickhouse-operator#811]
I am using ClickHouse cluster on kubernetes for high availability testing.
In the process of writing data, I exec `kill 1` in clickhouse pod, and wait for the pod to restart automatically and data write complete.
After the test, I found that part of the data of the killed ClickHouse pod was lost.

Here is some information:
Test tool: tsbs
ClickHouse version: 21.3
ClickHouse Cluster: 2 shards 2 replicas
Data replication method: Distributed + MergeTree

```bash
# kubectl exec -it chi-click-all-nodes-0-0-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1726207
# kubectl exec -it chi-click-all-nodes-0-1-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1726207
# kubectl exec -it chi-click-all-nodes-1-0-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1729793
# kubectl exec -it chi-click-all-nodes-1-1-0 -n clickhouse -c clickhouse -- clickhouse-client --query 'SELECT COUNT() FROM test2.cpu_tags_metrics'
1728782
```

**Comment by Slach** [comment]
Did you define `volumeClaimTemplates` in your `kind: ClickHouseInstallation` manifest?

**Comment by su-houzhen** [comment]
yes. This is my full CR.

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: click
  namespace: clickhouse
spec:
  configuration:
    zookeeper:
       nodes:
         - host: zookeeper-0.zookeepers.clickhouse
           port: 2181
         - host: zookeeper-1.zookeepers.clickhouse
           port: 2181
         - host: zookeeper-2.zookeepers.clickhouse
           port: 2181
    users:
      readonly/profile: readonly
      clickhouse/password: c1ickh0use0perator
      clickhouse/networks/ip:
        - 127.0.0.1
        - ::/0
      clickhouse/profile: default
      clickhouse/quotas: default
    profiles:
      readonly/readonly: "1"
    quotas:
      default/interval/duration: "3600"
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
    clusters:
      - name: all-nodes
        templates:
          podTemplate: pod-template-with-volume
        layout:
          shardsCount: 2
          replicasCount: 2
 
  defaults:
    templates:
      podTemplate: pod-template-with-volume
      dataVolumeClaimTemplate: data
      logVolumeClaimTemplate: data
      serviceTemplate: chi-svc-template
 
  templates:
    serviceTemplates:
      - name: chi-svc-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
 
    podTemplates:
      - name: pod-template-with-volume
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: "clickhouse.altinity.com/chi"
                          operator: In
                          values:
                            - test
                    topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:21.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: data
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: 4Gi
                  cpu: 2
                limits:
                  memory: 4Gi
                  cpu: 2
 
    volumeClaimTemplates:
      - name: data
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```
