### ISSUE TITLE
DBeaver to Clickhouse in Kubernetes connection

### ISSUE THREAD

**Issue by Tomislav24i** [Altinity/clickhouse-operator#822]
I was able to connect to the clickHouse database running via independent instance on AWS with DBeaver without problem.
But now as database is running in Kubernetes on AWS and ClickHouse is open to public, I am not able to connect with DBeaver.
With some other apps, I do not have problem with connection.
Do I need to adjust some special setting in DBeaver to connect to ClickHouse running in Kubernetes on AWS?

**Comment by Slach** [comment]
Could you share your `kind: ClickHouseInstallation` manifest?

When you set up `clickhouse` via `clickhouse-operator`, by default it creates one service with `type: LoadBalancer`
check it
```kubectl get svc --all-namespaces -o wide | grep Load | grep chi```

and check external `LoadBalancer` DNS name like
`c1ca6a04611544ae195f69367c4ec043-c28c310e0e208e73.elb.us-east-1.amazonaws.com`

Moreover, you should define your custom user which allow connecting from external hosts, cause `default` user restricted to `127.0.0.1` 

look to ` kubectl explain chi.spec.configuration.users`, https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#specconfigurationusers and https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/05-settings-03-2-user2.yaml
for examples

**Comment by xgengsjc2021** [comment]
@Slach Hi I have an internal LoadBalancer setting here here and a test user account, 
```
service-clickhouse                   LoadBalancer   172.20.136.205   a523d9524-bbe659915e57d664.elb.us-west-2.amazonaws.com   8123:31209/TCP,9000:31062/TCP   46h
```
```
# config in my clickhouse installation yaml
users:
      test/password: test123
      test/networks/ip:
        - "0.0.0.0/0"
      test/profile: default
```

I put the dns name mentioned above in the Host section in DBeaver, but still got the connection timeout. Is this right? (Btw, I did port-forward first, then tried to connect the clickhouse through DBeaver. )

```
kubectl -n clickhouse port-forward svc/service-clickhouse 8123
```

![Screenshot2022_06_17_120311](https://user-images.githubusercontent.com/79334945/174386928-4b677634-21d9-4eb9-98ed-ed6a27d5bb36.jpg)

**Comment by xgengsjc2021** [comment]
![Screenshot2022_06_17_120233](https://user-images.githubusercontent.com/79334945/174387495-471bde90-bdb2-49b5-93b7-c01030ac3970.jpg)

**Comment by Slach** [comment]
![image](https://user-images.githubusercontent.com/105560/174489777-59b50bc3-420d-4efc-990c-4ad745fd8e7e.png)

**Comment by Slach** [comment]
> kubectl -n clickhouse port-forward svc/service-clickhouse 8123

it should allow connect to localhost:8123

**Comment by xgengsjc2021** [comment]
@Slach for the DNS name, I just remove part of if on purpose. I did not show the whole DNS name here.  For now, I run port-forward and then run DBeaver with the right DNS name but still timeout. What else I need to do when I try to connect ClickHouse database through DBeaver?

**Comment by Slach** [comment]
did you try to connect to localhost:8123 after port forward?

**Comment by xgengsjc2021** [comment]
@Slach yes, I tried but it did not open a web page.

**Comment by Slach** [comment]
do you mean 
`curl -vvv http://localhost:8123`
show nothing?
`kubectl port-forward` is still running in separate terminal window?

**Comment by xgengsjc2021** [comment]
@Slach I want to specify that my LoadBalancer is the internal one not the external LoadBalancer. 
After  
```
 kubectl -n clickhouse port-forward svc/service-ch-cn-01 8123
```

I opened a web page and 
```
http://localhost:8123/
```

![Screenshot2022_06_19_234537](https://user-images.githubusercontent.com/79334945/174541217-40dcc6fd-d5fc-46d2-a95d-94146e553d92.jpg)

**Comment by xgengsjc2021** [comment]
my service template
```
serviceTemplates:
      - name: chi-service-template
        generateName: "service-{chi}"
        metadata:
          labels:
            custom.label: "custom.value"
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"

            # NLB Load Balancer
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

        # type ServiceSpec struct from k8s.io/core/v1
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
```

**Comment by Slach** [comment]
why you try https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml ? what is the root reason?

why you just not use simple CHI installation and add necessary parts if you really need it

try use something like https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/01-simple-layout-02-1shard-2repl.yaml

**Comment by Slach** [comment]
which cloud provider do you use?

**Comment by xgengsjc2021** [comment]
@Slach I am using AWS EKS to host clickhouse. 
Although I use https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml, but I did not use all of the settings in this file. Mainly, we want to assign the clickhouse pod to each node in different available zone.

**Comment by xgengsjc2021** [comment]
@Slach my customized config
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch-cn-01"
  namespace: "clickhouse"

spec:

  restart: "RollingUpdate"]

  reconciling:
    policy: "nowait"
    configMapPropagationTimeout: 90
    cleanup:
      unknownObjects:
        statefulSet: Delete
        pvc: Delete
        configMap: Delete
        service: Delete
      reconcileFailedObjects:
        statefulSet: Retain
        pvc: Retain
        configMap: Retain
        service: Retain

  defaults:
    replicasUseFQDN: "no"
    distributedDDL:
      profile: default
    templates:
      hostTemplate: host-template-custom-ports
      dataVolumeClaimTemplate: default-volume-claim
      logVolumeClaimTemplate: default-volume-claim
      serviceTemplate: chi-service-template

  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoons
          port: 2181
        - host: zookeeper-1.zookeepers.zoons
          port: 2181
        - host: zookeeper-2.zookeepers.zoons
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
    users:
      # test user has 'password' specified, while admin user has 'password_sha256_hex' specified
      test/password: test123
      test/networks/ip:
        - "0.0.0.0/0"
      test/profile: default
      admin/password_sha256_hex: 749f09bade8aca755660eeb17792da880218d4fbdc4e25fbec279d7fe9f65d70
      admin/networks/ip: 
        - "127.0.0.1/32"
        - "10.0.0.0/8"
      admin/profile: default
      admin/quota: default
      # readonly user has 'password' field specified, not 'password_sha256_hex' as admin user above
      readonly/password: readonly_password
      readonly/profile: readonly
      readonly/quota: default
    profiles:
      test_profile/max_memory_usage: 1000000000
      test_profile/readonly: 1
      readonly/readonly: 1
    quotas:
      default/interval/duration: "3600"
      default/interval/queries: 10000
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
    files:
      dict1.xml: |
        <yandex>
            <!-- ref to file /etc/clickhouse-data/config.d/source1.csv -->
        </yandex>
      source1.csv: |
        a1,b1,c1,d1
        a2,b2,c2,d2
    clusters:
      # spec.configuration.clusters.name in body should be at most 15 chars long
      - name: ch-cn-01
        layout:
          shards:
            - name: shard0
              replicas:
                - templates:
                    podTemplate: us-west-1a-v22_2
                - templates:
                    podTemplate: us-west-1b-v22_2
            - name: shard1
              replicas:
                - templates:
                    podTemplate: us-west-1b-v22_2
                - templates:
                    podTemplate: us-west-1c-v22_2
            - name: shard2
              replicas:
                - templates:
                    podTemplate: us-west-1c-v22_2
                - templates:
                    podTemplate: us-west-1a-v22_2
 
  templates:
    hostTemplates:
      - name: host-template-custom-ports
        spec:
          tcpPort: 7000
          httpPort: 7001
          interserverHTTPPort: 7002
    serviceTemplates:
      - name: chi-service-template
        generateName: "service-{chi}"
        # type ObjectMeta struct from k8s.io/meta/v1
        metadata:
          labels:
            custom.label: "custom.value"
          annotations:
            # For more details on Internal Load Balancer check
            # https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
            cloud.google.com/load-balancer-type: "Internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"

            # NLB Load Balancer
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

        # type ServiceSpec struct from k8s.io/core/v1
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer

      - name: replica-service-template
        # type ServiceSpec struct from k8s.io/core/v1
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
          clusterIP: None
    volumeClaimTemplates:
      - name: default-volume-claim
        reclaimPolicy: Retain
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    podTemplates:
      - name: us-west-1a-v22_2
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - us-west-1a
                  - key: k8s.xxxx.xxx/node-group
                    operator: In
                    values:
                    - CLICKHOUSE      
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.2
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse

      - name: us-west-1b-v22_2
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - us-west-1b
                  - key: k8s.xxxx.xxx/node-group
                    operator: In
                    values:
                    - CLICKHOUSE 
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.2
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse

      - name: us-west-1c-v22_2
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - us-west-1c
                  - key: k8s.xxxx.xxx/node-group
                    operator: In
                    values:
                    - CLICKHOUSE 
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.2
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse
      
      

```
