### ISSUE TITLE
Users config not being applied

### ISSUE THREAD

**Issue by alex88** [Altinity/clickhouse-operator#824]
Hi everyone, I'm trying to add a user in clickhouse using thie configuration:

```
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers
        - host: zookeeper-1.zookeepers
        - host: zookeeper-2.zookeepers
    clusters:
      - name: replicated
        layout:
          shardsCount: 1
          replicasCount: 2
    users:
      admin:
        profile: default
        password_sha256_hex: some_sha256_password
        access_management: 1
```

tried to apply config, restart operator, the `chi-clickhouse-common-usersd` configmap doesn't have the user nor the clickhouse server files.
Am I missing a step?

Note that I see some operator logs like these:
```
W1106 05:04:56.085797       1 reflector.go:436] pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseOperatorConfiguration ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"ClickHouseO
peratorConfiguration\" is registered for version \"clickhouse.altinity.com/v1\" in scheme \"pkg/client/clientset/versioned/scheme/register.go:30\"") has prevented the request from succeeding
```
but they don't show up again after restart

Update: after a while they eventually show again (without applying any config or anything)

**Comment by alex88** [comment]
Oh my fault, seems there's no support for full objects, just single line overrides

```
    users:
      admin/profile: default
      admin/password_sha256_hex: some_sha256_password
      admin/access_management: 1
```

this works
