### ISSUE TITLE
Deleting the operator while clusters are running can cause them to be deleted without warning

### ISSUE THREAD

**Issue by hodgesrm** [Altinity/clickhouse-operator#830]
Deleting the operator and then reinstalling it may cause currently running clusters to be deleted without warning. Here's a reproduction of the problem from current HEAD repo contents. 

1. Install operator according to instructions at docs.altinity.com: 
```kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml```
2. Start a cluster in default namespace by executing `kubectl apply -f simple-01-a.yaml` on attached file. Wait for cluster to install. 
3. Delete the operator (you have to ^C out of the command as it hangs): 
```kubectl delete -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml```
4. Install the operator again:
```kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml```
5. At this point two things happen. 
5.1 The simple-01-a.yaml cluster is deleted without warning. 
5.2 The new operator installation is broken. Trying to install a new cluster fails as shown below. 
```kubectl apply -f simple-01-a.yaml
error: unable to recognize "simple-01-a.yaml": no matches for kind "ClickHouseInstallation" in version "clickhouse.altinity.com/v1"
```
It looks as if 5.2 is explained by the following: 
```
kubectl api-resources|grep click
clickhouseinstallationtemplates    chit         clickhouse.altinity.com/v1             true         ClickHouseInstallationTemplate
clickhouseoperatorconfigurations   chopconf     clickhouse.altinity.com/v1             true         ClickHouseOperatorConfiguration
```
The chi resource is now missing after the cluster was deleted.

**Comment by hodgesrm** [comment]
Here's the simple-01-a.yaml file to create a cluster, since Github won't let me attach it. 
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "cl"
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:21.8.10.1.altinitystable
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
