### ISSUE TITLE
Clickhouse Golang Client problems

### ISSUE THREAD

**Issue by apibfilip** [Altinity/clickhouse-operator#832]
Dear all,

my deployment schema is:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "prod-01"
spec:
  configuration:
    zookeeper:
        nodes:
        - host: zookeeper.zoo1ns
          port: 2181
    clusters:
      - name: "prod-01"
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:21.1.10.3.altinitystable
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
```

I am trying to connect using the default user from another go application in Kubernetes using the loadbalancer cloud IP. The connection initiation as well as ping works. The same data retrieval code (below) gives different results when used, it seem like as if the loadbalancer connects only to a specific pod but on the next request it connects to a different pod and gives different result.

```golang	
   db, err := sql.Open("clickhouse", "tcp://10.100.65.133:9000?username="+os.Getenv("CLICKHOUSE_USERNAME")+"&password="+os.Getenv("CLICKHOUSE_PASSWORD")+"&debug=true")

	if err != nil {
		log.Fatal().Err(err).Msgf("Could not connect to Clickhouse db")
	}

	if err := db.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			log.Error().Err(err).Msg(fmt.Sprintf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace))
		} else {
			log.Error().Err(err).Msg("")
		}
		return err
	}

	rows, err := db.Query("SELECT * FROM table WHERE dstip='" + ipAddress + "'")
```	

Any help highly appreciated.

Filip

**Comment by Slach** [comment]
By default, `clickhouse-operator` restricts `default` user connection to `127.0.0.1` for security reason

you can add
```
spec:
  configuration:
    users:
      default/password: "setup_password"
      networks/ip: "0.0.0.0/0" 
```

and you should use IP address (or maybe DNS name will better) of your `kind: Service` which Will generated and cover replica or shard, or cluster or whole Installation

look services list on 
```
kubectl get svc --all-namespaces -o wide -l clickhouse.altinity.com/chi=prod-01
```

**Comment by apibfilip** [comment]
So I included the user in the spec and I can connect using the clickhouse-cli. However when I list the services using the provided snippet I only get cluster IP on the loadbalancer. When trying to connect using the cluster IP using Golang client I get permission denied error. Any ideas why this is happening?

Thank tou,
Filip

**Comment by Slach** [comment]
@apibfilip sorry, i miss `default` username in `users` specification for `networks/ip` key
so, properly manifest should look like this:

```yaml

spec:
  configuration:
    users:
      default/password: "setup_password"
      default/networks/ip: "0.0.0.0/0"
```
