### ISSUE TITLE
how to upgrade ClickHouse version upgrades ？

### ISSUE THREAD

**Issue by jessezax** [Altinity/clickhouse-operator#835]
just modify the image and apply？

**Comment by jessezax** [comment]
Will this lose data？

**Comment by Slach** [comment]
If your cluster has properly configured CSI / volume provisioner
data will not lose, when define  in your `kind: ClickHouseInstallation` something like that

```yaml
spec:
  templates:
    volumeClaimTemplates:
      - name: data
        reclaimPolicy: Retain
        spec:
          accessModes:
           - ReadWriteOnce
         resources:
           requests:
              storage: XXXGi # how much data size you need to storage data
   defaults:  
      dataVolumeClaimTemplate:  data   
```

after it, you can update image: in your `podTemplates` section

Moreover, will useful  look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md to understand format for `chi` custom resources
