### ISSUE TITLE
feature: templating for nodeSelector

### ISSUE THREAD

**Issue by UnamedRus** [Altinity/clickhouse-operator#841]
Ability to bind specific replicas/shards to k8s nodes without copy-paste whole podTemplate for each replica.

```
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: kubernetes.io/hostname
                 operator: In
                 values:
                 - hostname1
               - key: replica_name
                 operator: In
                 values:
                 - {replicaID}
```

It useful in case of local path provisioning.
