### ISSUE TITLE
missing cluster service

### ISSUE THREAD

**Issue by pschiffe** [Altinity/clickhouse-operator#860]
Hello,

when deploying clickhouse, service per pod is created correctly, but I'm not getting any service for whole cluster (with all pods):
```
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
chi-clickhouse-plausible-0-0   ClusterIP   None            <none>        8123/TCP,9000/TCP,9009/TCP   29d
chi-clickhouse-plausible-0-1   ClusterIP   None            <none>        8123/TCP,9000/TCP,9009/TCP   29d
```

`ClickHouseInstallation` YAML config:
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
  labels:
      app: clickhouse
spec:
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: service-template
      dataVolumeClaimTemplate: data-volumeclaim-template

  configuration:
    users:
{{ toYaml .Values.clickhouse.users | indent 8 }}

    zookeeper:
      nodes:
        - host: zookeeper.{{ .Release.Namespace }}
          port: {{ .Values.zookeeper.clientPort }}

    clusters:
      - name: "{{ .Values.clickhouse.clusterName }}"
        layout:
          shardsCount: {{ .Values.clickhouse.shards }}
          replicasCount: {{ .Values.clickhouse.replicas }}

    settings:
      http_port: {{ .Values.zookeeper.httpPort }}
      tcp_port: {{ .Values.zookeeper.tcpPort }}
      interserver_http_port: {{ .Values.zookeeper.interserverHttpPort }}

  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            custom.label: "label.value"
          annotations:
            custom.annotation: "annotation.value"
        spec:
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:{{ .Chart.AppVersion }}.altinitystable
              ports:
                - name: http
                  containerPort: {{ .Values.zookeeper.httpPort }}
                - name: tcp
                  containerPort: {{ .Values.zookeeper.tcpPort }}
                - name: interserver
                  containerPort: {{ .Values.zookeeper.interserverHttpPort }}
              zone:
                values:
                  - "{{ .Values.clickhouse.awsRegion }}"
                podDistribution:
                  - type: "ClickHouseAntiAffinity"
              resources:
                requests:
                  memory: "{{ .Values.clickhouse.resources.requests.memory }}"
                  cpu: "{{ .Values.clickhouse.resources.requests.cpu }}"
                limits:
                  memory: "{{ .Values.clickhouse.resources.limits.memory }}"
                  cpu: "{{ .Values.clickhouse.resources.limits.cpu }}"

    serviceTemplates:
      - name: service-template
        generateName: chendpoint-{chi}
        metadata:
          labels:
            custom.label: "custom.value"
        spec:
          ports:
            - name: http
              port: {{ .Values.zookeeper.httpPort }}
            - name: tcp
              port: {{ .Values.zookeeper.tcpPort }}
          type: ClusterIP

    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "{{ .Values.clickhouse.resources.requests.disk }}"
```

Am I missing something? Operator version is 0.17

Thank you.

**Comment by Slach** [comment]
you share part of helm chart
could you share
```
kubectl -n clickhouse get chi plausible -o yaml
```

also first look 
```
 port: {{ .Values.zookeeper.httpPort }}
```
doesn't look properly for describe clickhouse related services
so, maybe your helm chart just not applied cause you have empty template values?

also for re-define cluster level service
you should use
```yaml
spec:
  defaults:
    templates:
      clusterServiceTemplate: cluster-service-template
```
