### ISSUE TITLE
Operator auto delete PVC after ClickHouseInstallation 

### ISSUE THREAD

**Issue by vanducvo** [Altinity/clickhouse-operator#863]
Operator delete pvc after remove ClickHouseInstallation although PVC RECLAIM POLICY is 'Delete'
```  templates:
    volumeClaimTemplates:
      - name: {{ include "clickhouse.cluster.name" . }}
        spec:
          storageClassName: {{ .Values.cluster.storeClassName }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.cluster.size }}
```

**Comment by Slach** [comment]
> Operator delete pvc after remove ClickHouseInstallation although PVC RECLAIM POLICY is 'Delete'
Dou you mean you have "Retain" here? 
"Delete" reclaim policy means PVC will delete when delete CHI and its default behavior

look ` kubectl explain chi.spec.templates.volumeClaimTemplates`

use 
```yaml
  volumeClaimTemplates:
      - name: {{ include "clickhouse.cluster.name" . }}
        spec:
          reclaimPolicy: Retain
```
if you want avoid deletion of PVC
