### ISSUE TITLE
is grpc supported?

### ISSUE THREAD

**Issue by gauravphoenix** [Altinity/clickhouse-operator#864]
I can't seem to find an example and when I look at the source code, I don't see any relevant reference either

**Comment by Slach** [comment]
Do you mean gRPC interface for `clickhouse-server`?

It could be added to manifest with something like that:

```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "test-021-rescale-volume"
spec:
  serviceTemplates:
    - name: svc-with-grpc
      spec:
        ports:
          - name: grpc
            port: 9100
       type: LoadBalancer # or ClusterIP if you want access to clickhouse cluster only inside k8s network
  defaults:
    templates:
      serviceTemplate: svc-with-grpc
        
  configuration:
    files:
      config.d/grpc.xml: |
        <grpc_port>9100</grpc_port>
        <grpc>
            <enable_ssl>false</enable_ssl>
    
            <!-- The following two files are used only if SSL is enabled -->
            <ssl_cert_file>/path/to/ssl_cert_file</ssl_cert_file>
            <ssl_key_file>/path/to/ssl_key_file</ssl_key_file>
    
            <!-- Whether server requests client for a certificate -->
            <ssl_require_client_auth>false</ssl_require_client_auth>
    
            <!-- The following file is used only if ssl_require_client_auth=true -->
            <ssl_ca_cert_file>/path/to/ssl_ca_cert_file</ssl_ca_cert_file>
    
            <!-- Default compression algorithm (applied if client doesn't specify another algorithm, see result_compression in QueryInfo).
                 Supported algorithms: none, deflate, gzip, stream_gzip -->
            <compression>deflate</compression>
    
            <!-- Default compression level (applied if client doesn't specify another level, see result_compression in QueryInfo).
                 Supported levels: none, low, medium, high -->
            <compression_level>medium</compression_level>
    
            <!-- Send/receive message size limits in bytes. -1 means unlimited -->
            <max_send_message_size>-1</max_send_message_size>
            <max_receive_message_size>-1</max_receive_message_size>
    
            <!-- Enable if you want to get detailed logs -->
            <verbose_logs>false</verbose_logs>
        </grpc>     
      
```

**Comment by gauravphoenix** [comment]
I shall give that a try, last time I tried something like that, I ran into some GKE issues giving me errors like- IP address is already allocated.

**Comment by mhconradt** [comment]
Here's what to do, folks:

1. Set `spec.configuration.settings.grpc_port` to 9100, or whatever pleases you more.

```
spec:
  configuration:
    settings:
      grpc_port: 9100
```

2. Add an entry to `spec.templates.serviceTemplates` with the port from step 1 and port 9100 (there are some other ports too, like 8123 and 9009 that are normally created, but I'm only using 9000 elsewhere).
```
spec:
  templates:
    serviceTemplates:
      - name: svc-plus-grpc
        spec:
          ports:
            - name: grpc
              port: 9100
            - name: tcp
              port: 9000
          type: ClusterIP
```
3. Set `spec.configuration.clusters[*].templates.replicaServiceTemplate` to `svc-plus-grpc`.
```
spec:
  configuration:
    settings:
      grpc_port: 9100
    clusters:
      - name: "db"
        templates:
          replicaServiceTemplate: svc-plus-grpc
```
This works for me!
