### ISSUE TITLE
How to create multi-zonal cluster without duplicating config

### ISSUE THREAD

**Issue by gauravphoenix** [Altinity/clickhouse-operator#867]
I would like to have an `n` shard cluster with 3 replicas with each replica in three different GCP zones (I'm using GKE). 
The config I am using is this- 

```yaml
podTemplates:
      - name: clickhouse-pod-template
        spec:
          metadata:
            labels:
              app: ch-writer
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: failure-domain.beta.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app: ch-writer
```

Is this the right way to go about it? The multi-zone example listed [here](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/10-zones-01-simple-01-aws-pods-in-availability-zones.yaml) requires repeating `podTemplate` for each zone and I would like to avoid duplication.
