### ISSUE TITLE
load balancer service template question

### ISSUE THREAD

**Issue by kanlee** [Altinity/clickhouse-operator#880]
Hi, I was able to get the load balancer to work as expected with an external IP using [this example](https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/04-replication-zookeeper-05-simple-PV.yaml).  it doesn't specify service templates and just use some sort of default I am guessing.

but when I specified the default serviceTemplate as below, it doesn't work anymore.  connection to it times out.  

```yaml
    serviceTemplates:
      - name: chi-service-template
        generateName: "service-{chi}"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
```

I also noticed that with this default load balancer serviceTemplate, External Traffic Policy changed from Local to Cluster.  

Can you provide a load balancer service template that I can specify externally?

also, when I changed the default serviceTemplate from LoadBalancer to ClusterIP to disable external IP, 
does the cluster wide service still route traffic to all the clickhouse pods in my cluster?  Or is it now only routing to one specific pod?

Thank you!

**Comment by Slach** [comment]
After define `seriveTemplates[]` items you also should link this template as default `serviceTempate` with spec something like that:

```yaml
spec:
  defaults:
    templates:
      serviceTemplate: chi-service-template
  templates:
    serviceTemplates:
      - name: chi-service-template
        generateName: "clickhouse-{chi}"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer      
          externalTrafficPolicy: Local
```

Moreover, look to 
```
kubectl get svc --all-namespaces -l  clickhouse.altinity.com/app=chop
```
and watch External-IP column, maybe your `LoadBalancer` provider setup your service external IP to `pending` state

> I also noticed that with this default load balancer serviceTemplate, External Traffic Policy changed from Local to Cluster.

you can specify traffic policy via `serviceTemplates[].spec.externalTrafficPolicy`
look to ` kubectl explain svc.spec.externalTrafficPolicy` for details

> also, when I changed the default serviceTemplate from LoadBalancer to ClusterIP to disable external IP,
does the cluster wide service still route traffic to all the clickhouse pods in my cluster? Or is it now only routing to one specific pod?

It means traffic will balanced via kuberenetes pod network, every new TCP connection to service IP will land to round-robin  Pod with `ready` status

look to ` kubectl get endpoints --all-namespaces -l  clickhouse.altinity.com/app=chop`
to see which pods ip used as endpoint for all clickhouse-operator related status
