### ISSUE TITLE
Support for the ability to add schema files via cluster configuration 

### ISSUE THREAD

**Issue by bopohaa** [Altinity/clickhouse-operator#888]
We have
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    settings:
      format_schema_path: config.d/
    files:
      schema.proto: |
```
Schema file placed in `/etc/clickhouse-server/config.d/schema.proto`
But would like to have it in the right place - `/etc/clickhouse-server/format_schemas/schema.proto`
To do this, you need to specify something like this in the configuration 
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    settings:
      format_schema_path: format_schemas/
    files:
      FORMAT_SCHEMAS/schema.proto: |
```

**Comment by Slach** [comment]
You can use initContainer in custom podTemplate
Look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/20-protobuf-schema-example.yaml

**Comment by bopohaa** [comment]
> You can use initContainer in custom podTemplate Look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/20-protobuf-schema-example.yaml

This looks like a temporary solution. I can make my own pull request. Just not sure if that would be in line with the general policy.

**Comment by qrpike** [comment]
This example doesnt work due to the following lines: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/20-protobuf-schema-example.yaml#L46-L47

Any insight on how to fix this?

**Comment by czephyr** [comment]
> Look to https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/20-protobuf-schema-example.yaml

I think this has some errors. Both in practice since the volumes are not declared and the code as is won't start, both in theory since when you declare the said volumes you overwrite the `conf.d` folder and the InitContainer will be stuck without the file its looking for. 

I managed to write my proto schema in `/var/lib/clickhouse/schema_formats/` by simply mounting a ConfigMap on the path but using the SecurityContext construct you are using in the example. 
```
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
```
I'm not sure if this is a security breach since this changes the user my containers run with into the `clickhouse` user.
@Slach

**Comment by Slach** [comment]
@qrpike 
> This example doesnt work due to the following lines: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/20-protobuf-schema-example.yaml#L46-L47

this example works as expected

`chi-protobuf-example-common-configd` means configmap name which generated by `clickhouse-operator`
so, if you change your metadata name from protobuf-example to other you need to change this name in manifest

**Comment by Slach** [comment]
@czephyr 

> Would you please clarify on the reason it's not possible to write on the /var/lib/clickhouse/ folder without the securityContext and why we should use the initContainer approach just to move a file?

in example I just tried to realize all inside `kind: ClickHouseInstallation`  if you will manage external `kind: ConfigMap`
you could mount it inside `/var/lib/clickhouse/schema_formats/` directly

But, `clickhouse-server` and change their process UID after start to `clickhouse` (101) even if your container user is `root`
So, it requires applying `securityContext` to allow reading `.proto` files inside `clickhouse-server` process.

**Comment by czephyr** [comment]
> `chi-protobuf-example-common-configd` means configmap name which generated by `clickhouse-operator`
> so, if you change your metadata name from protobuf-example to other you need to change this name in manifest
the wouldnt you need a volume definition in there like
``` volumes:
            - name: chi-protobuf-example-common-configd
              configMap:
                name: name-of-configmap-generated-by-operator
```

**Comment by telperions** [comment]
@Slach Is there a way to update .proto files "on the fly" without restarting clickhouse pod and without creating sidecar which will copy proto files?
`cp -L -rfv /etc/clickhouse-server/config.d/*.proto /var/lib/clickhouse/format_schemas/`

**Comment by Slach** [comment]
@s-b90 try to mount ConfigMap with schemas directly into
`/var/lib/clickhouse/format_schemas/`
something like that

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-proto-schema
data:
  your_schema.proto: |
    syntax = "proto3";

    message MessageType {
      string name = 1;
      string surname = 2;
      uint32 birthDate = 3;
      repeated string phoneNumbers = 4;
    };
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "protobuf-example"
spec:
  configuration:
    clusters:
      - name: cluster
        layout:
          shardsCount: 1
          replicasCount: 1

  defaults:
    templates:
      podTemplate: pod-template-with-proto-mount
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template

  templates:
    podTemplates:
      - name: pod-template-with-proto-mount
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              volumeMounts:
                - name: proto-schema-volume
                  mountPath: /var/lib/clickhouse/format_schemas/
                  readOnly: true
          volumes:
            - name: proto-schema-volume
              configMap:
                name: clickhouse-proto-schema

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
```
