### ISSUE TITLE
Clickhouse Operator exception causes clickhouse cluster exception

### ISSUE THREAD

**Issue by czhfe** [Altinity/clickhouse-operator#890]
**Environment**
Clickhouse Operator version: 0.17.0

**Question**
Clickhouse Operator restart (oom, update, etc.) will cause clickhouse exceptions. The error is as follows:
```
2022.02.23 11:14:56.675790 [ 10484 ] {52fafb46-2a44-4028-9a3b-0e8d82237a02} <Error> TCPHandler: Code: 170, e.displayText() = DB::Exception: Requested cluster 'skyline' not found, Stack trace:
```
![image](https://user-images.githubusercontent.com/19341806/155258082-402971bc-0acd-477a-97ba-bb865b7b3f15.png)

> **Can Clickhouse Operator support running multiple copies?**

**Comment by Slach** [comment]
Could you share your `kind: ClickHouseInstallation` manifest?
Which layout do you use?

> Can Clickhouse Operator support running multiple copies?

Multiple copies of what do you need?
Do you mean multiple clickhouse-server instances? 

All clusters defined in ConfigMap and mounted in file `/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml`
I not sure OOM will root cause this exception.

**Comment by czhfe** [comment]
> Could you share your `kind: ClickHouseInstallation` manifest? Which layout do you use?
> 
> > Can Clickhouse Operator support running multiple copies?
> 
> Multiple copies of what do you need? Do you mean multiple clickhouse-server instances?
> 
> All clusters defined in ConfigMap and mounted in file `/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml` I not sure OOM will root cause this exception.

**1、ClickHouseInstallation manifest**
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: clickhouse
spec:
  defaults:
    templates: 
      dataVolumeClaimTemplate: clickhouse-data
      podTemplate: clickhouse
      serviceTemplate: clickhouse-default
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeeper-headless
          port: 2181
        - host: zookeeper-1.zookeeper-headless
          port: 2181
        - host: zookeeper-2.zookeeper-headless
          port: 2181
    clusters:
      - name: czhfe
        layout:
          shardsCount: 2
          replicasCount: 2
    profiles:
      default/distributed_aggregation_memory_efficient: "1"
      default/max_bytes_before_external_sort: "6184752906"
      default/max_bytes_before_external_group_by: "3865470566"
    settings:
      disable_internal_dns_cache: "1"
      max_server_memory_usage: "7730941133"
      prometheus/asynchronous_metrics: "true"
      prometheus/endpoint: /metrics
      prometheus/events: "true"
      prometheus/metrics: "true"
      prometheus/port: "8001"
      prometheus/status_info: "true"
    users:
      clickhouse_admin/networks/ip: "::/0"
      clickhouse_admin/password: "xxxxxxxxxx"
      clickhouse_admin/profile: default
      clickhouse_admin/access_management: 1
  templates:
    podTemplates:
      - name: clickhouse
        podDistribution:
          - type: ShardAntiAffinity
            scope: Shard
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:21.8.14.5
              ports:
              - name: metrics
                containerPort: 8001
              resources:
                requests:
                  memory: "8Gi"
                  cpu: "1"
                limits:
                  memory: "8Gi"
                  cpu: "1"
              env:
                - name: TZ
                  value: "Asia/Shanghai"
              lifecycle:
                preStop:
                  exec:
                    command: [ "/bin/sh","-c","clickhouse stop" ]
              livenessProbe:
                initialDelaySeconds: 10
                failureThreshold: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
                httpGet:
                  port: http
                  scheme: HTTP
                  path: /ping
              readinessProbe:
                initialDelaySeconds: 5
                failureThreshold: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
                httpGet:
                  port: http
                  scheme: HTTP
                  path: /ping
              startupProbe:
                initialDelaySeconds: 20
                failureThreshold: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
                httpGet:
                  port: http
                  scheme: HTTP
                  path: /ping
          terminationGracePeriodSeconds: 60
    volumeClaimTemplates:
      - name: clickhouse-data
        reclaimPolicy: Retain
        spec:
          storageClassName: csi-disk-ssd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    serviceTemplates:
      - name: clickhouse-default
        generateName: clickhouse-server
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
```


**2、This refers to whether the clickhouse operator can run multiple copies, not to the clickhouse-server**

**3、This problem may occur whenever the clickhouse-operator has restarted**

**Comment by Slach** [comment]
1 I don't see `skyline` cluster in your spec, only `czhfe` cluster, 
```
  clusters:
      - name: czhfe
        layout:
          shardsCount: 2
          replicasCount: 2
```

could you share following query result?

```sql
SELECT hostName() h, * FROM cluster('all-sharded',system.query_log) WHERE query_id='52fafb46-2a44-4028-9a3b-0e8d82237a02' FORMAT Vertical
```

> This refers to whether the clickhouse operator can run multiple copies, not to the clickhouse-server

It's possible, but only for the same version of `clickhouse-operator` and each `clickhouse-operator` instance shall watch separate namespaces (if you install clickhouse-operator in `kube-system` it will watch  all namespaces, if you install clickhouse-operator into the other namespace, it will watch only one namespace where `clickhouse-operator`  installed

If you have multiple `clickhouse-operator` instance, it could have race-condition.

could you share following command?
```bash
kubectl get deploy --all-namespaces -l app=clickhouse-operator
```

> This problem may occur whenever the clickhouse-operator has restarted
I not sure
