### ISSUE TITLE
Cycling to New Hosts with Persistent volume setup

### ISSUE THREAD

**Issue by chanadian** [Altinity/clickhouse-operator#893]
Hi we are doing a migration on our cluster that requires us to move all CH nodes to new hosts. Our cluster is setup as a replicated cluster with persistent volume storage provided by EBS. I am considering two options and would love any recommendations you have.

Operator version: 0.13.5 (we prefer to wait for this migration to complete before upgrading versions, since upgrading in the past has caused problems)

## Option 1: Allow operator to move node and PV

We can cordon the old EC2 machine by removing node selector preference, and stand up new EC2 machine with the proper node selector criteria. Will the operator keep the PV and automatically attach the old PV to the new EC2 node?

```
volumeClaimTemplates:
      - name: data-storage-vc-template-ebs
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: gp2
          resources:
            requests:
              storage: 2Ti
```

## Option 2: Expand cluster, wait for replication to complete then shrink cluster

Perform the migration by expanding the CH cluster. When all nodes are replicated, remove the replicas that belong to the old hosts by removing them from the CHI spec.

Question: is there a deterministic way we know all replicas are caught up in replication in the cluster?
