### ISSUE TITLE
Attach a existing Persistent Volume to New Deployment

### ISSUE THREAD

**Issue by pdsaiteja** [Altinity/clickhouse-operator#898]
Hi Team, 

I am deploying Clickhouse  on Google Kubernetes Engine cluster. I am using like two shards and two replicas as mentioned below. When I create a clickhouse cluster, the clickhouse operator automatically creates Persistent volumes and persistent volume claims for each shard. Like in this case may be 4 PVC's and 4 PV's. I made all these PV's reclaim policy to "Retain. 

I have two main scenarios here. 

1. If my namespace which contains Clickhouse cluster is dropped. I would like to restore database from the previous PV's
2. If my GKE cluster is deleted by any chance, I would like to restore it from already existing PV's

I approached and tried various formats. I could find any deployment files to cover my scenarios. 

I have zookepper and cluster configuration template ready. Along with them, I need a template (may be volume claim part) which should be able to re-use existing PV's and restore database.

Please help me. 

Thanks,
Sai teja

----- The deployment file I used for initial setup
```yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "chdev"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoo1ns
          port: 2181
    clusters:
      - name: "chdev"
        layout:
          shardsCount: 3
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
  defaults:
    templates:
      volumeClaimTemplate: default
      podTemplate: default
  templates:
    volumeClaimTemplates:
      - name: default
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```
