### ISSUE TITLE
Can I Configure CH server to listen_host equals to POD IP environment variable 

### ISSUE THREAD

**Issue by HeenaBansal2009** [Altinity/clickhouse-operator#905]
I can update pod template to have a environment variable from POD metadata which contains POD IP.

My question is , can I configure my CH server configuration to listen on POD IP  using that environment variable.

**Comment by Slach** [comment]
You could attempt to use something like this:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseIntallation
spec:
  files:
    config.d/listen_pod_ip.xml: |
      <listen_host from_env="POD_IP"/> 
  templates:
    podTemplates:
      - name: pod-template-with-pod-ip
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP                
```
