### ISSUE TITLE
How to use shardID and clusterID in volumeClaimTemplates for label selector

### ISSUE THREAD

**Issue by cryptomacma** [Altinity/clickhouse-operator#909]
Hi, Suppose I have the shardsCount: 2 and replicasCount: 2, the expected the 4 pods to be as chi-simple-01-simple-[0/1]-[0/1]-0
I've declared 4 PVs with the label as 0-0, 0-1, 1-0, 1-1 accordingly.
I would expect each pod will find the PV directly using the selector under volumeClaimTemplates by referencing https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml#L259:
```
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          selector: 
            matchLabels:
              chop-data: "{shardID}-{replicaID}"
```

But when i am trying to do the cluster installation, I got the value from sts:
  `Warning  FailedCreate  1s (x12 over 11s)  statefulset-controller  create Claim storage-vc-template-chi-simple-01-simple-0-0-0 for Pod chi-simple-01-simple-0-0-0 in StatefulSet chi-simple-01-simple-0-0 failed error: PersistentVolumeClaim "storage-vc-template-chi-simple-01-simple-0-0-0" is invalid: spec.selector.matchLabels: Invalid value: "{shardID}-{replicaID}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

Any suggestions I can use those IDs dynamically for the case here?
