### ISSUE TITLE
Setting clickhouse logging level to something other than debug

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#919]
I'm trying to change the logging level for the Clickhouse Server by adding this configuration in my CHI manifest
```
configuration:
  settings:
    logger:
      level: information
```

But the setting does not make it into the chop-generated-settings.xml file. What am I doing wrong? Thanks!

**Comment by a-dot** [comment]
Nevermind... I figured it out... it has to be specified as
```
configuration:
  settings:
    logger/level: information
```
Thanks!

**Comment by roshanths** [comment]
HI @a-dot , yes logger should be specified as ` logger/level`

```
  spec:
  configuration:
    settings:
      logger/level: [information/debug]
```

You can also control the verbosity of the logger, Please find the complete logger setting below :
```

                logger:
                  type: object
                  properties:
                    logtostderr:
                      type: string
                      description: "boolean, allows logs to stderr"
                    alsologtostderr:
                      type: string
                      description: "boolean allows logs to stderr and files both"
                    v:
                      type: string
                      description: "verbosity level of clickhouse-operator log, default - 1 max - 9"
                    stderrthreshold:
                      type: string
                    vmodule:
                      type: string
                      description: |
                        Comma-separated list of filename=N, where filename (can be a pattern) must have no .go ext, and N is a V level.
                        Ex.: file*=2 sets the 'V' to 2 in all files with names like file*.
                    log_backtrace_at:
                      type: string
                      description: |
                        It can be set to a file and line number with a logging line.
                        Ex.: file.go:123
                        Each time when this line is being executed, a stack trace will be written to the Info log.
```
