### ISSUE TITLE
[clickhouseinstallation] Cluster Name cannot use "_" joined?

### ISSUE THREAD

**Issue by zhu733756** [Altinity/clickhouse-operator#921]
Hi, guys.   I get an error during the installation.

- Example for clickhouseinstallation CR:

```
clusters:
      - name: "cestc_cluster"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          # serviceTemplate: chi-service-template
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
```

will  lead to errors:
```
The ClickHouseInstallation "clickhouse-demo" is invalid: spec.configuration.clusters.name: Invalid value: "cestc_cluster": spec.configuration.clusters.name in body should match '^[a-zA-Z0-9-]{0,15}$'
```

But "cestc-cluster" is legal.

See the CRD https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/parts/crd.yaml#L574. The regex is not matched.

By the way, the CRD is not generated by the kubebuilder tool or some other same tools ?

Glad to hear your reply. Thanks.
