### ISSUE TITLE
replicaServiceTemplate is selected at a shard, not the replica.

### ISSUE THREAD

**Issue by RossRothenstine** [Altinity/clickhouse-operator#923]
Using operator 0.18.4. My understanding of replicaServiceTemplate is that it will be generated per replica, not per shard. The goal is to have a service that can load balance between replicas specifically, not just the whole CHI. 

I've omitted some configuration for posterity.

```
...
clusters:
  - name: simple-test
    templates:
      replicaServiceTemplate: replica-service-template
    layout:
      replicas:
        - name: ro
          shardsCount: 2
          templates:
        - name: wo
          shardsCount: 2
          templates:
            replicaServiceTemplate: replica-service-template-wo

serviceTemplates:
  - name: replica-service-template
    generateName: "replica-{chi}-{cluster}-{replica}"
...
```

This produces the following selector, for example:

```
$ kubectl describe service/replica-clickhouse-chart-test-simple-test-ro
...
clickhouse.altinity.com/app=chop
clickhouse.altinity.com/chi=clickhouse-chart-test
clickhouse.altinity.com/cluster=simple-test
clickhouse.altinity.com/namespace=default
clickhouse.altinity.com/replica=ro
clickhouse.altinity.com/shard=1
...
```

Please advise if I understand replicaServiceTemplate correctly, its goals, and whether or not it should be applying the shard to the selector.
