### ISSUE TITLE
K8S complains failure-domain.beta.kubernetes.io/zone is deprecated since v1.17

### ISSUE THREAD

**Issue by minhtd1981** [Altinity/clickhouse-operator#937]
Here is our ClickhouseInstallation:
```
 podTemplates:
      - name: clickhouse-in-zone-westeurope-1
        zone:
          values:
            - westeurope-1
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
```

and here is how statefulset is created
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - westeurope-1
```

Then K8S would return a warning like this
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: [failure-domain.beta.kubernetes.io/zone](http://failure-domain.beta.kubernetes.io/zone) is deprecated since v1.17; use "[topology.kubernetes.io/zone](http://topology.kubernetes.io/zone)" instead

**Comment by filimonov** [comment]
https://github.com/Altinity/clickhouse-operator/blob/28ca2237ba6419c9ac1019da2e462a8c42a7a919/pkg/model/normalizer.go#L577

**Comment by sunsingerus** [comment]
please check in 0.19.0

**Comment by alex-zaitsev** [comment]
@minhtd1981 ,

```
      podDistribution:
      - scope: ClickHouseInstallation
        type: ClickHouseAntiAffinity
        topologyKey: "topology.kubernetes.io/zone"
```

**Comment by minhtd1981** [comment]
@alex-zaitsev you are right :( Not sure why I could not see that field customizable. Thanks a lot

**Comment by tdminh** [comment]
I could finally fix the warning.
```
zone:
          values:
            - westeurope-1
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
```
should be
```
       zone:
          key: "topology.kubernetes.io/zone"
          values:
            - westeurope-1
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
```
