### ISSUE TITLE
Does AWS PVC storage support online expansion without restarting the container?

### ISSUE THREAD

**Issue by chhan-coupang** [Altinity/clickhouse-operator#946]
AWS can re-scale EBS volumes, without shutting down the container upfront.
So can we provide a way to control allowing for example Storage resources to modify the PVC directly without rebuilding the container?

For reference, vitess-operator handles it like this:
```yaml
  updateStrategy:
    external:
      allowResourceChanges:
      - storage
    type: External
```
link: https://github.com/planetscale/vitess-operator/blob/main/docs/api.md#planetscale.com/v2.ExternalVitessClusterUpdateStrategyOptions

Thank you so much! Please let me know if you have any suggestions or concerns.

**Comment by Slach** [comment]
Currently, it is hard to implements for us

`clickhouse-operator` itself manage only `Kind: StatefulSet` resources and calculate settings and pvc settings hash and store it in labels inside `statefulset.template.metadata`, it requires re-create `StatefulSet` when we change volumeClaimTemplate

to leverage this downtime, we provide additional logic for remove replica from chi level and cluster level `kind: Service` resources endpoints and from `<remote_servers>`

**Comment by chhan-coupang** [comment]
Thanks Reply!
I filed a PR #947 please check.

If this PR is lucky enough to be merged, do I need to add an option like Restart to control whether the feature is enabled or not
e.g:
```yaml
allowResourceChanges:
  type: array/string
  description: "Allow the specified resource to be updated directly and skip the restart of the container/statefulset"
  enum:
    - ""
    - "Storage"
```
