### ISSUE TITLE
Operater think EKS EBS PVs are Non-reconciled objects and scheduling for deletion

### ISSUE THREAD

**Issue by ayinakuna** [Altinity/clickhouse-operator#948]
Here are the logs.

**Non-reconciled objects:
PV: /pvc-68b34bb0-8355-40ff-85f2-576cbb7f9bae
PV: /pvc-e4330cc5-6182-4075-bb34-0532fd7dc226**

```
I0602 13:20:29.617036       1 worker.go:361] clear():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:Reconciled objects:
StatefulSet: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-0
StatefulSet: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-1
PVC: mvd-clickhouse/volume-claim-template-chi-mvd-clickhouse-nse-replicated-0-0-0
PVC: mvd-clickhouse/volume-claim-template-chi-mvd-clickhouse-nse-replicated-0-1-0
Service: mvd-clickhouse/clickhouse-mvd-clickhouse-nse
Service: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-0
Service: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-1
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-common-configd
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-common-usersd
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-deploy-confd-replicated-0-0
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-deploy-confd-replicated-0-1
I0602 13:20:29.617087       1 worker.go:362] clear():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:Existing objects:
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-common-configd
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-common-usersd
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-deploy-confd-replicated-0-0
ConfigMap: mvd-clickhouse/chi-mvd-clickhouse-nse-deploy-confd-replicated-0-1
Service: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-0
Service: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-1
Service: mvd-clickhouse/clickhouse-mvd-clickhouse-nse
PVC: mvd-clickhouse/volume-claim-template-chi-mvd-clickhouse-nse-replicated-0-0-0
PVC: mvd-clickhouse/volume-claim-template-chi-mvd-clickhouse-nse-replicated-0-1-0
PV: /pvc-68b34bb0-8355-40ff-85f2-576cbb7f9bae
PV: /pvc-e4330cc5-6182-4075-bb34-0532fd7dc226
StatefulSet: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-0
StatefulSet: mvd-clickhouse/chi-mvd-clickhouse-nse-replicated-0-1
I0602 13:20:29.617115       1 worker.go:364] clear():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:Non-reconciled objects:
PV: /pvc-68b34bb0-8355-40ff-85f2-576cbb7f9bae
PV: /pvc-e4330cc5-6182-4075-bb34-0532fd7dc226
I0602 13:20:29.617152       1 worker.go:374] clear():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:remove items scheduled for deletion
I0602 13:20:29.848500       1 worker.go:378] worker.go:378:dropReplicas():start:mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:drop replicas based on AP
I0602 13:20:29.848539       1 worker.go:399] worker.go:399:dropReplicas():end:mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:processed replicas: 0
I0602 13:20:29.848558       1 worker.go:352] includeStopped():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:add CHI to monitoring
I0602 13:20:30.074213       1 worker.go:424] markReconcileComplete():mvd-clickhouse/mvd-clickhouse-nse/04ac1604-3097-43d0-a87a-a1ffab1b9df7:reconcile completed
```

**Comment by ayinakuna** [comment]
Operator version: 0.18.5
Zookeeper: 3.8.0


```
   volumeClaimTemplates:
      - name: volume-claim-template
        metadata:
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Prune=false
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3T
```
