### ISSUE TITLE
Add affinity and tolerations to ChiPodTemplate

### ISSUE THREAD

**Issue by svmaris** [Altinity/clickhouse-operator#95]
Currently only Name, Containers and Volumes from the PodTemplate are copied to the Pod spec. I'm trying to use dedicated nodes for Clickhouse, so it would be nice if the affinity and tolerations are copied from the template, so I can do something like this:

```yaml
    podTemplates:
    - name: clickhouse-v19.6.2.11
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "clickhouse"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - clickhouse
```
