### ISSUE TITLE
Option to rotate passwords passed from Kubernetes Secrets

### ISSUE THREAD

**Issue by lambdanis** [Altinity/clickhouse-operator#960]
I have a CHI with user passwords passed via `*/k8s_secret_password` settings. When I change passwords in the k8s secrets, clickhouse-operator doesn't change them in the database until some change in the CHI spec triggers reconciliation. It would be nice to have an option to force reconciliation, to be able to rotate passwords without modifying the CHI definition itself.

I didn't find any mention of passwords rotation in the docs. If you have any recommendations on how to achieve that, then it would be very useful, I think it's a common use case.

**Comment by jun0tpyrc** [comment]
same , my workaround is playing this field to add/remove a temp network whitlist on user to trigger reconcile of readonly volume of generated users xml

```
    users:
      user-ttttttt/k8s_secret_password_sha256_hex: ns/ch-idx-ttttttt/user-ttttttt_password_sha256_hex
      user-ttttttt/networks/ip:
      - "x.x.x.x/x"
      - "127.0.0.0/32" <= add then apply, verify then remove and apply again
```
