### ISSUE TITLE
QA: Does it possible to use several PVC in JBOD?

### ISSUE THREAD

**Issue by Nefelim4ag** [Altinity/clickhouse-operator#964]
Hi, amazon have limits on performance for EBS, and it is just economically and performance profitable to have 4 volumes per node instead of big one

Like 4 gp3 128GB volumes with default 125 MB/s & 3000 iops = 512 GB 600 MB/s and 3000 iops
vs 1 gp3 512GB volumes with increased limits to 500 MB/s & 12000 iops

<img width="588" alt="Screenshot 2022-06-28 at 17 00 08" src="https://user-images.githubusercontent.com/3943460/176212809-97df1773-0d7b-49a5-87d3-e5af94fb1202.png">
<img width="588" alt="Screenshot 2022-06-28 at 17 00 30" src="https://user-images.githubusercontent.com/3943460/176212821-c21d2b7b-d35b-4771-84f5-8e0966715cf2.png">

**Comment by Slach** [comment]
yes it possible
you could use something like this
```yaml
spec:
  configuration:
    files:
      config.d/storage_policy_jbod.xml: |
       <yandex>
          <storage_configuration>
            <disks>
              <disk2>
                <path>/var/lib/clickhouse2/</path>
              </disk2>
              <disk3>
                <path>/var/lib/clickhouse3/</path>
              </disk3>
              <disk4>
                <path>/var/lib/clickhouse4/</path>
              </disk4>
            </disks>
            <policies>
              <default>
                <volumes>
                  <default>
                    <disk>default</disk>
                    <disk>disk2</disk>
                    <disk>disk3</disk>
                    <disk>disk4</disk>
                  </default>
                </volumes>
              </default>
            </policies>
          </storage_configuration>
       
  defaults:
    podTemplate: multi-disk
  templates:  
    podTemplates:
    - name: multi-disk
      spec:
        containers:
        - image: clickhouse/clickhouse-server:22.6
          name: clickhouse
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: default-gp3
          - mountPath: /var/lib/clickhouse2
            name: disk2-gp3
          - mountPath: /var/lib/clickhouse3
            name: disk3-gp3
          - mountPath: /var/lib/clickhouse4
            name: disk3-gp3

    volumeClaimTemplates:
    - name: default-gp3
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp3
    - name: disk2-gp3
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp3
    - name: disk4-gp3
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp3
    - name: disk4-gp3
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp3

```

But this approach has tradeoff.
`clickhouse-server` splits data by parts (file level) not block level, and use `round_robin` (`least_used` in 22.6+) for JBOD balancing. 

So, when new part creates after insert or after background merge / mutation then parts / data doesn't shuffle / spread between disks smoothly

you would get the "hot" data parts which will store on the only one disk and read / write iops can't be spread between disks the same way as RAID
