### ISSUE TITLE
merge tree settings

### ISSUE THREAD

**Issue by rsaphala** [Altinity/clickhouse-operator#968]
How do i override merge tree settings? I want to include this

```
<merge_tree>
        <max_suspicious_broken_parts>20</max_suspicious_broken_parts>
</merge_tree>
```

into the configuration definition

**Comment by Slach** [comment]
```yaml
spec:
  configuration:
    settings:
      mergree/max_suspicious_broken_parts: 20
```
