### ISSUE TITLE
prometheus setup to monitor clickhouse

### ISSUE THREAD

**Issue by xgengsjc2021** [Altinity/clickhouse-operator#971]
Hi, I have prometheus installed. So follow this link, https://github.com/Altinity/clickhouse-operator/blob/eb3fc4e28514d0d6ea25a40698205b02949bcf9d/docs/prometheus_setup.md#prometheus-already-available. 
But still not sure how you configure on prometheus to collect CH metrics. 

I tried to configure the additionalScrapeConfigs in prometheus, but did not work as expected(I did not see these metrics on Prometheus). 
```
additionalScrapeConfigs:
    - job_name: clickhouse
      static_config:
        targets: [localhost:8888/metrics]
        labels: [app: clickhouse-operator]
```
Since my CH operator(kube-system) is in different namespace from promethes(monitoring). Not sure if targets part is correct or not. 

Do I need to create service monitor for the exporter?
Could you explain it more details? @Slach Do you have a min to take a look?
