### ISSUE TITLE
configuration files as a secret

### ISSUE THREAD

**Issue by dheerajathrey** [Altinity/clickhouse-operator#981]
Does clickhouse operator support providing an entire file say kafka.xml or setttings.xml as a secret in the clickhouse operator, instead of having a very big cluster definition file with all files data hardcoded?

My yaml file:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch"
spec:
  defaults:
    templates:
      serviceTemplate: svc-template
  configuration:
    files:
      settings.xml: |
        <yandex>
            <timezone>UTC</timezone>
            <database_atomic_delay_before_drop_table_sec>120</database_atomic_delay_before_drop_table_sec>
            <dictionaries_lazy_load>false</dictionaries_lazy_load>
        </yandex>
      kafka.xml: |
        <yandex>
            # kafka related configurations with secrets inside
        </yandex>
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeeper-headless.zookeeper
          port: 2181
        - host: zookeeper-1.zookeeper-headless.zookeeper
          port: 2181
        - host: zookeeper-2.zookeeper-headless.zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
    clusters:
      - name: "cl"
        templates:
          podTemplate: pod-template-with-volumes
          volumeClaimTemplate: storage-vc-template
        layout:
          type: Standard
          shardsCount: 2
          replicasCount: 2

  templates:
    serviceTemplates:
      - name: svc-template
        generateName: service-{chi}
        metadata:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: az-disk-retain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: <ch-image>
              volumeMounts:
                - name: cert-volume
                  mountPath: /var/lib/cert
                - name: storage-vc-template
                  mountPath: /var/lib/clickhouse
              resources:
                limits:
                  memory: 120Gi
                  cpu: 15
                requests:
                  memory: 120Gi
                  cpu: 15
          volumes:
            - name: cert-volume
              secret:
                secretName: certfile

```
