### ISSUE TITLE
Access Management for Kubernetes operator

### ISSUE THREAD

**Issue by oktayalizada** [Altinity/clickhouse-operator#990]
Hi,
Is there a way in clickhouse on Kubernetes operator to uncomment access_management in users.xml file?
And what is the best way to do that?

**Comment by Slach** [comment]
look to `kubectl explain chi.spec.configuration.files` and `kubectl explain chi.spec.configuration.users`

```yaml
spec:
  configuration:
    files:
      users.d/access_management.xml: | 
         <clickhouse><users><default><access_management>1</access_management></default></users></clickhouse>
```
