### ISSUE TITLE
Reconcilation not triggered on config change in CR

### ISSUE THREAD

**Issue by AdheipSingh** [Altinity/clickhouse-operator#998]
- ```Clickhouse operator version: altinity/clickhouse-operator:0.19.1```
- I have created a custom resource, which the operator reconciles successfully. 
- When i try to update the custom resource with change in clickhouse image or adding of user. I see no reconcilation of the CR.
- No error or info is emitted in operator logs. Also the databases and tables mentioned in the CR were not created on bootstrapping of the cluster.

My CR where i faced the issue
```
apiVersion: v1
kind: "ConfigMap"
metadata:
  name: "bootstrap-mounted-configmap"
data:
  01_create_databases.sh: |
    #!/bin/bash
    set -e
    clickhouse client -n <<-EOSQL
      CREATE DATABASE users;
      CREATE DATABASE analytics;
      CREATE DATABASE flowers;
    EOSQL
  02_create_table.sh: |
    #!/bin/bash
    set -e
    clickhouse client -n <<-EOSQL
      CREATE TABLE users.logs (x Int32) ENGINE = Log;
    EOSQL
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "bootstrap"
spec:
  configuration:
    users:
    # Password = topsecret
        demo/password_sha256_hex: 53336a676c64c1396553b2b7c92f38126768827c93b64d9142069c10eda7a721
        demo/profile: default
        demo/quota: default
        demo/networks/ip:
        - 0.0.0.0/0
        - ::/0
    clusters:
      - name: "bootstrap"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.1
              securityContext:
               capabilities:
                 add: ["CAP_SYS_NICE"]
              volumeMounts:
                - name: bootstrap-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: bootstrap-configmap-volume
              configMap:
                name: bootstrap-mounted-configmap

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
```

**Comment by Slach** [comment]
`clickhouse-operator` watch only `kind: ClickHouseInstallation` resources for reconciling

so, if you change `kind: ConfigMap` it will just update `/docker-entrypoint-initdb.d` content in your pod bypass clickhouse-operator 

for manual reconcile trigger, you can change inside `ClickHouseInstallation` 
```
spec: 
  taskID: "any_random_string"
```

**Comment by AdheipSingh** [comment]
@Slach thanks for the response.

i am aware that operator will watch only custom resource ie ClickHouseInstallation, but with even that, any change i do in the CR around image version change, also isnt getting reconciled.

**Comment by Slach** [comment]
Try to add inside `ClickHouseInstallation` link to `podTemplate` explicitly

```yaml
spec:
 defaults:
    templates:
      podTemplate: pod-template
```
